<?php

use yii\db\Migration;

/**
 * Class m200131_064632_seeder_lookup_m
 */
class m200131_064632_seeder_lookup_m extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->execute('TRUNCATE TABLE lookup_m RESTART IDENTITY;');

        $this->execute("

INSERT INTO \"public\".\"lookup_m\"(\"lookup_id\",\"lookup_type\",\"lookup_name\",\"lookup_value\",\"lookup_urutan\",\"lookup_kode\",\"additional_data\",\"created_date\",\"created_by\",\"modified_count\",\"last_modified_date\",\"last_modified_by\",\"is_deleted\",\"is_active\",\"deleted_date\",\"deleted_by\") VALUES 
(1, 'status_periksa', 'Antrian Poliklinik', 'Antrian Poliklinik', 1, NULL, '{\"instalasi_id\" : [1]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(2, 'status_periksa', 'Diperiksa', 'Diperiksa', 2, NULL, '{\"instalasi_id\" : [1,2,3]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(3, 'status_periksa', 'Sudah Diperiksa', 'Sudah Diperiksa', 3, NULL, '', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(4, 'status_periksa', 'Pulang', 'Pulang', 4, NULL, '{\"instalasi_id\" : [1,2,3]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(5, 'gelar_depan', 'dr.', 'dr.', 1, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(6, 'gelar_depan', 'Prof.', 'Prof.', 2, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(7, 'gelar_depan', 'drs.', 'drs.', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(8, 'gelar_depan', 'drs.', 'drs.', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(9, 'gelar_depan', 'DR.', 'DR.', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(10, 'gelar_depan', 'Dra.', 'Dra.', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(11, 'gelar_depan', 'Ir.', 'Ir.', 6, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(12, 'gelar_depan', 'H.', 'H.', 7, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(13, 'gelar_depan', 'Hj.', 'Hj.', 8, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(14, 'gelar_depan', 'Drg.', 'Drg.', 9, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(15, 'jenis_kelamin', 'Laki-laki', 'Laki-laki', 1, 'L', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(16, 'jenis_kelamin', 'Perempuan', 'Perempuan', 2, 'P', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(17, 'agama', 'Islam', 'Islam', 1, '0', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(18, 'agama', 'Katholik', 'Katholik', 2, '1', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(19, 'agama', 'Protestan', 'Protestan', 3, '2', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(20, 'agama', 'Hindu', 'Hindu', 4, '4', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(21, 'agama', 'Budha', 'Budha', 5, '3', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(22, 'agama', 'Lainnya', 'Lainnya', 6, '5', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(23, 'golongan_darah', 'A', 'A', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(24, 'golongan_darah', 'AB', 'AB', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(25, 'golongan_darah', 'O', 'O', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(26, 'golongan_darah', 'B', 'B', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(27, 'metode_bayar', 'Tunai', 'Tunai', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(28, 'metode_bayar', 'Transfer', 'Transfer', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(29, 'barang_umumtype', 'Aset', 'Aset', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(30, 'barang_umumtype', 'Persediaan', 'Persediaan', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(31, 'cara_pembayaran', 'Tunai', 'Tunai', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(32, 'cara_pembayaran', 'Hutang', 'Hutang', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(33, 'cara_pembayaran', 'Piutang', 'Piutang', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(34, 'cara_pembayaran', 'Cicilan', 'Cicilan', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(35, 'cara_persalinan', 'Normal', 'Normal', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(36, 'cara_persalinan', 'Persalinan dengan Ekstrasi Vakum', 'Persalinan dengan Ekstrasi Vakum', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(37, 'cara_persalinan', 'Persalinan dengan ekstrasi forsep', 'Persalinan dengan ekstrasi forsep', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(38, 'cara_persalinan', 'Persalinan dengan operasi', 'Persalinan dengan operasi', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(39, 'denyut_jantung', 'Inreguler', 'Inreguler', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(40, 'denyut_jantung', 'Reguler', 'Reguler', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(41, 'etiket', 'Biru -  Penggunaan Luar', 'Biru -  Penggunaan Luar', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(42, 'etiket', 'Putih - Penggunaan Dalam', 'Putih - Penggunaan Dalam', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(43, 'evaluasi_assesment', 'Masalah Teratasi', 'Masalah Teratasi', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(44, 'evaluasi_assesment', 'Masala Tidak Teratasi', 'Masala Tidak Teratasi', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(45, 'formularium', 'non formularium', 'non formularium', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(46, 'formularium', 'formularium', 'formularium', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(47, 'gravida', 'Gravida 1 - hamil untuk pertama kalinya', 'Gravida 1 - hamil untuk pertama kalinya', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(48, 'gravida', 'Gravida 0 - belum pernah hamil', 'Gravida 0 - belum pernah hamil', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(49, 'hubungan_keluarga', 'Ayah', 'Ayah', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(50, 'hubungan_keluarga', 'Ibu', 'Ibu', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(51, 'hubungan_keluarga', 'Anak', 'Anak', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(52, 'hubungan_keluarga', 'Suami', 'Suami', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(53, 'hubungan_keluarga', 'Istri', 'Istri', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(54, 'hubungan_keluarga', 'Mertua', 'Mertua', 6, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(55, 'hubungan_keluarga', 'Lainnya', 'Lainnya', 7, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(56, 'hubungan_keluarga', 'Teman Sejawat', 'Teman Sejawat', 8, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(57, 'hubungan_keluarga', 'Teman Kerja', 'Teman Kerja', 9, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(58, 'hubungan_keluarga', 'Paman', 'Paman', 10, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(59, 'hubungan_keluarga', 'Bibi', 'Bibi', 11, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(60, 'hubungan_keluarga', 'Uwa', 'Uwa', 12, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(61, 'hubungan_keluarga', 'Kakek', 'Kakek', 13, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(62, 'hubungan_keluarga', 'Nenek', 'Nenek', 14, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(63, 'hubungan_keluarga', 'Sepupu', 'Sepupu', 15, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(64, 'hubungan_keluarga', 'Tetangga', 'Tetangga', 16, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(65, 'hubungan_keluarga', 'Menantu', 'Menantu', 17, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(66, 'hubungan_keluarga', 'Keponakan', 'Keponakan', 18, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(67, 'hubungan_keluarga', 'Cucu', 'Cucu', 19, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(68, 'hubungan_keluarga', 'Kakak', 'Kakak', 20, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(69, 'hubungan_keluarga', 'Adik', 'Adik', 21, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(70, 'hubungan_keluarga', 'Saudara', 'Saudara', 22, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(71, 'inventaris_keadaan', 'Baik', 'Baik', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(72, 'inventaris_keadaan', 'Kurang Baik', 'Kurang Baik', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(73, 'inventaris_keadaan', 'Rusak Berat', 'Rusak Berat', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(74, 'inventaris_keadaan', 'Rusak Ringan', 'Rusak Ringan', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(75, 'hari', 'Senin', 'Senin', 1, 'hari_senin', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(76, 'hari', 'Selasa', 'Selasa', 2, 'hari_selasa', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(77, 'hari', 'Rabu', 'Rabu', 3, 'hari_rabu', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(78, 'hari', 'Kamis', 'Kamis', 4, 'hari_kamis', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(79, 'hari', 'Jumat', 'Jumat', 5, 'hari_jumat', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(80, 'hari', 'Sabtu', 'Sabtu', 6, 'hari_sabtu', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(81, 'hari', 'Minggu', 'Minggu', 7, 'hari_minggu', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(82, 'status_kepemilikanrs', 'Kemkes, Pemprop, Pemkab, Pemkot, dll', 'Kemkes, Pemprop, Pemkab, Pemkot, dll', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(83, 'status_kepemilikanrs', 'TNI/ Polri', 'TNI/ Polri', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(84, 'status_kepemilikanrs', 'DEPARTEMEN KESEHATAN', 'DEPARTEMEN KESEHATAN', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(85, 'status_kepemilikanrs', 'PEMDA PROPINSI', 'PEMDA PROPINSI', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(86, 'status_kepemilikanrs', 'PEMDA KOTA', 'PEMDA KOTA', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(87, 'status_kepemilikanrs', 'PEMDA KABUPATEN', 'PEMDA KABUPATEN', 6, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(88, 'status_kepemilikanrs', 'TNI AD', 'TNI AD', 7, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(89, 'status_kepemilikanrs', 'TNI AL', 'TNI AL', 8, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(90, 'status_kepemilikanrs', 'TNI AU', 'TNI AU', 9, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(91, 'status_kepemilikanrs', 'POLRI', 'POLRI', 10, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(92, 'status_kepemilikanrs', 'PERUSAHAAN', 'PERUSAHAAN', 11, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(93, 'status_kepemilikanrs', 'PERORANGAN', 'PERORANGAN', 12, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(94, 'jenis_identitas', 'KTP', 'KTP', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(95, 'jenis_identitas', 'SIM', 'SIM', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(96, 'jenis_identitas', 'Kartu Pelajar', 'Kartu Pelajar', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(97, 'jenis_identitas', 'KTA', 'KTA', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(98, 'jenis_identitas', 'KITAS', 'KITAS', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(99, 'jenis_identitas', 'PASPOR', 'PASPOR', 6, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(100, 'jenis_identitas', 'Lainnya', 'Lainnya', 7, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(101, 'jenis_imunisasi', 'Imunisasi yang di wajibkan', 'Imunisasi yang di wajibkan', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(102, 'jenis_imunisasi', 'Imunisasi yang di anjurkan', 'Imunisasi yang di di anjurkan', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(103, 'jenis_invoice', 'Invoice Rumah Sakit', 'Invoice Rumah Sakit', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(104, 'jenis_invoice', 'Invoice Supplier', 'Invoice Supplier', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(105, 'jenis_invoice', 'Invoice Umum', 'Invoice Umum', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(106, 'jenis_kegiatanpersalinan', 'Persalinan', 'Persalinan', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(107, 'jenis_kegiatanpersalinan', 'Sectio Caesaria', 'Sectio Caesaria', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(108, 'jenis_kegiatanpersalinan', 'Abortus', 'Abortus', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(109, 'jenis_kegiatanpersalinan', 'Kematian Perinatal', 'Kematian Perinatal', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(110, 'jenis_kendaraan', 'Mobil Ambulans', 'Mobil Ambulans', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(111, 'jenis_kendaraan', 'Mobil Jenazah', 'Mobil Jenazah', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(112, 'jenis_lembur', 'Biasa/Terencana', 'Biasa/Terencana', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(113, 'jenis_lembur', 'On Call/ Emergency', 'On Call/ Emergency', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(114, 'jenis_lembur', 'P3K', 'P3K', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(115, 'jenis_lembur', 'Shut Down', 'Shut Down', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(116, 'jenis_lembur', 'Pengganti Cuti/ Dinas', 'Pengganti Cuti/ Dinas', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(117, 'jenisrs_profilrs', 'RSU', 'RSU', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(118, 'jenisrs_profilrs', 'RSB', 'RSB', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(119, 'jenisrs_profilrs', 'RS MATA', 'RS MATA', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(120, 'jenisrs_profilrs', 'RS TP', 'RS TP', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(121, 'jenisrs_profilrs', 'RS KUSTA', 'RS KUSTA', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(122, 'jenisrs_profilrs', 'RS OP', 'RS OP', 6, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(123, 'jenisrs_profilrs', 'RSK P.DALAM', 'RSK P.DALAM', 7, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(124, 'jenisrs_profilrs', 'RSK BEDAH', 'RSK BEDAH', 8, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(125, 'jenisrs_profilrs', 'RS JANTUNG', 'RS JANTUNG', 9, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(126, 'jenisrs_profilrs', 'RSK THT', 'RSK THT', 10, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(127, 'jenisrs_profilrs', 'RSAB', 'RSAB', 11, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(128, 'jenisrs_profilrs', 'RSK Anak', 'RSK Anak', 12, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(129, 'jenisrs_profilrs', 'RSK Syaraf', 'RSK Syaraf', 13, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(130, 'jenisrs_profilrs', 'RS JIWA / RSKO', 'RS JIWA / RSKO', 14, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(131, 'jenisrs_profilrs', 'RS PENYAKIT INFEKSI', 'RS PENYAKIT INFEKSI', 15, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(132, 'jenisrs_profilrs', 'RS Stroke', 'RS Stroke', 16, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(133, 'jenisrs_profilrs', 'test', 'test', 17, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(134, 'jenisrs_profilrs', 'RS KANKER', 'RS KANKER', 18, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(135, 'jenisrs_profilrs', 'RSK Ginjal', 'RSK Ginjal', 19, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(136, 'jenisrs_profilrs', 'RSK GM', 'RSK GM', 20, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(137, 'jenisrs_profilrs', 'RSS', 'RSS', 21, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(138, 'jenis_stokopname', 'Penyesuaian', 'Penyesuaian', 1, 'P', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(139, 'jenis_stokopname', 'Stok Awal', 'Stok Awal', 2, 'SA', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(140, 'jenis_supplier', 'Farmasi', 'Farmasi', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(141, 'jenis_supplier', 'Umum', 'Umum', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(142, 'jenis_supplier', 'Gizi', 'Gizi', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(143, 'kategori_modul', 'kategorimodul', 'kategorimodul', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(144, 'kategori_modul', 'kategorimodul', 'kategorimodul', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(145, 'kategori_pegawai', 'CPNS', 'CPNS', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(146, 'kategori_pegawai', 'PNS', 'PNS', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(147, 'kategori_pegawai', 'PTT', 'PTT', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(148, 'kategori_pegawai', 'STT', 'STT', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(149, 'kategori_pegawai', 'Tetap', 'Tetap', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(150, 'kategori_pegawai', 'Lainnya', 'Lainnya', 6, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(151, 'kategori_pegawai', 'Tidak Tetap', 'Tidak Tetap', 7, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(152, 'kategori_pekerjaan', 'Ringan', 'Ringan', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(153, 'kategori_pekerjaan', 'Sedang', 'Sedang', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(154, 'kategori_pekerjaan', 'Berat', 'Berat', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(155, 'keadaan_lahir', 'Lahir Hidup', 'Lahir Hidup', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(156, 'keadaan_lahir', 'Lahir Mati', 'Lahir Mati', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(157, 'keadaan_lahir', 'Kembar Hidup dan Mati', 'Kembar Hidup dan Mati', 7, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(158, 'keadaan_masuk', 'Gawat - Tidak Darurat', 'Gawat - Tidak Darurat', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(159, 'keadaan_masuk', 'Tidak Gawat - Tidak Darurat', 'Tidak Gawat - Tidak Darurat', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(160, 'keadaan_masuk', 'Gawat - Darurat', 'Gawat - Darurat', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(161, 'keadaan_masuk', 'Tidak Gawat - Tidak Darurat', 'Tidak Gawat - Tidak Darurat', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(162, 'kelas_rumahsakit', 'A', 'A', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(163, 'kelas_rumahsakit', 'B', 'B', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(164, 'kelas_rumahsakit', 'C', 'C', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(165, 'kelas_rumahsakit', 'D', 'D', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(166, 'kelompok_jabatan', 'Struktural', 'Struktural', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(167, 'kelompok_jabatan', 'Fungsional', 'Fungsional', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(168, 'kelompok_jabatan', 'Administrasi', 'Administrasi', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(169, 'kelompok_jabatan', 'Staf', 'Staf', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(170, 'keterangan_kamar', 'Tersedia', 'Tersedia', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(171, 'keterangan_kamar', 'Rusak', 'Rusak', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(172, 'keterangan_tempattidur', 'Terpakai', 'Terpakai', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(173, 'keterangan_tempattidur', 'Tidak Terpakai', 'Tidak Terpakai', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(174, 'keterangan_tempattidur', 'Dipesan', 'Dipesan', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(175, 'keterangan_tempattidur', 'Dibersihkan', 'Dibersihkan', 6, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(176, 'jenis_antrian', 'Farmasi', 'Farmasi', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(177, 'jenis_antrian', 'Pendaftaran', 'Pendaftaran', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(178, 'jenis_antrian', 'Kasir', 'Kasir', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(179, 'jenis_antrian', 'Penunjang', 'Penunjang', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(180, 'kunjungan', 'Kunjungan Baru', 'Kunjungan Baru', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(181, 'kunjungan', 'Kunjungan Lama', 'Kunjungan Lama', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(182, 'mata_persepsiwarna', 'Buta Warna Total', 'Buta Warna Total', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(183, 'mata_persepsiwarna', 'Buta Warna Parsial', 'Buta Warna Parsial', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(184, 'mata_persepsiwarna', 'Normal', 'Normal', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(185, 'mata_uang', 'Rupiah', 'Rupiah', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(186, 'mata_uang', 'Dollar', 'Dollar', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(187, 'obat_antrian', 'FIFO', 'FIFO', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(188, 'obat_antrian', 'FEFO', 'FEFO', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(189, 'obat_antrian', 'LIFO', 'LIFO', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(190, 'metode_kb', 'IUD', 'IUD', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(191, 'metode_kb', 'PIL', 'PIL', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(192, 'metode_kb', 'Kondom', 'Kondom', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(193, 'metode_kb', 'Suntikan', 'Suntikan', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(194, 'metode_kb', 'Obat Vagina', 'Obat Vagina', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(195, 'metode_kb', 'MO Pria', 'MO Pria', 6, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(196, 'metode_kb', 'Mo Wanita', 'Mo Wanita', 7, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(197, 'metode_kb', 'Implant', 'Implant', 8, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(198, 'metode_napza', 'Preventif', 'Preventif', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(199, 'metode_napza', 'Kuratif', 'Kuratif', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(200, 'metode_napza', 'Aftercare', 'Aftercare', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(201, 'nama_depan', 'Tn. ', 'Tn. ', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(202, 'nama_depan', 'Ny. ', 'Ny. ', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(203, 'nama_depan', 'An. ', 'An. ', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(204, 'nama_depan', 'Nn. ', 'Nn. ', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(205, 'nama_depan', 'By.', 'By.', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(206, 'nama_depan', 'By. Ny.', 'BY. Ny.', 6, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(207, 'nama_kepemilikanrs', 'Kemkes, Pemprop, Pemkab, Pemkot, dll', 'Kemkes, Pemprop, Pemkab, Pemkot, dll', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(208, 'nama_kepemilikanrs', 'TNI/ Polri', 'TNI/ Polri', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(209, 'nama_kepemilikanrs', 'Swasta', 'Swasta', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(210, 'nilai_uang', '100.000', '100000', 11, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(211, 'nilai_uang', '50.000', '50000', 10, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(212, 'nilai_uang', '20.000', '20000', 9, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(213, 'nilai_uang', '10.000', '10000', 8, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(214, 'nilai_uang', '5.000', '5000', 7, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(215, 'nilai_uang', '2.000', '2000', 6, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(216, 'nilai_uang', '1.000', '1000', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(217, 'nilai_uang', '500', '500', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(218, 'nilai_uang', '200', '200', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(219, 'nilai_uang', '100', '100', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(220, 'nilai_uang', '50', '50', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(221, 'obatalkes_golongan', 'Obat Bebas', 'Obat Bebas', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(222, 'obatalkes_golongan', 'Obat Dengan Resep', 'Obat Dengan Resep', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(223, 'obatalkes_golongan', 'Obat Antibiotika', 'Obat Antibiotika', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(224, 'obatalkes_golongan', 'Obat Narkotika', 'Obat Narkotika', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(225, 'obatalkes_golongan', 'Obat Non Antibiotika', 'Obat Non Antibiotika', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(226, 'obatalkes_golongan', 'Obat Psikotropika', 'Obat Psikotropika', 6, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(227, 'obatalkes_golongan', 'Obat Prekusor', 'Obat Prekusor', 7, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(228, 'obatalkes_golongan', 'Tetes', 'Tetes', 8, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(229, 'obatalkes_golongan', 'Obat Bebas Terbatas', 'Obat Bebas Terbatas', 9, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(230, 'obatalkes_golongan', 'Multivitamin', 'Multivitamin', 10, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(231, 'obatalkes_kadarobat', 'Rendah', 'Rendah', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(232, 'obatalkes_kadarobat', 'Sedang', 'Sedang', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(233, 'obatalkes_kadarobat', 'Tinggi', 'Tinggi', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(234, 'obatalkes_kategori', 'GNR', 'GNR', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(235, 'obatalkes_kategori', 'NGNR', 'NGNR', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(236, 'obatalkes_kategori', 'Narkotika', 'Narkotika', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(237, 'obatalkes_kategori', 'Umum', 'Umum', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(238, 'obatalkes_kategori', 'DPHO', 'DPHO', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(239, 'obatalkes_kategori', 'Psikotropika', 'Psikotropika', 6, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(240, 'pengantar', 'Keluarga', 'Keluarga', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(241, 'pengantar', 'Pihak Berwajib / Polisi', 'Pihak Berwajib / Polisi', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(242, 'pengantar', 'Warga Setempat', 'Warga Setempat', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(243, 'pengantar', 'Orang Lain', 'Orang Lain', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(244, 'pengantar', 'Lainnya', 'Lainnya', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(245, 'pengantar', 'Diri Sendiri', 'Diri Sendiri', 6, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(246, 'rhesus', 'RH+', 'RH+', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(247, 'rhesus', 'RH-', 'RH-', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(248, 'rangetdsistolic', '< 120', '< 120', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(249, 'rangetdsistolic', '120 - 129', '120 - 129', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(250, 'rangetdsistolic', '130 - 139', '130 - 139', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(251, 'rangetdsistolic', '140 - 149', '140 - 149', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(252, 'rangetdsistolic', '150 - 159', '150 - 159', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(253, 'rangetdsistolic', '> 160', '> 160', 6, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(254, 'routeofadmatc', 'Inhal', 'Inhal', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(255, 'routeofadmatc', 'N', 'N', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(256, 'routeofadmatc', 'Instill', 'Instill', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(257, 'routeofadmatc', 'O', 'O', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(258, 'routeofadmatc', 'P', 'P', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(259, 'routeofadmatc', 'R', 'R', 6, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(260, 'routeofadmatc', 'SL', 'SL', 7, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(261, 'routeofadmatc', 'TD', 'TD', 8, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(262, 'routeofadmatc', 'Implant', 'Implant', 9, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(263, 'satuan_hasillab', 'mm/jam', 'mm/jam', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(264, 'satuan_hasillab', '%', '%', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(265, 'satuan_hasillab', '/ ul', '/ ul', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(266, 'satuan_hasillab', 'fl', 'fl', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(267, 'satuan_hasillab', 'pg', 'pg', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(268, 'satuan_hasillab', 'Negatif', 'Negatif', 6, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(269, 'satuan_hasillab', 'Menit', 'Menit', 7, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(270, 'satuan_hasillab', '% / 2 jam', '% / 2 jam', 8, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(271, 'satuan_hasillab', 'Detil', 'Detil', 9, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(272, 'satuan_hasillab', 'Detik', 'Detik', 10, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(273, 'satuan_hasillab', 'mg / dl', 'mg / dl', 11, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(274, 'satuan_hasillab', 'U / L / 370C', 'U / L / 370C', 12, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(275, 'satuan_hasillab', 'mg/dl', 'mg/dl', 13, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(276, 'satuan_hasillab', 'mmol/l', 'mmol/l', 14, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(277, 'satuan_hasillab', 'juta /uL', 'juta /uL', 15, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(278, 'satuan_hasillab', 'IU / L', 'IU / L', 16, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(279, 'satuan_hasillab', 'ng / ml', 'ng / ml', 17, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(280, 'satuan_hasillab', 'ug / ml', 'ug / ml', 18, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(281, 'satuan_hasillab', 'plp', 'plp', 19, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(282, 'satuan_hasillab', 'C', 'C', 20, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(283, 'satuan_hasillab', 'mmHg', 'mmHg', 21, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(284, 'satuan_hasillab', '/mm3', '/mm3', 22, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(285, 'satuan_hasillab', 'PLP', 'PLP', 23, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(286, 'satuan_hasillab', 'mg', 'mg', 24, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(287, 'satuan_hasillab', 'U/l', 'U/l', 25, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(288, 'satuan_hasillab', 'u3', 'u3', 26, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(289, 'satuan_hasillab', 'mg%', 'mg%', 27, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(290, 'satuan_hasillab', 'Vol %', 'Vol %', 28, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(291, 'satuan_hasillab', 'ml', 'ml', 29, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(292, 'satuan_hasillab', 'juta / ml', 'juta / ml', 30, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(293, 'satuan_hasillab', 'Gram%', 'Gram%', 31, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(294, 'satuan_hasillab', 'Mg/dl', 'Mg/dl', 32, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(295, 'satuan_hasillab', 'Mmol/l', 'Mmol/l', 33, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(296, 'satuan_hasillab', '/ Lpb', '/ Lpb', 34, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(297, 'satuan_hasillab', ' Ml', ' Ml', 35, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(298, 'satuan_hasillab', 'gr/dl', 'gr/dl', 36, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(299, 'satuan_kekuatan', 'mg', 'mg', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(300, 'satuan_kekuatan', 'g', 'g', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(301, 'satuan_kekuatan', 'ml', 'ml', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(302, 'status_perkawinan', 'Kawin', 'Kawin', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(303, 'status_perkawinan', 'Belum Kawin', 'Belum Kawin', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(304, 'status_perkawinan', 'Janda', 'Janda', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 't', 't', NULL, NULL),
(305, 'status_perkawinan', 'Duda', 'Duda', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 't', 't', NULL, NULL),
(306, 'status_perkawinan', 'Nikah Sirih', 'Nikah Sirih', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 't', 't', NULL, NULL),
(307, 'status_perkawinan', 'Tidak Kawin', 'Tidak Kawin', 6, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 't', 't', NULL, NULL),
(308, 'warga_negara', 'Indonesia ', 'Indonesia ', 1, 'INA', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(309, 'warga_negara', 'Asing', 'Asing', 2, 'XXX', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(310, 'status_pasien', 'Pasien Baru', 'Pasien Baru', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(311, 'status_pasien', 'Pasien Lama', 'Pasien Lama', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(312, 'jenis_antrian', 'Poliklinik', 'Poliklinik', 6, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(313, 'fungsi_antrian', 'Default Pendaftaran', 'P', 1, '177', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(314, 'fungsi_antrian', 'Pasien Baru', 'PB', 2, '177', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(315, 'fungsi_antrian', 'Pasien Lama', 'PL', 3, '177', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(316, 'status_po', 'Belum Dibuat', 'Belum Dibuat', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(317, 'status_po', 'Sudah Dibuat', 'Sudah Dibuat', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(318, 'fungsi_antrian', 'Default Kasir', 'K', 6, '178', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(319, 'fungsi_antrian', 'Instalasi Kasir', 'KRJ', 7, '178', '{\"instalasi_id\":[9]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(320, 'status_po', 'Dibatalkan', 'Dibatalkan', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(321, 'fungsi_antrian', 'Default', 'DP', 9, '312', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(322, 'status_po', 'Ditolak', 'Ditolak', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(323, 'fungsi_antrian', 'Default Apotek', 'A', 11, '176', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(324, 'fungsi_antrian', 'Racikan', 'AR', 12, '176', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(325, 'fungsi_antrian', 'Non Racikan', 'ANR', 13, '176', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(326, 'fungsi_antrian', 'Apotek Cara Bayar', 'ACB', 14, '176', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(327, 'jenis_antrian', 'Pendaftaran Online', 'Pendaftaran Online', 7, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(328, 'fungsi_antrian', 'Default Penunjang', 'PEN', 16, '179', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(329, 'fungsi_antrian', 'Pasien Penunjang Lama', 'PPL', 17, '179', '{\"instalasi_id\" : [4,5,7]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(330, 'fungsi_antrian', 'Pasien Penunjang Baru', 'PPB', 18, '179', '{\"instalasi_id\" : [4,5,7]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(331, 'bahasa', 'Indonesia ', 'Indonesia ', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(332, 'bahasa', 'Arab', 'Arab', 2, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(333, 'bahasa', 'Inggris', 'Inggris', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(334, 'bahasa', 'Mandarin', 'Mandarin', 4, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(335, 'bahasa', 'Lainnya', 'Lainnya', 5, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(336, 'status_rekammedik', 'Aktif', 'Aktif', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(337, 'status_rekammedik', 'Tidak Aktif', 'Tidak Aktif', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(338, 'status_rekammedik', 'Expired', 'Expired', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(339, 'status_periksa', 'Atrian Pendaftaran', 'Atrian Pendaftaran', 5, '', '', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(340, 'jenis_kamar', 'Laki-Laki', 'Laki-Laki', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(341, 'jenis_kamar', 'Wanita', 'Wanita', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(342, 'jenis_kamar', 'Fleksibel', 'Fleksibel', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(343, 'jenis_resep', 'Penjualan Resep Bebas', 'Penjualan Resep Bebas', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(344, 'jenis_resep', 'Penjualan Resep Pasien Rumah Sakit', 'Penjualan Resep Pasien Rumah Sakit', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(345, 'jenis_resep', 'Penjualan Resep Karyawan', 'Penjualan Resep Karyawan', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(346, 'status_reseptur', 'Belum Diproses', 'Belum Diproses', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(347, 'status_reseptur', 'Sudah Diproses', 'Sudah Diproses', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(348, 'status_bayar', 'Lunas', 'Lunas', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(349, 'status_bayar', 'Belum Lunas', 'Belum Lunas', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(350, 'satuan_tindakan', 'Hari', 'Hari', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(351, 'satuan_tindakan', 'Kali', 'Kali', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(352, 'satuan_tindakan', 'Jam', 'Jam', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(353, 'status_janjipoli', 'Expired', 'Expired', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(354, 'status_janjipoli', 'Batal', 'Batal', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(355, 'status_janjipoli', 'Ditolak', 'Ditolak', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(356, 'status_janjipoli', 'Disetujui', 'Disetujui', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(357, 'status_janjipoli', 'Belum Konfirmasi', 'Belum Konfirmasi', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(358, 'status_masuk', 'Rujukan', 'Rujukan', 1, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(359, 'status_masuk', 'Non Rujukan', 'Non Rujukan', 2, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(360, 'kontras_radiologi', 'Kontras', 'Kontras', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(361, 'kontras_radiologi', 'Non Kontras', 'Non Kontras', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(362, 'kasus_diagnosa', 'Kasus Baru', 'Kasus Baru', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(363, 'kasus_diagnosa', 'Kasus Lama', 'Kasus Lama', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(364, 'ven', 'Vital', 'V', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(365, 'ven', 'Esensial', 'E', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(366, 'ven', 'Non-esensial', 'N', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(367, 'status_bookingkamar', 'Expired', 'Expired', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(368, 'status_bookingkamar', 'Batal', 'Batal', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(369, 'status_bookingkamar', 'Ditolak', 'Ditolak', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(370, 'status_bookingkamar', 'Disetujui', 'Disetujui', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(371, 'status_bookingkamar', 'Belum Konfirmasi', 'Belum Konfirmasi', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(372, 'jenis_rl', 'RL1.1 Data Dasar Rumah Sakit', 'RL1.1 Data Dasar Rumah Sakit', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(373, 'jenis_rl', 'RL1.2 Indikator Pelayanan Rumah Sakit', 'RL1.2 Indikator Pelayanan Rumah Sakit', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(374, 'jenis_rl', 'RL1.3 Fasilitas Tempat Tidur Rawat Inap', 'RL1.3 Fasilitas Tempat Tidur Rawat Inap', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(375, 'jenis_rl', 'RL2 Ketenagaan', 'RL2 Ketenagaan', 4, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(376, 'jenis_rl', 'RL3.1 Kegiatan Pelayanan Rawat Inap', 'RL3.1 Kegiatan Pelayanan Rawat Inap', 5, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(377, 'jenis_rl', 'RL3.2 Kegiatan Pelayanan Rawat Darurat', 'RL3.2 Kegiatan Pelayanan Rawat Darurat', 6, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(378, 'jenis_rl', 'RL3.3 Gigi dan Mulut', 'RL3.3 Gigi dan Mulut', 7, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(379, 'jenis_rl', 'RL3.4 Kebidanan', 'RL3.4 Kebidanan', 8, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(380, 'jenis_rl', 'RL3.5 Perinatologi', 'RL3.5 Perinatologi', 9, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(381, 'jenis_rl', 'RL3.6 Pembedahan', 'RL3.6 Pembedahan', 10, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(382, 'jenis_rl', 'RL3.7 Radiologi', 'RL3.7 Radiologi', 11, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(383, 'jenis_rl', 'RL3.8 Laboratorium', 'RL3.8 Laboratorium', 12, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(384, 'jenis_rl', 'RL3.9 Rehabilitasi Medik', 'RL3.9 Rehabilitasi Medik', 13, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(385, 'jenis_rl', 'RL3.10 Pelayanan Khusus', 'RL3.10 Pelayanan Khusus', 14, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(386, 'jenis_rl', 'RL3.11 Kesehatan Jiwa', 'RL3.11 Kesehatan Jiwa', 15, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(387, 'jenis_rl', 'RL3.12 Keluarga Berancana', 'RL3.12 Keluarga Berancana', 16, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(388, 'jenis_rl', 'RL3.13 Farmasi Rumah Sakit', 'RL3.13 Farmasi Rumah Sakit', 17, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(389, 'jenis_rl', 'RL3.14 Rujukan', 'RL3.14 Rujukan', 18, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(390, 'jenis_rl', 'RL3.15 Cara Bayar', 'RL3.15 Cara Bayar', 19, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(391, 'jenis_rl', 'RL4a Morbiditas Rawat Inap', 'RL4a Morbiditas Rawat Inap', 20, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(392, 'jenis_rl', 'RL4b Morbiditas Rawat Jalan', 'RL4b Morbiditas Rawat Jalan', 21, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(393, 'jenis_rl', 'RL5.1 Pengunjung Rumah Sakit', 'RL5.1 Pengunjung Rumah Sakit', 22, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(394, 'jenis_rl', 'RL5.2 Kunjungan Rawat Jalan', 'RL5.2 Kunjungan Rawat Jalan', 23, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(395, 'jenis_rl', 'RL5.3 Daftar 10 Besar Penyakit Rawat Inap', 'RL5.3 Daftar 10 Besar Penyakit Rawat Inap', 24, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(396, 'jenis_rl', 'RL5.4 Daftar 10 Besar Penyakit Rawat Jalan', 'RL5.4 Daftar 10 Besar Penyakit Rawat Jalan', 25, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(397, 'status_pesan', '-', '-', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(398, 'status_pesan', 'Belum Dikirim', 'Belum Dikirim', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(399, 'status_pesan', 'Sudah Dikirim', 'Sudah Dikirim', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(400, 'status_mutasi', 'Sudah Diterima', 'Sudah Diterima', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(401, 'status_mutasi', 'Belum Diterima', 'Belum Diterima', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(402, 'status_periksa', 'Batal Periksa', 'Batal Periksa', 6, '', '{\"instalasi_id\" : [1,2,3]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(403, 'metode_bayar', 'Tunai & Transfer', 'Tunai & Transfer', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(404, 'kondisi_barang', 'Baik', 'Baik', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(405, 'kondisi_barang', 'Rusak', 'Rusak', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(406, 'kondisi_barang', 'Expired', 'Expired', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(407, 'bpjs', 'url', 'https://dvlp.bpjs-kesehatan.go.id/vClaim-rest/', 1, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(408, 'bpjs', 'cons_id', '32053', 2, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(409, 'bpjs', 'secret_key', '7aWA5BBC47', 3, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(410, 'bpjs', 'ppkPelayanan', '0114R033', 4, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(411, 'status_periksa', 'Batal Konsultasi', 'Batal Konsultasi', 7, NULL, '{\"instalasi_id\" : [1]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(412, 'isantrian', 'pendaftaran', 'false', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(413, 'isantrian', 'poli', 'true', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(414, 'null', '-', '-', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(415, 'asd_type', 'asd_name', 'asd_value', 1, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(416, 'limit_antrian', 'Limit Pemanggilan Antrian', '4', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(417, 'group_carabayar', 'Pribadi', 'U', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(418, 'group_carabayar', 'BPJS', 'B', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(419, 'group_carabayar', 'Jaminan / Asuransi', 'A', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(420, 'status_kirim', 'Belum Diterima', 'Belum Diterima', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(421, 'status_kirim', 'Sudah Diterima', 'Sudah Diterima', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(422, 'transportasi', 'Mobil', 'Mobil', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(423, 'transportasi', 'Motor', 'Motor', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(424, 'satuan_tindakan', 'KALI', 'KALI', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(425, 'satuan_tindakan', 'HARI', 'HARI', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(426, 'satuan_tindakan', 'JAM', 'JAM', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(427, 'metode_harga', 'MIN', 'MIN', 1, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(428, 'metode_harga', 'MAX', 'MAX', 2, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(429, 'metode_harga', 'AVERAGE', 'AVERAGE', 3, '', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(430, 'status_periksa', 'Antrian Kasir', 'Antrian Kasir', 8, NULL, '{\"instalasi_id\" : [1]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(431, 'jenis_kamar', 'Campur', 'Campur', 4, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(432, 'status_reseptur', 'Batal Reseptur', 'Batal Reseptur', 3, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(433, 'status_periksa', 'Rujuk Rawat Inap', 'Rujuk Rawat Inap', NULL, NULL, '{\"instalasi_id\" : [1,2]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(434, 'jenis_konsul', 'Konsul 1 Kali', 'Konsul 1 Kali', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(435, 'jenis_konsul', 'Rawat Bersama', 'Rawat Bersama', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(436, 'jenis_konsul', 'Alih Rawat', 'Alih Rawat', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(437, 'status_mintakonsul', 'Setuju', 'Setuju', NULL, NULL, '{\"instalasi_id\" : [2,3]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(438, 'status_mintakonsul', 'Tidak Setuju', 'Tidak Setuju', NULL, NULL, '{\"instalasi_id\" : [2,3]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(439, 'status_mintakonsul', 'Batal', 'Batal', NULL, NULL, '{\"instalasi_id\" : [2,3]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(440, 'status_ranap', 'Belum Periksa', 'Belum Periksa', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(441, 'status_ranap', 'Periksa', 'Periksa', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(442, 'jenis_input', 'Title', 'title', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(443, 'jenis_input', 'Text Field', 'textfield', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(444, 'jenis_input', 'Check Box', 'checkbox', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(445, 'jenis_input', 'Radio', 'radio', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(446, 'jenis_input', 'Dropdown', 'dropdwon', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(447, 'jenis_input', 'Text Area', 'text_area', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(448, 'jenis_input', 'Date Picker', 'datepicker', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(449, 'jenis_input', 'Date Time Picker', 'datetime', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(450, 'jenis_input', 'Number Field', 'number', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(451, 'jenis_input', 'Summary', 'summary', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(452, 'jenis_input', 'Button Group', 'bottongroup', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(453, 'status_ranap', 'Batal Rawat', 'Batal Rawat', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(454, 'status_implementasi', 'Belum Implementasi', 'BELUM', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(455, 'status_implementasi', 'Sudah Implementasi', 'SUDAH', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(456, 'status_implementasi', 'Belum Selesai Implementasi', 'BELUM SELESAI', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(457, 'jenis_instruksi', 'TINDAKAN', 'TINDAKAN', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(458, 'jenis_instruksi', 'OBAT', 'OBAT', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(459, 'jenis_instruksi', 'PENUNJANG', 'PENUNJANG', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(460, 'separator', '+', '+', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(461, 'separator', '-', '-', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(462, 'efek_obat', 'Tetap (Keluhan Tetap)', 'Tetap', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(463, 'efek_obat', 'Keluhan Berkurang', 'Keluhan Berkurang ', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(464, 'efek_obat', 'Keluhan Bertambah', 'Keluhan Bertambah', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(465, 'efek_obat', 'Tidak Ada Keluhan', 'Tidak Ada Keluhan', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(466, 'ket_pemberian', 'A - Tidak Diberikan', 'A - Tidak Diberikan', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(467, 'ket_pemberian', 'M - Muntah', 'M - Muntah', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(468, 'ket_pemberian', 'P - Puasa', 'P - Puasa', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(469, 'ket_pemberian', 'T - Pasien Menolak', 'T - Pasien Menolak', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(470, 'status_penunjang', 'BELUM DISETUJUI', 'BELUM DISETUJUI', NULL, NULL, '{\"instalasi_id\" : [4,5,12]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(471, 'status_penunjang', 'SUDAH DISETUJUI', 'SUDAH DISETUJUI', NULL, NULL, '{\"instalasi_id\" : [4,5,12]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(472, 'status_penunjang', 'BATAL', 'BATAL', NULL, NULL, '{\"instalasi_id\" : [4,5]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(473, 'status_periksa_penunjang', 'PERIKSA', 'PERIKSA', NULL, 'LAB,RAD', '{\"instalasi_id\" : [4,5]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(474, 'status_periksa_penunjang', 'AMBIL SAMPLE', 'AMBIL SAMPLE', NULL, 'LAB', '{\"instalasi_id\" : [4]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(475, 'status_periksa_penunjang', 'SELESAI', 'SELESAI', NULL, 'LAB,RAD', '{\"instalasi_id\" : [4,5]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(476, 'status_periksa_penunjang', 'BATAL', 'BATAL', NULL, 'LAB,RAD,IBS', '{\"instalasi_id\" : [4,5,12]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(477, 'status_periksa_penunjang', 'BELUM PERIKSA', 'BELUM PERIKSA', NULL, 'LAB,RAD', '{\"instalasi_id\" : [4,5]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(478, 'label_gelang', 'Resiko Jatuh', '#FFD700', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(479, 'label_gelang', 'Alergi', '#8B0000', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(480, 'label_gelang', 'DNR', '#8A2BE2', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(481, 'label_gelang', 'Tanggal Lahir Sama', '#8B4513', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(482, 'status_periksa_penunjang', 'SEDANG OPERASI', 'SEDANG OPERASI', NULL, 'IBS', '{\"instalasi_id\" : [12]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(483, 'status_periksa_penunjang', 'SUDAH OPERASI', 'SUDAH OPERASI', NULL, 'IBS', '{\"instalasi_id\" : [12]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(484, 'jenis_dokter', 'Dokter Konsul', 'Dokter Konsul', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(485, 'jenis_dokter', 'Dokter PJ', 'Dokter PJ', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(486, 'status_periksa', 'Belum Periksa', 'Belum Periksa', NULL, NULL, '{\"instalasi_id\" : [1,2,3]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(487, 'status_ranap', 'Pulang', 'Pulang', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(488, 'status_periksa_penunjang', 'BELUM OPERASI', 'BELUM OPERASI', NULL, 'IBS', '{\"instalasi_id\" : [12]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(489, 'ket_pemberian', 'D - Dikonsumsi', 'D - Dikonsumsi', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(490, 'kesadaran_umum', 'Memuaskan', 'Memuaskan', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(491, 'kesadaran_umum', 'Jelek', 'Jelek', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(492, 'kesadaran_umum', 'Lain-lain', 'Lain-lain', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(493, 'tingkat_kesadaran', 'Terjaga', 'Terjaga', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(494, 'tingkat_kesadaran', 'Mudah Dibangunkan', 'Mudah Dibangunkan', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(495, 'tingkat_kesadaran', 'Lain-lain', 'Lain-lain', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(496, 'jalan_napas', 'Oral', 'Oral', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(497, 'jalan_napas', 'Nasal', 'Nasal', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(498, 'jalan_napas', 'Lain-lain', 'Lain-lain', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(499, 'terapi_oksigen', 'Oral', 'Oral', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(500, 'terapi_oksigen', 'Kanula Hidung', 'Kanula Hidung', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(501, 'terapi_oksigen', 'Lain-lain', 'Lain-lain', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(502, 'keadaan_kulit', 'Kering/lembab', 'Kering/lembab', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(503, 'keadaan_kulit', 'Merah Muda', 'Merah Muda', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(504, 'keadaan_kulit', 'Lain-lain', 'Lain-lain', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(505, 'sirkulasi_badan', 'Merah Muda', 'Merah Muda', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(506, 'sirkulasi_badan', 'Kebiru-biruan', 'Kebiru-biruan', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(507, 'sirkulasi_badan', 'Lain-lain', 'Lain-lain', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(508, 'tim_operasi', 'Dokter Bedah', 'Dokter Bedah', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(509, 'tim_operasi', 'Asisten Bedah 1', 'Asisten Bedah 1', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(510, 'tim_operasi', 'Asisten Bedah 2', 'Asisten Bedah 2', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(511, 'tim_operasi', 'Dokter Anastesi', 'Dokter Anastesi', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(512, 'tim_operasi', 'Asisten Anastesi', 'Asisten Anastesi', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(513, 'tim_operasi', 'Perawat Instrumen 1', 'Perawat Instrumen 1', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(514, 'tim_operasi', 'Perawat Instrumen 2', 'Perawat Instrumen 2', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(515, 'tim_operasi', 'Perawat Sirkuler 1', 'Perawat Sirkuler 1', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(516, 'tim_operasi', 'Perawat Sirkuler 2', 'Perawat Sirkuler 2', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(517, 'tim_operasi', 'Perawat Anastesi', 'Perawat Anastesi', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(518, 'jenis_luka', 'Luka Bersih', 'Luka Bersih', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(519, 'jenis_luka', 'Luka Bersih Terkontaminasi', 'Luka Bersih Terkontaminasi', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(520, 'jenis_luka', 'Luka Terkontaminasi', 'Luka Terkontaminasi', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(521, 'jenis_luka', 'Luka Kotor / Terinfeksi', 'Luka Kotor / Terinfeksi', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(522, 'keadaan_kulit', 'Utuh', 'Utuh', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(523, 'keadaan_kulit', 'Menggelembung', 'Menggelembung', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(524, 'posisi_operasi', 'Supine / Terlentang', 'Supine / Terlentang', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(525, 'posisi_operasi', 'Prone / Telungkup', 'Prone / Telungkup', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(526, 'posisi_operasi', 'Lithotomi', 'Lithotomi', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(527, 'posisi_operasi', 'Fowler / Duduk', 'Fowler / Duduk', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(528, 'posisi_operasi', 'Lumbotomi / Miring', 'Lumbotomi / Miring', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(529, 'posisi_operasi', 'Trendelenburg', 'Trendelenburg', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(530, 'posisi_operasi', 'Knee-chest', 'Knee-chest', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(531, 'posisi_operasi', 'Jack-knife', 'Jack-knife', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(532, 'posisi_operasi', 'Miring Kiri', 'Miring Kiri', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(533, 'pencucian_operasi', 'Braunoderm', 'Braunoderm', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(534, 'pencucian_operasi', 'Triclosan 2%', 'Triclosan 2%', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(535, 'pencucian_operasi', 'Alcohol 70%', 'Alcohol 70%', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(536, 'pencucian_operasi', 'Povidone Lodine 10%', 'Povidone Lodine 10%', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(537, 'posisi_elektroda', 'Bokong / Kaki', 'Bokong / Kaki', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(538, 'posisi_elektroda', 'Paha / Kaki', 'Paha / Kaki', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(539, 'posisi_elektroda', 'Lain-Lain', 'Lain-Lain', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(540, 'status_periksa', 'Set Dokter Jaga', 'Set Dokter Jaga', NULL, NULL, '{\"instalasi_id\" : [2]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(541, 'status_penunjang', 'DITOLAK', 'DITOLAK', NULL, NULL, '{\"instalasi_id\" : [12]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(542, 'warna_kulit', 'Hitam', 'Hitam', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(543, 'warna_kulit', 'Putih', 'Putih', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(544, 'warna_kulit', 'Kuning Langsat', 'Kuning Langsat', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(545, 'status_mintakonsul', 'Belum Proses', 'Belum Proses', NULL, NULL, '{\"instalasi_id\" : [2]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(546, 'status_gantidokter', 'Belum Aktif', 'Belum Aktif', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(547, 'status_gantidokter', 'Aktif', 'Aktif', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(548, 'status_gantidokter', 'Tidak Aktif', 'Tidak Aktif', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(549, 'status_verifikasi', 'Belum Dikoreksi', 'Belum Dikoreksi', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(550, 'status_verifikasi', 'Sudah Dikoreksi', 'Sudah Dikoreksi', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(551, 'status_verifikasi', 'Sudah Final Klaim', 'Sudah Final Klaim', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(552, 'pengajuan_klaim', 'Pengajuan', 'Pengajuan', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(553, 'pengajuan_klaim', 'Proses Penerimaan', 'Proses Penerimaan', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(554, 'pengajuan_klaim', 'Sudah Penerimaan', 'Sudah Penerimaan', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(555, 'pengajuan_klaim', 'Batal Alokasi Pembayaran', 'Batal Alokasi Pembayaran', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(556, 'status_verifikasi', 'Proses Klaim', 'Proses Klaim', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(557, 'metode_nyeri', 'NRS', 'NRS', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(558, 'metode_nyeri', 'WBF', 'WBF', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(559, 'metode_nyeri', 'BPS', 'BPS', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(560, 'metode_nyeri', 'NIPS', 'NIPS', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(561, 'metode_nyeri', 'FLACC', 'FLACC', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(562, 'golongan_barang', 'Inventaris', 'Inventaris', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(563, 'golongan_barang', 'Pengadaan', 'Pengadaan', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(564, 'status_daftar_ol', 'Belum Diproses', 'Belum Diproses', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(565, 'status_daftar_ol', 'Disetujui', 'Disetujui', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(566, 'status_daftar_ol', 'Ditolak', 'Ditolak', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(567, 'carapulang_inacbg', 'Atas Persetujuan Dokter', '1', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(568, 'carapulang_inacbg', 'Dirujuk', '2', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(569, 'carapulang_inacbg', 'Atas Permintaan Sendiri', '3', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(570, 'carapulang_inacbg', 'Meninggal', '4', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(571, 'carapulang_inacbg', 'Lain-lain', '5', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(572, 'status_penerimaan_po', 'Belum Diterima', 'Belum Diterima', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(573, 'status_penerimaan_po', 'Belum Semua Diterima', 'Belum Semua Diterima', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(574, 'status_penerimaan_po', 'Sudah Semua Diterima', 'Sudah Semua Diterima', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(575, 'status_penerimaan_po', 'Dibatalkan', 'Dibatalkan', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(576, 'pengajuan_klaim', 'Alokasi Pembayaran', 'Alokasi Pembayaran', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(577, 'status_periksa_penunjang', 'DITERIMA', 'DITERIMA', NULL, 'JNZ', '{\"instalasi_id\" : [16]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(578, 'status_periksa_penunjang', 'DIPROSES', 'DIPROSES', NULL, 'JNZ', '{\"instalasi_id\" : [16]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(579, 'status_periksa_penunjang', 'DISERAHKAN', 'DISERAHKAN', NULL, 'JNZ', '{\"instalasi_id\" : [16]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(580, 'status_penerimaan_po', 'Closing Supplier', 'Closing Supplier', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(581, 'status_periksa_penunjang', 'BELUM DITERIMA', 'BELUM DITERIMA', NULL, 'JNZ', '{\"instalasi_id\" : [16]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(582, 'status_periksa_penunjang', 'PERSETUJUAN', 'PERSETUJUAN', NULL, 'JNZ', '{\"instalasi_id\" : [16]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(583, 'antrian_farmasi', 'Belum Proses', 'Belum Proses', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(584, 'antrian_farmasi', 'Sedang Proses', 'Sedang Proses', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(585, 'antrian_farmasi', 'Siap Ambil', 'Siap Ambil', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(586, 'antrian_farmasi', 'Selesai', 'Selesai', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(587, 'waktu', 'Pagi', 'Pagi', 1, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(588, 'waktu', 'Siang', 'Siang', 2, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(589, 'waktu', 'Sore', 'Sore', 3, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(590, 'waktu', 'Malam', 'Malam', 4, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(591, 'status_ambulan', 'Tersedia', 'Tersedia', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(592, 'status_ambulan', 'Dipesan', 'Dipesan', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(593, 'status_ambulan', 'SedangDipakai', 'SedangDipakai', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(594, 'pelayanan_ambulan', 'Antar', 'Antar', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(595, 'pelayanan_ambulan', 'Jemput', 'Jemput', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(596, 'pelayanan_ambulan', 'Event', 'Event', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(597, 'kuota_antrian', 'Kuota Poliklinik', 'Kuota Poliklinik', NULL, '0', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(598, 'kuota_antrian', 'Kuota Dokter', 'Kuota Dokter', NULL, '1', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(599, 'kuota_antrian', 'Tanpa Kuota', 'Tanpa Kuota', NULL, '2', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(600, 'golongan_darah', 'Tidak Tahu', 'Tidak Tahu', 5, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(601, 'jenis_identitas', 'BPJS', 'BPJS', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(602, 'status_pesan', 'Batal', 'Batal', 4, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(603, 'pengambilan_darah', 'Manual', 'Manual', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(604, 'pengambilan_darah', 'Optipres', 'Optipres', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(605, 'pengambilan_darah', 'Apheresis ', 'Apheresis ', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(606, 'status_pesanambulan', 'BELUM DIPROSES', 'BELUM DIPROSES', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(607, 'status_pesanambulan', 'SUDAH DIPROSES', 'SUDAH DIPROSES', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(608, 'status_pesanambulan', 'BATAL', 'BATAL', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(609, 'status_pesandarah', 'Belum Diproses', 'Belum Diproses', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(610, 'status_pesandarah', 'Crossmatch', 'Crossmatch', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(611, 'status_pesandarah', 'Mutasi', 'Mutasi', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(612, 'status_pesandarah', 'Telah Diterima', 'Telah Diterima', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(613, 'keterangan_history_tt', 'Penambahan', 'Penambahan', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(614, 'keterangan_history_tt', 'Penghapusan', 'Penghapusan', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(615, 'keterangan_history_tt', 'Pengaktifan', 'Pengaktifan', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(616, 'keterangan_history_tt', 'Pengnon-Aktifan', 'Pengnon-Aktifan', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(617, 'keterangan_history_tt', 'Pemindaham Ke', 'Pemindaham Ke', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(618, 'keterangan_history_tt', 'Pemindahan Dari', 'Pemindahan Dari', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(619, 'group_jenisobat', 'Obat', 'Obat', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(620, 'group_jenisobat', 'Alkes', 'Alkes', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(621, 'jenis_reservasi', 'Pendaftaran Online', 'Pendaftaran Online', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(622, 'jenis_reservasi', 'Reservasi ', 'Reservasi', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(623, 'jenis_reservasi', 'Rencana Kontrol', 'Rencana Kontrol', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(624, 'ket_hargaobat', 'Penerimaan Obat Manual', 'Penerimaan Obat', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(625, 'ket_hargaobat', 'Adjusment Obat', 'Adjusment Obat', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(626, 'ket_hargaobat', 'Perubahan Manual', 'Perubahan Manual', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(627, 'ket_hargaobat', 'Penerimaan Obat Supplier', 'Penerimaan Obat Supplier', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(628, 'status_periksa', 'Batal Kunjungan', 'Batal Kunjungan', NULL, NULL, '{\"instalasi_id\" : [1,2,3]}', CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(629, 'null', '-', '-', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(630, 'null', '-', '-', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(631, 'bpjs_asal_rujukan', 'Faskes Tingkat 1', '1', 1, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(632, 'bpjs_asal_rujukan', 'Faskes Tingkat 2', '2', 2, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(633, 'bpjs_pelayanan', 'Rawat Jalan', '2', 1, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(634, 'bpjs_pelayanan', 'Rawat Inap', '1', 2, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(635, 'bpjs_kasus_kecelakaan', 'Bukan Kecelakaan', '1', 1, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(636, 'bpjs_kasus_kecelakaan', 'Kecelakaan Lalulintas dan bukan kecelakaan kerja', '2', 2, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(637, 'bpjs_kasus_kecelakaan', 'Kecelakaan Lalulintas dan kecelakaan kerja', '3', 3, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(638, 'bpjs_kasus_kecelakaan', 'Kecelakaan kerja', '4', 4, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(639, 'kode_tarifbpjs', 'Tarif RS Kelas A Pemerintah', 'AP', NULL, 'AP', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(640, 'kode_tarifbpjs', 'Tarif RS Kelas A Swasta', 'AS', NULL, 'AS', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(641, 'kode_tarifbpjs', 'Tarif RS Kelas B Pemerintah', 'BP', NULL, 'BP', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(642, 'kode_tarifbpjs', 'Tarif RS Kelas B Swasta', 'BS', NULL, 'BS', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(643, 'kode_tarifbpjs', 'Tarif RS Kelas C Pemerintah', 'CP', NULL, 'CP', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(644, 'kode_tarifbpjs', 'Tarif RS Kelas C Swasta', 'CS', NULL, 'CS', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(645, 'kode_tarifbpjs', 'Tarif RS Kelas D Pemerintah', 'DP', NULL, 'DP', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(646, 'kode_tarifbpjs', 'Tarif RS Kelas D Swasta', 'DS', NULL, 'DS', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(647, 'bpjs_periode', 'Waktu Pulang', '1', 1, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(648, 'bpjs_periode', 'Waktu Masuk', '2', 2, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(649, 'bpjs_saverity', 'Saverity 0', '0', 0, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(650, 'bpjs_saverity', 'Saverity 1', '1', 1, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(651, 'bpjs_saverity', 'Saverity 2', '2', 2, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(652, 'bpjs_saverity', 'Saverity 3', '3', 3, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(653, 'logactivity_aksi', 'tambah', 'tambah', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(654, 'logactivity_aksi', 'hapus', 'hapus', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(655, 'logactivity_tipe', 'tindakan', 'tindakan', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(656, 'logactivity_tipe', 'BMHP', 'BMHP', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(657, 'logactivity_tipe', 'Paket', 'Paket', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(658, 'logactivity_tipe', 'Penjamin', 'Penjamin', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(659, 'logactivity_tipe', 'Catatan', 'Catatan', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(660, 'status_reseptur', 'Diserahkan', 'Diserahkan', 4, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(661, 'kesimpulan', 'Sehat', 'Sehat', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(662, 'kesimpulan', 'Sehat Dengan Catatan', 'Sehat Dengan Catatan', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(663, 'kesimpulan', 'Tidak Sehat', 'Tidak Sehat', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL),
(9999, 'null', '-', '-', NULL, NULL, NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, 'f', 't', NULL, NULL);

");


    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m200131_064632_seeder_lookup_m cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m200131_064632_seeder_lookup_m cannot be reverted.\n";

        return false;
    }
    */
}
