<?php

use yii\db\Migration;

/**
 * Class m201020_031456_oddo_tabelrekap_20201020
 */
class m201020_031456_oddo_tabelrekap_20201020 extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->execute('CREATE TABLE IF NOT EXISTS "public"."adjusmenobatkeluar_r" (
  "id" serial8,
  "adjusmenobatkeluar_id" int4,
  "adjusmenobat_id" int4,
  "obatalkes_id" int4,
  "qty" int4,
  "satuankecil_id" int4,
  "alasan" text COLLATE "pg_catalog"."default",
  "satuanbesar_id" int4,
  "qty_konversi" int4,
  "satuankonversi_id" int4,
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "no_batch" varchar(255) COLLATE "pg_catalog"."default",
  "keterangan" text COLLATE "pg_catalog"."default",
  "keterangan_rekap" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  CONSTRAINT "adjusmentkeluar_r_pkey" PRIMARY KEY ("id")
)
;');

        $this->execute('CREATE TABLE IF NOT EXISTS "public"."adjusmenobatmasuk_r" (
  "id" serial8,
  "adjusmenobatmasuk_id" int4,
  "adjusmenobat_id" int4,
  "obatalkes_id" int4,
  "tgl_kadaluarsa" timestamp(0),
  "qty" int4,
  "satuankecil_id" int4,
  "harga_netto" float8,
  "satuanbesar_id" int4,
  "qty_konversi" int4,
  "satuankonversi_id" int4,
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "no_batch" varchar(100) COLLATE "pg_catalog"."default",
  "keterangan" text COLLATE "pg_catalog"."default",
  "keterangan_rekap" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  CONSTRAINT "adjusmenobatmasuk_r_pkey" PRIMARY KEY ("id")
)
;');

        $this->execute('CREATE TABLE IF NOT EXISTS "public"."bayaruangmuka_r" (
  "id" serial8,
  "bayaruangmuka_id" int4,
  "pembatalanuangmuka_id" int4,
  "pasienadmisi_id" int4,
  "pemakaianuangmuka_id" int4,
  "tandabuktibayar_id" int4,
  "ruangan_id" int4,
  "pasien_id" int4,
  "pendaftaran_id" int4,
  "tgl_uangmuka" timestamp(6),
  "jumlah_uangmuka" float8,
  "keterangan_uangmuka" text COLLATE "pg_catalog"."default",
  "tgl_perjanjian" date,
  "keterangan_perjanjian" varchar(200) COLLATE "pg_catalog"."default",
  "pembayarankapitasidetail_id" int4,
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool DEFAULT false,
  "is_active" bool DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "no_uangmuka" varchar(50) COLLATE "pg_catalog"."default",
  "pengembalianuangmuka_id" int4,
  "metode_pembayaran" int2,
  "jenisnontunai_id" int4,
  "keterangan" text COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(0) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sending" bool DEFAULT false,
  "is_sent" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  "is_sending_scr" bool DEFAULT false,
  "is_sent_scr" bool DEFAULT false,
  "id_sync_sercon_scr" text COLLATE "pg_catalog"."default",
  "sync_respon_scr" text COLLATE "pg_catalog"."default",
  CONSTRAINT "bayaruangmuka_r_pkey" PRIMARY KEY ("id")
)
;');

        $this->execute('CREATE TABLE IF NOT EXISTS "public"."int_obatalkespasien_r" (
  "id" serial8,
  "obatalkespasien_id" int4,
  "sumberdana_id" int4,
  "racikan_id" int4,
  "returresepdetail_id" int4,
  "tipepaket_id" int4,
  "ruangan_id" int4,
  "carabayar_id" int4,
  "pegawai_id" int4,
  "daftartindakan_id" int4,
  "tindakanpelayanan_id" int4,
  "satuankecil_id" int4,
  "shift_id" int4,
  "pendaftaran_id" int4,
  "obatalkes_id" int4,
  "pasien_id" int4,
  "penjamin_id" int4,
  "kelaspelayanan_id" int4,
  "pasienanastesi_id" int4,
  "pasienmasukpenunjang_id" int4,
  "pasienadmisi_id" int4,
  "obatsudahbayar_id" int4,
  "penjualanresep_id" int4,
  "tglpelayanan" timestamp(6),
  "r" char(1) COLLATE "pg_catalog"."default",
  "rke" int2,
  "permintaan_oa" int4,
  "jmlkemasan_oa" int4,
  "kekuatan_oa" int4,
  "satuankekuatan_oa" varchar COLLATE "pg_catalog"."default",
  "qty_oa" float8,
  "hargasatuan_oa" float8,
  "signa_oa" varchar(53) COLLATE "pg_catalog"."default",
  "harganetto_oa" float8,
  "hargajual_oa" float8,
  "etiket" varchar COLLATE "pg_catalog"."default",
  "jmlexposerad" float8,
  "kontrasrad" varchar COLLATE "pg_catalog"."default",
  "biayaservice" float8,
  "biayakonseling" float8,
  "jasadokterresep" float8,
  "biayakemasan" float8,
  "biayaadministrasi" float8,
  "tarifcyto" float8,
  "discount" float8,
  "subsidiasuransi" float8,
  "subsidipemerintah" float8,
  "subsidirs" float8,
  "iurbiaya" float8,
  "oa" char(1) COLLATE "pg_catalog"."default",
  "pembulatan" float8,
  "verifikasitagihan_id" int4,
  "jurnalrekening_id" int4,
  "permohonanoadetail_id" int4,
  "persenppnjual" int4,
  "resepturdetail_id" int4,
  "nilaippnjual" float8,
  "perawat1_id" int4,
  "perawat2_id" int4,
  "instruksitindakanbmhp_id" int4,
  "implementasi_id" int4,
  "is_dilakukan" bool DEFAULT false,
  "pemakaianambulan_id" int4,
  "is_jurnal" bool DEFAULT false,
  "konfigmargindetail_id" int4,
  "qty_konversi" float8,
  "is_penatajasa" bool,
  "det" float8,
  "status_bmhp" int2,
  "det_konversi" float8,
  "signa" json,
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "keterangan" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "no_obatalkespasien" varchar(255) COLLATE "pg_catalog"."default",
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  CONSTRAINT "int_obatalkespasien_r_pkey" PRIMARY KEY ("id")
)
;');

        $this->execute('
            CREATE TABLE IF NOT EXISTS "public"."int_pendaftaranbmhp_r" (
  "id" serial8,
  "pendaftaran_id" int4,
  "no_pendaftaran" varchar(20) COLLATE "pg_catalog"."default",
  "tgl_pendaftaran" timestamp(6),
  "pasienpulang_id" int4,
  "pasienbatalperiksa_id" int4,
  "penanggungjawab_id" int4,
  "penjamin_id" int4,
  "shift_id" int4,
  "pasien_id" int4,
  "persalinan_id" int4,
  "pegawai_id" int4,
  "instalasi_id" int4,
  "caramasuk_id" int4,
  "jeniskasuspenyakit_id" int4,
  "pembayaranpelayanan_id" int4,
  "kelaspelayanan_id" int4,
  "carabayar_id" int4,
  "pasienadmisi_id" int4,
  "golonganumur_id" int4,
  "rujukan_id" int4,
  "antrian_id" int4,
  "karcis_id" int4,
  "ruangan_id" int4,
  "no_urutantri" varchar(6) COLLATE "pg_catalog"."default",
  "transportasi" varchar(50) COLLATE "pg_catalog"."default" DEFAULT 9999,
  "keadaan_masuk" varchar(50) COLLATE "pg_catalog"."default" DEFAULT 9999,
  "status_periksa" varchar(50) COLLATE "pg_catalog"."default",
  "status_pasien" varchar(50) COLLATE "pg_catalog"."default",
  "kunjungan" varchar(50) COLLATE "pg_catalog"."default",
  "alih_status" bool DEFAULT false,
  "by_phone" bool DEFAULT false,
  "kunjungan_rumah" bool DEFAULT false,
  "status_masuk" varchar(50) COLLATE "pg_catalog"."default",
  "umur" varchar(30) COLLATE "pg_catalog"."default",
  "tgl_selesaiperiksa" timestamp(6),
  "keterangan_pendaftaran" text COLLATE "pg_catalog"."default",
  "nopendaftaran_aktif" bool DEFAULT true,
  "status_konfirmasi" varchar(50) COLLATE "pg_catalog"."default" DEFAULT 664,
  "tgl_konfirmasi" timestamp(6),
  "tgl_renkontrol" timestamp(6),
  "status_farmasi" bool DEFAULT false,
  "panggil_antrian" bool DEFAULT false,
  "asuransipasien_id" int4,
  "tgl_akandilayani" timestamp(6),
  "statusdok_rekammedik" varchar(50) COLLATE "pg_catalog"."default" DEFAULT 336,
  "bpjs_id" int4,
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool DEFAULT false,
  "is_active" bool DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "status_bayar" int4 DEFAULT 349,
  "is_aps" bool,
  "label_gelang" text COLLATE "pg_catalog"."default",
  "is_karcis" bool DEFAULT true,
  "tgl_masukperiksa" timestamp(0),
  "status_verifikasi" int4 DEFAULT 549,
  "is_ranap" bool DEFAULT false,
  "is_skd" bool DEFAULT false,
  "pendaftaranibu_id" int4,
  "is_skl" bool DEFAULT false,
  "catatan_penatajasa" text COLLATE "pg_catalog"."default",
  "is_stopakomodasi" bool DEFAULT false,
  "tgl_stopakomodasi" timestamp(0),
  "is_bsl" bool DEFAULT false,
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  "keterangan" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  CONSTRAINT "int_pendaftaranbmhp_r_pkey" PRIMARY KEY ("id")
)
;');

        $this->execute('
            CREATE TABLE IF NOT EXISTS "public"."int_penjualanresep_r" (
  "id" serial8,
  "penjualanresep_id" int4,
  "pasienadmisi_id" int4,
  "pegawai_id" int4,
  "pendaftaran_id" int4,
  "returresep_id" int4,
  "kelaspelayanan_id" int4,
  "penjamin_id" int4,
  "pasien_id" int4,
  "carabayar_id" int4,
  "ruangan_id" int4,
  "reseptur_id" int4,
  "shift_id" int4,
  "tglpenjualan" timestamp(6),
  "jenispenjualan" varchar COLLATE "pg_catalog"."default",
  "tglresep" timestamp(6),
  "noresep" varchar COLLATE "pg_catalog"."default",
  "totharganetto" float8,
  "totalhargajual" float8,
  "totaltarifservice" float8,
  "biayaadministrasi" float8,
  "biayakonseling" float8,
  "pembulatanharga" float8,
  "jasadokterresep" float8,
  "discount" float8,
  "subsidiasuransi" float8,
  "subsidipemerintah" float8,
  "subsidirs" float8,
  "iurbiaya" float8,
  "lamapelayanan" int4,
  "penjpasienpegawai_id" int4,
  "penjpasienruangan_id" int4,
  "antrianfarmasi_id" int4,
  "permohonanoa_id" int4,
  "takaranresep" float8,
  "isresepperawatan" bool,
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool DEFAULT false,
  "is_active" bool DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "iter" float4,
  "nama_pembeli" varchar(255) COLLATE "pg_catalog"."default",
  "pegawairesep_id" int4,
  "karyawan_id" int4,
  "catatan" text COLLATE "pg_catalog"."default",
  "status_bayar" int2 DEFAULT 349,
  "status_reseptur" int2 DEFAULT 347,
  "antrian_id" int4,
  "pembatalanresep_id" int4,
  "status_worklist" int2 DEFAULT 674,
  "tgl_lahir" date,
  "log_user" json,
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  "keterangan" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  CONSTRAINT "int_penjualanresep_r_pkey" PRIMARY KEY ("id")
)
;');

        $this->execute('CREATE TABLE IF NOT EXISTS "public"."obatalkes_r" (
  "id" serial8,
  "obatalkes_id" int4,
  "jenisobatalkes_id" int4,
  "sumberdana_id" int4,
  "lokasigudang_id" int4,
  "satuankecil_id" int4 DEFAULT 1,
  "satuanbesar_id" int4,
  "ven" int4,
  "obatalkes_barcode" varchar(100) COLLATE "pg_catalog"."default",
  "obatalkes_kode" varchar(100) COLLATE "pg_catalog"."default",
  "obatalkes_namalain" varchar(100) COLLATE "pg_catalog"."default",
  "obatalkes_nobatch" varchar(50) COLLATE "pg_catalog"."default",
  "obatalkes_kategori" varchar(50) COLLATE "pg_catalog"."default",
  "obatalkes_kadarobat" varchar(50) COLLATE "pg_catalog"."default",
  "kemasan_besar" int4 DEFAULT 0,
  "kekuatan_obat" int4 DEFAULT 0,
  "satuankekuatan" varchar(32) COLLATE "pg_catalog"."default",
  "ppn_persen" float8 DEFAULT 0,
  "harganetto" float8 DEFAULT 0,
  "hargajual" float8 DEFAULT 0,
  "hargamaksimum" float8 DEFAULT 0,
  "hargaminimum" float8 DEFAULT 0,
  "hargaratarata" float8 DEFAULT 0,
  "discount" float8 DEFAULT 0,
  "tglkadaluarsa" date,
  "minimalstok" int4 DEFAULT 0,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "is_generik" bool,
  "satuansedang_id" int4,
  "obatalkes_nama" varchar(255) COLLATE "pg_catalog"."default",
  "is_formularium" bool,
  "kemasan_sedang" int4,
  "supplier_id" int4,
  "indikasi" text COLLATE "pg_catalog"."default",
  "kontradiksi" text COLLATE "pg_catalog"."default",
  "interaksi" text COLLATE "pg_catalog"."default",
  "efek_samping" text COLLATE "pg_catalog"."default",
  "maksimalstok" int4 DEFAULT 0,
  "harga_beli" float8,
  "lead_time" int4 DEFAULT 0,
  "avg_usage" int4 DEFAULT 0,
  "min_order" int4 DEFAULT 0,
  "max_order" int4 DEFAULT 0,
  "nilai_ro" int4 DEFAULT 0,
  "groupinacbg_id" int4,
  "on_ro" int4 DEFAULT 0,
  "on_po" int4 DEFAULT 0,
  "hargaterakhir" float8 DEFAULT 0,
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "ket_ubah_harga" int4,
  "kode_ecatalog" varchar(255) COLLATE "pg_catalog"."default",
  "is_oral" bool,
  "is_antibiotic" bool,
  "is_psycothropica" bool,
  "is_prescibe_item" bool,
  "is_allow_franction" bool,
  "is_lasa" bool,
  "is_expiry" bool,
  "is_highalert" bool,
  "is_consigment" bool,
  "is_embalase" bool,
  "strength" numeric(15,2) DEFAULT 0,
  "strength_uom" varchar(255) COLLATE "pg_catalog"."default",
  "catatan" text COLLATE "pg_catalog"."default",
  "keterangan_rekap" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  CONSTRAINT "obatalkes_r_pkey" PRIMARY KEY ("id")
)
;');

        $this->execute('CREATE TABLE IF NOT EXISTS "public"."obatalkespasien_r" (
  "id" serial8,
  "obatalkespasien_id" int4,
  "sumberdana_id" int4,
  "racikan_id" int4,
  "returresepdetail_id" int4,
  "tipepaket_id" int4,
  "ruangan_id" int4,
  "carabayar_id" int4,
  "pegawai_id" int4,
  "daftartindakan_id" int4,
  "tindakanpelayanan_id" int4,
  "satuankecil_id" int4,
  "shift_id" int4,
  "pendaftaran_id" int4,
  "obatalkes_id" int4,
  "pasien_id" int4,
  "penjamin_id" int4,
  "kelaspelayanan_id" int4,
  "pasienanastesi_id" int4,
  "pasienmasukpenunjang_id" int4,
  "pasienadmisi_id" int4,
  "obatsudahbayar_id" int4,
  "penjualanresep_id" int4,
  "tglpelayanan" timestamp(6),
  "r" char(1) COLLATE "pg_catalog"."default",
  "rke" int2,
  "permintaan_oa" int4,
  "jmlkemasan_oa" int4,
  "kekuatan_oa" int4,
  "satuankekuatan_oa" varchar COLLATE "pg_catalog"."default",
  "qty_oa" float8,
  "hargasatuan_oa" float8,
  "signa_oa" varchar(53) COLLATE "pg_catalog"."default",
  "harganetto_oa" float8,
  "hargajual_oa" float8,
  "etiket" varchar COLLATE "pg_catalog"."default",
  "jmlexposerad" float8,
  "kontrasrad" varchar COLLATE "pg_catalog"."default",
  "biayaservice" float8,
  "biayakonseling" float8,
  "jasadokterresep" float8,
  "biayakemasan" float8,
  "biayaadministrasi" float8,
  "tarifcyto" float8,
  "discount" float8,
  "subsidiasuransi" float8,
  "subsidipemerintah" float8,
  "subsidirs" float8,
  "iurbiaya" float8,
  "oa" char(1) COLLATE "pg_catalog"."default",
  "pembulatan" float8,
  "verifikasitagihan_id" int4,
  "jurnalrekening_id" int4,
  "permohonanoadetail_id" int4,
  "persenppnjual" int4,
  "resepturdetail_id" int4,
  "nilaippnjual" float8,
  "perawat1_id" int4,
  "perawat2_id" int4,
  "instruksitindakanbmhp_id" int4,
  "implementasi_id" int4,
  "is_dilakukan" bool DEFAULT false,
  "pemakaianambulan_id" int4,
  "is_jurnal" bool DEFAULT false,
  "konfigmargindetail_id" int4,
  "qty_konversi" float8,
  "is_penatajasa" bool,
  "det" float8,
  "status_bmhp" int2,
  "det_konversi" float8,
  "signa" json,
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "keterangan" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "no_obatalkespasien" varchar(255) COLLATE "pg_catalog"."default",
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  "tarif_dijamin" float8 DEFAULT 0,
  "tarif_dibayarkan" float8 DEFAULT 0,
  CONSTRAINT "obatalkespasien_r_pkey" PRIMARY KEY ("id")
)
;');

        $this->execute('CREATE TABLE IF NOT EXISTS "public"."pasien_r" (
  "id" serial8,
  "pasien_id" int4,
  "no_rekam_medik" varchar(100) COLLATE "pg_catalog"."default",
  "tgl_rekam_medik" date,
  "jenisidentitas" varchar(20) COLLATE "pg_catalog"."default",
  "no_identitas_pasien" varchar(30) COLLATE "pg_catalog"."default",
  "namadepan" varchar(20) COLLATE "pg_catalog"."default",
  "nama_pasien" varchar(50) COLLATE "pg_catalog"."default",
  "nama_bin" varchar(30) COLLATE "pg_catalog"."default",
  "jeniskelamin" varchar(20) COLLATE "pg_catalog"."default" DEFAULT 9999,
  "tempat_lahir" varchar(25) COLLATE "pg_catalog"."default",
  "tanggal_lahir" date,
  "golonganumur_id" int4,
  "alamat_pasien" text COLLATE "pg_catalog"."default",
  "rt" int2,
  "rw" int2,
  "propinsi_id" int4,
  "kabupaten_id" int4,
  "kecamatan_id" int4,
  "kelurahan_id" int4,
  "pendidikan_id" int4,
  "pekerjaan_id" int4,
  "suku_id" int4,
  "statusperkawinan" varchar(20) COLLATE "pg_catalog"."default" DEFAULT 9999,
  "agama" varchar(20) COLLATE "pg_catalog"."default" DEFAULT 9999,
  "golongandarah" varchar(10) COLLATE "pg_catalog"."default" DEFAULT 9999,
  "rhesus" varchar(20) COLLATE "pg_catalog"."default" DEFAULT 9999,
  "anakke" int2,
  "jumlah_bersaudara" int2,
  "no_telepon_pasien" varchar(15) COLLATE "pg_catalog"."default",
  "no_mobile_pasien" varchar(20) COLLATE "pg_catalog"."default",
  "warga_negara" varchar(25) COLLATE "pg_catalog"."default" DEFAULT 9999,
  "photopasien" varchar(200) COLLATE "pg_catalog"."default",
  "alamatemail" varchar(100) COLLATE "pg_catalog"."default",
  "nama_ibu" varchar(50) COLLATE "pg_catalog"."default",
  "nama_ayah" varchar(50) COLLATE "pg_catalog"."default",
  "dokrekammedis_id" int4,
  "tgl_meninggal" date,
  "pegawai_id" int4,
  "loginpemakai_id" int4,
  "garis_latitude" float8,
  "garis_longitude" float8,
  "statusrekammedis" varchar(10) COLLATE "pg_catalog"."default",
  "profilrs_id" int4,
  "alamat_sekarang" text COLLATE "pg_catalog"."default",
  "nopeserta_bpjs" varchar(255) COLLATE "pg_catalog"."default",
  "is_aps" bool,
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool DEFAULT false,
  "is_active" bool DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "keterangan" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sending" bool DEFAULT false,
  "is_sent" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  CONSTRAINT "pasien_r_pkey" PRIMARY KEY ("id")
)
;');

        $this->execute('CREATE TABLE IF NOT EXISTS "public"."pasienadmisi_r" (
  "id" serial8,
  "pasienadmisi_id" int4,
  "shift_id" int4,
  "carabayar_id" int4,
  "penjamin_id" int4,
  "pasien_id" int4,
  "caramasuk_id" int4,
  "ruangan_id" int4,
  "pasienpulang_id" int4,
  "bookingkamar_id" int4,
  "pembayaranpelayanan_id" int4,
  "pendaftaran_id" int4,
  "kamarruangan_id" int4,
  "kelaspelayanan_id" int4,
  "pegawai_id" int4,
  "tgl_admisi" timestamp(6),
  "tgl_pendaftaran" timestamp(6),
  "tgl_pulang" timestamp(6),
  "kunjungan" varchar(50) COLLATE "pg_catalog"."default",
  "status_keluar" bool,
  "rawat_gabung" bool,
  "rencana_pulang" timestamp(6),
  "kamartempattidur_id" int4,
  "bpjs_id" int4,
  "status_ranap" int4,
  "pasienbatalperiksa_id" int4,
  "tgl_pindahkamar" timestamp(6),
  "status_verifikasi" int4 DEFAULT 549,
  "is_skd" bool DEFAULT false,
  "is_pasientitipan" bool DEFAULT false,
  "is_aps" bool,
  "asuransipasien_id" int4,
  "kelas_ditagihkan_id" int4,
  "kamar_titipan_id" int4,
  "tempattidur_titipan_id" int4,
  "ruangan_titipan_id" int4,
  "is_stoptitipan" bool DEFAULT false,
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool DEFAULT false,
  "is_active" bool DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "keterangan" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  CONSTRAINT "pasienadmisi_r_pkey" PRIMARY KEY ("id")
)
;');

        $this->execute('CREATE TABLE IF NOT EXISTS "public"."pemakaianobatdetail_r" (
  "id" serial8,
  "pemakaianobatdetail_id" int4,
  "satuankecil_id" int4,
  "pemakaianobat_id" int4,
  "obatalkes_id" int4,
  "qty_satuanpakai" numeric,
  "harga_satuanpakai" float8,
  "harganetto_satuanpakai" float8,
  "ket_obatpakai" varchar(200) COLLATE "pg_catalog"."default",
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "satuanbesar_id" int4,
  "jumlah_input" float8 DEFAULT 0,
  "keterangan_rekap" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  CONSTRAINT "pemakaianobatdetail_r_pkey" PRIMARY KEY ("id")
)
;');

        $this->execute('CREATE TABLE IF NOT EXISTS "public"."pemakaianuangmuka_r" (
  "id" serial8,
  "pemakaianuangmuka_id" int4,
  "pembayaranpelayanan_id" int4,
  "tandabuktikeluar_id" int4,
  "pendaftaran_id" int4,
  "tgl_pemakaian" timestamp(6),
  "total_uangmuka" float8,
  "pemakaian_uangmuka" float8,
  "sisa_uangmuka" float8,
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "bayaruangmuka_id" int4,
  "keterangan" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sending" bool DEFAULT false,
  "is_sent" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  CONSTRAINT "pemakaianuangmuka_r_pkey" PRIMARY KEY ("id")
)
;');

        $this->execute('CREATE TABLE IF NOT EXISTS "public"."pembatalanresep_r" (
  "id" serial8,
  "pembatalanresep_id" int4,
  "penjualanresep_id" int4,
  "tgl_pembatalan" timestamp(6),
  "no_pembatalan" varchar COLLATE "pg_catalog"."default",
  "petugas_batal_id" int4,
  "alasan_batal" text COLLATE "pg_catalog"."default",
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "keterangan_rekap" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  CONSTRAINT "pembatalanresep_r_pkey" PRIMARY KEY ("id")
)
;');

        $this->execute('CREATE TABLE IF NOT EXISTS "public"."pembatalanresepdetail_r" (
  "id" serial8,
  "obatalkespasien_id" int4,
  "sumberdana_id" int4,
  "racikan_id" int4,
  "returresepdetail_id" int4,
  "tipepaket_id" int4,
  "ruangan_id" int4,
  "carabayar_id" int4,
  "pegawai_id" int4,
  "daftartindakan_id" int4,
  "tindakanpelayanan_id" int4,
  "satuankecil_id" int4,
  "shift_id" int4,
  "pendaftaran_id" int4,
  "obatalkes_id" int4,
  "pasien_id" int4,
  "penjamin_id" int4,
  "kelaspelayanan_id" int4,
  "pasienanastesi_id" int4,
  "pasienmasukpenunjang_id" int4,
  "pasienadmisi_id" int4,
  "obatsudahbayar_id" int4,
  "penjualanresep_id" int4,
  "tglpelayanan" timestamp(6),
  "r" char(1) COLLATE "pg_catalog"."default",
  "rke" int2,
  "permintaan_oa" int4,
  "jmlkemasan_oa" int4,
  "kekuatan_oa" int4,
  "satuankekuatan_oa" varchar COLLATE "pg_catalog"."default",
  "qty_oa" float8,
  "hargasatuan_oa" float8,
  "signa_oa" varchar(53) COLLATE "pg_catalog"."default",
  "harganetto_oa" float8,
  "hargajual_oa" float8,
  "etiket" varchar COLLATE "pg_catalog"."default",
  "jmlexposerad" float8,
  "kontrasrad" varchar COLLATE "pg_catalog"."default",
  "biayaservice" float8,
  "biayakonseling" float8,
  "jasadokterresep" float8,
  "biayakemasan" float8,
  "biayaadministrasi" float8,
  "tarifcyto" float8,
  "discount" float8,
  "subsidiasuransi" float8,
  "subsidipemerintah" float8,
  "subsidirs" float8,
  "iurbiaya" float8,
  "oa" char(1) COLLATE "pg_catalog"."default",
  "pembulatan" float8,
  "verifikasitagihan_id" int4,
  "jurnalrekening_id" int4,
  "permohonanoadetail_id" int4,
  "persenppnjual" int4,
  "resepturdetail_id" int4,
  "nilaippnjual" float8,
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "perawat1_id" int4,
  "perawat2_id" int4,
  "instruksitindakanbmhp_id" int4,
  "implementasi_id" int4,
  "is_dilakukan" bool DEFAULT false,
  "pemakaianambulan_id" int4,
  "is_jurnal" bool DEFAULT false,
  "konfigmargindetail_id" int4,
  "qty_konversi" float8,
  "is_penatajasa" bool,
  "det" float8,
  "status_bmhp" int2,
  "det_konversi" float8,
  "signa" json,
  "no_obatalkespasien" varchar(255) COLLATE "pg_catalog"."default",
  "keterangan_rekap" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  CONSTRAINT "pembatalanresepdetail_r_pkey" PRIMARY KEY ("id")
)
;');
        $this->execute('CREATE TABLE IF NOT EXISTS "public"."pembayaran_r" (
  "id" serial8,
  "pembayaran_id" int4,
  "pendaftaran_id" int4,
  "pasienadmisi_id" int4,
  "total_tagihan" float8,
  "total_dibayar" float8,
  "total_dijamin" float8,
  "total_sisatagihan" float8,
  "total_kembalian" float8,
  "total_administrasi" float8 DEFAULT 0,
  "total_pembulatan" float8 DEFAULT 0,
  "total_pembebasan" float8 DEFAULT 0,
  "penggunaan_uangmuka" float8,
  "pemberianpiutang_id" int4,
  "total_ditagihkan" float4,
  "total_tunai" float8,
  "total_nontunai" float8,
  "total_discount" float8,
  "total_discountpembayaran" float8,
  "catatan" text COLLATE "pg_catalog"."default",
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool DEFAULT false,
  "is_active" bool DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "keterangan" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  "is_update" bool DEFAULT false,
  "id_sync_sercon_update" text COLLATE "pg_catalog"."default",
  "sync_respon_update" text COLLATE "pg_catalog"."default",
  "nama_edc" varchar(255) COLLATE "pg_catalog"."default",
  "tipe_pembayaran" int4,
  CONSTRAINT "pembayaran_r_pkey" PRIMARY KEY ("id")
)
;');
        $this->execute('CREATE TABLE IF NOT EXISTS "public"."pemusnahanobatdetail_r" (
  "id" serial8,
  "pemusnahanobatdetail_id" int4,
  "pemusnahanobat_id" int4,
  "obatalkes_id" int4,
  "jumlah" float8 DEFAULT 0,
  "tglkadaluarsa" date,
  "nobatch" varchar(200) COLLATE "pg_catalog"."default",
  "kondisibarang" text COLLATE "pg_catalog"."default",
  "harganetto" float8 DEFAULT 0,
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "satuan_id" int4,
  "keterangan_rekap" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  CONSTRAINT "pemusnahanobatdetail_r_pkey" PRIMARY KEY ("id")
)
;');

        $this->execute('CREATE TABLE IF NOT EXISTS "public"."pendaftaran_r" (
  "id" serial8,
  "pendaftaran_id" int4,
  "no_pendaftaran" varchar(20) COLLATE "pg_catalog"."default",
  "tgl_pendaftaran" timestamp(6),
  "pasienpulang_id" int4,
  "pasienbatalperiksa_id" int4,
  "penanggungjawab_id" int4,
  "penjamin_id" int4,
  "shift_id" int4,
  "pasien_id" int4,
  "persalinan_id" int4,
  "pegawai_id" int4,
  "instalasi_id" int4,
  "caramasuk_id" int4,
  "jeniskasuspenyakit_id" int4,
  "pembayaranpelayanan_id" int4,
  "kelaspelayanan_id" int4,
  "carabayar_id" int4,
  "pasienadmisi_id" int4,
  "golonganumur_id" int4,
  "rujukan_id" int4,
  "antrian_id" int4,
  "karcis_id" int4,
  "ruangan_id" int4,
  "no_urutantri" varchar(6) COLLATE "pg_catalog"."default",
  "transportasi" varchar(50) COLLATE "pg_catalog"."default",
  "keadaan_masuk" varchar(50) COLLATE "pg_catalog"."default",
  "status_periksa" varchar(50) COLLATE "pg_catalog"."default",
  "status_pasien" varchar(50) COLLATE "pg_catalog"."default",
  "kunjungan" varchar(50) COLLATE "pg_catalog"."default",
  "alih_status" bool DEFAULT false,
  "by_phone" bool DEFAULT false,
  "kunjungan_rumah" bool DEFAULT false,
  "status_masuk" varchar(50) COLLATE "pg_catalog"."default",
  "umur" varchar(30) COLLATE "pg_catalog"."default",
  "tgl_selesaiperiksa" timestamp(6),
  "keterangan_pendaftaran" text COLLATE "pg_catalog"."default",
  "nopendaftaran_aktif" bool DEFAULT true,
  "status_konfirmasi" varchar(50) COLLATE "pg_catalog"."default",
  "tgl_konfirmasi" timestamp(6),
  "tgl_renkontrol" timestamp(6),
  "status_farmasi" bool DEFAULT false,
  "panggil_antrian" bool DEFAULT false,
  "asuransipasien_id" int4,
  "tgl_akandilayani" timestamp(6),
  "statusdok_rekammedik" varchar(50) COLLATE "pg_catalog"."default",
  "bpjs_id" int4,
  "status_bayar" int4,
  "is_aps" bool,
  "label_gelang" text COLLATE "pg_catalog"."default",
  "is_karcis" bool DEFAULT true,
  "tgl_masukperiksa" timestamp(0),
  "status_verifikasi" int4,
  "is_ranap" bool DEFAULT false,
  "is_skd" bool DEFAULT false,
  "pendaftaranibu_id" int4,
  "is_skl" bool DEFAULT false,
  "catatan_penatajasa" text COLLATE "pg_catalog"."default",
  "is_stopakomodasi" bool DEFAULT false,
  "tgl_stopakomodasi" timestamp(0),
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6),
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool DEFAULT false,
  "is_active" bool DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "keterangan" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sending" bool DEFAULT false,
  "is_sent" bool DEFAULT false,
  "namapemilikasuransi" varchar(50) COLLATE "pg_catalog"."default",
  "nokartuasuransi" varchar(50) COLLATE "pg_catalog"."default",
  CONSTRAINT "pendaftaran_r_pkey" PRIMARY KEY ("id")
)
;');
        $this->execute('CREATE TABLE IF NOT EXISTS "public"."penerimaanobat_r" (
  "id" serial8,
  "penerimaanobat_id" int4,
  "validasipoobat_id" int4,
  "no_penerimaan" varchar(100) COLLATE "pg_catalog"."default",
  "tgl_penerimaan" timestamp(0) DEFAULT (\'now\'::text)::date,
  "supplier_id" int4,
  "no_suratjalan" varchar(100) COLLATE "pg_catalog"."default",
  "tgl_suratjalan" timestamp(0) DEFAULT (\'now\'::text)::date,
  "no_faktur" varchar(100) COLLATE "pg_catalog"."default",
  "diterima_oleh" int4,
  "ruanganpenerima_id" int4,
  "peg_mengetahui" int4,
  "peg_menyetujui" int4,
  "upload_berkas" text COLLATE "pg_catalog"."default",
  "catatan_berkas" text COLLATE "pg_catalog"."default",
  "catatan" text COLLATE "pg_catalog"."default",
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "is_verifikasi" int2,
  "status_rekap" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  CONSTRAINT "penerimaanobat_r_pkey" PRIMARY KEY ("id")
)
;');
        $this->execute('CREATE TABLE IF NOT EXISTS "public"."penerimaanobatdetail_r" (
  "id" serial8,
  "penerimaanobatdetail_id" int4,
  "penerimaanobat_id" int4,
  "validasipoobatdetail_id" int4,
  "obatalkes_id" int4,
  "qty_po" int4,
  "po_balance" int4,
  "qty_diterima" int4,
  "s_konversiobt_id" int4,
  "tgl_kadaluarsa" date,
  "no_batch" varchar(100) COLLATE "pg_catalog"."default",
  "harga" float8 DEFAULT 0,
  "discount" float4 DEFAULT 0,
  "discount_rp" float8 DEFAULT 0,
  "jumlah" float8 DEFAULT 0,
  "keterangan" text COLLATE "pg_catalog"."default",
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool DEFAULT false,
  "is_active" bool DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "status_rekap" text COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(0) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sending" bool DEFAULT false,
  "is_sent" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  CONSTRAINT "penerimaanobatdetail_r_pkey" PRIMARY KEY ("id")
)
;');
        $this->execute('CREATE TABLE IF NOT EXISTS "public"."penerimaansupp_r" (
  "id" serial8,
  "penerimaansupp_id" int4,
  "no_penerimaan" varchar(100) COLLATE "pg_catalog"."default",
  "tgl_penerimaan" timestamp(0),
  "supplier_id" int4,
  "no_faktur" varchar(100) COLLATE "pg_catalog"."default",
  "peg_mengetahui" int4,
  "peg_menyetujui" int4,
  "ruanganpenerima_id" int2,
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "pajak_id" int4,
  "payterm_id" int4,
  "is_tipe" int2 DEFAULT 0,
  "no_suratjalan" varchar(100) COLLATE "pg_catalog"."default",
  "is_verifikasi" bool DEFAULT false,
  "tgl_verifikasi" date,
  "status_rekap" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  CONSTRAINT "penerimaansupp_r_pkey" PRIMARY KEY ("id")
)
;');
        $this->execute('CREATE TABLE IF NOT EXISTS "public"."penerimaansuppdetail_r" (
  "id" serial8,
  "penerimaansuppdetail_id" int4,
  "penerimaansupp_id" int4,
  "obatalkes_id" int4,
  "tgl_kadaluarsa" timestamp(0),
  "satuanbesar_id" int4,
  "qty_besar" int4,
  "satuankecil_id" int4,
  "qty_kecil" int4,
  "harga_netto" float8,
  "ppn" int2,
  "diskon" numeric(15,2),
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "satuankonversi_id" int4,
  "no_batch" varchar(100) COLLATE "pg_catalog"."default",
  "keterangan" text COLLATE "pg_catalog"."default",
  "barang_id" int4,
  "status_rekap" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  CONSTRAINT "penerimaansuppdetail_r_pkey" PRIMARY KEY ("id")
)
;');
        $this->execute('CREATE TABLE IF NOT EXISTS "public"."pengembalianuangmuka_r" (
  "id" serial8,
  "pengembalianuangmuka_id" int4,
  "pendaftaran_id" int4,
  "tandabuktikeluar_id" int4,
  "ruangan_id" int4,
  "tgl_pengembalian" timestamp(0),
  "total_pengembalian" float8,
  "biaya_administrasi" float8,
  "pembulatan" float8,
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "keterangan" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sending" bool DEFAULT false,
  "is_sent" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  "is_sending_scr" bool DEFAULT false,
  "is_sent_scr" bool DEFAULT false,
  "id_sync_sercon_scr" text COLLATE "pg_catalog"."default",
  "sync_respon_scr" text COLLATE "pg_catalog"."default",
  CONSTRAINT "pengembalianuangmuka_r_pkey" PRIMARY KEY ("id")
)
;');
        $this->execute('CREATE TABLE IF NOT EXISTS "public"."returpenerimaanobat_r" (
  "id" serial8,
  "returpenerimaanobat_id" int4,
  "panerimaanobatsupp_id" int4,
  "no_returpenerimaanobat" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_retur" timestamp(0),
  "pegawairetur_id" int4,
  "alasan_retur" text COLLATE "pg_catalog"."default",
  "ruanganretur_id" int4,
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "keterangan_rekap" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  CONSTRAINT "returpenerimaanobat_r_pkey" PRIMARY KEY ("id")
)
;');
        $this->execute('CREATE TABLE IF NOT EXISTS "public"."returpenerimaanobatdetail_r" (
  "id" serial8,
  "returpenerimaanobatdetail_id" int4,
  "returpenerimaanobat_id" int4,
  "obatalkes_id" int4,
  "satuanbesar_id" int4,
  "tgl_kadaluarsa" timestamp(0),
  "qty_retur" int4,
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "penerimaansuppdetail_id" int4,
  "penerimaanobat_id" int4,
  "qty_input" int4,
  "penerimaanobatdetail_id" int4,
  "keterangan_rekap" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  CONSTRAINT "returpenerimaanobatdetail_r_pkey" PRIMARY KEY ("id")
)
;');
        $this->execute('CREATE TABLE IF NOT EXISTS "public"."returresep_r" (
  "id" serial8,
  "returresep_id" int4,
  "ruangan_id" int4,
  "penjualanresep_id" int4,
  "pendaftaran_id" int4,
  "pasien_id" int4,
  "pasienadmisi_id" int4,
  "tgl_retur" timestamp(6),
  "no_returresep" varchar COLLATE "pg_catalog"."default",
  "alasan_retur" varchar COLLATE "pg_catalog"."default",
  "keterangan_retur" text COLLATE "pg_catalog"."default",
  "pegawaimengetahui_id" int4,
  "pegawairetur_id" int4,
  "total_retur" float8,
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "keterangan_rekap" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  CONSTRAINT "returresep_r_pkey" PRIMARY KEY ("id")
)
;');
        $this->execute('CREATE TABLE IF NOT EXISTS "public"."returresepdetail_r" (
  "id" serial8,
  "returresepdetail_id" int4,
  "obatalkespasien_id" int4,
  "returresep_id" int4,
  "qty_retur" float8,
  "hargasatuan" float8,
  "kondisibrg" varchar COLLATE "pg_catalog"."default",
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "keterangan_rekap" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  CONSTRAINT "returresepdetail_r_pkey" PRIMARY KEY ("id")
)
;');
        $this->execute('CREATE TABLE IF NOT EXISTS "public"."satuanunit_r" (
  "id" serial8,
  "satuanunit_id" int4,
  "satuanunit_nama" varchar COLLATE "pg_catalog"."default",
  "satuanunit_singkatan" varchar COLLATE "pg_catalog"."default",
  "satuan_jenis" varchar(10) COLLATE "pg_catalog"."default",
  "satuanunit_namalain" varchar(255) COLLATE "pg_catalog"."default",
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "keterangan_rekap" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  CONSTRAINT "satuanunit_r_pkey" PRIMARY KEY ("id")
)
;');
        $this->execute('CREATE TABLE IF NOT EXISTS "public"."servicecategory_m" (
  "servicecategory_id" serial8,
  "servicecategory_nama" varchar(255) COLLATE "pg_catalog"."default",
  "is_obat" bool,
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  CONSTRAINT "servicecategory_m_pkey" PRIMARY KEY ("servicecategory_id")
)
;');
        $this->execute('CREATE TABLE IF NOT EXISTS "public"."servicegroup_m" (
  "servicegroup_id" serial8,
  "servicegroup_nama" text COLLATE "pg_catalog"."default",
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  CONSTRAINT "servicegroup_m_pkey" PRIMARY KEY ("servicegroup_id")
)
;');
        $this->execute('CREATE TABLE IF NOT EXISTS "public"."spesialis_m" (
  "spesialis_id" serial8,
  "spesialis_kode" varchar(255) COLLATE "pg_catalog"."default",
  "spesialis_nama" varchar(255) COLLATE "pg_catalog"."default",
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  CONSTRAINT "spesialis_m_pkey" PRIMARY KEY ("spesialis_id")
)
;');
        $this->execute('CREATE TABLE IF NOT EXISTS "public"."supplier_r" (
  "id" serial8,
  "supplier_id" int4,
  "pbf_id" int4,
  "supplier_kode" varchar(25) COLLATE "pg_catalog"."default",
  "supplier_nama" varchar(100) COLLATE "pg_catalog"."default",
  "supplier_namalain" varchar(100) COLLATE "pg_catalog"."default",
  "supplier_alamat" text COLLATE "pg_catalog"."default",
  "propinsi_id" int4,
  "kabupaten_id" int4,
  "no_tlp" varchar(30) COLLATE "pg_catalog"."default",
  "email" varchar(100) COLLATE "pg_catalog"."default",
  "no_fax" varchar(50) COLLATE "pg_catalog"."default",
  "no_npwp" varchar(100) COLLATE "pg_catalog"."default",
  "no_rekening" varchar(255) COLLATE "pg_catalog"."default",
  "nama_pemilikrek" varchar(255) COLLATE "pg_catalog"."default",
  "bank_id" int4,
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "is_pmi" bool DEFAULT false,
  "negara_id" int4,
  "website" text COLLATE "pg_catalog"."default",
  "nama_pic" varchar(255) COLLATE "pg_catalog"."default",
  "credit_limit" int4,
  "remarks" varchar(255) COLLATE "pg_catalog"."default",
  "parent_suppliercode" varchar(100) COLLATE "pg_catalog"."default",
  "keterangan_rekap" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  CONSTRAINT "supplier_r_pkey" PRIMARY KEY ("id")
)
;');
        $this->execute('CREATE TABLE IF NOT EXISTS "public"."tindakankomponen_r" (
  "id" serial8,
  "tindakankomponen_id" int4,
  "komponentarif_id" int4,
  "tindakanpelayanan_id" int4,
  "tarif_kompsatuan" float8 DEFAULT 0,
  "tarif_tindakankomp" float8 DEFAULT 0,
  "tarifcyto_tindakankomp" float8 DEFAULT 0,
  "subsidiasuransikomp" float8 DEFAULT 0,
  "subsidipemerintahkomp" float8 DEFAULT 0,
  "subsidirumahsakitkomp" float8 DEFAULT 0,
  "iurbiayakomp" float8,
  "pembayaranjasa_id" int4,
  "is_jurnal" bool DEFAULT false,
  "discount_komponen" float8 DEFAULT 0,
  "tarifpenyulit_komponen" float8 DEFAULT 0,
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "keterangan" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  CONSTRAINT "tindakankomponen_r_pkey" PRIMARY KEY ("id")
)
;');
        $this->execute('CREATE TABLE IF NOT EXISTS "public"."tindakanpelayanan_r" (
  "id" serial8,
  "tindakanpelayanan_id" int4,
  "shift_id" int4,
  "kelaspelayanan_id" int4,
  "kelastanggungan_id" int4,
  "pasien_id" int4,
  "rencanaoperasi_id" int4,
  "instalasi_id" int4,
  "daftartindakan_id" int4,
  "alatmedis_id" int4,
  "tipepaket_id" int4,
  "tindakansudahbayar_id" int4,
  "carabayar_id" int4,
  "pendaftaran_id" int4,
  "hasilpemeriksaanrad_id" int4,
  "jeniskasuspenyakit_id" int4,
  "hasilpemeriksaanrm_id" int4,
  "ruangan_id" int4,
  "konsulpoli_id" int4,
  "pasienmasukpenunjang_id" int4,
  "hasilpemeriksaanlabdetail_id" int4,
  "penjamin_id" int4,
  "pasienadmisi_id" int4,
  "verifikasitagihan_id" int4,
  "jurnalrekening_id" int4,
  "instruksitindakan_id" int4,
  "tgl_tindakan" timestamp(6),
  "tarif_rsakomodasi" float8 DEFAULT (0)::double precision,
  "tarif_medis" float8 DEFAULT (0)::double precision,
  "tarif_paramedis" float8 DEFAULT (0)::double precision,
  "tarif_bhp" float8 DEFAULT (0)::double precision,
  "tarif_satuan" float8 DEFAULT (0)::double precision,
  "tarif_tindakan" float8,
  "tarifcyto_tindakan" float8,
  "satuan_tindakan" varchar(10) COLLATE "pg_catalog"."default",
  "qty_tindakan" int4 DEFAULT 1,
  "cyto_tindakan" bool,
  "dokterpenanggungjawab_id" int8,
  "dokterpelaksana_id" int8,
  "dokteranastesi_id" int8,
  "dokterdelegasi_id" int8,
  "bidan1_id" int8,
  "bidan2_id" int8,
  "perawat1_id" int8,
  "perawat2_id" int4,
  "discount_tindakan" float8,
  "pembebasan_tindakan" float8 DEFAULT (0)::double precision,
  "subsidiasuransi_tindakan" float8,
  "subsidipemerintah_tindakan" float8,
  "subsisidirumahsakit_tindakan" float8,
  "uangditerima_tindakan" float8,
  "keterangantindakan" text COLLATE "pg_catalog"."default",
  "pembulatan" float8,
  "implementasi_id" int4,
  "is_dilakukan" bool DEFAULT false,
  "pemakaianambulan_id" int4,
  "is_penatajasa" bool,
  "additional_riwayat" text COLLATE "pg_catalog"."default",
  "is_valid" bool DEFAULT true,
  "kamarruangan_id" int4,
  "kamartempattidur_id" int4,
  "penyulit_tindakan" bool DEFAULT false,
  "tarifpenyulit_tindakan" float8 DEFAULT 0,
  "additional_data" text COLLATE "pg_catalog"."default",
  "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
  "created_by" int4,
  "modified_count" int4,
  "last_modified_date" timestamp(6),
  "last_modified_by" int4,
  "is_deleted" bool NOT NULL DEFAULT false,
  "is_active" bool NOT NULL DEFAULT true,
  "deleted_date" timestamp(6),
  "deleted_by" int4,
  "keterangan" varchar(255) COLLATE "pg_catalog"."default",
  "tgl_proses" timestamp(6) DEFAULT (to_char(now(), \'YYYY-MM-DD hh:mm:ss\'::text))::timestamp without time zone,
  "no_tindakanpelayanan" varchar(255) COLLATE "pg_catalog"."default",
  "is_sent" bool DEFAULT false,
  "is_sending" bool DEFAULT false,
  "id_sync_sercon" text COLLATE "pg_catalog"."default",
  "sync_respon" text COLLATE "pg_catalog"."default",
  "pembayaran_id" int4,
  "tarif_dijamin" float8 DEFAULT 0,
  "tarif_dibayarkan" float8 DEFAULT 0,
  CONSTRAINT "tindakanpelayanan_r_pkey" PRIMARY KEY ("id")
)
;');
        

    }

    /**
     * {@inheritdoc} 
     */
    public function safeDown()
    {
        echo "m201020_031456_oddo_tabelrekap_20201020 cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m201020_031456_oddo_tabelrekap_20201020 cannot be reverted.\n";

        return false;
    }
    */
}
