<?php

use yii\db\Migration;

/**
 * Class m201118_092447_oddo_function_20201118_1
 */
class m201118_092447_oddo_function_20201118_1 extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->execute("
            CREATE OR REPLACE FUNCTION \"public\".\"int_obatalkespasien_r_insert\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$
DECLARE

    
BEGIN
------------------------------->INSERT table history int_obatalkespasien_r<----------------------------------
        INSERT INTO int_obatalkespasien_r (     
        obatalkespasien_id ,
        sumberdana_id ,
        racikan_id ,
        returresepdetail_id ,
        tipepaket_id ,
        ruangan_id ,
        carabayar_id ,
        pegawai_id ,
        daftartindakan_id ,
        tindakanpelayanan_id ,
        satuankecil_id ,
        shift_id ,
        pendaftaran_id ,
        obatalkes_id ,
        pasien_id ,
        penjamin_id ,
        kelaspelayanan_id ,
        pasienanastesi_id ,
        pasienmasukpenunjang_id ,
        pasienadmisi_id ,
        obatsudahbayar_id ,
        penjualanresep_id ,
        tglpelayanan ,
        r ,
        rke ,
        permintaan_oa ,
        jmlkemasan_oa ,
        kekuatan_oa ,
        satuankekuatan_oa ,
        qty_oa ,
        hargasatuan_oa ,
        signa_oa ,
        harganetto_oa ,
        hargajual_oa , 
        etiket ,
        jmlexposerad ,
        kontrasrad ,
        biayaservice ,
        biayakonseling ,
        jasadokterresep ,
        biayakemasan ,
        biayaadministrasi ,
        tarifcyto ,
        discount , 
        subsidiasuransi ,
        subsidipemerintah ,
        subsidirs ,
        iurbiaya ,
        oa ,
        pembulatan ,
        verifikasitagihan_id ,
        jurnalrekening_id ,
        permohonanoadetail_id ,
        persenppnjual ,
        resepturdetail_id ,
        nilaippnjual ,
        perawat1_id ,
        perawat2_id ,
        instruksitindakanbmhp_id ,
        implementasi_id ,
        is_dilakukan ,
        pemakaianambulan_id ,
        is_jurnal ,
        konfigmargindetail_id ,
        qty_konversi ,
        is_penatajasa ,
        det ,
        status_bmhp ,
        det_konversi ,
        signa ,
        additional_data ,
        created_date ,
        created_by ,
        modified_count ,
        last_modified_date ,
        last_modified_by ,
        is_deleted ,
        is_active ,
        deleted_date , 
        deleted_by ,
        keterangan,
        no_obatalkespasien
        )VALUES(
        NEW.obatalkespasien_id ,
        NEW.sumberdana_id ,
        NEW.racikan_id ,
        NEW.returresepdetail_id ,
        NEW.tipepaket_id ,
        NEW.ruangan_id ,
        NEW.carabayar_id ,
        NEW.pegawai_id ,
        NEW.daftartindakan_id ,
        NEW.tindakanpelayanan_id ,
        NEW.satuankecil_id ,
        NEW.shift_id ,
        NEW.pendaftaran_id ,
        NEW.obatalkes_id ,
        NEW.pasien_id ,
        NEW.penjamin_id ,
        NEW.kelaspelayanan_id ,
        NEW.pasienanastesi_id ,
        NEW.pasienmasukpenunjang_id ,
        NEW.pasienadmisi_id ,
        NEW.obatsudahbayar_id ,
        NEW.penjualanresep_id ,
        NEW.tglpelayanan ,
        NEW.r ,
        NEW.rke ,
        NEW.permintaan_oa ,
        NEW.jmlkemasan_oa ,
        NEW.kekuatan_oa ,
        NEW.satuankekuatan_oa ,
        NEW.qty_oa ,
        NEW.hargasatuan_oa ,
        NEW.signa_oa ,
        NEW.harganetto_oa ,
        NEW.hargajual_oa , 
        NEW.etiket ,
        NEW.jmlexposerad ,
        NEW.kontrasrad ,
        NEW.biayaservice ,
        NEW.biayakonseling ,
        NEW.jasadokterresep ,
        NEW.biayakemasan ,
        NEW.biayaadministrasi ,
        NEW.tarifcyto ,
        NEW.discount , 
        NEW.subsidiasuransi ,
        NEW.subsidipemerintah ,
        NEW.subsidirs ,
        NEW.iurbiaya ,
        NEW.oa ,
        NEW.pembulatan ,
        NEW.verifikasitagihan_id ,
        NEW.jurnalrekening_id ,
        NEW.permohonanoadetail_id ,
        NEW.persenppnjual ,
        NEW.resepturdetail_id ,
        NEW.nilaippnjual ,
        NEW.perawat1_id ,
        NEW.perawat2_id ,
        NEW.instruksitindakanbmhp_id ,
        NEW.implementasi_id ,
        NEW.is_dilakukan ,
        NEW.pemakaianambulan_id ,
        NEW.is_jurnal ,
        NEW.konfigmargindetail_id ,
        NEW.qty_konversi ,
        NEW.is_penatajasa ,
        NEW.det ,
        NEW.status_bmhp ,
        NEW.det_konversi ,
        NEW.signa ,
        NEW.additional_data ,
        NEW.created_date ,
        NEW.created_by ,
        NEW.modified_count ,
        NEW.last_modified_date ,
        NEW.last_modified_by ,
        NEW.is_deleted ,
        NEW.is_active ,
        NEW.deleted_date , 
        NEW.deleted_by ,
        'ACCRUAL',
        NEW.no_obatalkespasien
        );

    RETURN NEW;
END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

        $this->execute("
            CREATE OR REPLACE FUNCTION \"public\".\"obatsudahbayar_t_insert\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$

BEGIN
        -- INSERT table history obatalkespasien_r BILLING(+)
        INSERT INTO obatalkespasien_r (     
                obatalkespasien_id ,
                sumberdana_id ,
                racikan_id ,
                returresepdetail_id ,
                tipepaket_id ,
                ruangan_id ,
                carabayar_id ,
                pegawai_id ,
                daftartindakan_id ,
                tindakanpelayanan_id ,
                satuankecil_id ,
                shift_id ,
                pendaftaran_id ,
                obatalkes_id ,
                pasien_id ,
                penjamin_id ,
                kelaspelayanan_id ,
                pasienanastesi_id ,
                pasienmasukpenunjang_id ,
                pasienadmisi_id ,
                obatsudahbayar_id ,
                penjualanresep_id ,
                tglpelayanan ,
                r ,
                rke ,
                permintaan_oa ,
                jmlkemasan_oa ,
                kekuatan_oa ,
                satuankekuatan_oa ,
                qty_oa ,
                hargasatuan_oa ,
                signa_oa ,
                harganetto_oa ,
                hargajual_oa , 
                etiket ,
                jmlexposerad ,
                kontrasrad ,
                biayaservice ,
                biayakonseling ,
                jasadokterresep ,
                biayakemasan ,
                biayaadministrasi ,
                tarifcyto ,
                discount , 
                subsidiasuransi ,
                subsidipemerintah ,
                subsidirs ,
                iurbiaya ,
                oa ,
                pembulatan ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                permohonanoadetail_id ,
                persenppnjual ,
                resepturdetail_id ,
                nilaippnjual ,
                perawat1_id ,
                perawat2_id ,
                instruksitindakanbmhp_id ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_jurnal ,
                konfigmargindetail_id ,
                qty_konversi ,
                is_penatajasa ,
                det ,
                status_bmhp ,
                det_konversi ,
                signa ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date , 
                deleted_by ,
                keterangan,
                no_obatalkespasien,
                tarif_dijamin,
                tarif_dibayarkan
        )
        SELECT  
                obatalkespasien_id ,
                sumberdana_id ,
                racikan_id ,
                returresepdetail_id ,
                tipepaket_id ,
                ruangan_id ,
                carabayar_id ,
                pegawai_id ,
                daftartindakan_id ,
                tindakanpelayanan_id ,
                satuankecil_id ,
                shift_id ,
                pendaftaran_id ,
                obatalkes_id ,
                pasien_id ,
                penjamin_id ,
                kelaspelayanan_id ,
                pasienanastesi_id ,
                pasienmasukpenunjang_id ,
                pasienadmisi_id ,
                NEW.obatsudahbayar_id ,
                penjualanresep_id ,
                tglpelayanan ,
                r ,
                rke ,
                permintaan_oa ,
                jmlkemasan_oa ,
                kekuatan_oa ,
                satuankekuatan_oa ,
                qty_oa ,
                hargasatuan_oa ,
                signa_oa ,
                harganetto_oa ,
                hargajual_oa , 
                etiket ,
                jmlexposerad ,
                kontrasrad ,
                biayaservice ,
                biayakonseling ,
                jasadokterresep ,
                biayakemasan ,
                biayaadministrasi ,
                tarifcyto ,
                discount , 
                subsidiasuransi ,
                subsidipemerintah ,
                subsidirs ,
                iurbiaya ,
                oa ,
                pembulatan ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                permohonanoadetail_id ,
                persenppnjual ,
                resepturdetail_id ,
                nilaippnjual ,
                perawat1_id ,
                perawat2_id ,
                instruksitindakanbmhp_id ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_jurnal ,
                konfigmargindetail_id ,
                qty_konversi ,
                is_penatajasa ,
                det ,
                status_bmhp ,
                det_konversi ,
                signa ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date , 
                deleted_by ,
                'BILLING',
                no_obatalkespasien,
                ((NEW.additional_data::json->>'data_dijamin')::json->>'dijamin')::float,
                ((NEW.additional_data::json->>'data_dijamin')::json->>'harusbayar')::float 
    FROM obatalkespasien_t
    WHERE obatalkespasien_id = NEW.obatalkespasien_id;
    
    RETURN NEW;

END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

        $this->execute("
            CREATE OR REPLACE FUNCTION \"public\".\"tindakansudahbayar_t_insert\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$

BEGIN
        -- INSERT table history tindakanpelayanan_r BILLING(+)
        INSERT INTO tindakanpelayanan_r (       
            tindakanpelayanan_id ,
            shift_id ,
            kelaspelayanan_id ,
            kelastanggungan_id ,
            pasien_id ,
            rencanaoperasi_id ,
            instalasi_id ,
            daftartindakan_id ,
            alatmedis_id ,
            tipepaket_id ,
            tindakansudahbayar_id ,
            carabayar_id ,
            pendaftaran_id ,
            hasilpemeriksaanrad_id ,
            jeniskasuspenyakit_id ,
            hasilpemeriksaanrm_id ,
            ruangan_id ,
            konsulpoli_id ,
            pasienmasukpenunjang_id ,
            hasilpemeriksaanlabdetail_id ,
            penjamin_id ,
            pasienadmisi_id ,
            verifikasitagihan_id ,
            jurnalrekening_id ,
            instruksitindakan_id ,
            tgl_tindakan ,
            tarif_rsakomodasi ,
            tarif_medis ,
            tarif_paramedis ,
            tarif_bhp ,
            tarif_satuan ,
            tarif_tindakan ,
            tarifcyto_tindakan ,
            satuan_tindakan ,
            qty_tindakan ,
            cyto_tindakan ,
            dokterpenanggungjawab_id ,
            dokterpelaksana_id ,
            dokteranastesi_id ,
            dokterdelegasi_id ,
            bidan1_id ,
            bidan2_id ,
            perawat1_id ,
            perawat2_id ,
            discount_tindakan ,
            pembebasan_tindakan ,
            subsidiasuransi_tindakan ,
            subsidipemerintah_tindakan ,
            subsisidirumahsakit_tindakan ,
            uangditerima_tindakan ,
            keterangantindakan ,
            pembulatan ,
            implementasi_id ,
            is_dilakukan ,
            pemakaianambulan_id ,
            is_penatajasa ,
            additional_riwayat ,
            is_valid ,
            kamarruangan_id ,
            kamartempattidur_id ,
            penyulit_tindakan ,
            tarifpenyulit_tindakan ,
            additional_data ,
            created_date ,
            created_by ,
            keterangan,
            no_tindakanpelayanan,
            tarif_dijamin,
            tarif_dibayarkan
        )
        SELECT  
            tindakanpelayanan_id ,
            shift_id ,
            kelaspelayanan_id ,
            kelastanggungan_id ,
            pasien_id ,
            rencanaoperasi_id ,
            instalasi_id ,
            daftartindakan_id ,
            alatmedis_id ,
            tipepaket_id ,
            NEW.tindakansudahbayar_id,
            carabayar_id ,
            pendaftaran_id ,
            hasilpemeriksaanrad_id ,
            jeniskasuspenyakit_id ,
            hasilpemeriksaanrm_id ,
            ruangan_id ,
            konsulpoli_id ,
            pasienmasukpenunjang_id ,
            hasilpemeriksaanlabdetail_id ,
            penjamin_id ,
            pasienadmisi_id ,
            verifikasitagihan_id ,
            jurnalrekening_id ,
            instruksitindakan_id ,
            tgl_tindakan ,
            tarif_rsakomodasi ,
            tarif_medis ,
            tarif_paramedis ,
            tarif_bhp ,
            tarif_satuan ,
            tarif_tindakan ,
            tarifcyto_tindakan ,
            satuan_tindakan ,
            qty_tindakan ,
            cyto_tindakan ,
            dokterpenanggungjawab_id ,
            dokterpelaksana_id ,
            dokteranastesi_id ,
            dokterdelegasi_id ,
            bidan1_id ,
            bidan2_id ,
            perawat1_id ,
            perawat2_id ,
            discount_tindakan ,
            pembebasan_tindakan ,
            subsidiasuransi_tindakan ,
            subsidipemerintah_tindakan ,
            subsisidirumahsakit_tindakan ,
            uangditerima_tindakan ,
            keterangantindakan ,
            pembulatan ,
            implementasi_id ,
            is_dilakukan ,
            pemakaianambulan_id ,
            is_penatajasa ,
            additional_riwayat ,
            is_valid ,
            kamarruangan_id ,
            kamartempattidur_id ,
            penyulit_tindakan ,
            tarifpenyulit_tindakan ,
            additional_data ,
            created_date ,
            created_by ,
            'BILLING',
            no_tindakanpelayanan,
            ((NEW.additional_data::json->>'data_dijamin')::json->>'dijamin')::float,
            ((NEW.additional_data::json->>'data_dijamin')::json->>'harusbayar')::float 
    FROM tindakanpelayanan_t
    WHERE tindakanpelayanan_id = NEW.tindakanpelayanan_id;
    
    RETURN NEW;

END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

       

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m201118_092447_oddo_function_20201118_1 cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m201118_092447_oddo_function_20201118_1 cannot be reverted.\n";

        return false;
    }
    */
}
