<?php

use yii\db\Migration;

/**
 * Class m201224_081403_improve_add_data_citizen_table_lookup_m
 */
class m201224_081403_improve_add_data_citizen_table_lookup_m extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
         $this->execute('UPDATE lookup_m SET lookup_name = \'INDONESIA\',  lookup_value = \'INDONESIA\', lookup_kode = \'01\' , lookup_urutan = 1 WHERE lookup_id = 308;');

         $this->execute('DELETE FROM lookup_m WHERE lookup_id BETWEEN 733 AND 977;');

         $this->execute('
            INSERT INTO "public"."lookup_m"("lookup_id", "lookup_type", "lookup_name", "lookup_value", "lookup_urutan", "lookup_kode", "additional_data", "created_date", "created_by", "modified_count", "last_modified_date", "last_modified_by", "is_deleted", "is_active", "deleted_date", "deleted_by") VALUES
                (733, \'warga_negara\', \'AFGHANISTAN\', \'AFGHANISTAN\', 2, \'AF\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                 (734, \'warga_negara\', \'ALBANIA\', \'ALBANIA\', 3, \'AL\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (735, \'warga_negara\', \'ALGERIA\', \'ALGERIA\', 4, \'DZ\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (736, \'warga_negara\', \'AMERICAN SAMOA\', \'AMERICAN SAMOA\', 5, \'AS\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (737, \'warga_negara\', \'ANDORRA\', \'ANDORRA\', 6, \'AD\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (738, \'warga_negara\', \'ANGOLA\', \'ANGOLA\', 7, \'AO\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (739, \'warga_negara\', \'ANGUILLA\', \'ANGUILLA\', 8, \'AI\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (740, \'warga_negara\', \'ANTARCTICA\', \'ANTARCTICA\', 9, \'AQ\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (741, \'warga_negara\', \'ANTIGUA AND BARBUDA\', \'ANTIGUA AND BARBUDA\', 10, \'AG\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (742, \'warga_negara\', \'ARGENTINA\', \'ARGENTINA\', 11, \'AR\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (743, \'warga_negara\', \'ARMENIA\', \'ARMENIA\', 12, \'AM\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (744, \'warga_negara\', \'ARUBA\', \'ARUBA\', 13, \'AW\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (745, \'warga_negara\', \'AUSTRALIA\', \'AUSTRALIA\', 14, \'AU\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (746, \'warga_negara\', \'AUSTRIA\', \'AUSTRIA\', 15, \'AT\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (747, \'warga_negara\', \'AZERBAIJAN\', \'AZERBAIJAN\', 16, \'AZ\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (748, \'warga_negara\', \'BAHAMAS\', \'BAHAMAS\', 17, \'BS\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (749, \'warga_negara\', \'BAHRAIN\', \'BAHRAIN\', 18, \'BH\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (750, \'warga_negara\', \'BANGLADESH\', \'BANGLADESH\', 19, \'BD\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (751, \'warga_negara\', \'BARBADOS\', \'BARBADOS\', 20, \'BB\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (752, \'warga_negara\', \'BELARUS\', \'BELARUS\', 21, \'BY\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (753, \'warga_negara\', \'BELGIUM\', \'BELGIUM\', 22, \'BE\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (754, \'warga_negara\', \'BELIZE\', \'BELIZE\', 23, \'BZ\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (755, \'warga_negara\', \'BENIN\', \'BENIN\', 24, \'BJ\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (756, \'warga_negara\', \'BERMUDA\', \'BERMUDA\', 25, \'BM\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (757, \'warga_negara\', \'BHUTAN\', \'BHUTAN\', 26, \'BT\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (758, \'warga_negara\', \'BOLIVIA\', \'BOLIVIA\', 27, \'BO\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (759, \'warga_negara\', \'BOSNIA AND HERZEGOVINA\', \'BOSNIA AND HERZEGOVINA\', 28, \'BA\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (760, \'warga_negara\', \'BOTSWANA\', \'BOTSWANA\', 29, \'BW\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (761, \'warga_negara\', \'BOUVET ISLAND\', \'BOUVET ISLAND\', 30, \'BV\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (762, \'warga_negara\', \'BRAZIL\', \'BRAZIL\', 31, \'BR\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (763, \'warga_negara\', \'BRITISH INDIAN OCEAN TERRITORY\', \'BRITISH INDIAN OCEAN TERRITORY\', 32, \'IO\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (764, \'warga_negara\', \'BRUNEI DARUSSALAM\', \'BRUNEI DARUSSALAM\', 33, \'BN\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (765, \'warga_negara\', \'BULGARIA\', \'BULGARIA\', 34, \'BG\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (766, \'warga_negara\', \'BURKINA FASO\', \'BURKINA FASO\', 35, \'BF\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (767, \'warga_negara\', \'BURUNDI\', \'BURUNDI\', 36, \'BI\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (768, \'warga_negara\', \'CAMBODIA\', \'CAMBODIA\', 37, \'KH\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (769, \'warga_negara\', \'CAMEROON\', \'CAMEROON\', 38, \'CM\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (770, \'warga_negara\', \'CANADA\', \'CANADA\', 39, \'CA\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (771, \'warga_negara\', \'CAPE VERDE\', \'CAPE VERDE\', 40, \'CV\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (772, \'warga_negara\', \'CAYMAN ISLANDS\', \'CAYMAN ISLANDS\', 41, \'KY\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (773, \'warga_negara\', \'CENTRAL AFRICAN REPUBLIC\', \'CENTRAL AFRICAN REPUBLIC\', 42, \'CF\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (774, \'warga_negara\', \'CHAD\', \'CHAD\', 43, \'TD\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (775, \'warga_negara\', \'CHILE\', \'CHILE\', 44, \'CL\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (776, \'warga_negara\', \'CHINA\', \'CHINA\', 45, \'CN\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (777, \'warga_negara\', \'CHRISTMAS ISLAND\', \'CHRISTMAS ISLAND\', 46, \'CX\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (778, \'warga_negara\', \'COCOS (KEELING) ISLANDS\', \'COCOS (KEELING) ISLANDS\', 47, \'CC\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (779, \'warga_negara\', \'COLOMBIA\', \'COLOMBIA\', 48, \'CO\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (780, \'warga_negara\', \'COMOROS\', \'COMOROS\', 49, \'KM\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (781, \'warga_negara\', \'CONGO\', \'CONGO\', 50, \'CG\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (782, \'warga_negara\', \'CONGO, THE DEMOCRATIC REPUBLIC OF THE\', \'CONGO, THE DEMOCRATIC REPUBLIC OF THE\', 51, \'CD\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (783, \'warga_negara\', \'COOK ISLANDS\', \'COOK ISLANDS\', 52, \'CK\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (784, \'warga_negara\', \'COSTA RICA\', \'COSTA RICA\', 53, \'CR\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (785, \'warga_negara\', \'CROATIA\', \'CROATIA\', 54, \'HR\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (786, \'warga_negara\', \'CTE D\'\'IVOIRE\', \'CTE D\'\'IVOIRE\', 55, \'CI\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (787, \'warga_negara\', \'CUBA\', \'CUBA\', 56, \'CU\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (788, \'warga_negara\', \'CYPRUS\', \'CYPRUS\', 57, \'CY\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (789, \'warga_negara\', \'CZECH REPUBLIC\', \'CZECH REPUBLIC\', 58, \'CZ\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (790, \'warga_negara\', \'DENMARK\', \'DENMARK\', 59, \'DK\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (791, \'warga_negara\', \'DJIBOUTI\', \'DJIBOUTI\', 60, \'DJ\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (792, \'warga_negara\', \'DOMINICA\', \'DOMINICA\', 61, \'DM\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (793, \'warga_negara\', \'DOMINICAN REPUBLIC\', \'DOMINICAN REPUBLIC\', 62, \'DO\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (794, \'warga_negara\', \'ECUADOR\', \'ECUADOR\', 63, \'EC\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (795, \'warga_negara\', \'EGYPT\', \'EGYPT\', 64, \'EG\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (796, \'warga_negara\', \'EL SALVADOR\', \'EL SALVADOR\', 65, \'SV\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (797, \'warga_negara\', \'EQUATORIAL GUINEA\', \'EQUATORIAL GUINEA\', 66, \'GQ\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (798, \'warga_negara\', \'ERITREA\', \'ERITREA\', 67, \'ER\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (799, \'warga_negara\', \'ESTONIA\', \'ESTONIA\', 68, \'EE\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (800, \'warga_negara\', \'ETHIOPIA\', \'ETHIOPIA\', 69, \'ET\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (801, \'warga_negara\', \'FALKLAND ISLANDS (MALVINAS)\', \'FALKLAND ISLANDS (MALVINAS)\', 70, \'FK\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (802, \'warga_negara\', \'FAROE ISLANDS\', \'FAROE ISLANDS\', 71, \'FO\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (803, \'warga_negara\', \'FIJI\', \'FIJI\', 72, \'FJ\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (804, \'warga_negara\', \'FINLAND\', \'FINLAND\', 73, \'FI\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (805, \'warga_negara\', \'FRANCE\', \'FRANCE\', 74, \'FR\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (806, \'warga_negara\', \'FRENCH GUIANA\', \'FRENCH GUIANA\', 75, \'GF\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (807, \'warga_negara\', \'FRENCH POLYNESIA\', \'FRENCH POLYNESIA\', 76, \'PF\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (808, \'warga_negara\', \'FRENCH SOUTHERN TERRITORIES\', \'FRENCH SOUTHERN TERRITORIES\', 77, \'TF\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (809, \'warga_negara\', \'GABON\', \'GABON\', 78, \'GA\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (810, \'warga_negara\', \'GAMBIA\', \'GAMBIA\', 79, \'GM\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (811, \'warga_negara\', \'GEORGIA\', \'GEORGIA\', 80, \'GE\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (812, \'warga_negara\', \'GERMANY\', \'GERMANY\', 81, \'DE\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (813, \'warga_negara\', \'GHANA\', \'GHANA\', 82, \'GH\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (814, \'warga_negara\', \'GIBRALTAR\', \'GIBRALTAR\', 83, \'GI\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (815, \'warga_negara\', \'GREECE\', \'GREECE\', 84, \'GR\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (816, \'warga_negara\', \'GREENLAND\', \'GREENLAND\', 85, \'GL\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (817, \'warga_negara\', \'GRENADA\', \'GRENADA\', 86, \'GD\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (818, \'warga_negara\', \'GUADELOUPE\', \'GUADELOUPE\', 87, \'GP\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (819, \'warga_negara\', \'GUAM\', \'GUAM\', 88, \'GU\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (820, \'warga_negara\', \'GUATEMALA\', \'GUATEMALA\', 89, \'GT\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (821, \'warga_negara\', \'GUERNSEY\', \'GUERNSEY\', 90, \'GG\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (822, \'warga_negara\', \'GUINEA\', \'GUINEA\', 91, \'GN\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (823, \'warga_negara\', \'GUINEA-BISSAU\', \'GUINEA-BISSAU\', 92, \'GW\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (824, \'warga_negara\', \'GUYANA\', \'GUYANA\', 93, \'GY\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (825, \'warga_negara\', \'HAITI\', \'HAITI\', 94, \'HT\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (826, \'warga_negara\', \'HEARD ISLAND AND MCDONALD ISLANDS\', \'HEARD ISLAND AND MCDONALD ISLANDS\', 95, \'HM\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (827, \'warga_negara\', \'HOLY SEE (VATICAN CITY STATE)\', \'HOLY SEE (VATICAN CITY STATE)\', 96, \'VA\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (828, \'warga_negara\', \'HONDURAS\', \'HONDURAS\', 97, \'HN\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (829, \'warga_negara\', \'HONG KONG\', \'HONG KONG\', 98, \'HK\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (830, \'warga_negara\', \'HUNGARY\', \'HUNGARY\', 99, \'HU\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (831, \'warga_negara\', \'ICELAND\', \'ICELAND\', 100, \'IS\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (832, \'warga_negara\', \'INDIA\', \'INDIA\', 101, \'IN\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (833, \'warga_negara\', \'IRAN, ISLAMIC REPUBLIC OF\', \'IRAN, ISLAMIC REPUBLIC OF\', 102, \'IR\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (834, \'warga_negara\', \'IRAQ\', \'IRAQ\', 103, \'IQ\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (835, \'warga_negara\', \'IRELAND\', \'IRELAND\', 104, \'IE\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (836, \'warga_negara\', \'ISLE OF MAN\', \'ISLE OF MAN\', 105, \'IM\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (837, \'warga_negara\', \'ISRAEL\', \'ISRAEL\', 106, \'IL\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (838, \'warga_negara\', \'ITALY\', \'ITALY\', 107, \'IT\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (839, \'warga_negara\', \'JAMAICA\', \'JAMAICA\', 108, \'JM\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (840, \'warga_negara\', \'JAPAN\', \'JAPAN\', 109, \'JP\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (841, \'warga_negara\', \'JERSEY\', \'JERSEY\', 110, \'JE\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (842, \'warga_negara\', \'JORDAN\', \'JORDAN\', 111, \'JO\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (843, \'warga_negara\', \'KAZAKHSTAN\', \'KAZAKHSTAN\', 112, \'KZ\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (844, \'warga_negara\', \'KENYA\', \'KENYA\', 113, \'KE\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (845, \'warga_negara\', \'KIRIBATI\', \'KIRIBATI\', 114, \'KI\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (846, \'warga_negara\', \'KOREA, DEMOCRATIC PEOPLE\'\'S REPUBLIC OF\', \'KOREA, DEMOCRATIC PEOPLE\'\'S REPUBLIC OF\', 115, \'KP\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (847, \'warga_negara\', \'KOREA, REPUBLIC OF\', \'KOREA, REPUBLIC OF\', 116, \'KR\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (848, \'warga_negara\', \'KUWAIT\', \'KUWAIT\', 117, \'KW\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (849, \'warga_negara\', \'KYRGYZSTAN\', \'KYRGYZSTAN\', 118, \'KG\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (850, \'warga_negara\', \'LAND ISLANDS\', \'LAND ISLANDS\', 119, \'AX\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (851, \'warga_negara\', \'LAO PEOPLE\'\'S DEMOCRATIC REPUBLIC\', \'LAO PEOPLE\'\'S DEMOCRATIC REPUBLIC\', 120, \'LA\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (852, \'warga_negara\', \'LATVIA\', \'LATVIA\', 121, \'LV\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (853, \'warga_negara\', \'LEBANON\', \'LEBANON\', 122, \'LB\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (854, \'warga_negara\', \'LESOTHO\', \'LESOTHO\', 123, \'LS\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (855, \'warga_negara\', \'LIBERIA\', \'LIBERIA\', 124, \'LR\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (856, \'warga_negara\', \'LIBYAN ARAB JAMAHIRIYA\', \'LIBYAN ARAB JAMAHIRIYA\', 125, \'LY\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (857, \'warga_negara\', \'LIECHTENSTEIN\', \'LIECHTENSTEIN\', 126, \'LI\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (858, \'warga_negara\', \'LITHUANIA\', \'LITHUANIA\', 127, \'LT\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (859, \'warga_negara\', \'LUXEMBOURG\', \'LUXEMBOURG\', 128, \'LU\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (860, \'warga_negara\', \'MACAO\', \'MACAO\', 129, \'MO\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (861, \'warga_negara\', \'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF\', \'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF\', 130, \'MK\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (862, \'warga_negara\', \'MADAGASCAR\', \'MADAGASCAR\', 131, \'MG\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (863, \'warga_negara\', \'MALAWI\', \'MALAWI\', 132, \'MW\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (864, \'warga_negara\', \'MALAYSIAN\', \'MALAYSIAN\', 133, \'02\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (865, \'warga_negara\', \'MALDIVES\', \'MALDIVES\', 134, \'MV\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (866, \'warga_negara\', \'MALI\', \'MALI\', 135, \'ML\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (867, \'warga_negara\', \'MALTA\', \'MALTA\', 136, \'MT\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (868, \'warga_negara\', \'MARSHALL ISLANDS\', \'MARSHALL ISLANDS\', 137, \'MH\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (869, \'warga_negara\', \'MARTINIQUE\', \'MARTINIQUE\', 138, \'MQ\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (870, \'warga_negara\', \'MAURITANIA\', \'MAURITANIA\', 139, \'MR\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (871, \'warga_negara\', \'MAURITIUS\', \'MAURITIUS\', 140, \'MU\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (872, \'warga_negara\', \'MAYOTTE\', \'MAYOTTE\', 141, \'YT\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (873, \'warga_negara\', \'MEXICO\', \'MEXICO\', 142, \'MX\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (874, \'warga_negara\', \'MICRONESIA, FEDERATED STATES OF\', \'MICRONESIA, FEDERATED STATES OF\', 143, \'FM\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (875, \'warga_negara\', \'MOLDOVA, REPUBLIC OF\', \'MOLDOVA, REPUBLIC OF\', 144, \'MD\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (876, \'warga_negara\', \'MONACO\', \'MONACO\', 145, \'MC\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (877, \'warga_negara\', \'MONGOLIA\', \'MONGOLIA\', 146, \'MN\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (878, \'warga_negara\', \'MONTENEGRO\', \'MONTENEGRO\', 147, \'ME\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (879, \'warga_negara\', \'MONTSERRAT\', \'MONTSERRAT\', 148, \'MS\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (880, \'warga_negara\', \'MOROCCO\', \'MOROCCO\', 149, \'MA\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (881, \'warga_negara\', \'MOZAMBIQUE\', \'MOZAMBIQUE\', 150, \'MZ\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (882, \'warga_negara\', \'MYANMAR\', \'MYANMAR\', 151, \'MM\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (883, \'warga_negara\', \'NAMIBIA\', \'NAMIBIA\', 152, \'NA\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (884, \'warga_negara\', \'NAURU\', \'NAURU\', 153, \'NR\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (885, \'warga_negara\', \'NEPAL\', \'NEPAL\', 154, \'NP\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (886, \'warga_negara\', \'NETHERLANDS\', \'NETHERLANDS\', 155, \'NL\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (887, \'warga_negara\', \'NETHERLANDS ANTILLES\', \'NETHERLANDS ANTILLES\', 156, \'AN\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (888, \'warga_negara\', \'NEW CALEDONIA\', \'NEW CALEDONIA\', 157, \'NC\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (889, \'warga_negara\', \'NEW ZEALAND\', \'NEW ZEALAND\', 158, \'NZ\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (890, \'warga_negara\', \'NICARAGUA\', \'NICARAGUA\', 159, \'NI\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (891, \'warga_negara\', \'NIGER\', \'NIGER\', 160, \'NE\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (892, \'warga_negara\', \'NIGERIA\', \'NIGERIA\', 161, \'NG\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (893, \'warga_negara\', \'NIUE\', \'NIUE\', 162, \'NU\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (894, \'warga_negara\', \'NORFOLK ISLAND\', \'NORFOLK ISLAND\', 163, \'NF\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (895, \'warga_negara\', \'NORTHERN MARIANA ISLANDS\', \'NORTHERN MARIANA ISLANDS\', 164, \'MP\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (896, \'warga_negara\', \'NORWAY\', \'NORWAY\', 165, \'NO\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (897, \'warga_negara\', \'OMAN\', \'OMAN\', 166, \'OM\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (898, \'warga_negara\', \'PAKISTAN\', \'PAKISTAN\', 167, \'PK\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (899, \'warga_negara\', \'PALAU\', \'PALAU\', 168, \'PW\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (900, \'warga_negara\', \'PALESTINIAN TERRITORY, OCCUPIED\', \'PALESTINIAN TERRITORY, OCCUPIED\', 169, \'PS\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (901, \'warga_negara\', \'PANAMA\', \'PANAMA\', 170, \'PA\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (902, \'warga_negara\', \'PAPUA NEW GUINEA\', \'PAPUA NEW GUINEA\', 171, \'PG\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (903, \'warga_negara\', \'PARAGUAY\', \'PARAGUAY\', 172, \'PY\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (904, \'warga_negara\', \'PERU\', \'PERU\', 173, \'PE\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (905, \'warga_negara\', \'PHILIPPINES\', \'PHILIPPINES\', 174, \'PH\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (906, \'warga_negara\', \'PITCAIRN\', \'PITCAIRN\', 175, \'PN\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (907, \'warga_negara\', \'POLAND\', \'POLAND\', 176, \'PL\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (908, \'warga_negara\', \'PORTUGAL\', \'PORTUGAL\', 177, \'PT\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (909, \'warga_negara\', \'PUERTO RICO\', \'PUERTO RICO\', 178, \'PR\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (910, \'warga_negara\', \'QATAR\', \'QATAR\', 179, \'QA\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (911, \'warga_negara\', \'REUNION\', \'REUNION\', 180, \'RE\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (912, \'warga_negara\', \'ROMANIA\', \'ROMANIA\', 181, \'RO\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (913, \'warga_negara\', \'RUSSIAN FEDERATION\', \'RUSSIAN FEDERATION\', 182, \'RU\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (914, \'warga_negara\', \'RWANDA\', \'RWANDA\', 183, \'RW\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (915, \'warga_negara\', \'SAINT BARTHLEMY\', \'SAINT BARTHLEMY\', 184, \'BL\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (916, \'warga_negara\', \'SAINT HELENA\', \'SAINT HELENA\', 185, \'SH\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (917, \'warga_negara\', \'SAINT KITTS AND NEVIS\', \'SAINT KITTS AND NEVIS\', 186, \'KN\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (918, \'warga_negara\', \'SAINT LUCIA\', \'SAINT LUCIA\', 187, \'LC\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (919, \'warga_negara\', \'SAINT MARTIN\', \'SAINT MARTIN\', 188, \'MF\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (920, \'warga_negara\', \'SAINT PIERRE AND MIQUELON\', \'SAINT PIERRE AND MIQUELON\', 189, \'PM\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (921, \'warga_negara\', \'SAINT VINCENT AND THE GRENADINES\', \'SAINT VINCENT AND THE GRENADINES\', 190, \'VC\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (922, \'warga_negara\', \'SAMOA\', \'SAMOA\', 191, \'WS\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (923, \'warga_negara\', \'SAN MARINO\', \'SAN MARINO\', 192, \'SM\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (924, \'warga_negara\', \'SAO TOME AND PRINCIPE\', \'SAO TOME AND PRINCIPE\', 193, \'ST\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (925, \'warga_negara\', \'SAUDI ARABIA\', \'SAUDI ARABIA\', 194, \'SA\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (926, \'warga_negara\', \'SENEGAL\', \'SENEGAL\', 195, \'SN\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (927, \'warga_negara\', \'SERBIA\', \'SERBIA\', 196, \'RS\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (928, \'warga_negara\', \'SEYCHELLES\', \'SEYCHELLES\', 197, \'SC\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (929, \'warga_negara\', \'SIERRA LEONE\', \'SIERRA LEONE\', 198, \'SL\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (930, \'warga_negara\', \'SINGAPORE\', \'SINGAPORE\', 199, \'SG\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (931, \'warga_negara\', \'SLOVAKIA\', \'SLOVAKIA\', 200, \'SK\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (932, \'warga_negara\', \'SLOVENIA\', \'SLOVENIA\', 201, \'SI\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (933, \'warga_negara\', \'SOLOMON ISLANDS\', \'SOLOMON ISLANDS\', 202, \'SB\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (934, \'warga_negara\', \'SOMALIA\', \'SOMALIA\', 203, \'SO\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (935, \'warga_negara\', \'SOUTH AFRICA\', \'SOUTH AFRICA\', 204, \'ZA\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (936, \'warga_negara\', \'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS\', \'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS\', 205, \'GS\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (937, \'warga_negara\', \'SPAIN\', \'SPAIN\', 206, \'ES\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (938, \'warga_negara\', \'SRI LANKA\', \'SRI LANKA\', 207, \'LK\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (939, \'warga_negara\', \'SUDAN\', \'SUDAN\', 208, \'SD\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (940, \'warga_negara\', \'SURINAME\', \'SURINAME\', 209, \'SR\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (941, \'warga_negara\', \'SVALBARD AND JAN MAYEN\', \'SVALBARD AND JAN MAYEN\', 210, \'SJ\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (942, \'warga_negara\', \'SWAZILAND\', \'SWAZILAND\', 211, \'SZ\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (943, \'warga_negara\', \'SWEDEN\', \'SWEDEN\', 212, \'SE\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (944, \'warga_negara\', \'SWITZERLAND\', \'SWITZERLAND\', 213, \'CH\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (945, \'warga_negara\', \'SYRIAN ARAB REPUBLIC\', \'SYRIAN ARAB REPUBLIC\', 214, \'SY\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (946, \'warga_negara\', \'TAIWAN, PROVINCE OF CHINA\', \'TAIWAN, PROVINCE OF CHINA\', 215, \'TW\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (947, \'warga_negara\', \'TAJIKISTAN\', \'TAJIKISTAN\', 216, \'TJ\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (948, \'warga_negara\', \'TANZANIA, UNITED REPUBLIC OF\', \'TANZANIA, UNITED REPUBLIC OF\', 217, \'TZ\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (949, \'warga_negara\', \'THAILAND\', \'THAILAND\', 218, \'TH\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (950, \'warga_negara\', \'TIMOR-LESTE\', \'TIMOR-LESTE\', 219, \'TL\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (951, \'warga_negara\', \'TOGO\', \'TOGO\', 220, \'TG\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (952, \'warga_negara\', \'TOKELAU\', \'TOKELAU\', 221, \'TK\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (953, \'warga_negara\', \'TONGA\', \'TONGA\', 222, \'TO\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (954, \'warga_negara\', \'TRINIDAD AND TOBAGO\', \'TRINIDAD AND TOBAGO\', 223, \'TT\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (955, \'warga_negara\', \'TUNISIA\', \'TUNISIA\', 224, \'TN\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (956, \'warga_negara\', \'TURKEY\', \'TURKEY\', 225, \'TR\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (957, \'warga_negara\', \'TURKMENISTAN\', \'TURKMENISTAN\', 226, \'TM\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (958, \'warga_negara\', \'TURKS AND CAICOS ISLANDS\', \'TURKS AND CAICOS ISLANDS\', 227, \'TC\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (959, \'warga_negara\', \'TUVALU\', \'TUVALU\', 228, \'TV\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (960, \'warga_negara\', \'UGANDA\', \'UGANDA\', 229, \'UG\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (961, \'warga_negara\', \'UKRAINE\', \'UKRAINE\', 230, \'UA\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (962, \'warga_negara\', \'UNITED ARAB EMIRATES\', \'UNITED ARAB EMIRATES\', 231, \'AE\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (963, \'warga_negara\', \'UNITED KINGDOM\', \'UNITED KINGDOM\', 232, \'GB\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (964, \'warga_negara\', \'UNITED STATES\', \'UNITED STATES\', 233, \'US\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (965, \'warga_negara\', \'UNITED STATES MINOR OUTLYING ISLANDS\', \'UNITED STATES MINOR OUTLYING ISLANDS\', 234, \'UM\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (966, \'warga_negara\', \'URUGUAY\', \'URUGUAY\', 235, \'UY\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (967, \'warga_negara\', \'UZBEKISTAN\', \'UZBEKISTAN\', 236, \'UZ\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (968, \'warga_negara\', \'VANUATU\', \'VANUATU\', 237, \'VU\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (969, \'warga_negara\', \'VENEZUELA\', \'VENEZUELA\', 238, \'VE\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (970, \'warga_negara\', \'VIET NAM\', \'VIET NAM\', 239, \'VN\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (971, \'warga_negara\', \'VIRGIN ISLANDS, BRITISH\', \'VIRGIN ISLANDS, BRITISH\', 240, \'VG\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (972, \'warga_negara\', \'VIRGIN ISLANDS, U.S.\', \'VIRGIN ISLANDS, U.S.\', 241, \'VI\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (973, \'warga_negara\', \'WALLIS AND FUTUNA\', \'WALLIS AND FUTUNA\', 242, \'WF\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (974, \'warga_negara\', \'WESTERN SAHARA\', \'WESTERN SAHARA\', 243, \'EH\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (975, \'warga_negara\', \'YEMEN\', \'YEMEN\', 244, \'YE\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (976, \'warga_negara\', \'ZAMBIA\', \'ZAMBIA\', 245, \'ZM\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL),
                (977, \'warga_negara\', \'ZIMBABWE\', \'ZIMBABWE\', 246, \'ZW\', NULL, CURRENT_DATE, NULL, NULL, NULL, NULL, \'f\', \'t\', NULL, NULL);
        ');
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m201224_081403_improve_add_data_citizen_table_lookup_m cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m201224_081403_improve_add_data_citizen_table_lookup_m cannot be reverted.\n";

        return false;
    }
    */
}
