<?php

use yii\db\Migration;

/**
 * Class m210526_070732_migrate_20210526_int_obatalkespasien_r_update
 */
class m210526_070732_migrate_20210526_int_obatalkespasien_r_update extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
$this->execute("CREATE OR REPLACE FUNCTION \"public\".\"int_obatalkespasien_r_update\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$ 
    
    DECLARE
        v_keterangan VARCHAR;
    BEGIN
        IF(NEW.is_deleted IS TRUE)
        THEN
            v_keterangan := 'ACCRUAL REVERSAL';
            
            -- INSERT table history int_obatalkespasien_r REVERSAL
                INSERT INTO int_obatalkespasien_r (     
                obatalkespasien_id ,
                sumberdana_id ,
                racikan_id ,
                returresepdetail_id ,
                tipepaket_id ,
                ruangan_id ,
                carabayar_id ,
                pegawai_id ,
                daftartindakan_id ,
                tindakanpelayanan_id ,
                satuankecil_id ,
                shift_id ,
                pendaftaran_id ,
                obatalkes_id ,
                pasien_id ,
                penjamin_id ,
                kelaspelayanan_id ,
                pasienanastesi_id ,
                pasienmasukpenunjang_id ,
                pasienadmisi_id ,
                obatsudahbayar_id ,
                penjualanresep_id ,
                tglpelayanan ,
                r ,
                rke ,
                permintaan_oa ,
                jmlkemasan_oa ,
                kekuatan_oa ,
                satuankekuatan_oa ,
                qty_oa ,
                hargasatuan_oa ,
                signa_oa ,
                harganetto_oa ,
                hargajual_oa , 
                etiket ,
                jmlexposerad ,
                kontrasrad ,
                biayaservice ,
                biayakonseling ,
                jasadokterresep ,
                biayakemasan ,
                biayaadministrasi ,
                tarifcyto ,
                discount , 
                subsidiasuransi ,
                subsidipemerintah ,
                subsidirs ,
                iurbiaya ,
                oa ,
                pembulatan ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                permohonanoadetail_id ,
                persenppnjual ,
                resepturdetail_id ,
                nilaippnjual ,
                perawat1_id ,
                perawat2_id ,
                instruksitindakanbmhp_id ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_jurnal ,
                konfigmargindetail_id ,
                qty_konversi ,
                is_penatajasa ,
                det ,
                status_bmhp ,
                det_konversi ,
                signa ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date , 
                deleted_by ,
                keterangan,
                no_obatalkespasien
            )VALUES(
                OLD.obatalkespasien_id ,
                OLD.sumberdana_id ,
                OLD.racikan_id ,
                OLD.returresepdetail_id ,
                OLD.tipepaket_id ,
                OLD.ruangan_id ,
                OLD.carabayar_id ,
                OLD.pegawai_id ,
                OLD.daftartindakan_id ,
                OLD.tindakanpelayanan_id ,
                OLD.satuankecil_id ,
                OLD.shift_id ,
                OLD.pendaftaran_id ,
                OLD.obatalkes_id ,
                OLD.pasien_id ,
                OLD.penjamin_id ,
                OLD.kelaspelayanan_id ,
                OLD.pasienanastesi_id ,
                OLD.pasienmasukpenunjang_id ,
                OLD.pasienadmisi_id ,
                OLD.obatsudahbayar_id ,
                OLD.penjualanresep_id ,
                OLD.tglpelayanan ,
                OLD.r ,
                OLD.rke ,
                OLD.permintaan_oa ,
                OLD.jmlkemasan_oa ,
                OLD.kekuatan_oa ,
                OLD.satuankekuatan_oa ,
                -1 * OLD.qty_oa ,
                -1 * OLD.hargasatuan_oa ,
                OLD.signa_oa ,
                -1 * OLD.harganetto_oa ,
                -1 * OLD.hargajual_oa , 
                OLD.etiket ,
                -1 * OLD.jmlexposerad ,
                OLD.kontrasrad ,
                -1 * OLD.biayaservice ,
                -1 * OLD.biayakonseling ,
                -1 * OLD.jasadokterresep ,
                -1 * OLD.biayakemasan ,
                -1 * OLD.biayaadministrasi ,
                -1 * OLD.tarifcyto ,
                -1 * OLD.discount , 
                -1 * OLD.subsidiasuransi ,
                -1 * OLD.subsidipemerintah ,
                -1 * OLD.subsidirs ,
                -1 * OLD.iurbiaya ,
                OLD.oa ,
                -1 * OLD.pembulatan ,
                OLD.verifikasitagihan_id ,
                OLD.jurnalrekening_id ,
                OLD.permohonanoadetail_id ,
                OLD.persenppnjual ,
                OLD.resepturdetail_id ,
                -1 * OLD.nilaippnjual ,
                OLD.perawat1_id ,
                OLD.perawat2_id ,
                OLD.instruksitindakanbmhp_id ,
                OLD.implementasi_id ,
                OLD.is_dilakukan ,
                OLD.pemakaianambulan_id ,
                OLD.is_jurnal ,
                OLD.konfigmargindetail_id ,
                -1 * OLD.qty_konversi ,
                OLD.is_penatajasa ,
                -1 * OLD.det ,
                OLD.status_bmhp ,
                -1 * OLD.det_konversi ,
                OLD.signa ,
                OLD.additional_data ,
                OLD.created_date ,
                OLD.created_by ,
                OLD.modified_count ,
                OLD.last_modified_date ,
                OLD.last_modified_by ,
                OLD.is_deleted ,
                OLD.is_active ,
                OLD.deleted_date , 
                OLD.deleted_by ,
                v_keterangan,
                OLD.no_obatalkespasien
            );
        ELSE
            v_keterangan := 'ACCRUAL';
            
            -- INSERT table history int_obatalkespasien_r REVERSAL
                INSERT INTO int_obatalkespasien_r (     
                obatalkespasien_id ,
                sumberdana_id ,
                racikan_id ,
                returresepdetail_id ,
                tipepaket_id ,
                ruangan_id ,
                carabayar_id ,
                pegawai_id ,
                daftartindakan_id ,
                tindakanpelayanan_id ,
                satuankecil_id ,
                shift_id ,
                pendaftaran_id ,
                obatalkes_id ,
                pasien_id ,
                penjamin_id ,
                kelaspelayanan_id ,
                pasienanastesi_id ,
                pasienmasukpenunjang_id ,
                pasienadmisi_id ,
                obatsudahbayar_id ,
                penjualanresep_id ,
                tglpelayanan ,
                r ,
                rke ,
                permintaan_oa ,
                jmlkemasan_oa ,
                kekuatan_oa ,
                satuankekuatan_oa ,
                qty_oa ,
                hargasatuan_oa ,
                signa_oa ,
                harganetto_oa ,
                hargajual_oa , 
                etiket ,
                jmlexposerad ,
                kontrasrad ,
                biayaservice ,
                biayakonseling ,
                jasadokterresep ,
                biayakemasan ,
                biayaadministrasi ,
                tarifcyto ,
                discount , 
                subsidiasuransi ,
                subsidipemerintah ,
                subsidirs ,
                iurbiaya ,
                oa ,
                pembulatan ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                permohonanoadetail_id ,
                persenppnjual ,
                resepturdetail_id ,
                nilaippnjual ,
                perawat1_id ,
                perawat2_id ,
                instruksitindakanbmhp_id ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_jurnal ,
                konfigmargindetail_id ,
                qty_konversi ,
                is_penatajasa ,
                det ,
                status_bmhp ,
                det_konversi ,
                signa ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date , 
                deleted_by ,
                keterangan,
                no_obatalkespasien
            )VALUES(
                OLD.obatalkespasien_id ,
                OLD.sumberdana_id ,
                OLD.racikan_id ,
                OLD.returresepdetail_id ,
                OLD.tipepaket_id ,
                OLD.ruangan_id ,
                OLD.carabayar_id ,
                OLD.pegawai_id ,
                OLD.daftartindakan_id ,
                OLD.tindakanpelayanan_id ,
                OLD.satuankecil_id ,
                OLD.shift_id ,
                OLD.pendaftaran_id ,
                OLD.obatalkes_id ,
                OLD.pasien_id ,
                OLD.penjamin_id ,
                OLD.kelaspelayanan_id ,
                OLD.pasienanastesi_id ,
                OLD.pasienmasukpenunjang_id ,
                OLD.pasienadmisi_id ,
                OLD.obatsudahbayar_id ,
                OLD.penjualanresep_id ,
                OLD.tglpelayanan ,
                OLD.r ,
                OLD.rke ,
                OLD.permintaan_oa ,
                OLD.jmlkemasan_oa ,
                OLD.kekuatan_oa ,
                OLD.satuankekuatan_oa ,
                -1 * OLD.qty_oa ,
                -1 * OLD.hargasatuan_oa ,
                OLD.signa_oa ,
                -1 * OLD.harganetto_oa ,
                -1 * OLD.hargajual_oa , 
                OLD.etiket ,
                -1 * OLD.jmlexposerad ,
                OLD.kontrasrad ,
                -1 * OLD.biayaservice ,
                -1 * OLD.biayakonseling ,
                -1 * OLD.jasadokterresep ,
                -1 * OLD.biayakemasan ,
                -1 * OLD.biayaadministrasi ,
                -1 * OLD.tarifcyto ,
                -1 * OLD.discount , 
                -1 * OLD.subsidiasuransi ,
                -1 * OLD.subsidipemerintah ,
                -1 * OLD.subsidirs ,
                -1 * OLD.iurbiaya ,
                OLD.oa ,
                -1 * OLD.pembulatan ,
                OLD.verifikasitagihan_id ,
                OLD.jurnalrekening_id ,
                OLD.permohonanoadetail_id ,
                OLD.persenppnjual ,
                OLD.resepturdetail_id ,
                -1 * OLD.nilaippnjual ,
                OLD.perawat1_id ,
                OLD.perawat2_id ,
                OLD.instruksitindakanbmhp_id ,
                OLD.implementasi_id ,
                OLD.is_dilakukan ,
                OLD.pemakaianambulan_id ,
                OLD.is_jurnal ,
                OLD.konfigmargindetail_id ,
                -1 * OLD.qty_konversi ,
                OLD.is_penatajasa ,
                -1 * OLD.det ,
                OLD.status_bmhp ,
                -1 * OLD.det_konversi ,
                OLD.signa ,
                OLD.additional_data ,
                OLD.created_date ,
                OLD.created_by ,
                OLD.modified_count ,
                OLD.last_modified_date ,
                OLD.last_modified_by ,
                OLD.is_deleted ,
                OLD.is_active ,
                OLD.deleted_date , 
                OLD.deleted_by ,
                'ACCRUAL REVERSAL',
                OLD.no_obatalkespasien
            );
        
    -- INSERT table history int_obatalkespasien_r
    INSERT INTO int_obatalkespasien_r (     
        obatalkespasien_id ,
        sumberdana_id ,
        racikan_id ,
        returresepdetail_id ,
        tipepaket_id ,
        ruangan_id ,
        carabayar_id ,
        pegawai_id ,
        daftartindakan_id ,
        tindakanpelayanan_id ,
        satuankecil_id ,
        shift_id ,
        pendaftaran_id ,
        obatalkes_id ,
        pasien_id ,
        penjamin_id ,
        kelaspelayanan_id ,
        pasienanastesi_id ,
        pasienmasukpenunjang_id ,
        pasienadmisi_id ,
        obatsudahbayar_id ,
        penjualanresep_id ,
        tglpelayanan ,
        r ,
        rke ,
        permintaan_oa ,
        jmlkemasan_oa ,
        kekuatan_oa ,
        satuankekuatan_oa ,
        qty_oa ,
        hargasatuan_oa ,
        signa_oa ,
        harganetto_oa ,
        hargajual_oa , 
        etiket ,
        jmlexposerad ,
        kontrasrad ,
        biayaservice ,
        biayakonseling ,
        jasadokterresep ,
        biayakemasan ,
        biayaadministrasi ,
        tarifcyto ,
        discount , 
        subsidiasuransi ,
        subsidipemerintah ,
        subsidirs ,
        iurbiaya ,
        oa ,
        pembulatan ,
        verifikasitagihan_id ,
        jurnalrekening_id ,
        permohonanoadetail_id ,
        persenppnjual ,
        resepturdetail_id ,
        nilaippnjual ,
        perawat1_id ,
        perawat2_id ,
        instruksitindakanbmhp_id ,
        implementasi_id ,
        is_dilakukan ,
        pemakaianambulan_id ,
        is_jurnal ,
        konfigmargindetail_id ,
        qty_konversi ,
        is_penatajasa ,
        det ,
        status_bmhp ,
        det_konversi ,
        signa ,
        additional_data ,
        created_date ,
        created_by ,
        modified_count ,
        last_modified_date ,
        last_modified_by ,
        is_deleted ,
        is_active ,
        deleted_date , 
        deleted_by ,
        keterangan,
        no_obatalkespasien
    )VALUES(
        NEW.obatalkespasien_id ,
        NEW.sumberdana_id ,
        NEW.racikan_id ,
        NEW.returresepdetail_id ,
        NEW.tipepaket_id ,
        NEW.ruangan_id ,
        NEW.carabayar_id ,
        NEW.pegawai_id ,
        NEW.daftartindakan_id ,
        NEW.tindakanpelayanan_id ,
        NEW.satuankecil_id ,
        NEW.shift_id ,
        NEW.pendaftaran_id ,
        NEW.obatalkes_id ,
        NEW.pasien_id ,
        NEW.penjamin_id ,
        NEW.kelaspelayanan_id ,
        NEW.pasienanastesi_id ,
        NEW.pasienmasukpenunjang_id ,
        NEW.pasienadmisi_id ,
        NEW.obatsudahbayar_id ,
        NEW.penjualanresep_id ,
        NEW.tglpelayanan ,
        NEW.r ,
        NEW.rke ,
        NEW.permintaan_oa ,
        NEW.jmlkemasan_oa ,
        NEW.kekuatan_oa ,
        NEW.satuankekuatan_oa ,
        NEW.qty_oa ,
        NEW.hargasatuan_oa ,
        NEW.signa_oa ,
        NEW.harganetto_oa ,
        NEW.hargajual_oa , 
        NEW.etiket ,
        NEW.jmlexposerad ,
        NEW.kontrasrad ,
        NEW.biayaservice ,
        NEW.biayakonseling ,
        NEW.jasadokterresep ,
        NEW.biayakemasan ,
        NEW.biayaadministrasi ,
        NEW.tarifcyto ,
        NEW.discount , 
        NEW.subsidiasuransi ,
        NEW.subsidipemerintah ,
        NEW.subsidirs ,
        NEW.iurbiaya ,
        NEW.oa ,
        NEW.pembulatan ,
        NEW.verifikasitagihan_id ,
        NEW.jurnalrekening_id ,
        NEW.permohonanoadetail_id ,
        NEW.persenppnjual ,
        NEW.resepturdetail_id ,
        NEW.nilaippnjual ,
        NEW.perawat1_id ,
        NEW.perawat2_id ,
        NEW.instruksitindakanbmhp_id ,
        NEW.implementasi_id ,
        NEW.is_dilakukan ,
        NEW.pemakaianambulan_id ,
        NEW.is_jurnal ,
        NEW.konfigmargindetail_id ,
        NEW.qty_konversi ,
        NEW.is_penatajasa ,
        NEW.det ,
        NEW.status_bmhp ,
        NEW.det_konversi ,
        NEW.signa ,
        NEW.additional_data ,
        NEW.created_date ,
        NEW.created_by ,
        NEW.modified_count ,
        NEW.last_modified_date ,
        NEW.last_modified_by ,
        NEW.is_deleted ,
        NEW.is_active ,
        NEW.deleted_date , 
        NEW.deleted_by ,
        v_keterangan,
        NEW.no_obatalkespasien
    );  
    END IF;

    RETURN NEW;

END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

$this->execute('ALTER FUNCTION "public"."int_obatalkespasien_r_update"() OWNER TO "postgres";');

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m210526_070732_migrate_20210526_int_obatalkespasien_r_update cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m210526_070732_migrate_20210526_int_obatalkespasien_r_update cannot be reverted.\n";

        return false;
    }
    */
}
