<?php

use yii\db\Migration;

/**
 * Class m210908_041229_improvment_history_asesmen_rd_US1280
 */
class m210908_041229_improvment_history_asesmen_rd_US1280 extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->execute('
           DROP TABLE IF EXISTS asesmenperawatrd_r; 
        ');

        $this->execute('
            CREATE TABLE IF NOT EXISTS "public"."asesmenperawatrd_r" (
                "id" serial8 NOT NULL,
                "asesmenperawatrd_id" int4,
                "pendaftaran_id" int4,
                "ruangan_id" int4,
                "tgl_asesmen" timestamp(0),
                "perawat_id" int4,
                "tgl_pendaftaran" timestamp(0),
                "tgl_datang" timestamp(0),
                "prioritas_triage" int4,
                "is_trauma" bool,
                "pasien_datang" int4,
                "jenis_asmenperawat" int4,
                "alasan_kunjungan" text COLLATE "pg_catalog"."default",
                "is_alergi" bool,
                "is_alergiobat" bool,
                "alergi_obat" text COLLATE "pg_catalog"."default",
                "is_alergilainnya" bool,
                "alergi_lainnya" text COLLATE "pg_catalog"."default",
                "keadaan_umum" text COLLATE "pg_catalog"."default",
                "is_nyeri" bool,
                "lokasi_nyeri" varchar(255) COLLATE "pg_catalog"."default",
                "skala_nyeri" int2,
                "metode_nyeri" text COLLATE "pg_catalog"."default",
                "is_resikojatuh" bool,
                "keluhan" text COLLATE "pg_catalog"."default",
                "lama_sakit" int4,
                "r_penyakitdahulu" text COLLATE "pg_catalog"."default",
                "r_penyakitkeluarga" text COLLATE "pg_catalog"."default",
                "catatan_asesmen" text COLLATE "pg_catalog"."default",
                "gcseye_id" int4,
                "gcsverbal_id" int4,
                "gcsmotorik_id" int4,
                "hasil_gcs" varchar(255) COLLATE "pg_catalog"."default",
                "is_kapitis" bool,
                "td_systolic" float4,
                "td_diastolic" float4,
                "tekanan_darah" varchar(100) COLLATE "pg_catalog"."default",
                "hasil_td" varchar(100) COLLATE "pg_catalog"."default",
                "detak_nadi" float4,
                "pernapasan" float4,
                "suhu_tubuh" float4,
                "tinggi_badan" float4,
                "berat_badan" float4,
                "bb_ideal" float4,
                "imt" float4,
                "ket_imt" varchar(100) COLLATE "pg_catalog"."default",
                "spo2" float4,
                "kelaianan_tubuh" text COLLATE "pg_catalog"."default",
                "detail_asesmen" text COLLATE "pg_catalog"."default",
                "additional_data" text COLLATE "pg_catalog"."default",
                "created_date" timestamp(6) NOT NULL DEFAULT (\'now\'::text)::date,
                "created_by" int4,
                "modified_count" int4,
                "last_modified_date" timestamp(6),
                "last_modified_by" int4,
                "is_deleted" bool NOT NULL DEFAULT false,
                "is_active" bool NOT NULL DEFAULT true,
                "deleted_date" timestamp(6),
                "deleted_by" int4,
                "formulir_triage" text COLLATE "pg_catalog"."default",
                "formulir_fisik" text COLLATE "pg_catalog"."default",
                "tgl_keluar" timestamp(6),
                "agama_id" int4,
                "pekerjaan_id" int4,
                "caramasuk_id" int4,
                "pendidikan_id" int4,
                "jalur_nafas" text COLLATE "pg_catalog"."default",
                "jalur_nafas_oksigen" text COLLATE "pg_catalog"."default",
                "pernafasan" text COLLATE "pg_catalog"."default",
                "pernafasan_spontan" text COLLATE "pg_catalog"."default",
                "pernafasan_takipnea" text COLLATE "pg_catalog"."default",
                "tensi" varchar(30) COLLATE "pg_catalog"."default",
                "reguler" varchar(30) COLLATE "pg_catalog"."default",
                "ireguler" varchar(30) COLLATE "pg_catalog"."default",
                "capilary_refill" text COLLATE "pg_catalog"."default",
                "perfusi" text COLLATE "pg_catalog"."default",
                "akral" text COLLATE "pg_catalog"."default",
                "pendarahan" text COLLATE "pg_catalog"."default",
                "pendarahan_cc" varchar(30) COLLATE "pg_catalog"."default",
                "is_bradikarida" bool,
                "is_takikardia" bool,
                "pupil" text COLLATE "pg_catalog"."default",
                "reaksi_pupil" text COLLATE "pg_catalog"."default",
                "reaksi_pupil_lainnya" text COLLATE "pg_catalog"."default",
                "kepala" text COLLATE "pg_catalog"."default",
                "abdomen" text COLLATE "pg_catalog"."default",
                "maksilofacial" text COLLATE "pg_catalog"."default",
                "parineum" text COLLATE "pg_catalog"."default",
                "tulan_leher" text COLLATE "pg_catalog"."default",
                "muskuloskeletal" text COLLATE "pg_catalog"."default",
                "paru_paru" text COLLATE "pg_catalog"."default",
                "extremitas" text COLLATE "pg_catalog"."default",
                "skala_wong_baker" text COLLATE "pg_catalog"."default",
                "asesmen_auto" text COLLATE "pg_catalog"."default",
                "asesmen_allo" text COLLATE "pg_catalog"."default",
                "r_penyakitsaatini" text COLLATE "pg_catalog"."default",
                "r_pengobatan" text COLLATE "pg_catalog"."default",
                "jalan_nafas_bersin" text COLLATE "pg_catalog"."default",
                "nilai_decubitus" text COLLATE "pg_catalog"."default",
                "nilai_luka_bakar" text COLLATE "pg_catalog"."default",
                "survey_kepala" text COLLATE "pg_catalog"."default",
                "survey_kepala_lacerasi" text COLLATE "pg_catalog"."default",
                "survey_kepala_battle_sign" text COLLATE "pg_catalog"."default",
                "survey_kepala_lainnya" text COLLATE "pg_catalog"."default",
                "survey_mata" text COLLATE "pg_catalog"."default",
                "survey_mulut" text COLLATE "pg_catalog"."default",
                "survey_mulut_luka_dalam" text COLLATE "pg_catalog"."default",
                "survey_mulut_lainnya" text COLLATE "pg_catalog"."default",
                "survey_telinga" text COLLATE "pg_catalog"."default",
                "survey_leher" text COLLATE "pg_catalog"."default",
                "survey_leher_lainnya" text COLLATE "pg_catalog"."default",
                "survey_extremitas" text COLLATE "pg_catalog"."default",
                "survey_extremitas_pulsasi" text COLLATE "pg_catalog"."default",
                "survey_dada" text COLLATE "pg_catalog"."default",
                "survey_dada_simetris_asimetris" text COLLATE "pg_catalog"."default",
                "survey_dada_pneumo_hamatotoraks" text COLLATE "pg_catalog"."default",
                "survey_dada_nyeri_lokasi" text COLLATE "pg_catalog"."default",
                "survey_dada_nyeri_kapan" text COLLATE "pg_catalog"."default",
                "survey_dada_nyeri_durasi" text COLLATE "pg_catalog"."default",
                "survey_dada_nyeri_kegiatan" text COLLATE "pg_catalog"."default",
                "survey_dada_bunyi_jantung" text COLLATE "pg_catalog"."default",
                "survey_abdomen" text COLLATE "pg_catalog"."default",
                "survey_abdomen_memas" text COLLATE "pg_catalog"."default",
                "survey_abdomen_nyeri" text COLLATE "pg_catalog"."default",
                "survey_abdomen_lainnya" text COLLATE "pg_catalog"."default",
                "survey_abdomen_bising_usus" text COLLATE "pg_catalog"."default",
                "survey_pelvis" text COLLATE "pg_catalog"."default",
                "survey_pelvis_lainnya" text COLLATE "pg_catalog"."default",
                "survey_medulla_spinalis" text COLLATE "pg_catalog"."default",
                "survey_kolumna_vertebralis" text COLLATE "pg_catalog"."default",
                "perasaan_klien" text COLLATE "pg_catalog"."default",
                "sosial_support" text COLLATE "pg_catalog"."default",
                "hubungan_pasien" text COLLATE "pg_catalog"."default",
                "keluarga_lain" text COLLATE "pg_catalog"."default",
                "keadaan_emosi" text COLLATE "pg_catalog"."default",
                "suku_id" text COLLATE "pg_catalog"."default",
                "bahasa_dipakai" text COLLATE "pg_catalog"."default",
                "bahasa_dipakai_lainnya" text COLLATE "pg_catalog"."default",
                "is_penerjemah" bool,
                "media" text COLLATE "pg_catalog"."default",
                "media_lainnya" text COLLATE "pg_catalog"."default",
                "identifikasi_hambatan" text COLLATE "pg_catalog"."default",
                "is_sistem_rujukan" bool,
                "materi" varchar(100) COLLATE "pg_catalog"."default",
                "edukator" varchar(100) COLLATE "pg_catalog"."default",
                "is_ketersediaan_pasien" bool,
                "is_kemampuan_membaca" bool,
                "bahasa" varchar(100) COLLATE "pg_catalog"."default",
                "is_dibutuhkan_penerjemah" bool,
                "penerjemah_bahasa" varchar(100) COLLATE "pg_catalog"."default",
                "is_hambatan_emotional" bool,
                "hambatan_emotional_lainnya" text COLLATE "pg_catalog"."default",
                "is_keterbatasan_fisik" bool,
                "keterbatasan_fisik" text COLLATE "pg_catalog"."default",
                "bersihan_jalan" text COLLATE "pg_catalog"."default",
                "pola_nafas" text COLLATE "pg_catalog"."default",
                "gangguan_gas" text COLLATE "pg_catalog"."default",
                "nyeri" text COLLATE "pg_catalog"."default",
                "penurunan_jantung" text COLLATE "pg_catalog"."default",
                "gangguan_perfusi_cerebral" text COLLATE "pg_catalog"."default",
                "gangguan_perfusi_perifer" text COLLATE "pg_catalog"."default",
                "valume_cairan_tubuh" text COLLATE "pg_catalog"."default",
                "gangguan_thermoregulasi_tipe" text COLLATE "pg_catalog"."default",
                "gangguan_thermoregulasi_nilai" text COLLATE "pg_catalog"."default",
                "tujuan_pulang" text COLLATE "pg_catalog"."default",
                "tujuan_pulang_lainnya" text COLLATE "pg_catalog"."default",
                "transportasi" text COLLATE "pg_catalog"."default",
                "orang_merawat" text COLLATE "pg_catalog"."default",
                "sarana_kesehatan" text COLLATE "pg_catalog"."default",
                "masuk_ke" text COLLATE "pg_catalog"."default",
                "persen_luka_bakar" text COLLATE "pg_catalog"."default",
                "pernafasan_gargling" text COLLATE "pg_catalog"."default",
                "kategori_triase_sehari" text COLLATE "pg_catalog"."default",
                "kategori_triase_disaster" text COLLATE "pg_catalog"."default",
                "survey_kepala_utuh" text COLLATE "pg_catalog"."default",
                "ireguler_tipe" text COLLATE "pg_catalog"."default",
                "hasil_resiko_jatuh" text COLLATE "pg_catalog"."default",
                "skrining_gizi" text COLLATE "pg_catalog"."default",
                "extremitas_utuh" text COLLATE "pg_catalog"."default",
                "extremitas_nyeri" text COLLATE "pg_catalog"."default",
                "extremitas_deformitas" text COLLATE "pg_catalog"."default",
                "extremitas_defisit_neurologis" text COLLATE "pg_catalog"."default",
                "extremitas_jejas" text COLLATE "pg_catalog"."default",
                "extremitas_pulsasi" text COLLATE "pg_catalog"."default",
                "tipe_nadi" text COLLATE "pg_catalog"."default",
                "hasil_nadi" text COLLATE "pg_catalog"."default",
                "pupil_os" text COLLATE "pg_catalog"."default",
                "pupil_od" text COLLATE "pg_catalog"."default",
                "jenis_resiko_jatuh" text COLLATE "pg_catalog"."default",
                "asesmen_auto_anamnesa" text COLLATE "pg_catalog"."default",
                "nutrisi_1a" text COLLATE "pg_catalog"."default",
                "nutrisi_1b" text COLLATE "pg_catalog"."default",
                "nutrisi_2" text COLLATE "pg_catalog"."default",
                "diagnosa_khusus" text COLLATE "pg_catalog"."default",
                "jenis_diagnosa_khusus" text COLLATE "pg_catalog"."default",
                "strongkids_kurus" text COLLATE "pg_catalog"."default",
                "strongkids_turunbb" text COLLATE "pg_catalog"."default",
                "strongkids_kondisikhusus" text COLLATE "pg_catalog"."default",
                "strongkids_keadaan_beresiko" text COLLATE "pg_catalog"."default",
                "resusitasi" text COLLATE "pg_catalog"."default",
                "extremitas_fraktur" text COLLATE "pg_catalog"."default",
                "pupil_os_text" text COLLATE "pg_catalog"."default",
                "pupil_od_text" text COLLATE "pg_catalog"."default",
                "diagnosa_keperawatan" text COLLATE "pg_catalog"."default",
                "asesmen_allo_text" text COLLATE "pg_catalog"."default",
                "pilih_skala" varchar(20) COLLATE "pg_catalog"."default" DEFAULT NULL::character varying,
                CONSTRAINT "asesmenperawatrd_r_pkey" PRIMARY KEY ("id")
                );
        ');

        $this->execute('
            COMMENT ON COLUMN "public"."asesmenperawatrd_r"."prioritas_triage" IS \'1=merah, 2=kuning, 3=hijau, 4=hitam\';
        ');

        $this->execute('
            COMMENT ON COLUMN "public"."asesmenperawatrd_r"."pasien_datang" IS \'lookup_m.lookup_type=\'\'pengantar\'\'\';
        ');

        $this->execute('
            COMMENT ON COLUMN "public"."asesmenperawatrd_r"."jenis_asmenperawat" IS \'lookupkeperawatan_m.lookup_type=\'\'jenis_asmen_perawat\'\'\';
        ');

        $this->execute('
            COMMENT ON COLUMN "public"."asesmenperawatrd_r"."keadaan_umum" IS \'lookupkeperawatan_m.lookup_type=\'\'keadaan_umum\'\'\';
        ');

        $this->execute('
            COMMENT ON COLUMN "public"."asesmenperawatrd_r"."is_resikojatuh" IS \'update pendaftaran_t.label_gelang -->"alergi":"#8B0000"\';
        ');

        $this->execute('
            CREATE OR REPLACE FUNCTION "public"."asesmenperawatrd_insert_r"()
                RETURNS "pg_catalog"."trigger" AS $BODY$

            DECLARE
            BEGIN
                IF(NEW.is_deleted = false)
                THEN
                    INSERT INTO asesmenperawatrd_r (       
                        asesmenperawatrd_id,
                        pendaftaran_id,
                        ruangan_id,
                        tgl_asesmen,
                        perawat_id,
                        tgl_pendaftaran,
                        tgl_datang,
                        prioritas_triage,
                        is_trauma,
                        pasien_datang,
                        jenis_asmenperawat,
                        alasan_kunjungan,
                        is_alergi,
                        is_alergiobat,
                        alergi_obat,
                        is_alergilainnya,
                        alergi_lainnya,
                        keadaan_umum,
                        is_nyeri,
                        lokasi_nyeri,
                        skala_nyeri,
                        metode_nyeri,
                        is_resikojatuh,
                        keluhan,
                        lama_sakit,
                        r_penyakitdahulu,
                        r_penyakitkeluarga,
                        catatan_asesmen,
                        gcseye_id,
                        gcsverbal_id,
                        gcsmotorik_id,
                        hasil_gcs,
                        is_kapitis,
                        td_systolic,
                        td_diastolic,
                        tekanan_darah,
                        hasil_td,
                        detak_nadi,
                        pernapasan,
                        suhu_tubuh,
                        tinggi_badan,
                        berat_badan,
                        bb_ideal,
                        imt,
                        ket_imt,
                        spo2,
                        kelaianan_tubuh,
                        detail_asesmen,
                        additional_data,
                        created_date,
                        created_by,
                        modified_count,
                        last_modified_date,
                        last_modified_by,
                        is_deleted,
                        is_active,
                        deleted_date,
                        deleted_by,
                        formulir_triage,
                        formulir_fisik,
                        tgl_keluar,
                        agama_id,
                        pekerjaan_id,
                        caramasuk_id,
                        pendidikan_id,
                        jalur_nafas,
                        jalur_nafas_oksigen,
                        pernafasan,
                        pernafasan_spontan,
                        pernafasan_takipnea,
                        tensi,
                        reguler,
                        ireguler,
                        capilary_refill,
                        perfusi,
                        akral,
                        pendarahan,
                        pendarahan_cc,
                        is_bradikarida,
                        is_takikardia,
                        pupil,
                        reaksi_pupil,
                        reaksi_pupil_lainnya,
                        kepala,
                        abdomen,
                        maksilofacial,
                        parineum,
                        tulan_leher,
                        muskuloskeletal,
                        paru_paru,
                        extremitas,
                        skala_wong_baker,
                        asesmen_auto,
                        asesmen_allo,
                        r_penyakitsaatini,
                        r_pengobatan,
                        jalan_nafas_bersin,
                        nilai_decubitus,
                        nilai_luka_bakar,
                        survey_kepala,
                        survey_kepala_lacerasi,
                        survey_kepala_battle_sign,
                        survey_kepala_lainnya,
                        survey_mata,
                        survey_mulut,
                        survey_mulut_luka_dalam,
                        survey_mulut_lainnya,
                        survey_telinga,
                        survey_leher,
                        survey_leher_lainnya,
                        survey_extremitas,
                        survey_extremitas_pulsasi,
                        survey_dada,
                        survey_dada_simetris_asimetris,
                        survey_dada_pneumo_hamatotoraks,
                        survey_dada_nyeri_lokasi,
                        survey_dada_nyeri_kapan,
                        survey_dada_nyeri_durasi,
                        survey_dada_nyeri_kegiatan,
                        survey_dada_bunyi_jantung,
                        survey_abdomen,
                        survey_abdomen_memas,
                        survey_abdomen_nyeri,
                        survey_abdomen_lainnya,
                        survey_abdomen_bising_usus,
                        survey_pelvis,
                        survey_pelvis_lainnya,
                        survey_medulla_spinalis,
                        survey_kolumna_vertebralis,
                        perasaan_klien,
                        sosial_support,
                        hubungan_pasien,
                        keluarga_lain,
                        keadaan_emosi,
                        suku_id,
                        bahasa_dipakai,
                        bahasa_dipakai_lainnya,
                        is_penerjemah,
                        media,
                        media_lainnya,
                        identifikasi_hambatan,
                        is_sistem_rujukan,
                        materi,
                        edukator,
                        is_ketersediaan_pasien,
                        is_kemampuan_membaca,
                        bahasa,
                        is_dibutuhkan_penerjemah,
                        penerjemah_bahasa,
                        is_hambatan_emotional,
                        hambatan_emotional_lainnya,
                        is_keterbatasan_fisik,
                        keterbatasan_fisik,
                        bersihan_jalan,
                        pola_nafas,
                        gangguan_gas,
                        nyeri,
                        penurunan_jantung,
                        gangguan_perfusi_cerebral,
                        gangguan_perfusi_perifer,
                        valume_cairan_tubuh,
                        gangguan_thermoregulasi_tipe,
                        gangguan_thermoregulasi_nilai,
                        tujuan_pulang,
                        tujuan_pulang_lainnya,
                        transportasi,
                        orang_merawat,
                        sarana_kesehatan,
                        masuk_ke,
                        persen_luka_bakar,
                        pernafasan_gargling,
                        kategori_triase_sehari,
                        kategori_triase_disaster,
                        survey_kepala_utuh,
                        ireguler_tipe,
                        hasil_resiko_jatuh,
                        skrining_gizi,
                        extremitas_utuh,
                        extremitas_nyeri,
                        extremitas_deformitas,
                        extremitas_defisit_neurologis,
                        extremitas_jejas,
                        extremitas_pulsasi,
                        tipe_nadi,
                        hasil_nadi,
                        pupil_os,
                        pupil_od,
                        jenis_resiko_jatuh,
                        asesmen_auto_anamnesa,
                        nutrisi_1a,
                        nutrisi_1b,
                        nutrisi_2,
                        diagnosa_khusus,
                        jenis_diagnosa_khusus,
                        strongkids_kurus,
                        strongkids_turunbb,
                        strongkids_kondisikhusus,
                        strongkids_keadaan_beresiko,
                        resusitasi,
                        extremitas_fraktur,
                        pupil_os_text,
                        pupil_od_text,
                        diagnosa_keperawatan,
                        asesmen_allo_text,
                        pilih_skala
                    )
                    VALUES(
                        NEW.asesmenperawatrd_id,
                        NEW.pendaftaran_id,
                        NEW.ruangan_id,
                        NEW.tgl_asesmen,
                        NEW.perawat_id,
                        NEW.tgl_pendaftaran,
                        NEW.tgl_datang,
                        NEW.prioritas_triage,
                        NEW.is_trauma,
                        NEW.pasien_datang,
                        NEW.jenis_asmenperawat,
                        NEW.alasan_kunjungan,
                        NEW.is_alergi,
                        NEW.is_alergiobat,
                        NEW.alergi_obat,
                        NEW.is_alergilainnya,
                        NEW.alergi_lainnya,
                        NEW.keadaan_umum,
                        NEW.is_nyeri,
                        NEW.lokasi_nyeri,
                        NEW.skala_nyeri,
                        NEW.metode_nyeri,
                        NEW.is_resikojatuh,
                        NEW.keluhan,
                        NEW.lama_sakit,
                        NEW.r_penyakitdahulu,
                        NEW.r_penyakitkeluarga,
                        NEW.catatan_asesmen,
                        NEW.gcseye_id,
                        NEW.gcsverbal_id,
                        NEW.gcsmotorik_id,
                        NEW.hasil_gcs,
                        NEW.is_kapitis,
                        NEW.td_systolic,
                        NEW.td_diastolic,
                        NEW.tekanan_darah,
                        NEW.hasil_td,
                        NEW.detak_nadi,
                        NEW.pernapasan,
                        NEW.suhu_tubuh,
                        NEW.tinggi_badan,
                        NEW.berat_badan,
                        NEW.bb_ideal,
                        NEW.imt,
                        NEW.ket_imt,
                        NEW.spo2,
                        NEW.kelaianan_tubuh,
                        NEW.detail_asesmen,
                        NEW.additional_data,
                        NEW.created_date,
                        NEW.created_by,
                        NEW.modified_count,
                        NEW.last_modified_date,
                        NEW.last_modified_by,
                        NEW.is_deleted,
                        NEW.is_active,
                        NEW.deleted_date,
                        NEW.deleted_by,
                        NEW.formulir_triage,
                        NEW.formulir_fisik,
                        NEW.tgl_keluar,
                        NEW.agama_id,
                        NEW.pekerjaan_id,
                        NEW.caramasuk_id,
                        NEW.pendidikan_id,
                        NEW.jalur_nafas,
                        NEW.jalur_nafas_oksigen,
                        NEW.pernafasan,
                        NEW.pernafasan_spontan,
                        NEW.pernafasan_takipnea,
                        NEW.tensi,
                        NEW.reguler,
                        NEW.ireguler,
                        NEW.capilary_refill,
                        NEW.perfusi,
                        NEW.akral,
                        NEW.pendarahan,
                        NEW.pendarahan_cc,
                        NEW.is_bradikarida,
                        NEW.is_takikardia,
                        NEW.pupil,
                        NEW.reaksi_pupil,
                        NEW.reaksi_pupil_lainnya,
                        NEW.kepala,
                        NEW.abdomen,
                        NEW.maksilofacial,
                        NEW.parineum,
                        NEW.tulan_leher,
                        NEW.muskuloskeletal,
                        NEW.paru_paru,
                        NEW.extremitas,
                        NEW.skala_wong_baker,
                        NEW.asesmen_auto,
                        NEW.asesmen_allo,
                        NEW.r_penyakitsaatini,
                        NEW.r_pengobatan,
                        NEW.jalan_nafas_bersin,
                        NEW.nilai_decubitus,
                        NEW.nilai_luka_bakar,
                        NEW.survey_kepala,
                        NEW.survey_kepala_lacerasi,
                        NEW.survey_kepala_battle_sign,
                        NEW.survey_kepala_lainnya,
                        NEW.survey_mata,
                        NEW.survey_mulut,
                        NEW.survey_mulut_luka_dalam,
                        NEW.survey_mulut_lainnya,
                        NEW.survey_telinga,
                        NEW.survey_leher,
                        NEW.survey_leher_lainnya,
                        NEW.survey_extremitas,
                        NEW.survey_extremitas_pulsasi,
                        NEW.survey_dada,
                        NEW.survey_dada_simetris_asimetris,
                        NEW.survey_dada_pneumo_hamatotoraks,
                        NEW.survey_dada_nyeri_lokasi,
                        NEW.survey_dada_nyeri_kapan,
                        NEW.survey_dada_nyeri_durasi,
                        NEW.survey_dada_nyeri_kegiatan,
                        NEW.survey_dada_bunyi_jantung,
                        NEW.survey_abdomen,
                        NEW.survey_abdomen_memas,
                        NEW.survey_abdomen_nyeri,
                        NEW.survey_abdomen_lainnya,
                        NEW.survey_abdomen_bising_usus,
                        NEW.survey_pelvis,
                        NEW.survey_pelvis_lainnya,
                        NEW.survey_medulla_spinalis,
                        NEW.survey_kolumna_vertebralis,
                        NEW.perasaan_klien,
                        NEW.sosial_support,
                        NEW.hubungan_pasien,
                        NEW.keluarga_lain,
                        NEW.keadaan_emosi,
                        NEW.suku_id,
                        NEW.bahasa_dipakai,
                        NEW.bahasa_dipakai_lainnya,
                        NEW.is_penerjemah,
                        NEW.media,
                        NEW.media_lainnya,
                        NEW.identifikasi_hambatan,
                        NEW.is_sistem_rujukan,
                        NEW.materi,
                        NEW.edukator,
                        NEW.is_ketersediaan_pasien,
                        NEW.is_kemampuan_membaca,
                        NEW.bahasa,
                        NEW.is_dibutuhkan_penerjemah,
                        NEW.penerjemah_bahasa,
                        NEW.is_hambatan_emotional,
                        NEW.hambatan_emotional_lainnya,
                        NEW.is_keterbatasan_fisik,
                        NEW.keterbatasan_fisik,
                        NEW.bersihan_jalan,
                        NEW.pola_nafas,
                        NEW.gangguan_gas,
                        NEW.nyeri,
                        NEW.penurunan_jantung,
                        NEW.gangguan_perfusi_cerebral,
                        NEW.gangguan_perfusi_perifer,
                        NEW.valume_cairan_tubuh,
                        NEW.gangguan_thermoregulasi_tipe,
                        NEW.gangguan_thermoregulasi_nilai,
                        NEW.tujuan_pulang,
                        NEW.tujuan_pulang_lainnya,
                        NEW.transportasi,
                        NEW.orang_merawat,
                        NEW.sarana_kesehatan,
                        NEW.masuk_ke,
                        NEW.persen_luka_bakar,
                        NEW.pernafasan_gargling,
                        NEW.kategori_triase_sehari,
                        NEW.kategori_triase_disaster,
                        NEW.survey_kepala_utuh,
                        NEW.ireguler_tipe,
                        NEW.hasil_resiko_jatuh,
                        NEW.skrining_gizi,
                        NEW.extremitas_utuh,
                        NEW.extremitas_nyeri,
                        NEW.extremitas_deformitas,
                        NEW.extremitas_defisit_neurologis,
                        NEW.extremitas_jejas,
                        NEW.extremitas_pulsasi,
                        NEW.tipe_nadi,
                        NEW.hasil_nadi,
                        NEW.pupil_os,
                        NEW.pupil_od,
                        NEW.jenis_resiko_jatuh,
                        NEW.asesmen_auto_anamnesa,
                        NEW.nutrisi_1a,
                        NEW.nutrisi_1b,
                        NEW.nutrisi_2,
                        NEW.diagnosa_khusus,
                        NEW.jenis_diagnosa_khusus,
                        NEW.strongkids_kurus,
                        NEW.strongkids_turunbb,
                        NEW.strongkids_kondisikhusus,
                        NEW.strongkids_keadaan_beresiko,
                        NEW.resusitasi,
                        NEW.extremitas_fraktur,
                        NEW.pupil_os_text,
                        NEW.pupil_od_text,
                        NEW.diagnosa_keperawatan,
                        NEW.asesmen_allo_text,
                        NEW.pilih_skala
                    );
                END IF;
                
                RETURN NEW;
            END
            $BODY$
              LANGUAGE plpgsql VOLATILE
              COST 100;
        ');

        $this->execute('
            CREATE OR REPLACE FUNCTION "public"."asesmenperawatrd_r"()
              RETURNS "pg_catalog"."trigger" AS $BODY$

            DECLARE
            BEGIN
                IF(OLD.is_deleted = false)
                THEN
                    INSERT INTO asesmenperawatrd_r (       
                        asesmenperawatrd_id,
                        pendaftaran_id,
                        ruangan_id,
                        tgl_asesmen,
                        perawat_id,
                        tgl_pendaftaran,
                        tgl_datang,
                        prioritas_triage,
                        is_trauma,
                        pasien_datang,
                        jenis_asmenperawat,
                        alasan_kunjungan,
                        is_alergi,
                        is_alergiobat,
                        alergi_obat,
                        is_alergilainnya,
                        alergi_lainnya,
                        keadaan_umum,
                        is_nyeri,
                        lokasi_nyeri,
                        skala_nyeri,
                        metode_nyeri,
                        is_resikojatuh,
                        keluhan,
                        lama_sakit,
                        r_penyakitdahulu,
                        r_penyakitkeluarga,
                        catatan_asesmen,
                        gcseye_id,
                        gcsverbal_id,
                        gcsmotorik_id,
                        hasil_gcs,
                        is_kapitis,
                        td_systolic,
                        td_diastolic,
                        tekanan_darah,
                        hasil_td,
                        detak_nadi,
                        pernapasan,
                        suhu_tubuh,
                        tinggi_badan,
                        berat_badan,
                        bb_ideal,
                        imt,
                        ket_imt,
                        spo2,
                        kelaianan_tubuh,
                        detail_asesmen,
                        additional_data,
                        created_date,
                        created_by,
                        modified_count,
                        last_modified_date,
                        last_modified_by,
                        is_deleted,
                        is_active,
                        deleted_date,
                        deleted_by,
                        formulir_triage,
                        formulir_fisik,
                        tgl_keluar,
                        agama_id,
                        pekerjaan_id,
                        caramasuk_id,
                        pendidikan_id,
                        jalur_nafas,
                        jalur_nafas_oksigen,
                        pernafasan,
                        pernafasan_spontan,
                        pernafasan_takipnea,
                        tensi,
                        reguler,
                        ireguler,
                        capilary_refill,
                        perfusi,
                        akral,
                        pendarahan,
                        pendarahan_cc,
                        is_bradikarida,
                        is_takikardia,
                        pupil,
                        reaksi_pupil,
                        reaksi_pupil_lainnya,
                        kepala,
                        abdomen,
                        maksilofacial,
                        parineum,
                        tulan_leher,
                        muskuloskeletal,
                        paru_paru,
                        extremitas,
                        skala_wong_baker,
                        asesmen_auto,
                        asesmen_allo,
                        r_penyakitsaatini,
                        r_pengobatan,
                        jalan_nafas_bersin,
                        nilai_decubitus,
                        nilai_luka_bakar,
                        survey_kepala,
                        survey_kepala_lacerasi,
                        survey_kepala_battle_sign,
                        survey_kepala_lainnya,
                        survey_mata,
                        survey_mulut,
                        survey_mulut_luka_dalam,
                        survey_mulut_lainnya,
                        survey_telinga,
                        survey_leher,
                        survey_leher_lainnya,
                        survey_extremitas,
                        survey_extremitas_pulsasi,
                        survey_dada,
                        survey_dada_simetris_asimetris,
                        survey_dada_pneumo_hamatotoraks,
                        survey_dada_nyeri_lokasi,
                        survey_dada_nyeri_kapan,
                        survey_dada_nyeri_durasi,
                        survey_dada_nyeri_kegiatan,
                        survey_dada_bunyi_jantung,
                        survey_abdomen,
                        survey_abdomen_memas,
                        survey_abdomen_nyeri,
                        survey_abdomen_lainnya,
                        survey_abdomen_bising_usus,
                        survey_pelvis,
                        survey_pelvis_lainnya,
                        survey_medulla_spinalis,
                        survey_kolumna_vertebralis,
                        perasaan_klien,
                        sosial_support,
                        hubungan_pasien,
                        keluarga_lain,
                        keadaan_emosi,
                        suku_id,
                        bahasa_dipakai,
                        bahasa_dipakai_lainnya,
                        is_penerjemah,
                        media,
                        media_lainnya,
                        identifikasi_hambatan,
                        is_sistem_rujukan,
                        materi,
                        edukator,
                        is_ketersediaan_pasien,
                        is_kemampuan_membaca,
                        bahasa,
                        is_dibutuhkan_penerjemah,
                        penerjemah_bahasa,
                        is_hambatan_emotional,
                        hambatan_emotional_lainnya,
                        is_keterbatasan_fisik,
                        keterbatasan_fisik,
                        bersihan_jalan,
                        pola_nafas,
                        gangguan_gas,
                        nyeri,
                        penurunan_jantung,
                        gangguan_perfusi_cerebral,
                        gangguan_perfusi_perifer,
                        valume_cairan_tubuh,
                        gangguan_thermoregulasi_tipe,
                        gangguan_thermoregulasi_nilai,
                        tujuan_pulang,
                        tujuan_pulang_lainnya,
                        transportasi,
                        orang_merawat,
                        sarana_kesehatan,
                        masuk_ke,
                        persen_luka_bakar,
                        pernafasan_gargling,
                        kategori_triase_sehari,
                        kategori_triase_disaster,
                        survey_kepala_utuh,
                        ireguler_tipe,
                        hasil_resiko_jatuh,
                        skrining_gizi,
                        extremitas_utuh,
                        extremitas_nyeri,
                        extremitas_deformitas,
                        extremitas_defisit_neurologis,
                        extremitas_jejas,
                        extremitas_pulsasi,
                        tipe_nadi,
                        hasil_nadi,
                        pupil_os,
                        pupil_od,
                        jenis_resiko_jatuh,
                        asesmen_auto_anamnesa,
                        nutrisi_1a,
                        nutrisi_1b,
                        nutrisi_2,
                        diagnosa_khusus,
                        jenis_diagnosa_khusus,
                        strongkids_kurus,
                        strongkids_turunbb,
                        strongkids_kondisikhusus,
                        strongkids_keadaan_beresiko,
                        resusitasi,
                        extremitas_fraktur,
                        pupil_os_text,
                        pupil_od_text,
                        diagnosa_keperawatan,
                        asesmen_allo_text,
                        pilih_skala
                    )VALUES(
                        OLD.asesmenperawatrd_id,
                        OLD.pendaftaran_id,
                        OLD.ruangan_id,
                        OLD.tgl_asesmen,
                        OLD.perawat_id,
                        OLD.tgl_pendaftaran,
                        OLD.tgl_datang,
                        OLD.prioritas_triage,
                        OLD.is_trauma,
                        OLD.pasien_datang,
                        OLD.jenis_asmenperawat,
                        OLD.alasan_kunjungan,
                        OLD.is_alergi,
                        OLD.is_alergiobat,
                        OLD.alergi_obat,
                        OLD.is_alergilainnya,
                        OLD.alergi_lainnya,
                        OLD.keadaan_umum,
                        OLD.is_nyeri,
                        OLD.lokasi_nyeri,
                        OLD.skala_nyeri,
                        OLD.metode_nyeri,
                        OLD.is_resikojatuh,
                        OLD.keluhan,
                        OLD.lama_sakit,
                        OLD.r_penyakitdahulu,
                        OLD.r_penyakitkeluarga,
                        OLD.catatan_asesmen,
                        OLD.gcseye_id,
                        OLD.gcsverbal_id,
                        OLD.gcsmotorik_id,
                        OLD.hasil_gcs,
                        OLD.is_kapitis,
                        OLD.td_systolic,
                        OLD.td_diastolic,
                        OLD.tekanan_darah,
                        OLD.hasil_td,
                        OLD.detak_nadi,
                        OLD.pernapasan,
                        OLD.suhu_tubuh,
                        OLD.tinggi_badan,
                        OLD.berat_badan,
                        OLD.bb_ideal,
                        OLD.imt,
                        OLD.ket_imt,
                        OLD.spo2,
                        OLD.kelaianan_tubuh,
                        OLD.detail_asesmen,
                        OLD.additional_data,
                        OLD.created_date,
                        OLD.created_by,
                        OLD.modified_count,
                        OLD.last_modified_date,
                        OLD.last_modified_by,
                        OLD.is_deleted,
                        OLD.is_active,
                        OLD.deleted_date,
                        OLD.deleted_by,
                        OLD.formulir_triage,
                        OLD.formulir_fisik,
                        OLD.tgl_keluar,
                        OLD.agama_id,
                        OLD.pekerjaan_id,
                        OLD.caramasuk_id,
                        OLD.pendidikan_id,
                        OLD.jalur_nafas,
                        OLD.jalur_nafas_oksigen,
                        OLD.pernafasan,
                        OLD.pernafasan_spontan,
                        OLD.pernafasan_takipnea,
                        OLD.tensi,
                        OLD.reguler,
                        OLD.ireguler,
                        OLD.capilary_refill,
                        OLD.perfusi,
                        OLD.akral,
                        OLD.pendarahan,
                        OLD.pendarahan_cc,
                        OLD.is_bradikarida,
                        OLD.is_takikardia,
                        OLD.pupil,
                        OLD.reaksi_pupil,
                        OLD.reaksi_pupil_lainnya,
                        OLD.kepala,
                        OLD.abdomen,
                        OLD.maksilofacial,
                        OLD.parineum,
                        OLD.tulan_leher,
                        OLD.muskuloskeletal,
                        OLD.paru_paru,
                        OLD.extremitas,
                        OLD.skala_wong_baker,
                        OLD.asesmen_auto,
                        OLD.asesmen_allo,
                        OLD.r_penyakitsaatini,
                        OLD.r_pengobatan,
                        OLD.jalan_nafas_bersin,
                        OLD.nilai_decubitus,
                        OLD.nilai_luka_bakar,
                        OLD.survey_kepala,
                        OLD.survey_kepala_lacerasi,
                        OLD.survey_kepala_battle_sign,
                        OLD.survey_kepala_lainnya,
                        OLD.survey_mata,
                        OLD.survey_mulut,
                        OLD.survey_mulut_luka_dalam,
                        OLD.survey_mulut_lainnya,
                        OLD.survey_telinga,
                        OLD.survey_leher,
                        OLD.survey_leher_lainnya,
                        OLD.survey_extremitas,
                        OLD.survey_extremitas_pulsasi,
                        OLD.survey_dada,
                        OLD.survey_dada_simetris_asimetris,
                        OLD.survey_dada_pneumo_hamatotoraks,
                        OLD.survey_dada_nyeri_lokasi,
                        OLD.survey_dada_nyeri_kapan,
                        OLD.survey_dada_nyeri_durasi,
                        OLD.survey_dada_nyeri_kegiatan,
                        OLD.survey_dada_bunyi_jantung,
                        OLD.survey_abdomen,
                        OLD.survey_abdomen_memas,
                        OLD.survey_abdomen_nyeri,
                        OLD.survey_abdomen_lainnya,
                        OLD.survey_abdomen_bising_usus,
                        OLD.survey_pelvis,
                        OLD.survey_pelvis_lainnya,
                        OLD.survey_medulla_spinalis,
                        OLD.survey_kolumna_vertebralis,
                        OLD.perasaan_klien,
                        OLD.sosial_support,
                        OLD.hubungan_pasien,
                        OLD.keluarga_lain,
                        OLD.keadaan_emosi,
                        OLD.suku_id,
                        OLD.bahasa_dipakai,
                        OLD.bahasa_dipakai_lainnya,
                        OLD.is_penerjemah,
                        OLD.media,
                        OLD.media_lainnya,
                        OLD.identifikasi_hambatan,
                        OLD.is_sistem_rujukan,
                        OLD.materi,
                        OLD.edukator,
                        OLD.is_ketersediaan_pasien,
                        OLD.is_kemampuan_membaca,
                        OLD.bahasa,
                        OLD.is_dibutuhkan_penerjemah,
                        OLD.penerjemah_bahasa,
                        OLD.is_hambatan_emotional,
                        OLD.hambatan_emotional_lainnya,
                        OLD.is_keterbatasan_fisik,
                        OLD.keterbatasan_fisik,
                        OLD.bersihan_jalan,
                        OLD.pola_nafas,
                        OLD.gangguan_gas,
                        OLD.nyeri,
                        OLD.penurunan_jantung,
                        OLD.gangguan_perfusi_cerebral,
                        OLD.gangguan_perfusi_perifer,
                        OLD.valume_cairan_tubuh,
                        OLD.gangguan_thermoregulasi_tipe,
                        OLD.gangguan_thermoregulasi_nilai,
                        OLD.tujuan_pulang,
                        OLD.tujuan_pulang_lainnya,
                        OLD.transportasi,
                        OLD.orang_merawat,
                        OLD.sarana_kesehatan,
                        OLD.masuk_ke,
                        OLD.persen_luka_bakar,
                        OLD.pernafasan_gargling,
                        OLD.kategori_triase_sehari,
                        OLD.kategori_triase_disaster,
                        OLD.survey_kepala_utuh,
                        OLD.ireguler_tipe,
                        OLD.hasil_resiko_jatuh,
                        OLD.skrining_gizi,
                        OLD.extremitas_utuh,
                        OLD.extremitas_nyeri,
                        OLD.extremitas_deformitas,
                        OLD.extremitas_defisit_neurologis,
                        OLD.extremitas_jejas,
                        OLD.extremitas_pulsasi,
                        OLD.tipe_nadi,
                        OLD.hasil_nadi,
                        OLD.pupil_os,
                        OLD.pupil_od,
                        OLD.jenis_resiko_jatuh,
                        OLD.asesmen_auto_anamnesa,
                        OLD.nutrisi_1a,
                        OLD.nutrisi_1b,
                        OLD.nutrisi_2,
                        OLD.diagnosa_khusus,
                        OLD.jenis_diagnosa_khusus,
                        OLD.strongkids_kurus,
                        OLD.strongkids_turunbb,
                        OLD.strongkids_kondisikhusus,
                        OLD.strongkids_keadaan_beresiko,
                        OLD.resusitasi,
                        OLD.extremitas_fraktur,
                        OLD.pupil_os_text,
                        OLD.pupil_od_text,
                        OLD.diagnosa_keperawatan,
                        OLD.asesmen_allo_text,
                        OLD.pilih_skala
                    );
                END IF;
                RETURN NEW;            
            END
            $BODY$
              LANGUAGE plpgsql VOLATILE
              COST 100;
        ');

        $this->execute('
            DROP TRIGGER IF EXISTS "asesmenperawatrd_insert_r" ON "public"."asesmenperawatrd_t";
        ');

        $this->execute('
            CREATE TRIGGER "asesmenperawatrd_insert_r" AFTER INSERT ON "public"."asesmenperawatrd_t"
            FOR EACH ROW
            EXECUTE PROCEDURE "public"."asesmenperawatrd_insert_r"();
        ');

        $this->execute('
            DROP TRIGGER IF EXISTS "asesmenperawatrd_r" ON "public"."asesmenperawatrd_t";
        ');

        $this->execute('
            CREATE TRIGGER "asesmenperawatrd_r" BEFORE UPDATE ON "public"."asesmenperawatrd_t"
            FOR EACH ROW
            EXECUTE PROCEDURE "public"."asesmenperawatrd_r"();
        ');
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m210908_041229_improvment_history_asesmen_rd_US1280 cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m210908_041229_improvment_history_asesmen_rd_US1280 cannot be reverted.\n";

        return false;
    }
    */
}
