<?php

use yii\db\Migration;

/**
 * Class m210321_074305_oddo_20200319_functionrekap
 */
class m210321_074305_oddo_20200319_functionrekap extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->execute("
            CREATE OR REPLACE FUNCTION \"public\".\"obatalkespasien_r_insert\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$
DECLARE

    
BEGIN
    NEW.hargajual_oa = NEW.hargasatuan_oa * NEW.qty_oa;
        
        -- INSERT table history obatalkespasien_r
        INSERT INTO obatalkespasien_r (     
        obatalkespasien_id ,
        sumberdana_id ,
        racikan_id ,
        returresepdetail_id ,
        tipepaket_id ,
        ruangan_id ,
        carabayar_id ,
        pegawai_id ,
        daftartindakan_id ,
        tindakanpelayanan_id ,
        satuankecil_id ,
        shift_id ,
        pendaftaran_id ,
        obatalkes_id ,
        pasien_id ,
        penjamin_id ,
        kelaspelayanan_id ,
        pasienanastesi_id ,
        pasienmasukpenunjang_id ,
        pasienadmisi_id ,
        obatsudahbayar_id ,
        penjualanresep_id ,
        tglpelayanan ,
        r ,
        rke ,
        permintaan_oa ,
        jmlkemasan_oa ,
        kekuatan_oa ,
        satuankekuatan_oa ,
        qty_oa ,
        hargasatuan_oa ,
        signa_oa ,
        harganetto_oa ,
        hargajual_oa , 
        etiket ,
        jmlexposerad ,
        kontrasrad ,
        biayaservice ,
        biayakonseling ,
        jasadokterresep ,
        biayakemasan ,
        biayaadministrasi ,
        tarifcyto ,
        discount , 
        subsidiasuransi ,
        subsidipemerintah ,
        subsidirs ,
        iurbiaya ,
        oa ,
        pembulatan ,
        verifikasitagihan_id ,
        jurnalrekening_id ,
        permohonanoadetail_id ,
        persenppnjual ,
        resepturdetail_id ,
        nilaippnjual ,
        perawat1_id ,
        perawat2_id ,
        instruksitindakanbmhp_id ,
        implementasi_id ,
        is_dilakukan ,
        pemakaianambulan_id ,
        is_jurnal ,
        konfigmargindetail_id ,
        qty_konversi ,
        is_penatajasa ,
        det ,
        status_bmhp ,
        det_konversi ,
        signa ,
        additional_data ,
        created_date ,
        created_by ,
        modified_count ,
        last_modified_date ,
        last_modified_by ,
        is_deleted ,
        is_active ,
        deleted_date , 
        deleted_by ,
        keterangan,
        no_obatalkespasien,
                tarif_dijamin,
                tarif_dibayarkan
        )VALUES(
        NEW.obatalkespasien_id ,
        NEW.sumberdana_id ,
        NEW.racikan_id ,
        NEW.returresepdetail_id ,
        NEW.tipepaket_id ,
        NEW.ruangan_id ,
        NEW.carabayar_id ,
        NEW.pegawai_id ,
        NEW.daftartindakan_id ,
        NEW.tindakanpelayanan_id ,
        NEW.satuankecil_id ,
        NEW.shift_id ,
        NEW.pendaftaran_id ,
        NEW.obatalkes_id ,
        NEW.pasien_id ,
        NEW.penjamin_id ,
        NEW.kelaspelayanan_id ,
        NEW.pasienanastesi_id ,
        NEW.pasienmasukpenunjang_id ,
        NEW.pasienadmisi_id ,
        NEW.obatsudahbayar_id ,
        NEW.penjualanresep_id ,
        NEW.tglpelayanan ,
        NEW.r ,
        NEW.rke ,
        NEW.permintaan_oa ,
        NEW.jmlkemasan_oa ,
        NEW.kekuatan_oa ,
        NEW.satuankekuatan_oa ,
        NEW.qty_oa ,
        NEW.hargasatuan_oa ,
        NEW.signa_oa ,
        NEW.harganetto_oa ,
                CASE
                    WHEN NEW.det <> 0  THEN NEW.hargasatuan_oa * NEW.det
                    WHEN NEW.det = 0 OR NEW.det IS NULL THEN  NEW.hargasatuan_oa * NEW.qty_oa 
                END,    
        NEW.etiket ,
        NEW.jmlexposerad ,
        NEW.kontrasrad ,
        NEW.biayaservice ,
        NEW.biayakonseling ,
        NEW.jasadokterresep ,
        NEW.biayakemasan ,
        NEW.biayaadministrasi ,
        NEW.tarifcyto ,
        NEW.discount , 
        NEW.subsidiasuransi ,
        NEW.subsidipemerintah ,
        NEW.subsidirs ,
        NEW.iurbiaya ,
        NEW.oa ,
        NEW.pembulatan ,
        NEW.verifikasitagihan_id ,
        NEW.jurnalrekening_id ,
        NEW.permohonanoadetail_id ,
        NEW.persenppnjual ,
        NEW.resepturdetail_id ,
        NEW.nilaippnjual ,
        NEW.perawat1_id ,
        NEW.perawat2_id ,
        NEW.instruksitindakanbmhp_id ,
        NEW.implementasi_id ,
        NEW.is_dilakukan ,
        NEW.pemakaianambulan_id ,
        NEW.is_jurnal ,
        NEW.konfigmargindetail_id ,
        NEW.qty_konversi ,
        NEW.is_penatajasa ,
        NEW.det ,
        NEW.status_bmhp ,
        NEW.det_konversi ,
        NEW.signa ,
        NEW.additional_data ,
        NEW.created_date ,
        NEW.created_by ,
        NEW.modified_count ,
        NEW.last_modified_date ,
        NEW.last_modified_by ,
        NEW.is_deleted ,
        NEW.is_active ,
        NEW.deleted_date , 
        NEW.deleted_by ,
        'ACCRUAL',
        NEW.no_obatalkespasien,
                NEW.tarif_dijamin,
                NEW.tarif_dibayarkan
        );

    RETURN NEW;
END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

        $this->execute('ALTER FUNCTION "public"."obatalkespasien_r_insert"() OWNER TO "postgres";');

        $this->execute("
            CREATE OR REPLACE FUNCTION \"public\".\"obatalkespasien_r_update\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$ 
    
DECLARE
        v_keterangan VARCHAR;
BEGIN
        IF((NEW.is_deleted IS TRUE OR NEW.obatsudahbayar_id IS NOT NULL) AND OLD.is_deleted IS FALSE)
        THEN
                v_keterangan := 'ACCRUAL REVERSAL';
                --> INSERT table history obatalkespasien_r menjadi ACCRUAL REVERSAL(-)
                INSERT INTO obatalkespasien_r (     
                obatalkespasien_id ,
                sumberdana_id ,
                racikan_id ,
                returresepdetail_id ,
                tipepaket_id ,
                ruangan_id ,
                carabayar_id ,
                pegawai_id ,
                daftartindakan_id ,
                tindakanpelayanan_id ,
                satuankecil_id ,
                shift_id ,
                pendaftaran_id ,
                obatalkes_id ,
                pasien_id ,
                penjamin_id ,
                kelaspelayanan_id ,
                pasienanastesi_id ,
                pasienmasukpenunjang_id ,
                pasienadmisi_id ,
                obatsudahbayar_id ,
                penjualanresep_id ,
                tglpelayanan ,
                r ,
                rke ,
                permintaan_oa ,
                jmlkemasan_oa ,
                kekuatan_oa ,
                satuankekuatan_oa ,
                qty_oa ,
                hargasatuan_oa ,
                signa_oa ,
                harganetto_oa ,
                hargajual_oa , 
                etiket ,
                jmlexposerad ,
                kontrasrad ,
                biayaservice ,
                biayakonseling ,
                jasadokterresep ,
                biayakemasan ,
                biayaadministrasi ,
                tarifcyto ,
                discount , 
                subsidiasuransi ,
                subsidipemerintah ,
                subsidirs ,
                iurbiaya ,
                oa ,
                pembulatan ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                permohonanoadetail_id ,
                persenppnjual ,
                resepturdetail_id ,
                nilaippnjual ,
                perawat1_id ,
                perawat2_id ,
                instruksitindakanbmhp_id ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_jurnal ,
                konfigmargindetail_id ,
                qty_konversi ,
                is_penatajasa ,
                det ,
                status_bmhp ,
                det_konversi ,
                signa ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date , 
                deleted_by ,
                keterangan,
                no_obatalkespasien,
                                tarif_dijamin,
                                tarif_dibayarkan
            )VALUES(
                OLD.obatalkespasien_id ,
                OLD.sumberdana_id ,
                OLD.racikan_id ,
                OLD.returresepdetail_id ,
                OLD.tipepaket_id ,
                OLD.ruangan_id ,
                OLD.carabayar_id ,
                OLD.pegawai_id ,
                OLD.daftartindakan_id ,
                OLD.tindakanpelayanan_id ,
                OLD.satuankecil_id ,
                OLD.shift_id ,
                OLD.pendaftaran_id ,
                OLD.obatalkes_id ,
                OLD.pasien_id ,
                OLD.penjamin_id ,
                OLD.kelaspelayanan_id ,
                OLD.pasienanastesi_id ,
                OLD.pasienmasukpenunjang_id ,
                OLD.pasienadmisi_id ,
                OLD.obatsudahbayar_id ,
                OLD.penjualanresep_id ,
                OLD.tglpelayanan ,
                OLD.r ,
                OLD.rke ,
                OLD.permintaan_oa ,
                OLD.jmlkemasan_oa ,
                OLD.kekuatan_oa ,
                OLD.satuankekuatan_oa ,
                -1 * OLD.qty_oa ,
                OLD.hargasatuan_oa ,
                OLD.signa_oa ,
                OLD.harganetto_oa ,
                CASE
                                    WHEN OLD.det <> 0  THEN -1 * OLD.hargasatuan_oa * OLD.det
                                    WHEN OLD.det = 0 OR OLD.det IS NULL THEN  -1 * OLD.hargasatuan_oa * OLD.qty_oa 
                                END, 
                OLD.etiket ,
                OLD.jmlexposerad ,
                OLD.kontrasrad ,
                OLD.biayaservice ,
                OLD.biayakonseling ,
                OLD.jasadokterresep ,
                OLD.biayakemasan ,
                OLD.biayaadministrasi ,
                OLD.tarifcyto ,
                OLD.discount , 
                OLD.subsidiasuransi ,
                OLD.subsidipemerintah ,
                OLD.subsidirs ,
                OLD.iurbiaya ,
                OLD.oa ,
                OLD.pembulatan ,
                OLD.verifikasitagihan_id ,
                OLD.jurnalrekening_id ,
                OLD.permohonanoadetail_id ,
                OLD.persenppnjual ,
                OLD.resepturdetail_id ,
                OLD.nilaippnjual ,
                OLD.perawat1_id ,
                OLD.perawat2_id ,
                OLD.instruksitindakanbmhp_id ,
                OLD.implementasi_id ,
                OLD.is_dilakukan ,
                OLD.pemakaianambulan_id ,
                OLD.is_jurnal ,
                OLD.konfigmargindetail_id ,
                -1 * OLD.qty_konversi ,
                OLD.is_penatajasa ,
                -1 * OLD.det ,
                OLD.status_bmhp ,
                OLD.det_konversi ,
                OLD.signa ,
                OLD.additional_data ,
                OLD.created_date ,
                OLD.created_by ,
                OLD.modified_count ,
                OLD.last_modified_date ,
                OLD.last_modified_by ,
                OLD.is_deleted ,
                OLD.is_active ,
                OLD.deleted_date , 
                OLD.deleted_by ,
                v_keterangan,
                OLD.no_obatalkespasien,
                                0,
                                0
            );
        RETURN NEW;
        END IF;
            
            IF (OLD.obatsudahbayar_id is null and OLD.is_deleted is FALSE)
                THEN    
                -- INSERT table history obatalkespasien_r menjadi ACCRUAL REVERSAL(-) setelah BILLING CANCEL
                INSERT INTO obatalkespasien_r (     
                obatalkespasien_id ,
                sumberdana_id ,
                racikan_id ,
                returresepdetail_id ,
                tipepaket_id ,
                ruangan_id ,
                carabayar_id ,
                pegawai_id ,
                daftartindakan_id ,
                tindakanpelayanan_id ,
                satuankecil_id ,
                shift_id ,
                pendaftaran_id ,
                obatalkes_id ,
                pasien_id ,
                penjamin_id ,
                kelaspelayanan_id ,
                pasienanastesi_id ,
                pasienmasukpenunjang_id ,
                pasienadmisi_id ,
                obatsudahbayar_id ,
                penjualanresep_id ,
                tglpelayanan ,
                r ,
                rke ,
                permintaan_oa ,
                jmlkemasan_oa ,
                kekuatan_oa ,
                satuankekuatan_oa ,
                qty_oa ,
                hargasatuan_oa ,
                signa_oa ,
                harganetto_oa ,
                hargajual_oa , 
                etiket ,
                jmlexposerad ,
                kontrasrad ,
                biayaservice ,
                biayakonseling ,
                jasadokterresep ,
                biayakemasan ,
                biayaadministrasi ,
                tarifcyto ,
                discount , 
                subsidiasuransi ,
                subsidipemerintah ,
                subsidirs ,
                iurbiaya ,
                oa ,
                pembulatan ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                permohonanoadetail_id ,
                persenppnjual ,
                resepturdetail_id ,
                nilaippnjual ,
                perawat1_id ,
                perawat2_id ,
                instruksitindakanbmhp_id ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_jurnal ,
                konfigmargindetail_id ,
                qty_konversi ,
                is_penatajasa ,
                det ,
                status_bmhp ,
                det_konversi ,
                signa ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date , 
                deleted_by ,
                keterangan,
                no_obatalkespasien,
                                tarif_dijamin,
                                tarif_dibayarkan
            )VALUES(
                OLD.obatalkespasien_id ,
                OLD.sumberdana_id ,
                OLD.racikan_id ,
                OLD.returresepdetail_id ,
                OLD.tipepaket_id ,
                OLD.ruangan_id ,
                OLD.carabayar_id ,
                OLD.pegawai_id ,
                OLD.daftartindakan_id ,
                OLD.tindakanpelayanan_id ,
                OLD.satuankecil_id ,
                OLD.shift_id ,
                OLD.pendaftaran_id ,
                OLD.obatalkes_id ,
                OLD.pasien_id ,
                OLD.penjamin_id ,
                OLD.kelaspelayanan_id ,
                OLD.pasienanastesi_id ,
                OLD.pasienmasukpenunjang_id ,
                OLD.pasienadmisi_id ,
                OLD.obatsudahbayar_id ,
                OLD.penjualanresep_id ,
                OLD.tglpelayanan ,
                OLD.r ,
                OLD.rke ,
                OLD.permintaan_oa ,
                OLD.jmlkemasan_oa ,
                OLD.kekuatan_oa ,
                OLD.satuankekuatan_oa ,
                -1 * OLD.qty_oa ,
                OLD.hargasatuan_oa ,
                OLD.signa_oa ,
                OLD.harganetto_oa ,
                CASE
                                    WHEN OLD.det <> 0  THEN -1 * OLD.hargasatuan_oa * OLD.det
                                    WHEN OLD.det = 0 OR OLD.det IS NULL THEN  -1 * OLD.hargasatuan_oa * OLD.qty_oa 
                                END,  
                OLD.etiket ,
                OLD.jmlexposerad ,
                OLD.kontrasrad ,
                OLD.biayaservice ,
                OLD.biayakonseling ,
                OLD.jasadokterresep ,
                OLD.biayakemasan ,
                OLD.biayaadministrasi ,
                OLD.tarifcyto ,
                OLD.discount , 
                OLD.subsidiasuransi ,
                OLD.subsidipemerintah ,
                OLD.subsidirs ,
                OLD.iurbiaya ,
                OLD.oa ,
                OLD.pembulatan ,
                OLD.verifikasitagihan_id ,
                OLD.jurnalrekening_id ,
                OLD.permohonanoadetail_id ,
                OLD.persenppnjual ,
                OLD.resepturdetail_id ,
                OLD.nilaippnjual ,
                OLD.perawat1_id ,
                OLD.perawat2_id ,
                OLD.instruksitindakanbmhp_id ,
                OLD.implementasi_id ,
                OLD.is_dilakukan ,
                OLD.pemakaianambulan_id ,
                OLD.is_jurnal ,
                OLD.konfigmargindetail_id ,
                -1 * OLD.qty_konversi ,
                OLD.is_penatajasa ,
                -1 * OLD.det ,
                OLD.status_bmhp ,
                OLD.det_konversi ,
                OLD.signa ,
                OLD.additional_data ,
                OLD.created_date ,
                OLD.created_by ,
                OLD.modified_count ,
                OLD.last_modified_date ,
                OLD.last_modified_by ,
                OLD.is_deleted ,
                OLD.is_active ,
                OLD.deleted_date , 
                OLD.deleted_by ,
                'ACCRUAL REVERSAL',
                OLD.no_obatalkespasien,
                                OLD.tarif_dijamin,
                                OLD.tarif_dibayarkan
            );
        
            INSERT INTO obatalkespasien_r (     
                obatalkespasien_id ,
                sumberdana_id ,
                racikan_id ,
                returresepdetail_id ,
                tipepaket_id ,
                ruangan_id ,
                carabayar_id ,
                pegawai_id ,
                daftartindakan_id ,
                tindakanpelayanan_id ,
                satuankecil_id ,
                shift_id ,
                pendaftaran_id ,
                obatalkes_id ,
                pasien_id ,
                penjamin_id ,
                kelaspelayanan_id ,
                pasienanastesi_id ,
                pasienmasukpenunjang_id ,
                pasienadmisi_id ,
                obatsudahbayar_id ,
                penjualanresep_id ,
                tglpelayanan ,
                r ,
                rke ,
                permintaan_oa ,
                jmlkemasan_oa ,
                kekuatan_oa ,
                satuankekuatan_oa ,
                qty_oa ,
                hargasatuan_oa ,
                signa_oa ,
                harganetto_oa ,
                hargajual_oa , 
                etiket ,
                jmlexposerad ,
                kontrasrad ,
                biayaservice ,
                biayakonseling ,
                jasadokterresep ,
                biayakemasan ,
                biayaadministrasi ,
                tarifcyto ,
                discount , 
                subsidiasuransi ,
                subsidipemerintah ,
                subsidirs ,
                iurbiaya ,
                oa ,
                pembulatan ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                permohonanoadetail_id ,
                persenppnjual ,
                resepturdetail_id ,
                nilaippnjual ,
                perawat1_id ,
                perawat2_id ,
                instruksitindakanbmhp_id ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_jurnal ,
                konfigmargindetail_id ,
                qty_konversi ,
                is_penatajasa ,
                det ,
                status_bmhp ,
                det_konversi ,
                signa ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date , 
                deleted_by ,
                keterangan,
                no_obatalkespasien,
                                tarif_dijamin,
                                tarif_dibayarkan
            )VALUES(
                OLD.obatalkespasien_id ,
                OLD.sumberdana_id ,
                OLD.racikan_id ,
                NEW.returresepdetail_id ,
                OLD.tipepaket_id ,
                OLD.ruangan_id ,
                OLD.carabayar_id ,
                OLD.pegawai_id ,
                NEW.daftartindakan_id ,
                NEW.tindakanpelayanan_id ,
                OLD.satuankecil_id ,
                OLD.shift_id ,
                OLD.pendaftaran_id ,
                OLD.obatalkes_id ,
                OLD.pasien_id ,
                NEW.penjamin_id ,
                NEW.kelaspelayanan_id ,
                OLD.pasienanastesi_id ,
                OLD.pasienmasukpenunjang_id ,
                OLD.pasienadmisi_id ,
                OLD.obatsudahbayar_id ,
                OLD.penjualanresep_id ,
                OLD.tglpelayanan ,
                OLD.r ,
                OLD.rke ,
                OLD.permintaan_oa ,
                OLD.jmlkemasan_oa ,
                OLD.kekuatan_oa ,
                OLD.satuankekuatan_oa ,
                NEW.qty_oa ,
                NEW.hargasatuan_oa ,
                NEW.signa_oa ,
                NEW.harganetto_oa ,
                CASE
                                    WHEN NEW.det <> 0  THEN NEW.hargasatuan_oa * NEW.det
                                    WHEN NEW.det = 0 OR NEW.det IS NULL THEN NEW.hargasatuan_oa * NEW.qty_oa 
                                END,  
                OLD.etiket ,
                OLD.jmlexposerad ,
                OLD.kontrasrad ,
                OLD.biayaservice ,
                OLD.biayakonseling ,
                OLD.jasadokterresep ,
                OLD.biayakemasan ,
                OLD.biayaadministrasi ,
                OLD.tarifcyto ,
                OLD.discount , 
                OLD.subsidiasuransi ,
                OLD.subsidipemerintah ,
                OLD.subsidirs ,
                OLD.iurbiaya ,
                OLD.oa ,
                OLD.pembulatan ,
                OLD.verifikasitagihan_id ,
                OLD.jurnalrekening_id ,
                OLD.permohonanoadetail_id ,
                OLD.persenppnjual ,
                OLD.resepturdetail_id ,
                OLD.nilaippnjual ,
                OLD.perawat1_id ,
                OLD.perawat2_id ,
                OLD.instruksitindakanbmhp_id ,
                OLD.implementasi_id ,
                OLD.is_dilakukan ,
                OLD.pemakaianambulan_id ,
                OLD.is_jurnal ,
                OLD.konfigmargindetail_id ,
                NEW.qty_konversi ,
                OLD.is_penatajasa ,
                NEW.det ,
                OLD.status_bmhp ,
                OLD.det_konversi ,
                OLD.signa ,
                OLD.additional_data ,
                OLD.created_date ,
                OLD.created_by ,
                OLD.modified_count ,
                OLD.last_modified_date ,
                OLD.last_modified_by ,
                OLD.is_deleted ,
                OLD.is_active ,
                OLD.deleted_date , 
                OLD.deleted_by ,
                'ACCRUAL',
                OLD.no_obatalkespasien,
                                NEW.tarif_dijamin,
                                NEW.tarif_dibayarkan
            );  

END IF;

    RETURN NEW;

END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

        $this->execute('ALTER FUNCTION "public"."obatalkespasien_r_update"() OWNER TO "postgres";');

        $this->execute("
            CREATE OR REPLACE FUNCTION \"public\".\"obatsudahbayar_t_cancel\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$ 
    
DECLARE
        v_keterangan VARCHAR;
    BEGIN
        IF(NEW.is_deleted IS TRUE)
        THEN
            -- INSERT table history obatalkespasien_r menjadi ACCRUAL(+), jika is_deleted=TRUE
            INSERT INTO obatalkespasien_r (     
                obatalkespasien_id ,
                sumberdana_id ,
                racikan_id ,
                returresepdetail_id ,
                tipepaket_id ,
                ruangan_id ,
                carabayar_id ,
                pegawai_id ,
                daftartindakan_id ,
                tindakanpelayanan_id ,
                satuankecil_id ,
                shift_id ,
                pendaftaran_id ,
                obatalkes_id ,
                pasien_id ,
                penjamin_id ,
                kelaspelayanan_id ,
                pasienanastesi_id ,
                pasienmasukpenunjang_id ,
                pasienadmisi_id ,
                obatsudahbayar_id ,
                penjualanresep_id ,
                tglpelayanan ,
                r ,
                rke ,
                permintaan_oa ,
                jmlkemasan_oa ,
                kekuatan_oa ,
                satuankekuatan_oa ,
                qty_oa ,
                hargasatuan_oa ,
                signa_oa ,
                harganetto_oa ,
                hargajual_oa , 
                etiket ,
                jmlexposerad ,
                kontrasrad ,
                biayaservice ,
                biayakonseling ,
                jasadokterresep ,
                biayakemasan ,
                biayaadministrasi ,
                tarifcyto ,
                discount , 
                subsidiasuransi ,
                subsidipemerintah ,
                subsidirs ,
                iurbiaya ,
                oa ,
                pembulatan ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                permohonanoadetail_id ,
                persenppnjual ,
                resepturdetail_id ,
                nilaippnjual ,
                perawat1_id ,
                perawat2_id ,
                instruksitindakanbmhp_id ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_jurnal ,
                konfigmargindetail_id ,
                qty_konversi ,
                is_penatajasa ,
                det ,
                status_bmhp ,
                det_konversi ,
                signa ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date , 
                deleted_by ,
                keterangan
                )
                SELECT
                obatalkespasien_id ,
                sumberdana_id ,
                racikan_id ,
                returresepdetail_id ,
                tipepaket_id ,
                ruangan_id ,
                carabayar_id ,
                pegawai_id ,
                daftartindakan_id ,
                tindakanpelayanan_id ,
                satuankecil_id ,
                shift_id ,
                pendaftaran_id ,
                obatalkes_id ,
                pasien_id ,
                penjamin_id ,
                kelaspelayanan_id ,
                pasienanastesi_id ,
                pasienmasukpenunjang_id ,
                pasienadmisi_id ,
                NEW.obatsudahbayar_id ,
                penjualanresep_id ,
                tglpelayanan ,
                r ,
                rke ,
                permintaan_oa ,
                jmlkemasan_oa ,
                kekuatan_oa ,
                satuankekuatan_oa ,
                qty_oa ,
                hargasatuan_oa ,
                signa_oa ,
                harganetto_oa ,
                hargajual_oa , 
                etiket ,
                jmlexposerad ,
                kontrasrad ,
                biayaservice ,
                biayakonseling ,
                jasadokterresep ,
                biayakemasan ,
                biayaadministrasi ,
                tarifcyto ,
                discount , 
                subsidiasuransi ,
                subsidipemerintah ,
                subsidirs ,
                iurbiaya ,
                oa ,
                pembulatan ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                permohonanoadetail_id ,
                persenppnjual ,
                resepturdetail_id ,
                nilaippnjual ,
                perawat1_id ,
                perawat2_id ,
                instruksitindakanbmhp_id ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_jurnal ,
                konfigmargindetail_id ,
                qty_konversi ,
                is_penatajasa ,
                det ,
                status_bmhp ,
                det_konversi ,
                signa ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date , 
                deleted_by ,
                'ACCRUAL'
                FROM obatalkespasien_t
            WHERE obatalkespasien_id = NEW.obatalkespasien_id;
        
            -- INSERT table history obatalkespasien_r menjadi BILLING CANCEL(-), jika is_deleted=TRUE
                INSERT INTO obatalkespasien_r (     
                    obatalkespasien_id ,
                    sumberdana_id ,
                    racikan_id ,
                    returresepdetail_id ,
                    tipepaket_id ,
                    ruangan_id ,
                    carabayar_id ,
                    pegawai_id ,
                    daftartindakan_id ,
                    tindakanpelayanan_id ,
                    satuankecil_id ,
                    shift_id ,
                    pendaftaran_id ,
                    obatalkes_id ,
                    pasien_id ,
                    penjamin_id ,
                    kelaspelayanan_id ,
                    pasienanastesi_id ,
                    pasienmasukpenunjang_id ,
                    pasienadmisi_id ,
                    obatsudahbayar_id ,
                    penjualanresep_id ,
                    tglpelayanan ,
                    r ,
                    rke ,
                    permintaan_oa ,
                    jmlkemasan_oa ,
                    kekuatan_oa ,
                    satuankekuatan_oa ,
                    qty_oa ,
                    hargasatuan_oa ,
                    signa_oa ,
                    harganetto_oa ,
                    hargajual_oa , 
                    etiket ,
                    jmlexposerad ,
                    kontrasrad ,
                    biayaservice ,
                    biayakonseling ,
                    jasadokterresep ,
                    biayakemasan ,
                    biayaadministrasi ,
                    tarifcyto ,
                    discount , 
                    subsidiasuransi ,
                    subsidipemerintah ,
                    subsidirs ,
                    iurbiaya ,
                    oa ,
                    pembulatan ,
                    verifikasitagihan_id ,
                    jurnalrekening_id ,
                    permohonanoadetail_id ,
                    persenppnjual ,
                    resepturdetail_id ,
                    nilaippnjual ,
                    perawat1_id ,
                    perawat2_id ,
                    instruksitindakanbmhp_id ,
                    implementasi_id ,
                    is_dilakukan ,
                    pemakaianambulan_id ,
                    is_jurnal ,
                    konfigmargindetail_id ,
                    qty_konversi ,
                    is_penatajasa ,
                    det ,
                    status_bmhp ,
                    det_konversi ,
                    signa ,
                    additional_data ,
                    created_date ,
                    created_by ,
                    modified_count ,
                    last_modified_date ,
                    last_modified_by ,
                    is_deleted ,
                    is_active ,
                    deleted_date , 
                    deleted_by ,
                    keterangan,
                                        tarif_dijamin,
                                        tarif_dibayarkan
                    )
                    SELECT
                    obatalkespasien_id ,
                    sumberdana_id ,
                    racikan_id ,
                    returresepdetail_id ,
                    tipepaket_id ,
                    ruangan_id ,
                    carabayar_id ,
                    pegawai_id ,
                    daftartindakan_id ,
                    tindakanpelayanan_id ,
                    satuankecil_id ,
                    shift_id ,
                    pendaftaran_id ,
                    obatalkes_id ,
                    pasien_id ,
                    penjamin_id ,
                    kelaspelayanan_id ,
                    pasienanastesi_id ,
                    pasienmasukpenunjang_id ,
                    pasienadmisi_id ,
                    NEW.obatsudahbayar_id ,
                    penjualanresep_id ,
                    tglpelayanan ,
                    r ,
                    rke ,
                    permintaan_oa ,
                    jmlkemasan_oa ,
                    kekuatan_oa ,
                    satuankekuatan_oa ,
                    -1 * OLD.qty_oa ,
                    hargasatuan_oa ,
                    signa_oa ,
                    harganetto_oa ,
                                        CASE
                                        WHEN OLD.det <> 0  THEN -1 * OLD.hargasatuan_oa * OLD.det
                                        WHEN OLD.det = 0 OR OLD.det IS NULL THEN  -1 * OLD.hargasatuan_oa * OLD.qty_oa 
                                        END,  
                    etiket ,
                    jmlexposerad ,
                    kontrasrad ,
                    biayaservice ,
                    biayakonseling ,
                    jasadokterresep ,
                    biayakemasan ,
                    biayaadministrasi ,
                    tarifcyto ,
                    discount , 
                    subsidiasuransi ,
                    subsidipemerintah ,
                    subsidirs ,
                    iurbiaya ,
                    oa ,
                    pembulatan ,
                    verifikasitagihan_id ,
                    jurnalrekening_id ,
                    permohonanoadetail_id ,
                    persenppnjual ,
                    resepturdetail_id ,
                    nilaippnjual ,
                    perawat1_id ,
                    perawat2_id ,
                    instruksitindakanbmhp_id ,
                    implementasi_id ,
                    is_dilakukan ,
                    pemakaianambulan_id ,
                    is_jurnal ,
                    konfigmargindetail_id ,
                    -1 * OLD.qty_konversi ,
                    is_penatajasa ,
                    -1 * OLD.det ,
                    status_bmhp ,
                    det_konversi ,
                    signa ,
                    additional_data ,
                    created_date ,
                    created_by ,
                    modified_count ,
                    last_modified_date ,
                    last_modified_by ,
                    is_deleted ,
                    is_active ,
                    deleted_date , 
                    deleted_by ,
                    'BILLING CANCEL',
                                        ((old.additional_data::json->>'data_dijamin')::json->>'dijamin')::float,
                                        ((old.additional_data::json->>'data_dijamin')::json->>'harusbayar')::float 
                    FROM obatalkespasien_t
                WHERE obatalkespasien_id = NEW.obatalkespasien_id;
                
    END IF;
    
    RETURN NEW;

END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

        $this->execute('ALTER FUNCTION "public"."obatsudahbayar_t_cancel"() OWNER TO "postgres";');

        $this->execute("
            CREATE OR REPLACE FUNCTION \"public\".\"pembayaran_r_delete\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$ 
    
DECLARE  
        v_daftartindakan_id int;
        v_ruangan_id int;
        v_penjamin_id int;
        v_instalasi_id int;
        v_pegawai_id int;
    v_totalpembulatan float;
    v_total_diskon float;
    v_total_discountpembayaran float;
    v_totaladministrasi float;
        v_totaltunai float;
        v_totaldijamin float;

BEGIN
        
        SELECT
            pembayaran_t.total_tunai
            INTO
            v_totaltunai
        FROM pembayaran_t
        WHERE pembayaran_t.pembayaran_id = NEW.pembayaran_id;
        
        IF(NEW.is_deleted IS TRUE and v_totaltunai <> 0)
        THEN
            
           -- INSERT table history pembayaran_r, menjadi Deposit Refund
           INSERT INTO pembayaran_r (       
                pembayaran_id,
                pendaftaran_id,
                pasienadmisi_id,
                total_tagihan,
                total_dibayar,
                total_dijamin,
                total_sisatagihan,
                total_kembalian,
                total_administrasi,
                total_pembulatan,
                total_pembebasan,
                penggunaan_uangmuka,
                pemberianpiutang_id,
                total_ditagihkan,
                total_tunai,
                total_nontunai,
                total_discount,
                total_discountpembayaran,
                catatan,
                tipe_pembayaran,
                additional_data,
                created_date,
                created_by,
                modified_count,
                last_modified_date,
                last_modified_by,
                is_deleted,
                is_active,
                deleted_date,
                deleted_by,
                keterangan
            )
            SELECT
                pembayaran_id,
                pendaftaran_id,
                pasienadmisi_id,
                -1 * total_tagihan ,
                -1 * total_dibayar ,
                0, -- total_dijamin
                -1 * total_sisatagihan ,
                -1 * total_kembalian ,
                -1 * total_administrasi ,
                -1 * total_pembulatan ,
                -1 * total_pembebasan ,
                penggunaan_uangmuka ,
                pemberianpiutang_id ,
                -1 * total_ditagihkan ,
                -1 * total_tunai ,
                0, -- total_nontunai
                -1 * total_discount ,
                -1 * total_discountpembayaran ,
                catatan,
                682,
                NEW.additional_data,
                NEW.created_date,
                NEW.created_by,
                NEW.modified_count,
                NEW.last_modified_date,
                NEW.last_modified_by,
                NEW.is_deleted,
                NEW.is_active,
                NEW.deleted_date,
                NEW.deleted_by,
                'REFUND'
            FROM pembayaran_t
            WHERE pembayaran_id = NEW.pembayaran_id;
    
    END IF;

----------------------------> insert pembatalan total_dijamin<---------------------------------   
        
                SELECT
            pembayaran_t.total_dijamin
            INTO
            v_totaldijamin
        FROM pembayaran_t
                    WHERE pembayaran_t.pembayaran_id = NEW.pembayaran_id;
        
        IF(NEW.is_deleted IS TRUE and v_totaldijamin <> 0)
        THEN
            
           -- INSERT table history pembayaran_r, menjadi Deposit Refund
           INSERT INTO pembayaran_r (       
                pembayaran_id,
                pendaftaran_id,
                pasienadmisi_id,
                total_tagihan,
                total_dibayar,
                total_dijamin,
                total_sisatagihan,
                total_kembalian,
                total_administrasi,
                total_pembulatan,
                total_pembebasan,
                penggunaan_uangmuka,
                pemberianpiutang_id,
                total_ditagihkan,
                total_tunai,
                total_nontunai,
                total_discount,
                total_discountpembayaran,
                catatan,
                tipe_pembayaran,
                additional_data,
                created_date,
                created_by,
                modified_count,
                last_modified_date,
                last_modified_by,
                is_deleted,
                is_active,
                deleted_date,
                deleted_by,
                keterangan
            )
            SELECT
                pembayaran_id,
                pendaftaran_id,
                pasienadmisi_id,
                -1 * total_tagihan ,
                -1 * total_dibayar ,
                -1 * total_dijamin ,
                -1 * total_sisatagihan ,
                -1 * total_kembalian ,
                -1 * total_administrasi ,
                -1 * total_pembulatan ,
                -1 * total_pembebasan ,
                penggunaan_uangmuka ,
                pemberianpiutang_id ,
                -1 * total_ditagihkan ,
                0, --total_tunai
                0, --total_nontunai
                -1 * total_discount ,
                -1 * total_discountpembayaran ,
                catatan,
                682,
                NEW.additional_data,
                NEW.created_date,
                NEW.created_by,
                NEW.modified_count,
                NEW.last_modified_date,
                NEW.last_modified_by,
                NEW.is_deleted,
                NEW.is_active,
                NEW.deleted_date,
                NEW.deleted_by,
                'REFUND'
            FROM pembayaran_t
            WHERE pembayaran_id = NEW.pembayaran_id;
    
    END IF; 
        
----------------------------> insert pembulatan ke tindakanpelayanan_r <---------------------------------   
    
            SELECT
                pembayaran_t.total_pembulatan
            INTO
                v_totalpembulatan
            FROM pembayaran_t
            WHERE pembayaran_t.pembayaran_id = NEW.pembayaran_id;
    
    IF(NEW.is_deleted IS TRUE and v_totalpembulatan <> 0)
        THEN

            SELECT 
                pendaftaran_t.ruangan_id,
                pendaftaran_t.penjamin_id,
                pendaftaran_t.instalasi_id,
                pendaftaran_t.pegawai_id
            INTO
                v_ruangan_id,
                v_penjamin_id,
                v_instalasi_id,
                v_pegawai_id
            FROM pendaftaran_t
            WHERE pendaftaran_t.pendaftaran_id = NEW.pendaftaran_id;
            
            v_daftartindakan_id:=99990; -- daftartindakan_id untuk pembulatan
                    
        INSERT INTO tindakanpelayanan_r (       
                pendaftaran_id,
                daftartindakan_id,
                tarif_satuan,
                tarif_tindakan,
                qty_tindakan,
                keterangan,
                ruangan_id,
                instalasi_id,
                penjamin_id,
                dokterpenanggungjawab_id,
                tgl_tindakan,
                additional_data,
                created_date,
                created_by,
                modified_count,
                last_modified_date,
                last_modified_by,
                is_deleted,
                is_active,
                deleted_date,
                deleted_by,
                                tgl_proses,
                pembayaran_id
        )VALUES(
                NEW.pendaftaran_id,
                v_daftartindakan_id,
                v_totalpembulatan,
                -1 * v_totalpembulatan,
                '-1',
                'BILLING CANCEL',
                v_ruangan_id,
                v_instalasi_id,
                v_penjamin_id,
                v_pegawai_id,
                NEW.created_date,
                NEW.additional_data,
                NEW.created_date,
                NEW.created_by,
                NEW.modified_count,
                NEW.last_modified_date,
                NEW.last_modified_by,
                NEW.is_deleted,
                NEW.is_active,
                NEW.deleted_date,
                NEW.deleted_by,
                NEW.created_date,
                NEW.pembayaran_id
        );
        
    END IF;
    
    ---------------------------> insert diskon ke tindakanpelayanan_r <-------------------------
    
            SELECT
                pembayaran_t.total_discount,
                pembayaran_t.total_discountpembayaran
            INTO
                v_total_diskon,
                v_total_discountpembayaran
            FROM pembayaran_t
            WHERE pembayaran_t.pembayaran_id = NEW.pembayaran_id;
    
    IF(NEW.is_deleted IS TRUE and (COALESCE(v_total_diskon,0) + COALESCE(v_total_discountpembayaran,0) <> 0))
        THEN

            SELECT 
                pendaftaran_t.ruangan_id,
                pendaftaran_t.penjamin_id,
                pendaftaran_t.instalasi_id,
                pendaftaran_t.pegawai_id
            INTO
                v_ruangan_id,
                v_penjamin_id,
                v_instalasi_id,
                v_pegawai_id
            FROM pendaftaran_t
            WHERE pendaftaran_t.pendaftaran_id = NEW.pendaftaran_id;
            
            v_daftartindakan_id:=99991; -- daftartindakan_id untuk diskon
            
        INSERT INTO tindakanpelayanan_r (       
                pendaftaran_id,
                daftartindakan_id,
                tarif_satuan,
                tarif_tindakan,
                qty_tindakan,
                keterangan,
                ruangan_id,
                instalasi_id,
                penjamin_id,
                dokterpenanggungjawab_id,
                tgl_tindakan,
                additional_data,
                created_date,
                created_by,
                modified_count,
                last_modified_date,
                last_modified_by,
                is_deleted,
                is_active,
                deleted_date,
                deleted_by,
                                tgl_proses,
                pembayaran_id
        )VALUES(
                NEW.pendaftaran_id,
                v_daftartindakan_id,
                COALESCE(-1 * v_total_diskon,0)+COALESCE(-1 * v_total_discountpembayaran,0),
                COALESCE(v_total_diskon,0)+COALESCE(v_total_discountpembayaran,0),
                '-1',
                'DISCOUNT CANCEL',
                v_ruangan_id,
                v_instalasi_id,
                v_penjamin_id,
                v_pegawai_id,
                NEW.created_date,
                NEW.additional_data,
                NEW.created_date,
                NEW.created_by,
                NEW.modified_count,
                NEW.last_modified_date,
                NEW.last_modified_by,
                NEW.is_deleted,
                NEW.is_active,
                NEW.deleted_date,
                NEW.deleted_by,
                NEW.created_date,
                NEW.pembayaran_id
        );
        
    END IF;
    
    -------------------------------------> insert administrasi ke tindakanpelayanan_r <--------------------------------------------
    
            SELECT
                pembayaran_t.total_administrasi
            INTO
                v_totaladministrasi
            FROM pembayaran_t
            WHERE pembayaran_t.pembayaran_id = NEW.pembayaran_id;
    
    IF(NEW.is_deleted IS TRUE and v_totaladministrasi <> 0)
        THEN

            SELECT 
                pendaftaran_t.ruangan_id,
                pendaftaran_t.penjamin_id,
                pendaftaran_t.instalasi_id,
                pendaftaran_t.pegawai_id
            INTO
                v_ruangan_id,
                v_penjamin_id,
                v_instalasi_id,
                v_pegawai_id
            FROM pendaftaran_t
            WHERE pendaftaran_t.pendaftaran_id = NEW.pendaftaran_id;
        
            v_daftartindakan_id:=99992; -- daftartindakan_id untuk administrasi
            
        INSERT INTO tindakanpelayanan_r (       
                pendaftaran_id,
                daftartindakan_id,
                tarif_satuan,
                tarif_tindakan,
                qty_tindakan,
                keterangan,
                ruangan_id,
                instalasi_id,
                penjamin_id,
                dokterpenanggungjawab_id,
                tgl_tindakan,
                additional_data,
                created_date,
                created_by,
                modified_count,
                last_modified_date,
                last_modified_by,
                is_deleted,
                is_active,
                deleted_date,
                deleted_by,
                                tgl_proses,
                pembayaran_id
        )VALUES(
                NEW.pendaftaran_id,
                v_daftartindakan_id,
                v_totaladministrasi,
                -1 * v_totaladministrasi,
                '-1',
                'BILLING CANCEL',
                v_ruangan_id,
                v_instalasi_id,
                v_penjamin_id,
                v_pegawai_id,
                NEW.created_date,
                NEW.additional_data,
                NEW.created_date,
                NEW.created_by,
                NEW.modified_count,
                NEW.last_modified_date,
                NEW.last_modified_by,
                NEW.is_deleted,
                NEW.is_active,
                NEW.deleted_date,
                NEW.deleted_by,
                NEW.created_date,
                NEW.pembayaran_id
        );
        
    END IF;
    
    RETURN NEW;

END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

        $this->execute('ALTER FUNCTION "public"."pembayaran_r_delete"() OWNER TO "postgres";');

        $this->execute("
            CREATE OR REPLACE FUNCTION \"public\".\"pembayaranpelayanan_batal\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$ 
  

BEGIN  
----------------------------------pemakaianuangmuka_t-----------------------------
--   IF(NEW.is_deleted = TRUE)
--     THEN
--       UPDATE pemakaianuangmuka_t SET is_deleted = TRUE
--       WHERE pembayaranpelayanan_id = NEW.pembayaranpelayanan_id;
-- 
--   END IF;

----------------------------------pembayaranmetode_t-----------------------------
  IF(NEW.is_deleted = TRUE)
    THEN
      UPDATE pembayaranmetode_t 
                    SET is_deleted = TRUE,
                            deleted_by = NEW.deleted_by
      WHERE pembayaran_id = NEW.pembayaran_id;

  END IF;
    
    ----------------------------------pembayaran_t-----------------------------
  IF(NEW.is_deleted = TRUE)
    THEN
      UPDATE pembayaran_t 
                    SET is_deleted = TRUE,
                            deleted_by = NEW.deleted_by
      WHERE pembayaran_id = NEW.pembayaran_id;

  END IF;

RETURN NEW;

END

\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

        $this->execute('ALTER FUNCTION "public"."pembayaranpelayanan_batal"() OWNER TO "postgres";');

        $this->execute("
            CREATE OR REPLACE FUNCTION \"public\".\"pembulatan_diskon_insert\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$ 
    
DECLARE  
        v_daftartindakan_id int;
        v_ruangan_id int;
        v_penjamin_id int;
        v_instalasi_id int;
        v_pegawai_id int;
        v_kelaspelayanan_id int;

BEGIN   
--------------------------> insert pembulatan ke tindakanpelayanan_r <--------------------------------

    IF(NEW.total_pembulatan <> 0)
        THEN
            
            SELECT 
                pendaftaran_t.ruangan_id,
                pendaftaran_t.penjamin_id,
                pendaftaran_t.instalasi_id,
                pendaftaran_t.pegawai_id,
                pendaftaran_t.kelaspelayanan_id
            INTO
                v_ruangan_id,
                v_penjamin_id,
                v_instalasi_id,
                v_pegawai_id,
                v_kelaspelayanan_id
            FROM pendaftaran_t
            WHERE pendaftaran_t.pendaftaran_id = NEW.pendaftaran_id;

            v_daftartindakan_id:=99990; -- daftartindakan_id untuk pembulatan
            
        
        INSERT INTO tindakanpelayanan_r (       
                pendaftaran_id,
                daftartindakan_id,
                tarif_satuan,
                tarif_tindakan,
                qty_tindakan,
                keterangan,
                ruangan_id,
                instalasi_id,
                penjamin_id,
                kelaspelayanan_id,
                dokterpenanggungjawab_id,
                tgl_tindakan,
                additional_data,
                created_date,
                created_by,
                modified_count,
                last_modified_date,
                last_modified_by,
                is_deleted,
                is_active,
                deleted_date,
                deleted_by,
              tgl_proses,
                pembayaran_id
        )VALUES(
                NEW.pendaftaran_id,
                v_daftartindakan_id,
                NEW.total_pembulatan,
                NEW.total_pembulatan,
                '1',
                'BILLING',
                v_ruangan_id,
                v_instalasi_id,
                v_penjamin_id,
                v_kelaspelayanan_id,
                v_pegawai_id,
                new.created_date,
                new.additional_data,
                new.created_date,
                new.created_by,
                new.modified_count,
                new.last_modified_date,
                new.last_modified_by,
                new.is_deleted,
                new.is_active,
                new.deleted_date,
                new.deleted_by,
                new.created_date,
                new.pembayaran_id
        );
        
END IF;     


-------------------------> insert diskon ke tindakanpelayanan_r <----------------------------------

IF(COALESCE(NEW.total_discount,0) + COALESCE(NEW.total_discountpembayaran,0) <> 0)
                THEN
                    
                    SELECT 
                        pendaftaran_t.ruangan_id,
                        pendaftaran_t.penjamin_id,
                        pendaftaran_t.instalasi_id,
                        pendaftaran_t.pegawai_id,
                        pendaftaran_t.kelaspelayanan_id
                    INTO
                        v_ruangan_id,
                        v_penjamin_id,
                        v_instalasi_id,
                        v_pegawai_id,
                        v_kelaspelayanan_id
                    FROM pendaftaran_t
                    WHERE pendaftaran_t.pendaftaran_id = NEW.pendaftaran_id;

                    v_daftartindakan_id:=99991; -- daftartindakan_id untuk diskon
                    
                
                INSERT INTO tindakanpelayanan_r (       
                        pendaftaran_id,
                        daftartindakan_id,
                        tarif_satuan,
                        tarif_tindakan,
                        qty_tindakan,
                        keterangan,
                        ruangan_id,
                        instalasi_id,
                        penjamin_id,
                        kelaspelayanan_id,
                        dokterpenanggungjawab_id,
                        tgl_tindakan,
                        additional_data,
                        created_date,
                        created_by,
                        modified_count,
                        last_modified_date,
                        last_modified_by,
                        is_deleted,
                        is_active,
                        deleted_date,
                        deleted_by,
                        tgl_proses,
                        pembayaran_id
                )VALUES(
                        NEW.pendaftaran_id,
                        v_daftartindakan_id,
                        COALESCE(-1 * NEW.total_discount,0) + COALESCE(-1 * NEW.total_discountpembayaran,0),
                      COALESCE(-1 * NEW.total_discount,0) + COALESCE(-1 * NEW.total_discountpembayaran,0),
                        '1',
                        'DISCOUNT',
                        v_ruangan_id,
                        v_instalasi_id,
                        v_penjamin_id,
                        v_kelaspelayanan_id,
                        v_pegawai_id,
                        new.created_date,
                        new.additional_data,
                        new.created_date,
                        new.created_by,
                        new.modified_count,
                        new.last_modified_date,
                        new.last_modified_by,
                        new.is_deleted,
                        new.is_active,
                        new.deleted_date,
                        new.deleted_by,
                        new.created_date,
                        new.pembayaran_id
                );

END IF;

---------------------------------> insert administrasi ke tindakanpelayanan_r <-------------------------------------

IF(NEW.total_administrasi <> 0)
                THEN
                    
                    SELECT 
                        pendaftaran_t.ruangan_id,
                        pendaftaran_t.penjamin_id,
                        pendaftaran_t.instalasi_id,
                        pendaftaran_t.pegawai_id,
                        pendaftaran_t.kelaspelayanan_id
                    INTO
                        v_ruangan_id,
                        v_penjamin_id,
                        v_instalasi_id,
                        v_pegawai_id,
                        v_kelaspelayanan_id
                    FROM pendaftaran_t
                    WHERE pendaftaran_t.pendaftaran_id = NEW.pendaftaran_id;

                    v_daftartindakan_id:=99992; -- daftartindakan_id untuk administrasi
                    
                
                INSERT INTO tindakanpelayanan_r (       
                        pendaftaran_id,
                        daftartindakan_id,
                        tarif_satuan,
                        tarif_tindakan,
                        qty_tindakan,
                        keterangan,
                        ruangan_id,
                        instalasi_id,
                        penjamin_id,
                        kelaspelayanan_id,
                        dokterpenanggungjawab_id,
                        tgl_tindakan,
                        additional_data,
                        created_date,
                        created_by,
                        modified_count,
                        last_modified_date,
                        last_modified_by,
                        is_deleted,
                        is_active,
                        deleted_date,
                        deleted_by,
                        tgl_proses,
                        pembayaran_id
                )VALUES(
                        NEW.pendaftaran_id,
                        v_daftartindakan_id,
                        NEW.total_administrasi,
                        NEW.total_administrasi,
                        '1',
                        'BILLING',
                        v_ruangan_id,
                        v_instalasi_id,
                        v_penjamin_id,
                        v_kelaspelayanan_id,
                        v_pegawai_id,
                        new.created_date,
                        new.additional_data,
                        new.created_date,
                        new.created_by,
                        new.modified_count,
                        new.last_modified_date,
                        new.last_modified_by,
                        new.is_deleted,
                        new.is_active,
                        new.deleted_date,
                        new.deleted_by,
                        new.created_date,
                        new.pembayaran_id
                );

END IF;

RETURN NEW;

END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

        $this->execute('ALTER FUNCTION "public"."pembulatan_diskon_insert"() OWNER TO "postgres";');

        $this->execute("
            CREATE OR REPLACE FUNCTION \"public\".\"tindakanpelayanan_r_update\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$

DECLARE
    v_keterangan VARCHAR;
BEGIN
    IF((NEW.is_deleted IS TRUE OR NEW.tindakansudahbayar_id IS NOT NULL) AND OLD.is_deleted IS FALSE)
        THEN
            v_keterangan := 'ACCRUAL REVERSAL';
        --> INSERT table history tindakanpelayanan_r menjadi ACCRUAL REVERSAL(-)
            INSERT INTO tindakanpelayanan_r (       
            tindakanpelayanan_id ,
            shift_id ,
            kelaspelayanan_id ,
            kelastanggungan_id ,
            pasien_id ,
            rencanaoperasi_id ,
            instalasi_id ,
            daftartindakan_id ,
            alatmedis_id ,
            tipepaket_id ,
            tindakansudahbayar_id ,
            carabayar_id ,
            pendaftaran_id ,
            hasilpemeriksaanrad_id ,
            jeniskasuspenyakit_id ,
            hasilpemeriksaanrm_id ,
            ruangan_id ,
            konsulpoli_id ,
            pasienmasukpenunjang_id ,
            hasilpemeriksaanlabdetail_id ,
            penjamin_id ,
            pasienadmisi_id ,
            verifikasitagihan_id ,
            jurnalrekening_id ,
            instruksitindakan_id ,
            tgl_tindakan ,
            tarif_rsakomodasi ,
            tarif_medis ,
            tarif_paramedis ,
            tarif_bhp ,
            tarif_satuan ,
            tarif_tindakan ,
            tarifcyto_tindakan ,
            satuan_tindakan ,
            qty_tindakan ,
            cyto_tindakan ,
            dokterpenanggungjawab_id ,
            dokterpelaksana_id ,
            dokteranastesi_id ,
            dokterdelegasi_id ,
            bidan1_id ,
            bidan2_id ,
            perawat1_id ,
            perawat2_id ,
            discount_tindakan ,
            pembebasan_tindakan ,
            subsidiasuransi_tindakan ,
            subsidipemerintah_tindakan ,
            subsisidirumahsakit_tindakan ,
            uangditerima_tindakan ,
            keterangantindakan ,
            pembulatan ,
            implementasi_id ,
            is_dilakukan ,
            pemakaianambulan_id ,
            is_penatajasa ,
            additional_riwayat ,
            is_valid ,
            kamarruangan_id ,
            kamartempattidur_id ,
            penyulit_tindakan ,
            tarifpenyulit_tindakan ,
            additional_data ,
            created_date ,
            created_by ,
            modified_count,
            last_modified_date,
            last_modified_by,
            is_deleted,
            is_active,
            deleted_date,
            deleted_by,
            keterangan,
            no_tindakanpelayanan,
                        tarif_dijamin,
                        tarif_dibayarkan
        )VALUES(
            OLD.tindakanpelayanan_id ,
            OLD.shift_id ,
            OLD.kelaspelayanan_id ,
            OLD.kelastanggungan_id ,
            OLD.pasien_id ,
            OLD.rencanaoperasi_id ,
            OLD.instalasi_id ,
            OLD.daftartindakan_id ,
            OLD.alatmedis_id ,
            OLD.tipepaket_id ,
            OLD.tindakansudahbayar_id ,
            OLD.carabayar_id ,
            OLD.pendaftaran_id ,
            OLD.hasilpemeriksaanrad_id ,
            OLD.jeniskasuspenyakit_id ,
            OLD.hasilpemeriksaanrm_id ,
            OLD.ruangan_id ,
            OLD.konsulpoli_id ,
            OLD.pasienmasukpenunjang_id ,
            OLD.hasilpemeriksaanlabdetail_id ,
            OLD.penjamin_id ,
            OLD.pasienadmisi_id ,
            OLD.verifikasitagihan_id ,
            OLD.jurnalrekening_id ,
            OLD.instruksitindakan_id ,
            OLD.tgl_tindakan ,
            OLD.tarif_rsakomodasi ,
            OLD.tarif_medis ,
            OLD.tarif_paramedis ,
            OLD.tarif_bhp ,
            OLD.tarif_satuan ,
            -1 * OLD.tarif_tindakan ,
            OLD.tarifcyto_tindakan ,
            OLD.satuan_tindakan ,
            -1 * OLD.qty_tindakan ,
            OLD.cyto_tindakan ,
            OLD.dokterpenanggungjawab_id ,
            OLD.dokterpelaksana_id ,
            OLD.dokteranastesi_id ,
            OLD.dokterdelegasi_id ,
            OLD.bidan1_id ,
            OLD.bidan2_id ,
            OLD.perawat1_id ,
            OLD.perawat2_id ,
            OLD.discount_tindakan ,
            OLD.pembebasan_tindakan ,
            OLD.subsidiasuransi_tindakan ,
            OLD.subsidipemerintah_tindakan ,
            OLD.subsisidirumahsakit_tindakan ,
            OLD.uangditerima_tindakan ,
            OLD.keterangantindakan ,
            OLD.pembulatan ,
            OLD.implementasi_id ,
            OLD.is_dilakukan ,
            OLD.pemakaianambulan_id ,
            OLD.is_penatajasa ,
            OLD.additional_riwayat ,
            OLD.is_valid ,
            OLD.kamarruangan_id ,
            OLD.kamartempattidur_id ,
            OLD.penyulit_tindakan ,
            OLD.tarifpenyulit_tindakan ,
            OLD.additional_data ,
            OLD.created_date ,
            OLD.created_by ,
            OLD.modified_count,
            OLD.last_modified_date,
            OLD.last_modified_by,
            OLD.is_deleted,
            OLD.is_active,
            OLD.deleted_date,
            OLD.deleted_by,
            v_keterangan,
            OLD.no_tindakanpelayanan,
                        0,
                        0
        );
            RETURN NEW;
            END IF;
            
            IF (old.tindakansudahbayar_id is null AND OLD.is_deleted= FALSE)
                THEN    
            -- INSERT table history tindakanpelayanan_r menjadi ACCRUAL REVERSAL(-) setelah BILLING CANCEL
                INSERT INTO tindakanpelayanan_r (       
                    tindakanpelayanan_id ,
                    shift_id ,
                    kelaspelayanan_id ,
                    kelastanggungan_id ,
                    pasien_id ,
                    rencanaoperasi_id ,
                    instalasi_id ,
                    daftartindakan_id ,
                    alatmedis_id ,
                    tipepaket_id ,
                    tindakansudahbayar_id ,
                    carabayar_id ,
                    pendaftaran_id ,
                    hasilpemeriksaanrad_id ,
                    jeniskasuspenyakit_id ,
                    hasilpemeriksaanrm_id ,
                    ruangan_id ,
                    konsulpoli_id ,
                    pasienmasukpenunjang_id ,
                    hasilpemeriksaanlabdetail_id ,
                    penjamin_id ,
                    pasienadmisi_id ,
                    verifikasitagihan_id ,
                    jurnalrekening_id ,
                    instruksitindakan_id ,
                    tgl_tindakan ,
                    tarif_rsakomodasi ,
                    tarif_medis ,
                    tarif_paramedis ,
                    tarif_bhp ,
                    tarif_satuan ,
                    tarif_tindakan ,
                    tarifcyto_tindakan ,
                    satuan_tindakan ,
                    qty_tindakan ,
                    cyto_tindakan ,
                    dokterpenanggungjawab_id ,
                    dokterpelaksana_id ,
                    dokteranastesi_id ,
                    dokterdelegasi_id ,
                    bidan1_id ,
                    bidan2_id ,
                    perawat1_id ,
                    perawat2_id ,
                    discount_tindakan ,
                    pembebasan_tindakan ,
                    subsidiasuransi_tindakan ,
                    subsidipemerintah_tindakan ,
                    subsisidirumahsakit_tindakan ,
                    uangditerima_tindakan ,
                    keterangantindakan ,
                    pembulatan ,
                    implementasi_id ,
                    is_dilakukan ,
                    pemakaianambulan_id ,
                    is_penatajasa ,
                    additional_riwayat ,
                    is_valid ,
                    kamarruangan_id ,
                    kamartempattidur_id ,
                    penyulit_tindakan ,
                    tarifpenyulit_tindakan ,
                    additional_data ,
                    created_date ,
                    created_by ,
                    modified_count,
                    last_modified_date,
                    last_modified_by,
                    is_deleted,
                    is_active,
                    deleted_date,
                    deleted_by,
                    keterangan,
                    no_tindakanpelayanan,
                                        tarif_dijamin,
                                        tarif_dibayarkan
                )VALUES(
                    OLD.tindakanpelayanan_id ,
                    OLD.shift_id ,
                    OLD.kelaspelayanan_id ,
                    OLD.kelastanggungan_id ,
                    OLD.pasien_id ,
                    OLD.rencanaoperasi_id ,
                    OLD.instalasi_id ,
                    OLD.daftartindakan_id ,
                    OLD.alatmedis_id ,
                    OLD.tipepaket_id ,
                    OLD.tindakansudahbayar_id ,
                    OLD.carabayar_id ,
                    OLD.pendaftaran_id ,
                    OLD.hasilpemeriksaanrad_id ,
                    OLD.jeniskasuspenyakit_id ,
                    OLD.hasilpemeriksaanrm_id ,
                    OLD.ruangan_id ,
                    OLD.konsulpoli_id ,
                    OLD.pasienmasukpenunjang_id ,
                    OLD.hasilpemeriksaanlabdetail_id ,
                    OLD.penjamin_id ,
                    OLD.pasienadmisi_id ,
                    OLD.verifikasitagihan_id ,
                    OLD.jurnalrekening_id ,
                    OLD.instruksitindakan_id ,
                    OLD.tgl_tindakan ,
                    OLD.tarif_rsakomodasi ,
                    OLD.tarif_medis ,
                    OLD.tarif_paramedis ,
                    OLD.tarif_bhp ,
                    OLD.tarif_satuan ,
                    -1 * OLD.tarif_tindakan ,
                    OLD.tarifcyto_tindakan ,
                    OLD.satuan_tindakan ,
                    -1 * OLD.qty_tindakan ,
                    OLD.cyto_tindakan ,
                    OLD.dokterpenanggungjawab_id ,
                    OLD.dokterpelaksana_id ,
                    OLD.dokteranastesi_id ,
                    OLD.dokterdelegasi_id ,
                    OLD.bidan1_id ,
                    OLD.bidan2_id ,
                    OLD.perawat1_id ,
                    OLD.perawat2_id ,
                    OLD.discount_tindakan ,
                    OLD.pembebasan_tindakan ,
                    OLD.subsidiasuransi_tindakan ,
                    OLD.subsidipemerintah_tindakan ,
                    OLD.subsisidirumahsakit_tindakan ,
                    OLD.uangditerima_tindakan ,
                    OLD.keterangantindakan ,
                    OLD.pembulatan ,
                    OLD.implementasi_id ,
                    OLD.is_dilakukan ,
                    OLD.pemakaianambulan_id ,
                    OLD.is_penatajasa ,
                    OLD.additional_riwayat ,
                    OLD.is_valid ,
                    OLD.kamarruangan_id ,
                    OLD.kamartempattidur_id ,
                    OLD.penyulit_tindakan ,
                    OLD.tarifpenyulit_tindakan ,
                    OLD.additional_data ,
                    OLD.created_date ,
                    OLD.created_by ,
                    OLD.modified_count,
                    OLD.last_modified_date,
                    OLD.last_modified_by,
                    OLD.is_deleted,
                    OLD.is_active,
                    OLD.deleted_date,
                    OLD.deleted_by,
                    'ACCRUAL REVERSAL',
                    OLD.no_tindakanpelayanan,
                                        OLD.tarif_dijamin,
                                        OLD.tarif_dibayarkan
                );
        
            INSERT INTO tindakanpelayanan_r (       
                        tindakanpelayanan_id ,
                        shift_id ,
                        kelaspelayanan_id ,
                        kelastanggungan_id ,
                        pasien_id ,
                        rencanaoperasi_id ,
                        instalasi_id ,
                        daftartindakan_id ,
                        alatmedis_id ,
                        tipepaket_id ,
                        tindakansudahbayar_id ,
                        carabayar_id ,
                        pendaftaran_id ,
                        hasilpemeriksaanrad_id ,
                        jeniskasuspenyakit_id ,
                        hasilpemeriksaanrm_id ,
                        ruangan_id ,
                        konsulpoli_id ,
                        pasienmasukpenunjang_id ,
                        hasilpemeriksaanlabdetail_id ,
                        penjamin_id ,
                        pasienadmisi_id ,
                        verifikasitagihan_id ,
                        jurnalrekening_id ,
                        instruksitindakan_id ,
                        tgl_tindakan ,
                        tarif_rsakomodasi ,
                        tarif_medis ,
                        tarif_paramedis ,
                        tarif_bhp ,
                        tarif_satuan ,
                        tarif_tindakan ,
                        tarifcyto_tindakan ,
                        satuan_tindakan ,
                        qty_tindakan ,
                        cyto_tindakan ,
                        dokterpenanggungjawab_id ,
                        dokterpelaksana_id ,
                        dokteranastesi_id ,
                        dokterdelegasi_id ,
                        bidan1_id ,
                        bidan2_id ,
                        perawat1_id ,
                        perawat2_id ,
                        discount_tindakan ,
                        pembebasan_tindakan ,
                        subsidiasuransi_tindakan ,
                        subsidipemerintah_tindakan ,
                        subsisidirumahsakit_tindakan ,
                        uangditerima_tindakan ,
                        keterangantindakan ,
                        pembulatan ,
                        implementasi_id ,
                        is_dilakukan ,
                        pemakaianambulan_id ,
                        is_penatajasa ,
                        additional_riwayat ,
                        is_valid ,
                        kamarruangan_id ,
                        kamartempattidur_id ,
                        penyulit_tindakan ,
                        tarifpenyulit_tindakan ,
                        additional_data ,
                        created_date ,
                        created_by ,
                        modified_count,
                        last_modified_date,
                        last_modified_by,
                        is_deleted,
                        is_active,
                        deleted_date,
                        deleted_by,
                        keterangan,
                        no_tindakanpelayanan,
                                                tarif_dijamin,
                                                tarif_dibayarkan
                    )VALUES(
                        OLD.tindakanpelayanan_id ,
                        OLD.shift_id ,
                        OLD.kelaspelayanan_id ,
                        OLD.kelastanggungan_id ,
                        OLD.pasien_id ,
                        OLD.rencanaoperasi_id ,
                        OLD.instalasi_id ,
                        OLD.daftartindakan_id ,
                        OLD.alatmedis_id ,
                        OLD.tipepaket_id ,
                        OLD.tindakansudahbayar_id ,
                        OLD.carabayar_id ,
                        OLD.pendaftaran_id ,
                        OLD.hasilpemeriksaanrad_id ,
                        OLD.jeniskasuspenyakit_id ,
                        OLD.hasilpemeriksaanrm_id ,
                        OLD.ruangan_id ,
                        OLD.konsulpoli_id ,
                        OLD.pasienmasukpenunjang_id ,
                        OLD.hasilpemeriksaanlabdetail_id ,
                        OLD.penjamin_id ,
                        OLD.pasienadmisi_id ,
                        OLD.verifikasitagihan_id ,
                        OLD.jurnalrekening_id ,
                        OLD.instruksitindakan_id ,
                        OLD.tgl_tindakan ,
                        OLD.tarif_rsakomodasi ,
                        OLD.tarif_medis ,
                        OLD.tarif_paramedis ,
                        OLD.tarif_bhp ,
                        OLD.tarif_satuan ,
                        OLD.tarif_tindakan ,
                        OLD.tarifcyto_tindakan ,
                        OLD.satuan_tindakan ,
                        OLD.qty_tindakan ,
                        OLD.cyto_tindakan ,
                        OLD.dokterpenanggungjawab_id ,
                        OLD.dokterpelaksana_id ,
                        OLD.dokteranastesi_id ,
                        OLD.dokterdelegasi_id ,
                        OLD.bidan1_id ,
                        OLD.bidan2_id ,
                        OLD.perawat1_id ,
                        OLD.perawat2_id ,
                        OLD.discount_tindakan ,
                        OLD.pembebasan_tindakan ,
                        OLD.subsidiasuransi_tindakan ,
                        OLD.subsidipemerintah_tindakan ,
                        OLD.subsisidirumahsakit_tindakan ,
                        OLD.uangditerima_tindakan ,
                        OLD.keterangantindakan ,
                        OLD.pembulatan ,
                        OLD.implementasi_id ,
                        OLD.is_dilakukan ,
                        OLD.pemakaianambulan_id ,
                        OLD.is_penatajasa ,
                        OLD.additional_riwayat ,
                        OLD.is_valid ,
                        OLD.kamarruangan_id ,
                        OLD.kamartempattidur_id ,
                        OLD.penyulit_tindakan ,
                        OLD.tarifpenyulit_tindakan ,
                        OLD.additional_data ,
                        OLD.created_date ,
                        OLD.created_by ,
                        OLD.modified_count,
                        OLD.last_modified_date,
                        OLD.last_modified_by,
                        OLD.is_deleted,
                        OLD.is_active,
                        OLD.deleted_date,
                        OLD.deleted_by,
                        'ACCRUAL',
                        OLD.no_tindakanpelayanan,
                                                NEW.tarif_dijamin,
                                                NEW.tarif_dibayarkan
                    );

            
    END IF;
    
    
    

    RETURN NEW;

END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

        $this->execute('ALTER FUNCTION "public"."tindakanpelayanan_r_update"() OWNER TO "postgres";');

        $this->execute("
            CREATE OR REPLACE FUNCTION \"public\".\"tindakansudahbayar_t_cancel\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$ 
    
DECLARE
        v_keterangan VARCHAR;
    BEGIN
        IF(NEW.is_deleted IS TRUE)
        THEN
            -- INSERT table history tindakanpelayanan_r menjadi ACCRUAL(+), jika is_deleted=TRUE
            INSERT INTO tindakanpelayanan_r (       
                tindakanpelayanan_id ,
                shift_id ,
                kelaspelayanan_id ,
                kelastanggungan_id ,
                pasien_id ,
                rencanaoperasi_id ,
                instalasi_id ,
                daftartindakan_id ,
                alatmedis_id ,
                tipepaket_id ,
                tindakansudahbayar_id ,
                carabayar_id ,
                pendaftaran_id ,
                hasilpemeriksaanrad_id ,
                jeniskasuspenyakit_id ,
                hasilpemeriksaanrm_id ,
                ruangan_id ,
                konsulpoli_id ,
                pasienmasukpenunjang_id ,
                hasilpemeriksaanlabdetail_id ,
                penjamin_id ,
                pasienadmisi_id ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                instruksitindakan_id ,
                tgl_tindakan ,
                tarif_rsakomodasi ,
                tarif_medis ,
                tarif_paramedis ,
                tarif_bhp ,
                tarif_satuan ,
                tarif_tindakan ,
                tarifcyto_tindakan ,
                satuan_tindakan ,
                qty_tindakan ,
                cyto_tindakan ,
                dokterpenanggungjawab_id ,
                dokterpelaksana_id ,
                dokteranastesi_id ,
                dokterdelegasi_id ,
                bidan1_id ,
                bidan2_id ,
                perawat1_id ,
                perawat2_id ,
                discount_tindakan ,
                pembebasan_tindakan ,
                subsidiasuransi_tindakan ,
                subsidipemerintah_tindakan ,
                subsisidirumahsakit_tindakan ,
                uangditerima_tindakan ,
                keterangantindakan ,
                pembulatan ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_penatajasa ,
                additional_riwayat ,
                is_valid ,
                kamarruangan_id ,
                kamartempattidur_id ,
                penyulit_tindakan ,
                tarifpenyulit_tindakan ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date ,
                deleted_by ,
                keterangan,
                no_tindakanpelayanan
                )
                SELECT
                tindakanpelayanan_id ,
                shift_id ,
                kelaspelayanan_id ,
                kelastanggungan_id ,
                pasien_id ,
                rencanaoperasi_id ,
                instalasi_id ,
                daftartindakan_id ,
                alatmedis_id ,
                tipepaket_id ,
                NEW.tindakansudahbayar_id ,
                carabayar_id ,
                pendaftaran_id ,
                hasilpemeriksaanrad_id ,
                jeniskasuspenyakit_id ,
                hasilpemeriksaanrm_id ,
                ruangan_id ,
                konsulpoli_id ,
                pasienmasukpenunjang_id ,
                hasilpemeriksaanlabdetail_id ,
                penjamin_id ,
                pasienadmisi_id ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                instruksitindakan_id ,
                tgl_tindakan ,
                tarif_rsakomodasi ,
                tarif_medis ,
                tarif_paramedis ,
                tarif_bhp ,
                tarif_satuan ,
                tarif_tindakan ,
                tarifcyto_tindakan ,
                satuan_tindakan ,
                qty_tindakan ,
                cyto_tindakan ,
                dokterpenanggungjawab_id ,
                dokterpelaksana_id ,
                dokteranastesi_id ,
                dokterdelegasi_id ,
                bidan1_id ,
                bidan2_id ,
                perawat1_id ,
                perawat2_id ,
                discount_tindakan ,
                pembebasan_tindakan ,
                subsidiasuransi_tindakan ,
                subsidipemerintah_tindakan ,
                subsisidirumahsakit_tindakan ,
                uangditerima_tindakan ,
                keterangantindakan ,
                pembulatan ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_penatajasa ,
                additional_riwayat ,
                is_valid ,
                kamarruangan_id ,
                kamartempattidur_id ,
                penyulit_tindakan ,
                tarifpenyulit_tindakan ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date ,
                deleted_by ,
                'ACCRUAL',
                no_tindakanpelayanan
                FROM tindakanpelayanan_t
            WHERE tindakanpelayanan_id = NEW.tindakanpelayanan_id;
        
        
            -- INSERT table history tindakanpelayanan_r menjadi BILLING CANCEL(-), jika is_deleted=TRUE
                INSERT INTO tindakanpelayanan_r (       
                    tindakanpelayanan_id ,
                    shift_id ,
                    kelaspelayanan_id ,
                    kelastanggungan_id ,
                    pasien_id ,
                    rencanaoperasi_id ,
                    instalasi_id ,
                    daftartindakan_id ,
                    alatmedis_id ,
                    tipepaket_id ,
                    tindakansudahbayar_id ,
                    carabayar_id ,
                    pendaftaran_id ,
                    hasilpemeriksaanrad_id ,
                    jeniskasuspenyakit_id ,
                    hasilpemeriksaanrm_id ,
                    ruangan_id ,
                    konsulpoli_id ,
                    pasienmasukpenunjang_id ,
                    hasilpemeriksaanlabdetail_id ,
                    penjamin_id ,
                    pasienadmisi_id ,
                    verifikasitagihan_id ,
                    jurnalrekening_id ,
                    instruksitindakan_id ,
                    tgl_tindakan ,
                    tarif_rsakomodasi ,
                    tarif_medis ,
                    tarif_paramedis ,
                    tarif_bhp ,
                    tarif_satuan ,
                    tarif_tindakan ,
                    tarifcyto_tindakan ,
                    satuan_tindakan ,
                    qty_tindakan ,
                    cyto_tindakan ,
                    dokterpenanggungjawab_id ,
                    dokterpelaksana_id ,
                    dokteranastesi_id ,
                    dokterdelegasi_id ,
                    bidan1_id ,
                    bidan2_id ,
                    perawat1_id ,
                    perawat2_id ,
                    discount_tindakan ,
                    pembebasan_tindakan ,
                    subsidiasuransi_tindakan ,
                    subsidipemerintah_tindakan ,
                    subsisidirumahsakit_tindakan ,
                    uangditerima_tindakan ,
                    keterangantindakan ,
                    pembulatan ,
                    implementasi_id ,
                    is_dilakukan ,
                    pemakaianambulan_id ,
                    is_penatajasa ,
                    additional_riwayat ,
                    is_valid ,
                    kamarruangan_id ,
                    kamartempattidur_id ,
                    penyulit_tindakan ,
                    tarifpenyulit_tindakan ,
                    additional_data ,
                    created_date ,
                    created_by ,
                    modified_count ,
                    last_modified_date ,
                    last_modified_by ,
                    is_deleted ,
                    is_active ,
                    deleted_date ,
                    deleted_by ,
                    keterangan,
                    no_tindakanpelayanan,
                                        tarif_dijamin,
                                        tarif_dibayarkan
                    )
                    SELECT
                    tindakanpelayanan_id ,
                    shift_id ,
                    kelaspelayanan_id ,
                    kelastanggungan_id ,
                    pasien_id ,
                    rencanaoperasi_id ,
                    instalasi_id ,
                    daftartindakan_id ,
                    alatmedis_id ,
                    tipepaket_id ,
                    NEW.tindakansudahbayar_id ,
                    carabayar_id ,
                    pendaftaran_id ,
                    hasilpemeriksaanrad_id ,
                    jeniskasuspenyakit_id ,
                    hasilpemeriksaanrm_id ,
                    ruangan_id ,
                    konsulpoli_id ,
                    pasienmasukpenunjang_id ,
                    hasilpemeriksaanlabdetail_id ,
                    penjamin_id ,
                    pasienadmisi_id ,
                    verifikasitagihan_id ,
                    jurnalrekening_id ,
                    instruksitindakan_id ,
                    tgl_tindakan ,
                    tarif_rsakomodasi ,
                    tarif_medis ,
                    tarif_paramedis ,
                    tarif_bhp ,
                    tarif_satuan ,
                    -1 * tarif_tindakan ,
                    tarifcyto_tindakan ,
                    satuan_tindakan ,
                    -1 * qty_tindakan ,
                    cyto_tindakan ,
                    dokterpenanggungjawab_id ,
                    dokterpelaksana_id ,
                    dokteranastesi_id ,
                    dokterdelegasi_id ,
                    bidan1_id ,
                    bidan2_id ,
                    perawat1_id ,
                    perawat2_id ,
                    discount_tindakan ,
                    pembebasan_tindakan ,
                    subsidiasuransi_tindakan ,
                    subsidipemerintah_tindakan ,
                    subsisidirumahsakit_tindakan ,
                    uangditerima_tindakan ,
                    keterangantindakan ,
                    pembulatan ,
                    implementasi_id ,
                    is_dilakukan ,
                    pemakaianambulan_id ,
                    is_penatajasa ,
                    additional_riwayat ,
                    is_valid ,
                    kamarruangan_id ,
                    kamartempattidur_id ,
                    penyulit_tindakan ,
                    tarifpenyulit_tindakan ,
                    additional_data ,
                    created_date ,
                    created_by ,
                    modified_count ,
                    last_modified_date ,
                    last_modified_by ,
                    is_deleted ,
                    is_active ,
                    deleted_date ,
                    deleted_by ,
                    'BILLING CANCEL',
                    no_tindakanpelayanan,
                                        ((old.additional_data::json->>'data_dijamin')::json->>'dijamin')::float,
                                        ((old.additional_data::json->>'data_dijamin')::json->>'harusbayar')::float 
                    FROM tindakanpelayanan_t
                WHERE tindakanpelayanan_id = NEW.tindakanpelayanan_id;
                
    END IF;
    
    RETURN NEW;

END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

        $this->execute('ALTER FUNCTION "public"."tindakansudahbayar_t_cancel"() OWNER TO "postgres";');

        $this->execute("
            CREATE OR REPLACE FUNCTION \"public\".\"tindakansudahbayar_t_insert\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$

BEGIN
        -- INSERT table history tindakanpelayanan_r BILLING(+)
        INSERT INTO tindakanpelayanan_r (       
            tindakanpelayanan_id ,
            shift_id ,
            kelaspelayanan_id ,
            kelastanggungan_id ,
            pasien_id ,
            rencanaoperasi_id ,
            instalasi_id ,
            daftartindakan_id ,
            alatmedis_id ,
            tipepaket_id ,
            tindakansudahbayar_id ,
            carabayar_id ,
            pendaftaran_id ,
            hasilpemeriksaanrad_id ,
            jeniskasuspenyakit_id ,
            hasilpemeriksaanrm_id ,
            ruangan_id ,
            konsulpoli_id ,
            pasienmasukpenunjang_id ,
            hasilpemeriksaanlabdetail_id ,
            penjamin_id ,
            pasienadmisi_id ,
            verifikasitagihan_id ,
            jurnalrekening_id ,
            instruksitindakan_id ,
            tgl_tindakan ,
            tarif_rsakomodasi ,
            tarif_medis ,
            tarif_paramedis ,
            tarif_bhp ,
            tarif_satuan ,
            tarif_tindakan ,
            tarifcyto_tindakan ,
            satuan_tindakan ,
            qty_tindakan ,
            cyto_tindakan ,
            dokterpenanggungjawab_id ,
            dokterpelaksana_id ,
            dokteranastesi_id ,
            dokterdelegasi_id ,
            bidan1_id ,
            bidan2_id ,
            perawat1_id ,
            perawat2_id ,
            discount_tindakan ,
            pembebasan_tindakan ,
            subsidiasuransi_tindakan ,
            subsidipemerintah_tindakan ,
            subsisidirumahsakit_tindakan ,
            uangditerima_tindakan ,
            keterangantindakan ,
            pembulatan ,
            implementasi_id ,
            is_dilakukan ,
            pemakaianambulan_id ,
            is_penatajasa ,
            additional_riwayat ,
            is_valid ,
            kamarruangan_id ,
            kamartempattidur_id ,
            penyulit_tindakan ,
            tarifpenyulit_tindakan ,
            additional_data ,
            created_date ,
            created_by ,
            keterangan,
            no_tindakanpelayanan,
            tarif_dijamin,
            tarif_dibayarkan
        )
        SELECT  
            tindakanpelayanan_id ,
            shift_id ,
            kelaspelayanan_id ,
            kelastanggungan_id ,
            pasien_id ,
            rencanaoperasi_id ,
            instalasi_id ,
            daftartindakan_id ,
            alatmedis_id ,
            tipepaket_id ,
            NEW.tindakansudahbayar_id,
            carabayar_id ,
            pendaftaran_id ,
            hasilpemeriksaanrad_id ,
            jeniskasuspenyakit_id ,
            hasilpemeriksaanrm_id ,
            ruangan_id ,
            konsulpoli_id ,
            pasienmasukpenunjang_id ,
            hasilpemeriksaanlabdetail_id ,
            penjamin_id ,
            pasienadmisi_id ,
            verifikasitagihan_id ,
            jurnalrekening_id ,
            instruksitindakan_id ,
            tgl_tindakan ,
            tarif_rsakomodasi ,
            tarif_medis ,
            tarif_paramedis ,
            tarif_bhp ,
            tarif_satuan ,
            tarif_tindakan ,
            tarifcyto_tindakan ,
            satuan_tindakan ,
            qty_tindakan ,
            cyto_tindakan ,
            dokterpenanggungjawab_id ,
            dokterpelaksana_id ,
            dokteranastesi_id ,
            dokterdelegasi_id ,
            bidan1_id ,
            bidan2_id ,
            perawat1_id ,
            perawat2_id ,
            discount_tindakan ,
            pembebasan_tindakan ,
            subsidiasuransi_tindakan ,
            subsidipemerintah_tindakan ,
            subsisidirumahsakit_tindakan ,
            uangditerima_tindakan ,
            keterangantindakan ,
            pembulatan ,
            implementasi_id ,
            is_dilakukan ,
            pemakaianambulan_id ,
            is_penatajasa ,
            additional_riwayat ,
            is_valid ,
            kamarruangan_id ,
            kamartempattidur_id ,
            penyulit_tindakan ,
            tarifpenyulit_tindakan ,
            additional_data ,
            created_date ,
            created_by ,
            'BILLING',
            no_tindakanpelayanan,
                        ((NEW.additional_data::json->>'data_dijamin')::json->>'dijamin')::float,
                        ((NEW.additional_data::json->>'data_dijamin')::json->>'harusbayar')::float 
    FROM tindakanpelayanan_t
    WHERE tindakanpelayanan_id = NEW.tindakanpelayanan_id;
    
    RETURN NEW;

END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

        $this->execute('ALTER FUNCTION "public"."tindakansudahbayar_t_insert"() OWNER TO "postgres";');
        

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m210321_074305_oddo_20200319_functionrekap cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m210321_074305_oddo_20200319_functionrekap cannot be reverted.\n";

        return false;
    }
    */
}
