<?php

use yii\db\Migration;

/**
 * Class m210222_152323_oddo_20210222_penyesuaiantrigger
 */
class m210222_152323_oddo_20210222_penyesuaiantrigger extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->execute("
            CREATE OR REPLACE FUNCTION \"public\".\"obatalkespasien_r_insert\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$
DECLARE

    
BEGIN
    NEW.hargajual_oa = NEW.hargasatuan_oa * NEW.qty_oa;
        
        -- INSERT table history obatalkespasien_r
        INSERT INTO obatalkespasien_r (     
        obatalkespasien_id ,
        sumberdana_id ,
        racikan_id ,
        returresepdetail_id ,
        tipepaket_id ,
        ruangan_id ,
        carabayar_id ,
        pegawai_id ,
        daftartindakan_id ,
        tindakanpelayanan_id ,
        satuankecil_id ,
        shift_id ,
        pendaftaran_id ,
        obatalkes_id ,
        pasien_id ,
        penjamin_id ,
        kelaspelayanan_id ,
        pasienanastesi_id ,
        pasienmasukpenunjang_id ,
        pasienadmisi_id ,
        obatsudahbayar_id ,
        penjualanresep_id ,
        tglpelayanan ,
        r ,
        rke ,
        permintaan_oa ,
        jmlkemasan_oa ,
        kekuatan_oa ,
        satuankekuatan_oa ,
        qty_oa ,
        hargasatuan_oa ,
        signa_oa ,
        harganetto_oa ,
        hargajual_oa , 
        etiket ,
        jmlexposerad ,
        kontrasrad ,
        biayaservice ,
        biayakonseling ,
        jasadokterresep ,
        biayakemasan ,
        biayaadministrasi ,
        tarifcyto ,
        discount , 
        subsidiasuransi ,
        subsidipemerintah ,
        subsidirs ,
        iurbiaya ,
        oa ,
        pembulatan ,
        verifikasitagihan_id ,
        jurnalrekening_id ,
        permohonanoadetail_id ,
        persenppnjual ,
        resepturdetail_id ,
        nilaippnjual ,
        perawat1_id ,
        perawat2_id ,
        instruksitindakanbmhp_id ,
        implementasi_id ,
        is_dilakukan ,
        pemakaianambulan_id ,
        is_jurnal ,
        konfigmargindetail_id ,
        qty_konversi ,
        is_penatajasa ,
        det ,
        status_bmhp ,
        det_konversi ,
        signa ,
        additional_data ,
        created_date ,
        created_by ,
        modified_count ,
        last_modified_date ,
        last_modified_by ,
        is_deleted ,
        is_active ,
        deleted_date , 
        deleted_by ,
        keterangan,
        no_obatalkespasien,
                tarif_dijamin,
                tarif_dibayarkan
        )VALUES(
        NEW.obatalkespasien_id ,
        NEW.sumberdana_id ,
        NEW.racikan_id ,
        NEW.returresepdetail_id ,
        NEW.tipepaket_id ,
        NEW.ruangan_id ,
        NEW.carabayar_id ,
        NEW.pegawai_id ,
        NEW.daftartindakan_id ,
        NEW.tindakanpelayanan_id ,
        NEW.satuankecil_id ,
        NEW.shift_id ,
        NEW.pendaftaran_id ,
        NEW.obatalkes_id ,
        NEW.pasien_id ,
        NEW.penjamin_id ,
        NEW.kelaspelayanan_id ,
        NEW.pasienanastesi_id ,
        NEW.pasienmasukpenunjang_id ,
        NEW.pasienadmisi_id ,
        NEW.obatsudahbayar_id ,
        NEW.penjualanresep_id ,
        NEW.tglpelayanan ,
        NEW.r ,
        NEW.rke ,
        NEW.permintaan_oa ,
        NEW.jmlkemasan_oa ,
        NEW.kekuatan_oa ,
        NEW.satuankekuatan_oa ,
        NEW.qty_oa ,
        NEW.hargasatuan_oa ,
        NEW.signa_oa ,
        NEW.harganetto_oa ,
                CASE
                    WHEN NEW.det <> 0  THEN NEW.hargasatuan_oa * NEW.det
                    WHEN NEW.det = 0 OR NEW.det IS NULL THEN  NEW.hargasatuan_oa * NEW.qty_oa 
                END,    
        NEW.etiket ,
        NEW.jmlexposerad ,
        NEW.kontrasrad ,
        NEW.biayaservice ,
        NEW.biayakonseling ,
        NEW.jasadokterresep ,
        NEW.biayakemasan ,
        NEW.biayaadministrasi ,
        NEW.tarifcyto ,
        NEW.discount , 
        NEW.subsidiasuransi ,
        NEW.subsidipemerintah ,
        NEW.subsidirs ,
        NEW.iurbiaya ,
        NEW.oa ,
        NEW.pembulatan ,
        NEW.verifikasitagihan_id ,
        NEW.jurnalrekening_id ,
        NEW.permohonanoadetail_id ,
        NEW.persenppnjual ,
        NEW.resepturdetail_id ,
        NEW.nilaippnjual ,
        NEW.perawat1_id ,
        NEW.perawat2_id ,
        NEW.instruksitindakanbmhp_id ,
        NEW.implementasi_id ,
        NEW.is_dilakukan ,
        NEW.pemakaianambulan_id ,
        NEW.is_jurnal ,
        NEW.konfigmargindetail_id ,
        NEW.qty_konversi ,
        NEW.is_penatajasa ,
        NEW.det ,
        NEW.status_bmhp ,
        NEW.det_konversi ,
        NEW.signa ,
        NEW.additional_data ,
        NEW.created_date ,
        NEW.created_by ,
        NEW.modified_count ,
        NEW.last_modified_date ,
        NEW.last_modified_by ,
        NEW.is_deleted ,
        NEW.is_active ,
        NEW.deleted_date , 
        NEW.deleted_by ,
        'ACCRUAL',
        NEW.no_obatalkespasien,
                NEW.tarif_dijamin,
                NEW.tarif_dibayarkan
        );

    RETURN NEW;
END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

        $this->execute('ALTER FUNCTION "public"."obatalkespasien_r_insert"() OWNER TO "postgres";');

        $this->execute("
            CREATE OR REPLACE FUNCTION \"public\".\"obatalkespasien_r_update\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$ 
    
DECLARE
        v_keterangan VARCHAR;
BEGIN
        IF((NEW.is_deleted IS TRUE OR NEW.obatsudahbayar_id IS NOT NULL) AND OLD.is_deleted IS FALSE)
        THEN
                v_keterangan := 'ACCRUAL REVERSAL';
                --> INSERT table history obatalkespasien_r menjadi ACCRUAL REVERSAL(-)
                INSERT INTO obatalkespasien_r (     
                obatalkespasien_id ,
                sumberdana_id ,
                racikan_id ,
                returresepdetail_id ,
                tipepaket_id ,
                ruangan_id ,
                carabayar_id ,
                pegawai_id ,
                daftartindakan_id ,
                tindakanpelayanan_id ,
                satuankecil_id ,
                shift_id ,
                pendaftaran_id ,
                obatalkes_id ,
                pasien_id ,
                penjamin_id ,
                kelaspelayanan_id ,
                pasienanastesi_id ,
                pasienmasukpenunjang_id ,
                pasienadmisi_id ,
                obatsudahbayar_id ,
                penjualanresep_id ,
                tglpelayanan ,
                r ,
                rke ,
                permintaan_oa ,
                jmlkemasan_oa ,
                kekuatan_oa ,
                satuankekuatan_oa ,
                qty_oa ,
                hargasatuan_oa ,
                signa_oa ,
                harganetto_oa ,
                hargajual_oa , 
                etiket ,
                jmlexposerad ,
                kontrasrad ,
                biayaservice ,
                biayakonseling ,
                jasadokterresep ,
                biayakemasan ,
                biayaadministrasi ,
                tarifcyto ,
                discount , 
                subsidiasuransi ,
                subsidipemerintah ,
                subsidirs ,
                iurbiaya ,
                oa ,
                pembulatan ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                permohonanoadetail_id ,
                persenppnjual ,
                resepturdetail_id ,
                nilaippnjual ,
                perawat1_id ,
                perawat2_id ,
                instruksitindakanbmhp_id ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_jurnal ,
                konfigmargindetail_id ,
                qty_konversi ,
                is_penatajasa ,
                det ,
                status_bmhp ,
                det_konversi ,
                signa ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date , 
                deleted_by ,
                keterangan,
                no_obatalkespasien,
                                tarif_dijamin,
                                tarif_dibayarkan
            )VALUES(
                OLD.obatalkespasien_id ,
                OLD.sumberdana_id ,
                OLD.racikan_id ,
                OLD.returresepdetail_id ,
                OLD.tipepaket_id ,
                OLD.ruangan_id ,
                OLD.carabayar_id ,
                OLD.pegawai_id ,
                OLD.daftartindakan_id ,
                OLD.tindakanpelayanan_id ,
                OLD.satuankecil_id ,
                OLD.shift_id ,
                OLD.pendaftaran_id ,
                OLD.obatalkes_id ,
                OLD.pasien_id ,
                OLD.penjamin_id ,
                OLD.kelaspelayanan_id ,
                OLD.pasienanastesi_id ,
                OLD.pasienmasukpenunjang_id ,
                OLD.pasienadmisi_id ,
                OLD.obatsudahbayar_id ,
                OLD.penjualanresep_id ,
                OLD.tglpelayanan ,
                OLD.r ,
                OLD.rke ,
                OLD.permintaan_oa ,
                OLD.jmlkemasan_oa ,
                OLD.kekuatan_oa ,
                OLD.satuankekuatan_oa ,
                OLD.qty_oa ,
                -1 * OLD.hargasatuan_oa ,
                OLD.signa_oa ,
                -1 * OLD.harganetto_oa ,
                CASE
                                    WHEN OLD.det <> 0  THEN -1 * OLD.hargasatuan_oa * OLD.det
                                    WHEN OLD.det = 0 OR OLD.det IS NULL THEN  -1 * OLD.hargasatuan_oa * OLD.qty_oa 
                                END, 
                OLD.etiket ,
                -1 * OLD.jmlexposerad ,
                OLD.kontrasrad ,
                -1 * OLD.biayaservice ,
                -1 * OLD.biayakonseling ,
                -1 * OLD.jasadokterresep ,
                -1 * OLD.biayakemasan ,
                -1 * OLD.biayaadministrasi ,
                -1 * OLD.tarifcyto ,
                -1 * OLD.discount , 
                -1 * OLD.subsidiasuransi ,
                -1 * OLD.subsidipemerintah ,
                -1 * OLD.subsidirs ,
                -1 * OLD.iurbiaya ,
                OLD.oa ,
                -1 * OLD.pembulatan ,
                OLD.verifikasitagihan_id ,
                OLD.jurnalrekening_id ,
                OLD.permohonanoadetail_id ,
                OLD.persenppnjual ,
                OLD.resepturdetail_id ,
                -1 * OLD.nilaippnjual ,
                OLD.perawat1_id ,
                OLD.perawat2_id ,
                OLD.instruksitindakanbmhp_id ,
                OLD.implementasi_id ,
                OLD.is_dilakukan ,
                OLD.pemakaianambulan_id ,
                OLD.is_jurnal ,
                OLD.konfigmargindetail_id ,
                -1 * OLD.qty_konversi ,
                OLD.is_penatajasa ,
                OLD.det ,
                OLD.status_bmhp ,
                OLD.det_konversi ,
                OLD.signa ,
                OLD.additional_data ,
                OLD.created_date ,
                OLD.created_by ,
                OLD.modified_count ,
                OLD.last_modified_date ,
                OLD.last_modified_by ,
                OLD.is_deleted ,
                OLD.is_active ,
                OLD.deleted_date , 
                OLD.deleted_by ,
                v_keterangan,
                OLD.no_obatalkespasien,
                                0,
                                0
            );
        RETURN NEW;
        END IF;
            
            IF (OLD.obatsudahbayar_id is null and OLD.is_deleted is FALSE)
                THEN    
                -- INSERT table history obatalkespasien_r menjadi ACCRUAL REVERSAL(-) setelah BILLING CANCEL
                INSERT INTO obatalkespasien_r (     
                obatalkespasien_id ,
                sumberdana_id ,
                racikan_id ,
                returresepdetail_id ,
                tipepaket_id ,
                ruangan_id ,
                carabayar_id ,
                pegawai_id ,
                daftartindakan_id ,
                tindakanpelayanan_id ,
                satuankecil_id ,
                shift_id ,
                pendaftaran_id ,
                obatalkes_id ,
                pasien_id ,
                penjamin_id ,
                kelaspelayanan_id ,
                pasienanastesi_id ,
                pasienmasukpenunjang_id ,
                pasienadmisi_id ,
                obatsudahbayar_id ,
                penjualanresep_id ,
                tglpelayanan ,
                r ,
                rke ,
                permintaan_oa ,
                jmlkemasan_oa ,
                kekuatan_oa ,
                satuankekuatan_oa ,
                qty_oa ,
                hargasatuan_oa ,
                signa_oa ,
                harganetto_oa ,
                hargajual_oa , 
                etiket ,
                jmlexposerad ,
                kontrasrad ,
                biayaservice ,
                biayakonseling ,
                jasadokterresep ,
                biayakemasan ,
                biayaadministrasi ,
                tarifcyto ,
                discount , 
                subsidiasuransi ,
                subsidipemerintah ,
                subsidirs ,
                iurbiaya ,
                oa ,
                pembulatan ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                permohonanoadetail_id ,
                persenppnjual ,
                resepturdetail_id ,
                nilaippnjual ,
                perawat1_id ,
                perawat2_id ,
                instruksitindakanbmhp_id ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_jurnal ,
                konfigmargindetail_id ,
                qty_konversi ,
                is_penatajasa ,
                det ,
                status_bmhp ,
                det_konversi ,
                signa ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date , 
                deleted_by ,
                keterangan,
                no_obatalkespasien,
                                tarif_dijamin,
                                tarif_dibayarkan
            )VALUES(
                OLD.obatalkespasien_id ,
                OLD.sumberdana_id ,
                OLD.racikan_id ,
                OLD.returresepdetail_id ,
                OLD.tipepaket_id ,
                OLD.ruangan_id ,
                OLD.carabayar_id ,
                OLD.pegawai_id ,
                OLD.daftartindakan_id ,
                OLD.tindakanpelayanan_id ,
                OLD.satuankecil_id ,
                OLD.shift_id ,
                OLD.pendaftaran_id ,
                OLD.obatalkes_id ,
                OLD.pasien_id ,
                OLD.penjamin_id ,
                OLD.kelaspelayanan_id ,
                OLD.pasienanastesi_id ,
                OLD.pasienmasukpenunjang_id ,
                OLD.pasienadmisi_id ,
                OLD.obatsudahbayar_id ,
                OLD.penjualanresep_id ,
                OLD.tglpelayanan ,
                OLD.r ,
                OLD.rke ,
                OLD.permintaan_oa ,
                OLD.jmlkemasan_oa ,
                OLD.kekuatan_oa ,
                OLD.satuankekuatan_oa ,
                OLD.qty_oa ,
                -1 * OLD.hargasatuan_oa ,
                OLD.signa_oa ,
                -1 * OLD.harganetto_oa ,
                CASE
                                    WHEN OLD.det <> 0  THEN -1 * OLD.hargasatuan_oa * OLD.det
                                    WHEN OLD.det = 0 OR OLD.det IS NULL THEN  -1 * OLD.hargasatuan_oa * OLD.qty_oa 
                                END,  
                OLD.etiket ,
                -1 * OLD.jmlexposerad ,
                OLD.kontrasrad ,
                -1 * OLD.biayaservice ,
                -1 * OLD.biayakonseling ,
                -1 * OLD.jasadokterresep ,
                -1 * OLD.biayakemasan ,
                -1 * OLD.biayaadministrasi ,
                -1 * OLD.tarifcyto ,
                -1 * OLD.discount , 
                -1 * OLD.subsidiasuransi ,
                -1 * OLD.subsidipemerintah ,
                -1 * OLD.subsidirs ,
                -1 * OLD.iurbiaya ,
                OLD.oa ,
                -1 * OLD.pembulatan ,
                OLD.verifikasitagihan_id ,
                OLD.jurnalrekening_id ,
                OLD.permohonanoadetail_id ,
                OLD.persenppnjual ,
                OLD.resepturdetail_id ,
                -1 * OLD.nilaippnjual ,
                OLD.perawat1_id ,
                OLD.perawat2_id ,
                OLD.instruksitindakanbmhp_id ,
                OLD.implementasi_id ,
                OLD.is_dilakukan ,
                OLD.pemakaianambulan_id ,
                OLD.is_jurnal ,
                OLD.konfigmargindetail_id ,
                -1 * OLD.qty_konversi ,
                OLD.is_penatajasa ,
                OLD.det ,
                OLD.status_bmhp ,
                OLD.det_konversi ,
                OLD.signa ,
                OLD.additional_data ,
                OLD.created_date ,
                OLD.created_by ,
                OLD.modified_count ,
                OLD.last_modified_date ,
                OLD.last_modified_by ,
                OLD.is_deleted ,
                OLD.is_active ,
                OLD.deleted_date , 
                OLD.deleted_by ,
                'ACCRUAL REVERSAL',
                OLD.no_obatalkespasien,
                                -1 * OLD.tarif_dijamin,
                                -1 * OLD.tarif_dibayarkan
            );
        
            INSERT INTO obatalkespasien_r (     
                obatalkespasien_id ,
                sumberdana_id ,
                racikan_id ,
                returresepdetail_id ,
                tipepaket_id ,
                ruangan_id ,
                carabayar_id ,
                pegawai_id ,
                daftartindakan_id ,
                tindakanpelayanan_id ,
                satuankecil_id ,
                shift_id ,
                pendaftaran_id ,
                obatalkes_id ,
                pasien_id ,
                penjamin_id ,
                kelaspelayanan_id ,
                pasienanastesi_id ,
                pasienmasukpenunjang_id ,
                pasienadmisi_id ,
                obatsudahbayar_id ,
                penjualanresep_id ,
                tglpelayanan ,
                r ,
                rke ,
                permintaan_oa ,
                jmlkemasan_oa ,
                kekuatan_oa ,
                satuankekuatan_oa ,
                qty_oa ,
                hargasatuan_oa ,
                signa_oa ,
                harganetto_oa ,
                hargajual_oa , 
                etiket ,
                jmlexposerad ,
                kontrasrad ,
                biayaservice ,
                biayakonseling ,
                jasadokterresep ,
                biayakemasan ,
                biayaadministrasi ,
                tarifcyto ,
                discount , 
                subsidiasuransi ,
                subsidipemerintah ,
                subsidirs ,
                iurbiaya ,
                oa ,
                pembulatan ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                permohonanoadetail_id ,
                persenppnjual ,
                resepturdetail_id ,
                nilaippnjual ,
                perawat1_id ,
                perawat2_id ,
                instruksitindakanbmhp_id ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_jurnal ,
                konfigmargindetail_id ,
                qty_konversi ,
                is_penatajasa ,
                det ,
                status_bmhp ,
                det_konversi ,
                signa ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date , 
                deleted_by ,
                keterangan,
                no_obatalkespasien,
                                tarif_dijamin,
                                tarif_dibayarkan
            )VALUES(
                OLD.obatalkespasien_id ,
                OLD.sumberdana_id ,
                OLD.racikan_id ,
                OLD.returresepdetail_id ,
                OLD.tipepaket_id ,
                OLD.ruangan_id ,
                OLD.carabayar_id ,
                OLD.pegawai_id ,
                OLD.daftartindakan_id ,
                OLD.tindakanpelayanan_id ,
                OLD.satuankecil_id ,
                OLD.shift_id ,
                OLD.pendaftaran_id ,
                OLD.obatalkes_id ,
                OLD.pasien_id ,
                OLD.penjamin_id ,
                OLD.kelaspelayanan_id ,
                OLD.pasienanastesi_id ,
                OLD.pasienmasukpenunjang_id ,
                OLD.pasienadmisi_id ,
                OLD.obatsudahbayar_id ,
                OLD.penjualanresep_id ,
                OLD.tglpelayanan ,
                OLD.r ,
                OLD.rke ,
                OLD.permintaan_oa ,
                OLD.jmlkemasan_oa ,
                OLD.kekuatan_oa ,
                OLD.satuankekuatan_oa ,
                OLD.qty_oa ,
                OLD.hargasatuan_oa ,
                OLD.signa_oa ,
                OLD.harganetto_oa ,
                CASE
                                    WHEN NEW.det <> 0  THEN NEW.hargasatuan_oa * NEW.det
                                    WHEN NEW.det = 0 OR NEW.det IS NULL THEN NEW.hargasatuan_oa * NEW.qty_oa 
                                END,  
                OLD.etiket ,
                OLD.jmlexposerad ,
                OLD.kontrasrad ,
                OLD.biayaservice ,
                OLD.biayakonseling ,
                OLD.jasadokterresep ,
                OLD.biayakemasan ,
                OLD.biayaadministrasi ,
                OLD.tarifcyto ,
                OLD.discount , 
                OLD.subsidiasuransi ,
                OLD.subsidipemerintah ,
                OLD.subsidirs ,
                OLD.iurbiaya ,
                OLD.oa ,
                OLD.pembulatan ,
                OLD.verifikasitagihan_id ,
                OLD.jurnalrekening_id ,
                OLD.permohonanoadetail_id ,
                OLD.persenppnjual ,
                OLD.resepturdetail_id ,
                OLD.nilaippnjual ,
                OLD.perawat1_id ,
                OLD.perawat2_id ,
                OLD.instruksitindakanbmhp_id ,
                OLD.implementasi_id ,
                OLD.is_dilakukan ,
                OLD.pemakaianambulan_id ,
                OLD.is_jurnal ,
                OLD.konfigmargindetail_id ,
                OLD.qty_konversi ,
                OLD.is_penatajasa ,
                NEW.det ,
                OLD.status_bmhp ,
                OLD.det_konversi ,
                OLD.signa ,
                OLD.additional_data ,
                OLD.created_date ,
                OLD.created_by ,
                OLD.modified_count ,
                OLD.last_modified_date ,
                OLD.last_modified_by ,
                OLD.is_deleted ,
                OLD.is_active ,
                OLD.deleted_date , 
                OLD.deleted_by ,
                'ACCRUAL',
                OLD.no_obatalkespasien,
                                NEW.tarif_dijamin,
                                NEW.tarif_dibayarkan
            );  

END IF;

    RETURN NEW;

END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

        $this->execute('ALTER FUNCTION "public"."obatalkespasien_r_update"() OWNER TO "postgres";');

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m210222_152323_oddo_20210222_penyesuaiantrigger cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m210222_152323_oddo_20210222_penyesuaiantrigger cannot be reverted.\n";

        return false;
    }
    */
}
