<?php

use yii\db\Migration;

/**
 * Class m210426_020515_oddo_20210426_penyesuaianfunction
 */
class m210426_020515_oddo_20210426_penyesuaianfunction extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
    $this->execute("
        CREATE OR REPLACE FUNCTION \"public\".\"int_billing_r_insert\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$
    
        
BEGIN
-- INSERT table history pembayaran_r--
    INSERT INTO int_billing_r (     
        pembayaran_id,
        pendaftaran_id,
        pasienadmisi_id,
        total_tagihan,
        total_dibayar,
        total_dijamin,
        total_sisatagihan,
        total_kembalian,
        total_administrasi,
        total_pembulatan,
        total_pembebasan,
        penggunaan_uangmuka,
        pemberianpiutang_id,
        total_ditagihkan,
        total_tunai,
        total_nontunai,
        total_discount,
        total_discountpembayaran,
        catatan,
        additional_data,
        created_date,
        created_by,
        modified_count,
        last_modified_date,
        last_modified_by,
        is_deleted,
        is_active,
        deleted_date,
        deleted_by,
        keterangan  
        )VALUES(
        NEW.pembayaran_id ,
        NEW.pendaftaran_id ,
        NEW.pasienadmisi_id ,
        NEW.total_tagihan ,
        NEW.total_dibayar ,
        NEW.total_dijamin,
        NEW.total_sisatagihan ,
        NEW.total_kembalian ,
        NEW.total_administrasi ,
        NEW.total_pembulatan ,
        NEW.total_pembebasan ,
        NEW.penggunaan_uangmuka ,
        NEW.pemberianpiutang_id ,
        NEW.total_ditagihkan ,
        NEW.total_tunai ,
        NEW.total_nontunai,
        NEW.total_discount ,
        NEW.total_discountpembayaran ,
        NEW.catatan ,
        NEW.additional_data ,
        NEW.created_date ,
        NEW.created_by ,
        NEW.modified_count ,
        NEW.last_modified_date ,
        NEW.last_modified_by ,
        NEW.is_deleted ,
        NEW.is_active ,
        NEW.deleted_date ,
        NEW.deleted_by ,
        'RECEIPT'
        );

    RETURN NEW;

END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

    $this->execute('ALTER FUNCTION "public"."int_billing_r_insert"() OWNER TO "postgres";');

    $this->execute("
        CREATE OR REPLACE FUNCTION \"public\".\"no_pembayaranpelayanan_t\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$-- author yaya

DECLARE
    vId INTEGER := 1;  
    vPrefix VARCHAR;
    vLast VARCHAR;
    vYear VARCHAR;
    vMonth VARCHAR;
    vNomor VARCHAR;
        v_day VARCHAR;
        v_reset VARCHAR;
    paramJson VARCHAR;

  vTPembayaran FLOAT;
  vAdmin FLOAT;
  vNamaBkm VARCHAR;
    vShifId INTEGER;
  vKeterangan VARCHAR;
  vCaraPembayaran VARCHAR;
  vTandaBuktiBayarId INTEGER;
  vPegawaiId INTEGER;
  vDataObat VARCHAR;
  vDataTindakan VARCHAR;
  vIdPendaftaran INTEGER;
  vJumlahUangMuka INTEGER;
    vUangDiterima FLOAT;
  vIdPemakaianUang INTEGER;
    vUangKembalian FLOAT;
BEGIN
    SELECT date_part('DAY',now()) INTO v_day;
    
    IF(v_day = '1')
    THEN
        SELECT CONCAT(LPAD(CAST(COALESCE(CAST(RIGHT(MAX(last_number), 5) AS INT), 0) AS VARCHAR(5)), 5, '0'))
            INTO v_reset
        FROM penomoran_k WHERE penomoran_id = vId;
        
        IF(v_reset <> '00001')
        THEN
            UPDATE penomoran_k SET 
                last_generate = '00001'
            WHERE penomoran_id = vId;
        END IF;
        
    END IF;

 -- Untuk Penomoran 
    SELECT 
        prefix,
        date_part('YEAR',now()) as year, 
        date_part('month',now()) as month,
        (
            SELECT CONCAT(LPAD(CAST(COALESCE(CAST(RIGHT(MAX(last_number), 5) AS INT), 0) + 1 AS VARCHAR(5)), 5, '0')) last_no
                FROM penomoran_k where penomoran_id = vId
        )
    INTO
        vPrefix,
        vYear,
        vMonth,
        vLast
        
    FROM penomoran_k WHERE penomoran_id = vId;
    vNomor = vPrefix || vYear || vMonth || vLast;

    UPDATE penomoran_k SET
        last_number = vLast,
        last_generate = vNomor
    WHERE penomoran_id = vId;

    NEW.no_pembayaran = vNomor;
 -- End Penomoran

  -- NEW.total_bayartindakan := NEW.total_biayapelayanan - (NEW.total_subsidirs + NEW.total_subsidiasuransi + NEW.total_subsidipemerintah);
  NEW.total_iurbiaya := NEW.total_biayapelayanan - (NEW.total_subsidirs + NEW.total_subsidiasuransi + NEW.total_subsidipemerintah);
  NEW.total_terbayar := NEW.total_iurbiaya;
  NEW.total_sisatagihan = NEW.total_iurbiaya - NEW.total_bayartindakan;
  vUangKembalian := NEW.total_bayartindakan - NEW.total_iurbiaya;
  IF (NEW.total_bayartindakan > NEW.total_iurbiaya) THEN
      NEW.total_sisatagihan = 0;
  END IF;

  NEW.statusbayar = 349;
  NEW.is_lunas = FALSE;
    
  IF (NEW.total_iurbiaya > NEW.total_bayartindakan) THEN
      NEW.total_terbayar := NEW.total_bayartindakan;
            IF (vCaraPembayaran = '31') THEN
                    NEW.is_lunas = FALSE;
     END IF;
END IF;

  vIdPendaftaran := NEW.pendaftaran_id;
  paramJson := NEW.additional_data;  
    vDataObat := paramJson::json->>'obat';
  vDataTindakan := paramJson::json->>'tindakan';

  -- Insert ke  pembayaranpelayanan_t
  IF (json_array_length(vDataTindakan::json) > 0)  THEN
            INSERT INTO tindakansudahbayar_t (
                            pembayaranpelayanan_id,
                                                        pembayaran_id, 
                            tindakanpelayanan_id, 
                            daftartindakan_id, 
                            ruangan_id,
                            qty_tindakan,
                            jmlbiaya_tindakan,
                            jmlsubsidi_asuransi,
                            jmlsubsidi_pemerintah,
                            jmlsubsidi_rs,
                            jmliur_biaya,
                            jml_pembebasan,
                            jmlbayar_tindakan,
                            jml_sisabayar_tindakan,
                            tipepaket_id,
                            pembulatan,
                            additional_data,
                            created_by
         ) SELECT 
                            NEW.pembayaranpelayanan_id as pembayaranpelayanan_id, 
                            NEW.pembayaran_id as pembayaran_id, 
                            tindakanpelayanan_id, 
                            daftartindakan_id, 
                            ruangan_id,
                            qty_tindakan,
                            jmlbiaya_tindakan,
                            jmlsubsidi_asuransi,
                            jmlsubsidi_pemerintah,
                            jmlsubsidi_rs,
                            jmliur_biaya,
                            jml_pembebasan,
                            jmlbayar_tindakan,
                            jml_sisabayar_tindakan,
                            tipepaket_id,
                            pembulatan,
                            additional_data,
              NEW.created_by as created_by
            FROM json_populate_recordset(null::tindakansudahbayar_t,vDataTindakan::json);
     -- Setelah insert updatekan ke tindakanpelayanan_t
    UPDATE tindakanpelayanan_t 
                SET tindakansudahbayar_id = tindakansudahbayar_t.tindakansudahbayar_id,
                    tarif_tindakan = tindakansudahbayar_t.jmlbiaya_tindakan,
                    tarif_satuan = (tindakansudahbayar_t.additional_data::json->>'tarif_satuan')::INTEGER,
                    tarif_diskon = (tindakansudahbayar_t.additional_data::json->>'tarif_diskon')::FLOAT,
                    keterangantindakan = (tindakansudahbayar_t.additional_data::json->>'keterangan')::TEXT,
                    tarifcyto_tindakan = (tindakansudahbayar_t.additional_data::json->>'tarif_cyto')::INTEGER,
                    tarif_dijamin = ((tindakansudahbayar_t.additional_data::json->>'data_dijamin')::json->>'dijamin')::float,
                    tarif_dibayarkan = ((tindakansudahbayar_t.additional_data::json->>'data_dijamin')::json->>'harusbayar')::float,
                    is_valid = TRUE,
                                        pembayaran_id = tindakansudahbayar_t.pembayaran_id
                FROM tindakansudahbayar_t 
    WHERE (tindakanpelayanan_t.tindakansudahbayar_id IS NULL OR tindakanpelayanan_t.tipepaket_id IS NULL)
                AND tindakansudahbayar_t.pembayaranpelayanan_id = NEW.pembayaranpelayanan_id
        AND tindakansudahbayar_t.tindakanpelayanan_id = tindakanpelayanan_t.tindakanpelayanan_id ;
    END IF;

  -- Insert ke  obatsudahbayar_t
  IF (json_array_length(vDataObat::json) > 0)  THEN
            INSERT INTO obatsudahbayar_t (
                            pembayaranpelayanan_id, 
                            pembayaran_id, 
                            ruangan_id, 
                            obatalkes_id, 
                            obatalkespasien_id, 
                            qty_obat, 
                            hargasatuan, 
                            jmlsubsidi_asuransi, 
                            jmlsubsidi_pemerintah,
                            jmlsubsidi_rs,
                            jmliurbiaya,
                            jmlbayar_obat,
                            jmlsisabayar_obat,
                            pembulatan,
                                                        created_by,
                                                        additional_data
            ) SELECT 
                            NEW.pembayaranpelayanan_id as pembayaranpelayanan_id, 
                            NEW.pembayaran_id as pembayaran_id, 
                            ruangan_id, 
                            obatalkes_id, 
                            obatalkespasien_id, 
                            qty_obat, 
                            hargasatuan, 
                            jmlsubsidi_asuransi, 
                            jmlsubsidi_pemerintah,
                            jmlsubsidi_rs,
                            jmliurbiaya,
                            jmlbayar_obat,
                            jmlsisabayar_obat,
                            pembulatan,
                                                        NEW.created_by as created_by,
                                                        additional_data
            FROM json_populate_recordset(null::obatsudahbayar_t,vDataObat::json);
     -- Setelah insert updatekan ke obat alkes pasien
    UPDATE obatalkespasien_t 
            SET obatsudahbayar_id = obatsudahbayar_t.obatsudahbayar_id,
                    tarif_diskon = (obatsudahbayar_t.additional_data::json->>'tarif_diskon')::float,
                    keterangan = (obatsudahbayar_t.additional_data::json->>'keterangan')::TEXT,
                    tarif_dijamin = ((obatsudahbayar_t.additional_data::json->>'data_dijamin')::json->>'dijamin')::float,
          tarif_dibayarkan = ((obatsudahbayar_t.additional_data::json->>'data_dijamin')::json->>'harusbayar')::float,
                    pembayaran_id = obatsudahbayar_t.pembayaran_id
      FROM obatsudahbayar_t 
            WHERE obatalkespasien_t.obatsudahbayar_id IS NULL 
                AND obatsudahbayar_t.pembayaranpelayanan_id = NEW.pembayaranpelayanan_id
        AND obatsudahbayar_t.obatalkespasien_id = obatalkespasien_t.obatalkespasien_id ;
        -- Update pembayaran Resep
        UPDATE penjualanresep_t 
                SET status_bayar = 348
            FROM obatalkespasien_t
                JOIN obatsudahbayar_t ON obatsudahbayar_t.obatsudahbayar_id = obatalkespasien_t.obatsudahbayar_id
            WHERE obatalkespasien_t.penjualanresep_id = penjualanresep_t.penjualanresep_id 
                    AND obatsudahbayar_t.pembayaranpelayanan_id = NEW.pembayaranpelayanan_id;
    END IF;
   
  NEW.additional_data := NULL;
  vAdmin := paramJson::json->>'biayaadministrasi';
  vKeterangan := paramJson::json->>'sebagaipembayaran_bkm';
  vNamaBkm := paramJson::json->>'darinama_bkm';
  vCaraPembayaran := paramJson::json->>'carapembayaran';
  vPegawaiId := paramJson::json->>'pegawai_id';
  vJumlahUangMuka := paramJson::json->>'jumlah_uangmuka';
    vShifId := paramJson::json->>'shift_id';

 -- Ini Status Ketika jaminan kalo perorangan dcheck ada pemakaian uang muka kalo ada insert ke pemakaian uang muka
 -- dan update uangmuka
--   vUangDiterima := NEW.total_terbayar;
--     IF (vCaraPembayaran != '31')
--      THEN
--             NEW.penggunaan_uangmuka := 0;
--       INSERT INTO piutangasuransi_t (
--                         pembayaranpelayanan_id,
--             penjamin_id,
--             carabayar_id,
--             jmlpiutangasuransi,
--             created_by
--         ) VALUES (
--            NEW.pembayaranpelayanan_id,
--            NEW.penjamin_id,
--            NEW.carabayar_id,
--            NEW.total_biayapelayanan,
--            NEW.created_by
--         );
--   ELSE
--             IF (NEW.penggunaan_uangmuka > 0)
--                 THEN
--                         INSERT INTO pemakaianuangmuka_t (
--                             pembayaranpelayanan_id,
--                             pendaftaran_id,
--                             tgl_pemakaian,
--                             total_uangmuka,
--                             pemakaian_uangmuka,
--                             sisa_uangmuka,
--                             created_by
--                         ) VALUES (
--                             NEW.pembayaranpelayanan_id,
--                             vIdPendaftaran,
--                             NEW.tgl_pembayaran,
--                             vJumlahUangMuka,
--                             NEW.penggunaan_uangmuka,
--                             (vJumlahUangMuka - NEW.penggunaan_uangmuka),
--                             NEW.created_by
--                         ) RETURNING pemakaianuangmuka_id INTO vIdPemakaianUang;
--                         
--                         UPDATE bayaruangmuka_t SET
--                             pemakaianuangmuka_id = vIdPemakaianUang
--                         WHERE pendaftaran_id = vIdPendaftaran AND pemakaianuangmuka_id IS NULL;
--             END IF;
--   END IF; 

    vUangDiterima := 0;
    IF (NEW.total_biayapelayanan > NEW.penggunaan_uangmuka)
     THEN
                IF (vCaraPembayaran = '31')
                    THEN
                            vUangDiterima := NEW.total_biayapelayanan -   NEW.penggunaan_uangmuka;
                    END IF;
  END IF;
-- Jika ada pemakaian uang muka
IF (NEW.penggunaan_uangmuka > 0)
        THEN
            IF (NEW.penggunaan_uangmuka > NEW.total_sisatagihan) 
                THEN
                        -- Komen
                        NEW.total_sisatagihan := 0;
                        vUangKembalian := vUangKembalian + NEW.penggunaan_uangmuka;
            ELSE
                        NEW.total_sisatagihan := NEW.total_sisatagihan - NEW.penggunaan_uangmuka;
            END IF;
END IF;

IF (vUangKembalian < 0)
        THEN
        vUangKembalian := 0;
END IF;

  IF (NEW.total_sisatagihan <= 0) THEN
            NEW.statusbayar = 348;
      NEW.is_lunas = TRUE;
    END IF;


 INSERT INTO tandabuktibayar_t (
    ruangan_id, 
    pembayaranpelayanan_id, 
    tglbuktibayar,
    darinama_bkm,
    sebagaipembayaran_bkm,
    jmlpembayaran,
    biayaadministrasi,
    biayamaterai,
    uangditerima,
    uangkembalian,
    namapemilik_rek,
    no_rek,
    carapembayaran,
    pegawai1_id,
    created_by,
    shift_id
  ) VALUES (
    NEW.ruangan_id,
    NEW.pembayaranpelayanan_id,
    NEW.tgl_pembayaran,
    vNamaBkm,
    vKeterangan,
    NEW.total_biayapelayanan,
    NEW.biaya_administrasi,
    0,
    NEW.total_bayartindakan,
    vUangKembalian,
    NEW.nama_pemrekening,
    NEW.no_rekening,
    vCaraPembayaran,
    vPegawaiId,
    NEW.created_by,
    vShifId
  ) RETURNING tandabuktibayar_id INTO vTandaBuktiBayarId;
    NEW.tandabuktibayar_id := vTandaBuktiBayarId;
    RETURN NEW;
END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

    $this->execute('ALTER FUNCTION "public"."no_pembayaranpelayanan_t"() OWNER TO "postgres";');

    $this->execute("
        CREATE OR REPLACE FUNCTION \"public\".\"obatalkespasien_r_update\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$ 
    
DECLARE
        v_keterangan VARCHAR;
BEGIN
        IF((NEW.is_deleted IS TRUE OR NEW.obatsudahbayar_id IS NOT NULL) AND OLD.is_deleted IS FALSE)
        THEN
                v_keterangan := 'ACCRUAL REVERSAL';
                --> INSERT table history obatalkespasien_r menjadi ACCRUAL REVERSAL(-)
                INSERT INTO obatalkespasien_r (     
                obatalkespasien_id ,
                sumberdana_id ,
                racikan_id ,
                returresepdetail_id ,
                tipepaket_id ,
                ruangan_id ,
                carabayar_id ,
                pegawai_id ,
                daftartindakan_id ,
                tindakanpelayanan_id ,
                satuankecil_id ,
                shift_id ,
                pendaftaran_id ,
                obatalkes_id ,
                pasien_id ,
                penjamin_id ,
                kelaspelayanan_id ,
                pasienanastesi_id ,
                pasienmasukpenunjang_id ,
                pasienadmisi_id ,
                obatsudahbayar_id ,
                penjualanresep_id ,
                tglpelayanan ,
                r ,
                rke ,
                permintaan_oa ,
                jmlkemasan_oa ,
                kekuatan_oa ,
                satuankekuatan_oa ,
                qty_oa ,
                hargasatuan_oa ,
                signa_oa ,
                harganetto_oa ,
                hargajual_oa , 
                etiket ,
                jmlexposerad ,
                kontrasrad ,
                biayaservice ,
                biayakonseling ,
                jasadokterresep ,
                biayakemasan ,
                biayaadministrasi ,
                tarifcyto ,
                discount , 
                subsidiasuransi ,
                subsidipemerintah ,
                subsidirs ,
                iurbiaya ,
                oa ,
                pembulatan ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                permohonanoadetail_id ,
                persenppnjual ,
                resepturdetail_id ,
                nilaippnjual ,
                perawat1_id ,
                perawat2_id ,
                instruksitindakanbmhp_id ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_jurnal ,
                konfigmargindetail_id ,
                qty_konversi ,
                is_penatajasa ,
                det ,
                status_bmhp ,
                det_konversi ,
                signa ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date , 
                deleted_by ,
                keterangan,
                no_obatalkespasien,
                                tarif_dijamin,
                                tarif_dibayarkan,
                                tarif_diskon,
                                pembayaran_id
            )VALUES(
                OLD.obatalkespasien_id ,
                OLD.sumberdana_id ,
                OLD.racikan_id ,
                OLD.returresepdetail_id ,
                OLD.tipepaket_id ,
                OLD.ruangan_id ,
                OLD.carabayar_id ,
                OLD.pegawai_id ,
                OLD.daftartindakan_id ,
                OLD.tindakanpelayanan_id ,
                OLD.satuankecil_id ,
                OLD.shift_id ,
                OLD.pendaftaran_id ,
                OLD.obatalkes_id ,
                OLD.pasien_id ,
                OLD.penjamin_id ,
                OLD.kelaspelayanan_id ,
                OLD.pasienanastesi_id ,
                OLD.pasienmasukpenunjang_id ,
                OLD.pasienadmisi_id ,
                OLD.obatsudahbayar_id ,
                OLD.penjualanresep_id ,
                OLD.tglpelayanan ,
                OLD.r ,
                OLD.rke ,
                OLD.permintaan_oa ,
                OLD.jmlkemasan_oa ,
                OLD.kekuatan_oa ,
                OLD.satuankekuatan_oa ,
                -1 * OLD.qty_oa ,
                OLD.hargasatuan_oa ,
                OLD.signa_oa ,
                OLD.harganetto_oa ,
                CASE
                                    WHEN OLD.det <> 0  THEN -1 * OLD.hargasatuan_oa * OLD.det
                                    WHEN OLD.det = 0 OR OLD.det IS NULL THEN  -1 * OLD.hargasatuan_oa * OLD.qty_oa 
                                END, 
                OLD.etiket ,
                OLD.jmlexposerad ,
                OLD.kontrasrad ,
                OLD.biayaservice ,
                OLD.biayakonseling ,
                OLD.jasadokterresep ,
                OLD.biayakemasan ,
                OLD.biayaadministrasi ,
                OLD.tarifcyto ,
                OLD.discount , 
                OLD.subsidiasuransi ,
                OLD.subsidipemerintah ,
                OLD.subsidirs ,
                OLD.iurbiaya ,
                OLD.oa ,
                OLD.pembulatan ,
                OLD.verifikasitagihan_id ,
                OLD.jurnalrekening_id ,
                OLD.permohonanoadetail_id ,
                OLD.persenppnjual ,
                OLD.resepturdetail_id ,
                OLD.nilaippnjual ,
                OLD.perawat1_id ,
                OLD.perawat2_id ,
                OLD.instruksitindakanbmhp_id ,
                OLD.implementasi_id ,
                OLD.is_dilakukan ,
                OLD.pemakaianambulan_id ,
                OLD.is_jurnal ,
                OLD.konfigmargindetail_id ,
                -1 * OLD.qty_konversi ,
                OLD.is_penatajasa ,
                -1 * OLD.det ,
                OLD.status_bmhp ,
                OLD.det_konversi ,
                OLD.signa ,
                OLD.additional_data ,
                OLD.created_date ,
                OLD.created_by ,
                OLD.modified_count ,
                OLD.last_modified_date ,
                OLD.last_modified_by ,
                OLD.is_deleted ,
                OLD.is_active ,
                OLD.deleted_date , 
                OLD.deleted_by ,
                v_keterangan,
                OLD.no_obatalkespasien,
                              -1 * OLD.tarif_dijamin,
                                -1 * OLD.tarif_dibayarkan,
                                -1 * OLD.tarif_diskon,
                                OLD.pembayaran_id
            );
        RETURN NEW;
        END IF;
            
            IF (OLD.obatsudahbayar_id is null and OLD.is_deleted is FALSE)
                THEN    
                -- INSERT table history obatalkespasien_r menjadi ACCRUAL REVERSAL(-) setelah BILLING CANCEL
                INSERT INTO obatalkespasien_r (     
                obatalkespasien_id ,
                sumberdana_id ,
                racikan_id ,
                returresepdetail_id ,
                tipepaket_id ,
                ruangan_id ,
                carabayar_id ,
                pegawai_id ,
                daftartindakan_id ,
                tindakanpelayanan_id ,
                satuankecil_id ,
                shift_id ,
                pendaftaran_id ,
                obatalkes_id ,
                pasien_id ,
                penjamin_id ,
                kelaspelayanan_id ,
                pasienanastesi_id ,
                pasienmasukpenunjang_id ,
                pasienadmisi_id ,
                obatsudahbayar_id ,
                penjualanresep_id ,
                tglpelayanan ,
                r ,
                rke ,
                permintaan_oa ,
                jmlkemasan_oa ,
                kekuatan_oa ,
                satuankekuatan_oa ,
                qty_oa ,
                hargasatuan_oa ,
                signa_oa ,
                harganetto_oa ,
                hargajual_oa , 
                etiket ,
                jmlexposerad ,
                kontrasrad ,
                biayaservice ,
                biayakonseling ,
                jasadokterresep ,
                biayakemasan ,
                biayaadministrasi ,
                tarifcyto ,
                discount , 
                subsidiasuransi ,
                subsidipemerintah ,
                subsidirs ,
                iurbiaya ,
                oa ,
                pembulatan ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                permohonanoadetail_id ,
                persenppnjual ,
                resepturdetail_id ,
                nilaippnjual ,
                perawat1_id ,
                perawat2_id ,
                instruksitindakanbmhp_id ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_jurnal ,
                konfigmargindetail_id ,
                qty_konversi ,
                is_penatajasa ,
                det ,
                status_bmhp ,
                det_konversi ,
                signa ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date , 
                deleted_by ,
                keterangan,
                no_obatalkespasien,
                                tarif_dijamin,
                                tarif_dibayarkan,
                                tarif_diskon,
                                pembayaran_id
            )VALUES(
                OLD.obatalkespasien_id ,
                OLD.sumberdana_id ,
                OLD.racikan_id ,
                OLD.returresepdetail_id ,
                OLD.tipepaket_id ,
                OLD.ruangan_id ,
                OLD.carabayar_id ,
                OLD.pegawai_id ,
                OLD.daftartindakan_id ,
                OLD.tindakanpelayanan_id ,
                OLD.satuankecil_id ,
                OLD.shift_id ,
                OLD.pendaftaran_id ,
                OLD.obatalkes_id ,
                OLD.pasien_id ,
                OLD.penjamin_id ,
                OLD.kelaspelayanan_id ,
                OLD.pasienanastesi_id ,
                OLD.pasienmasukpenunjang_id ,
                OLD.pasienadmisi_id ,
                OLD.obatsudahbayar_id ,
                OLD.penjualanresep_id ,
                OLD.tglpelayanan ,
                OLD.r ,
                OLD.rke ,
                OLD.permintaan_oa ,
                OLD.jmlkemasan_oa ,
                OLD.kekuatan_oa ,
                OLD.satuankekuatan_oa ,
                -1 * OLD.qty_oa ,
                OLD.hargasatuan_oa ,
                OLD.signa_oa ,
                OLD.harganetto_oa ,
                CASE
                                    WHEN OLD.det <> 0  THEN -1 * OLD.hargasatuan_oa * OLD.det
                                    WHEN OLD.det = 0 OR OLD.det IS NULL THEN  -1 * OLD.hargasatuan_oa * OLD.qty_oa 
                                END,  
                OLD.etiket ,
                OLD.jmlexposerad ,
                OLD.kontrasrad ,
                OLD.biayaservice ,
                OLD.biayakonseling ,
                OLD.jasadokterresep ,
                OLD.biayakemasan ,
                OLD.biayaadministrasi ,
                OLD.tarifcyto ,
                OLD.discount , 
                OLD.subsidiasuransi ,
                OLD.subsidipemerintah ,
                OLD.subsidirs ,
                OLD.iurbiaya ,
                OLD.oa ,
                OLD.pembulatan ,
                OLD.verifikasitagihan_id ,
                OLD.jurnalrekening_id ,
                OLD.permohonanoadetail_id ,
                OLD.persenppnjual ,
                OLD.resepturdetail_id ,
                OLD.nilaippnjual ,
                OLD.perawat1_id ,
                OLD.perawat2_id ,
                OLD.instruksitindakanbmhp_id ,
                OLD.implementasi_id ,
                OLD.is_dilakukan ,
                OLD.pemakaianambulan_id ,
                OLD.is_jurnal ,
                OLD.konfigmargindetail_id ,
                -1 * OLD.qty_konversi ,
                OLD.is_penatajasa ,
                -1 * OLD.det ,
                OLD.status_bmhp ,
                OLD.det_konversi ,
                OLD.signa ,
                OLD.additional_data ,
                OLD.created_date ,
                OLD.created_by ,
                OLD.modified_count ,
                OLD.last_modified_date ,
                OLD.last_modified_by ,
                OLD.is_deleted ,
                OLD.is_active ,
                OLD.deleted_date , 
                OLD.deleted_by ,
                'ACCRUAL REVERSAL',
                OLD.no_obatalkespasien,
                                -1 * OLD.tarif_dijamin,
                                -1 * OLD.tarif_dibayarkan,
                                -1 * OLD.tarif_diskon,
                                OLD.pembayaran_id
            );
        
            INSERT INTO obatalkespasien_r (     
                obatalkespasien_id ,
                sumberdana_id ,
                racikan_id ,
                returresepdetail_id ,
                tipepaket_id ,
                ruangan_id ,
                carabayar_id ,
                pegawai_id ,
                daftartindakan_id ,
                tindakanpelayanan_id ,
                satuankecil_id ,
                shift_id ,
                pendaftaran_id ,
                obatalkes_id ,
                pasien_id ,
                penjamin_id ,
                kelaspelayanan_id ,
                pasienanastesi_id ,
                pasienmasukpenunjang_id ,
                pasienadmisi_id ,
                obatsudahbayar_id ,
                penjualanresep_id ,
                tglpelayanan ,
                r ,
                rke ,
                permintaan_oa ,
                jmlkemasan_oa ,
                kekuatan_oa ,
                satuankekuatan_oa ,
                qty_oa ,
                hargasatuan_oa ,
                signa_oa ,
                harganetto_oa ,
                hargajual_oa , 
                etiket ,
                jmlexposerad ,
                kontrasrad ,
                biayaservice ,
                biayakonseling ,
                jasadokterresep ,
                biayakemasan ,
                biayaadministrasi ,
                tarifcyto ,
                discount , 
                subsidiasuransi ,
                subsidipemerintah ,
                subsidirs ,
                iurbiaya ,
                oa ,
                pembulatan ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                permohonanoadetail_id ,
                persenppnjual ,
                resepturdetail_id ,
                nilaippnjual ,
                perawat1_id ,
                perawat2_id ,
                instruksitindakanbmhp_id ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_jurnal ,
                konfigmargindetail_id ,
                qty_konversi ,
                is_penatajasa ,
                det ,
                status_bmhp ,
                det_konversi ,
                signa ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date , 
                deleted_by ,
                keterangan,
                no_obatalkespasien,
                                tarif_dijamin,
                                tarif_dibayarkan,
                                tarif_diskon,
                                pembayaran_id
            )VALUES(
                OLD.obatalkespasien_id ,
                OLD.sumberdana_id ,
                OLD.racikan_id ,
                NEW.returresepdetail_id ,
                OLD.tipepaket_id ,
                OLD.ruangan_id ,
                OLD.carabayar_id ,
                OLD.pegawai_id ,
                NEW.daftartindakan_id ,
                NEW.tindakanpelayanan_id ,
                OLD.satuankecil_id ,
                OLD.shift_id ,
                OLD.pendaftaran_id ,
                OLD.obatalkes_id ,
                OLD.pasien_id ,
                NEW.penjamin_id ,
                NEW.kelaspelayanan_id ,
                OLD.pasienanastesi_id ,
                OLD.pasienmasukpenunjang_id ,
                OLD.pasienadmisi_id ,
                OLD.obatsudahbayar_id ,
                OLD.penjualanresep_id ,
                OLD.tglpelayanan ,
                OLD.r ,
                OLD.rke ,
                OLD.permintaan_oa ,
                OLD.jmlkemasan_oa ,
                OLD.kekuatan_oa ,
                OLD.satuankekuatan_oa ,
                NEW.qty_oa ,
                NEW.hargasatuan_oa ,
                NEW.signa_oa ,
                NEW.harganetto_oa ,
                CASE
                                    WHEN NEW.det <> 0  THEN NEW.hargasatuan_oa * NEW.det
                                    WHEN NEW.det = 0 OR NEW.det IS NULL THEN NEW.hargasatuan_oa * NEW.qty_oa 
                                END,  
                OLD.etiket ,
                OLD.jmlexposerad ,
                OLD.kontrasrad ,
                OLD.biayaservice ,
                OLD.biayakonseling ,
                OLD.jasadokterresep ,
                OLD.biayakemasan ,
                OLD.biayaadministrasi ,
                OLD.tarifcyto ,
                OLD.discount , 
                OLD.subsidiasuransi ,
                OLD.subsidipemerintah ,
                OLD.subsidirs ,
                OLD.iurbiaya ,
                OLD.oa ,
                OLD.pembulatan ,
                OLD.verifikasitagihan_id ,
                OLD.jurnalrekening_id ,
                OLD.permohonanoadetail_id ,
                OLD.persenppnjual ,
                OLD.resepturdetail_id ,
                OLD.nilaippnjual ,
                OLD.perawat1_id ,
                OLD.perawat2_id ,
                OLD.instruksitindakanbmhp_id ,
                OLD.implementasi_id ,
                OLD.is_dilakukan ,
                OLD.pemakaianambulan_id ,
                OLD.is_jurnal ,
                OLD.konfigmargindetail_id ,
                NEW.qty_konversi ,
                OLD.is_penatajasa ,
                NEW.det ,
                OLD.status_bmhp ,
                OLD.det_konversi ,
                OLD.signa ,
                OLD.additional_data ,
                OLD.created_date ,
                OLD.created_by ,
                OLD.modified_count ,
                OLD.last_modified_date ,
                OLD.last_modified_by ,
                OLD.is_deleted ,
                OLD.is_active ,
                OLD.deleted_date , 
                OLD.deleted_by ,
                'ACCRUAL',
                OLD.no_obatalkespasien,
                                NEW.tarif_dijamin,
                                NEW.tarif_dibayarkan,
                                NEW.tarif_diskon,
                                NEW.pembayaran_id
            );  

END IF;

    RETURN NEW;

END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

    $this->execute('ALTER FUNCTION "public"."obatalkespasien_r_update"() OWNER TO "postgres";');

    $this->execute("
        CREATE OR REPLACE FUNCTION \"public\".\"obatsudahbayar_t_cancel\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$ 
    
DECLARE
        v_keterangan VARCHAR;
    BEGIN
        IF(NEW.is_deleted IS TRUE)
        THEN
            -- INSERT table history obatalkespasien_r menjadi ACCRUAL(+), jika is_deleted=TRUE
            INSERT INTO obatalkespasien_r (     
                obatalkespasien_id ,
                sumberdana_id ,
                racikan_id ,
                returresepdetail_id ,
                tipepaket_id ,
                ruangan_id ,
                carabayar_id ,
                pegawai_id ,
                daftartindakan_id ,
                tindakanpelayanan_id ,
                satuankecil_id ,
                shift_id ,
                pendaftaran_id ,
                obatalkes_id ,
                pasien_id ,
                penjamin_id ,
                kelaspelayanan_id ,
                pasienanastesi_id ,
                pasienmasukpenunjang_id ,
                pasienadmisi_id ,
                obatsudahbayar_id ,
                penjualanresep_id ,
                tglpelayanan ,
                r ,
                rke ,
                permintaan_oa ,
                jmlkemasan_oa ,
                kekuatan_oa ,
                satuankekuatan_oa ,
                qty_oa ,
                hargasatuan_oa ,
                signa_oa ,
                harganetto_oa ,
                hargajual_oa , 
                etiket ,
                jmlexposerad ,
                kontrasrad ,
                biayaservice ,
                biayakonseling ,
                jasadokterresep ,
                biayakemasan ,
                biayaadministrasi ,
                tarifcyto ,
                discount , 
                subsidiasuransi ,
                subsidipemerintah ,
                subsidirs ,
                iurbiaya ,
                oa ,
                pembulatan ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                permohonanoadetail_id ,
                persenppnjual ,
                resepturdetail_id ,
                nilaippnjual ,
                perawat1_id ,
                perawat2_id ,
                instruksitindakanbmhp_id ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_jurnal ,
                konfigmargindetail_id ,
                qty_konversi ,
                is_penatajasa ,
                det ,
                status_bmhp ,
                det_konversi ,
                signa ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date , 
                deleted_by ,
                keterangan,
                                no_obatalkespasien,
                                tarif_dijamin,
                                tarif_dibayarkan,
                                tarif_diskon,
                                pembayaran_id
                )
                SELECT
                obatalkespasien_id ,
                sumberdana_id ,
                racikan_id ,
                returresepdetail_id ,
                tipepaket_id ,
                ruangan_id ,
                carabayar_id ,
                pegawai_id ,
                daftartindakan_id ,
                tindakanpelayanan_id ,
                satuankecil_id ,
                shift_id ,
                pendaftaran_id ,
                obatalkes_id ,
                pasien_id ,
                penjamin_id ,
                kelaspelayanan_id ,
                pasienanastesi_id ,
                pasienmasukpenunjang_id ,
                pasienadmisi_id ,
                NEW.obatsudahbayar_id ,
                penjualanresep_id ,
                tglpelayanan ,
                r ,
                rke ,
                permintaan_oa ,
                jmlkemasan_oa ,
                kekuatan_oa ,
                satuankekuatan_oa ,
                qty_oa ,
                hargasatuan_oa ,
                signa_oa ,
                harganetto_oa ,
                hargajual_oa , 
                etiket ,
                jmlexposerad ,
                kontrasrad ,
                biayaservice ,
                biayakonseling ,
                jasadokterresep ,
                biayakemasan ,
                biayaadministrasi ,
                tarifcyto ,
                discount , 
                subsidiasuransi ,
                subsidipemerintah ,
                subsidirs ,
                iurbiaya ,
                oa ,
                pembulatan ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                permohonanoadetail_id ,
                persenppnjual ,
                resepturdetail_id ,
                nilaippnjual ,
                perawat1_id ,
                perawat2_id ,
                instruksitindakanbmhp_id ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_jurnal ,
                konfigmargindetail_id ,
                qty_konversi ,
                is_penatajasa ,
                det ,
                status_bmhp ,
                det_konversi ,
                signa ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date , 
                deleted_by ,
                'ACCRUAL',
                                no_obatalkespasien,
                                0,
                                0,
                                0,
                                NULL
                FROM obatalkespasien_t
            WHERE obatalkespasien_id = NEW.obatalkespasien_id;
        
            -- INSERT table history obatalkespasien_r menjadi BILLING CANCEL(-), jika is_deleted=TRUE
                INSERT INTO obatalkespasien_r (     
                    obatalkespasien_id ,
                    sumberdana_id ,
                    racikan_id ,
                    returresepdetail_id ,
                    tipepaket_id ,
                    ruangan_id ,
                    carabayar_id ,
                    pegawai_id ,
                    daftartindakan_id ,
                    tindakanpelayanan_id ,
                    satuankecil_id ,
                    shift_id ,
                    pendaftaran_id ,
                    obatalkes_id ,
                    pasien_id ,
                    penjamin_id ,
                    kelaspelayanan_id ,
                    pasienanastesi_id ,
                    pasienmasukpenunjang_id ,
                    pasienadmisi_id ,
                    obatsudahbayar_id ,
                    penjualanresep_id ,
                    tglpelayanan ,
                    r ,
                    rke ,
                    permintaan_oa ,
                    jmlkemasan_oa ,
                    kekuatan_oa ,
                    satuankekuatan_oa ,
                    qty_oa ,
                    hargasatuan_oa ,
                    signa_oa ,
                    harganetto_oa ,
                    hargajual_oa , 
                    etiket ,
                    jmlexposerad ,
                    kontrasrad ,
                    biayaservice ,
                    biayakonseling ,
                    jasadokterresep ,
                    biayakemasan ,
                    biayaadministrasi ,
                    tarifcyto ,
                    discount , 
                    subsidiasuransi ,
                    subsidipemerintah ,
                    subsidirs ,
                    iurbiaya ,
                    oa ,
                    pembulatan ,
                    verifikasitagihan_id ,
                    jurnalrekening_id ,
                    permohonanoadetail_id ,
                    persenppnjual ,
                    resepturdetail_id ,
                    nilaippnjual ,
                    perawat1_id ,
                    perawat2_id ,
                    instruksitindakanbmhp_id ,
                    implementasi_id ,
                    is_dilakukan ,
                    pemakaianambulan_id ,
                    is_jurnal ,
                    konfigmargindetail_id ,
                    qty_konversi ,
                    is_penatajasa ,
                    det ,
                    status_bmhp ,
                    det_konversi ,
                    signa ,
                    additional_data ,
                    created_date ,
                    created_by ,
                    modified_count ,
                    last_modified_date ,
                    last_modified_by ,
                    is_deleted ,
                    is_active ,
                    deleted_date , 
                    deleted_by ,
                    keterangan,
                                        no_obatalkespasien,
                                        tarif_dijamin,
                                        tarif_dibayarkan,
                                        tarif_diskon,
                                        pembayaran_id
                    )
                    SELECT
                    obatalkespasien_id ,
                    sumberdana_id ,
                    racikan_id ,
                    returresepdetail_id ,
                    tipepaket_id ,
                    ruangan_id ,
                    carabayar_id ,
                    pegawai_id ,
                    daftartindakan_id ,
                    tindakanpelayanan_id ,
                    satuankecil_id ,
                    shift_id ,
                    pendaftaran_id ,
                    obatalkes_id ,
                    pasien_id ,
                    penjamin_id ,
                    kelaspelayanan_id ,
                    pasienanastesi_id ,
                    pasienmasukpenunjang_id ,
                    pasienadmisi_id ,
                    NEW.obatsudahbayar_id ,
                    penjualanresep_id ,
                    tglpelayanan ,
                    r ,
                    rke ,
                    permintaan_oa ,
                    jmlkemasan_oa ,
                    kekuatan_oa ,
                    satuankekuatan_oa ,
                    -1 * qty_oa ,
                    hargasatuan_oa ,
                    signa_oa ,
                    harganetto_oa ,
                    -1 * hargajual_oa,  
                    etiket ,
                    jmlexposerad ,
                    kontrasrad ,
                    biayaservice ,
                    biayakonseling ,
                    jasadokterresep ,
                    biayakemasan ,
                    biayaadministrasi ,
                    tarifcyto ,
                    discount , 
                    subsidiasuransi ,
                    subsidipemerintah ,
                    subsidirs ,
                    iurbiaya ,
                    oa ,
                    pembulatan ,
                    verifikasitagihan_id ,
                    jurnalrekening_id ,
                    permohonanoadetail_id ,
                    persenppnjual ,
                    resepturdetail_id ,
                    nilaippnjual ,
                    perawat1_id ,
                    perawat2_id ,
                    instruksitindakanbmhp_id ,
                    implementasi_id ,
                    is_dilakukan ,
                    pemakaianambulan_id ,
                    is_jurnal ,
                    konfigmargindetail_id ,
                    -1 * qty_konversi ,
                    is_penatajasa ,
                    -1 * det ,
                    status_bmhp ,
                    det_konversi ,
                    signa ,
                    additional_data ,
                    created_date ,
                    created_by ,
                    modified_count ,
                    last_modified_date ,
                    last_modified_by ,
                    is_deleted ,
                    is_active ,
                    deleted_date , 
                    deleted_by ,
                    'BILLING CANCEL',
                                        no_obatalkespasien,
                                        -1 * ((OLD.additional_data::json->>'data_dijamin')::json->>'dijamin')::float,
                                        -1 * ((OLD.additional_data::json->>'data_dijamin')::json->>'harusbayar')::float, 
                                        -1 * (OLD.additional_data::json->>'tarif_diskon')::float,
                                        OLD.pembayaran_id 
                    FROM obatalkespasien_t
                WHERE obatalkespasien_id = NEW.obatalkespasien_id;
                
    END IF;
    
    RETURN NEW;

END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

    $this->execute('ALTER FUNCTION "public"."obatsudahbayar_t_cancel"() OWNER TO "postgres";');

    $this->execute("
        CREATE OR REPLACE FUNCTION \"public\".\"obatsudahbayar_t_insert\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$

BEGIN
        -- INSERT table history obatalkespasien_r BILLING(+)
        INSERT INTO obatalkespasien_r (     
                obatalkespasien_id ,
                sumberdana_id ,
                racikan_id ,
                returresepdetail_id ,
                tipepaket_id ,
                ruangan_id ,
                carabayar_id ,
                pegawai_id ,
                daftartindakan_id ,
                tindakanpelayanan_id ,
                satuankecil_id ,
                shift_id ,
                pendaftaran_id ,
                obatalkes_id ,
                pasien_id ,
                penjamin_id ,
                kelaspelayanan_id ,
                pasienanastesi_id ,
                pasienmasukpenunjang_id ,
                pasienadmisi_id ,
                obatsudahbayar_id ,
                penjualanresep_id ,
                tglpelayanan ,
                r ,
                rke ,
                permintaan_oa ,
                jmlkemasan_oa ,
                kekuatan_oa ,
                satuankekuatan_oa ,
                qty_oa ,
                hargasatuan_oa ,
                signa_oa ,
                harganetto_oa ,
                hargajual_oa , 
                etiket ,
                jmlexposerad ,
                kontrasrad ,
                biayaservice ,
                biayakonseling ,
                jasadokterresep ,
                biayakemasan ,
                biayaadministrasi ,
                tarifcyto ,
                discount , 
                subsidiasuransi ,
                subsidipemerintah ,
                subsidirs ,
                iurbiaya ,
                oa ,
                pembulatan ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                permohonanoadetail_id ,
                persenppnjual ,
                resepturdetail_id ,
                nilaippnjual ,
                perawat1_id ,
                perawat2_id ,
                instruksitindakanbmhp_id ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_jurnal ,
                konfigmargindetail_id ,
                qty_konversi ,
                is_penatajasa ,
                det ,
                status_bmhp ,
                det_konversi ,
                signa ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date , 
                deleted_by ,
                keterangan,
                no_obatalkespasien,
                                tarif_dijamin,
                                tarif_dibayarkan,
                                tarif_diskon,
                                pembayaran_id
        )
        SELECT  
                obatalkespasien_id ,
                sumberdana_id ,
                racikan_id ,
                returresepdetail_id ,
                tipepaket_id ,
                ruangan_id ,
                carabayar_id ,
                pegawai_id ,
                daftartindakan_id ,
                tindakanpelayanan_id ,
                satuankecil_id ,
                shift_id ,
                pendaftaran_id ,
                obatalkes_id ,
                pasien_id ,
                penjamin_id ,
                kelaspelayanan_id ,
                pasienanastesi_id ,
                pasienmasukpenunjang_id ,
                pasienadmisi_id ,
                NEW.obatsudahbayar_id ,
                penjualanresep_id ,
                tglpelayanan ,
                r ,
                rke ,
                permintaan_oa ,
                jmlkemasan_oa ,
                kekuatan_oa ,
                satuankekuatan_oa ,
                qty_oa ,
                hargasatuan_oa ,
                signa_oa ,
                harganetto_oa ,
                hargajual_oa , 
                etiket ,
                jmlexposerad ,
                kontrasrad ,
                biayaservice ,
                biayakonseling ,
                jasadokterresep ,
                biayakemasan ,
                biayaadministrasi ,
                tarifcyto ,
                discount , 
                subsidiasuransi ,
                subsidipemerintah ,
                subsidirs ,
                iurbiaya ,
                oa ,
                pembulatan ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                permohonanoadetail_id ,
                persenppnjual ,
                resepturdetail_id ,
                nilaippnjual ,
                perawat1_id ,
                perawat2_id ,
                instruksitindakanbmhp_id ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_jurnal ,
                konfigmargindetail_id ,
                qty_konversi ,
                is_penatajasa ,
                det ,
                status_bmhp ,
                det_konversi ,
                signa ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date , 
                deleted_by ,
                'BILLING',
                no_obatalkespasien,
                                ((NEW.additional_data::json->>'data_dijamin')::json->>'dijamin')::float,
                                ((NEW.additional_data::json->>'data_dijamin')::json->>'harusbayar')::float,
                                (NEW.additional_data::json->>'tarif_diskon')::float,
                                NEW.pembayaran_id                                
    FROM obatalkespasien_t
    WHERE obatalkespasien_id = NEW.obatalkespasien_id;
    
    RETURN NEW;

END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

    $this->execute('ALTER FUNCTION "public"."obatsudahbayar_t_insert"() OWNER TO "postgres";');

    $this->execute("
        CREATE OR REPLACE FUNCTION \"public\".\"tindakanpelayanan_r_update\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$

DECLARE
    v_keterangan VARCHAR;
BEGIN
    IF((NEW.is_deleted IS TRUE OR NEW.tindakansudahbayar_id IS NOT NULL) AND OLD.is_deleted IS FALSE)
        THEN
            v_keterangan := 'ACCRUAL REVERSAL';
        --> INSERT table history tindakanpelayanan_r menjadi ACCRUAL REVERSAL(-)
            INSERT INTO tindakanpelayanan_r (       
            tindakanpelayanan_id ,
            shift_id ,
            kelaspelayanan_id ,
            kelastanggungan_id ,
            pasien_id ,
            rencanaoperasi_id ,
            instalasi_id ,
            daftartindakan_id ,
            alatmedis_id ,
            tipepaket_id ,
            tindakansudahbayar_id ,
            carabayar_id ,
            pendaftaran_id ,
            hasilpemeriksaanrad_id ,
            jeniskasuspenyakit_id ,
            hasilpemeriksaanrm_id ,
            ruangan_id ,
            konsulpoli_id ,
            pasienmasukpenunjang_id ,
            hasilpemeriksaanlabdetail_id ,
            penjamin_id ,
            pasienadmisi_id ,
            verifikasitagihan_id ,
            jurnalrekening_id ,
            instruksitindakan_id ,
            tgl_tindakan ,
            tarif_rsakomodasi ,
            tarif_medis ,
            tarif_paramedis ,
            tarif_bhp ,
            tarif_satuan ,
            tarif_tindakan ,
            tarifcyto_tindakan ,
            satuan_tindakan ,
            qty_tindakan ,
            cyto_tindakan ,
            dokterpenanggungjawab_id ,
            dokterpelaksana_id ,
            dokteranastesi_id ,
            dokterdelegasi_id ,
            bidan1_id ,
            bidan2_id ,
            perawat1_id ,
            perawat2_id ,
            discount_tindakan ,
            pembebasan_tindakan ,
            subsidiasuransi_tindakan ,
            subsidipemerintah_tindakan ,
            subsisidirumahsakit_tindakan ,
            uangditerima_tindakan ,
            keterangantindakan ,
            pembulatan ,
            implementasi_id ,
            is_dilakukan ,
            pemakaianambulan_id ,
            is_penatajasa ,
            additional_riwayat ,
            is_valid ,
            kamarruangan_id ,
            kamartempattidur_id ,
            penyulit_tindakan ,
            tarifpenyulit_tindakan ,
            additional_data ,
            created_date ,
            created_by ,
            modified_count,
            last_modified_date,
            last_modified_by,
            is_deleted,
            is_active,
            deleted_date,
            deleted_by,
            keterangan,
            no_tindakanpelayanan,
                        tarif_dijamin,
                        tarif_dibayarkan,
                        tarif_diskon,
                        pembayaran_id
        )VALUES(
            OLD.tindakanpelayanan_id ,
            OLD.shift_id ,
            OLD.kelaspelayanan_id ,
            OLD.kelastanggungan_id ,
            OLD.pasien_id ,
            OLD.rencanaoperasi_id ,
            OLD.instalasi_id ,
            OLD.daftartindakan_id ,
            OLD.alatmedis_id ,
            OLD.tipepaket_id ,
            OLD.tindakansudahbayar_id ,
            OLD.carabayar_id ,
            OLD.pendaftaran_id ,
            OLD.hasilpemeriksaanrad_id ,
            OLD.jeniskasuspenyakit_id ,
            OLD.hasilpemeriksaanrm_id ,
            OLD.ruangan_id ,
            OLD.konsulpoli_id ,
            OLD.pasienmasukpenunjang_id ,
            OLD.hasilpemeriksaanlabdetail_id ,
            OLD.penjamin_id ,
            OLD.pasienadmisi_id ,
            OLD.verifikasitagihan_id ,
            OLD.jurnalrekening_id ,
            OLD.instruksitindakan_id ,
            OLD.tgl_tindakan ,
            OLD.tarif_rsakomodasi ,
            OLD.tarif_medis ,
            OLD.tarif_paramedis ,
            OLD.tarif_bhp ,
            OLD.tarif_satuan ,
            -1 * OLD.tarif_tindakan ,
            OLD.tarifcyto_tindakan ,
            OLD.satuan_tindakan ,
            -1 * OLD.qty_tindakan ,
            OLD.cyto_tindakan ,
            OLD.dokterpenanggungjawab_id ,
            OLD.dokterpelaksana_id ,
            OLD.dokteranastesi_id ,
            OLD.dokterdelegasi_id ,
            OLD.bidan1_id ,
            OLD.bidan2_id ,
            OLD.perawat1_id ,
            OLD.perawat2_id ,
            OLD.discount_tindakan ,
            OLD.pembebasan_tindakan ,
            OLD.subsidiasuransi_tindakan ,
            OLD.subsidipemerintah_tindakan ,
            OLD.subsisidirumahsakit_tindakan ,
            OLD.uangditerima_tindakan ,
            OLD.keterangantindakan ,
            OLD.pembulatan ,
            OLD.implementasi_id ,
            OLD.is_dilakukan ,
            OLD.pemakaianambulan_id ,
            OLD.is_penatajasa ,
            OLD.additional_riwayat ,
            OLD.is_valid ,
            OLD.kamarruangan_id ,
            OLD.kamartempattidur_id ,
            OLD.penyulit_tindakan ,
            OLD.tarifpenyulit_tindakan ,
            OLD.additional_data ,
            OLD.created_date ,
            OLD.created_by ,
            OLD.modified_count,
            OLD.last_modified_date,
            OLD.last_modified_by,
            OLD.is_deleted,
            OLD.is_active,
            OLD.deleted_date,
            OLD.deleted_by,
            v_keterangan,
            OLD.no_tindakanpelayanan,
                        -1 * OLD.tarif_dijamin,
                        -1 * OLD.tarif_dibayarkan,
                        -1 * OLD.tarif_diskon,
                        OLD.pembayaran_id
        );
            RETURN NEW;
            END IF;
            
            IF (old.tindakansudahbayar_id is null AND OLD.is_deleted= FALSE)
                THEN    
            -- INSERT table history tindakanpelayanan_r menjadi ACCRUAL REVERSAL(-) setelah BILLING CANCEL
                INSERT INTO tindakanpelayanan_r (       
                    tindakanpelayanan_id ,
                    shift_id ,
                    kelaspelayanan_id ,
                    kelastanggungan_id ,
                    pasien_id ,
                    rencanaoperasi_id ,
                    instalasi_id ,
                    daftartindakan_id ,
                    alatmedis_id ,
                    tipepaket_id ,
                    tindakansudahbayar_id ,
                    carabayar_id ,
                    pendaftaran_id ,
                    hasilpemeriksaanrad_id ,
                    jeniskasuspenyakit_id ,
                    hasilpemeriksaanrm_id ,
                    ruangan_id ,
                    konsulpoli_id ,
                    pasienmasukpenunjang_id ,
                    hasilpemeriksaanlabdetail_id ,
                    penjamin_id ,
                    pasienadmisi_id ,
                    verifikasitagihan_id ,
                    jurnalrekening_id ,
                    instruksitindakan_id ,
                    tgl_tindakan ,
                    tarif_rsakomodasi ,
                    tarif_medis ,
                    tarif_paramedis ,
                    tarif_bhp ,
                    tarif_satuan ,
                    tarif_tindakan ,
                    tarifcyto_tindakan ,
                    satuan_tindakan ,
                    qty_tindakan ,
                    cyto_tindakan ,
                    dokterpenanggungjawab_id ,
                    dokterpelaksana_id ,
                    dokteranastesi_id ,
                    dokterdelegasi_id ,
                    bidan1_id ,
                    bidan2_id ,
                    perawat1_id ,
                    perawat2_id ,
                    discount_tindakan ,
                    pembebasan_tindakan ,
                    subsidiasuransi_tindakan ,
                    subsidipemerintah_tindakan ,
                    subsisidirumahsakit_tindakan ,
                    uangditerima_tindakan ,
                    keterangantindakan ,
                    pembulatan ,
                    implementasi_id ,
                    is_dilakukan ,
                    pemakaianambulan_id ,
                    is_penatajasa ,
                    additional_riwayat ,
                    is_valid ,
                    kamarruangan_id ,
                    kamartempattidur_id ,
                    penyulit_tindakan ,
                    tarifpenyulit_tindakan ,
                    additional_data ,
                    created_date ,
                    created_by ,
                    modified_count,
                    last_modified_date,
                    last_modified_by,
                    is_deleted,
                    is_active,
                    deleted_date,
                    deleted_by,
                    keterangan,
                    no_tindakanpelayanan,
                                        tarif_dijamin,
                                        tarif_dibayarkan,
                                        tarif_diskon,
                                        pembayaran_id
                )VALUES(
                    OLD.tindakanpelayanan_id ,
                    OLD.shift_id ,
                    OLD.kelaspelayanan_id ,
                    OLD.kelastanggungan_id ,
                    OLD.pasien_id ,
                    OLD.rencanaoperasi_id ,
                    OLD.instalasi_id ,
                    OLD.daftartindakan_id ,
                    OLD.alatmedis_id ,
                    OLD.tipepaket_id ,
                    OLD.tindakansudahbayar_id ,
                    OLD.carabayar_id ,
                    OLD.pendaftaran_id ,
                    OLD.hasilpemeriksaanrad_id ,
                    OLD.jeniskasuspenyakit_id ,
                    OLD.hasilpemeriksaanrm_id ,
                    OLD.ruangan_id ,
                    OLD.konsulpoli_id ,
                    OLD.pasienmasukpenunjang_id ,
                    OLD.hasilpemeriksaanlabdetail_id ,
                    OLD.penjamin_id ,
                    OLD.pasienadmisi_id ,
                    OLD.verifikasitagihan_id ,
                    OLD.jurnalrekening_id ,
                    OLD.instruksitindakan_id ,
                    OLD.tgl_tindakan ,
                    OLD.tarif_rsakomodasi ,
                    OLD.tarif_medis ,
                    OLD.tarif_paramedis ,
                    OLD.tarif_bhp ,
                    OLD.tarif_satuan ,
                    -1 * OLD.tarif_tindakan ,
                    OLD.tarifcyto_tindakan ,
                    OLD.satuan_tindakan ,
                    -1 * OLD.qty_tindakan ,
                    OLD.cyto_tindakan ,
                    OLD.dokterpenanggungjawab_id ,
                    OLD.dokterpelaksana_id ,
                    OLD.dokteranastesi_id ,
                    OLD.dokterdelegasi_id ,
                    OLD.bidan1_id ,
                    OLD.bidan2_id ,
                    OLD.perawat1_id ,
                    OLD.perawat2_id ,
                    OLD.discount_tindakan ,
                    OLD.pembebasan_tindakan ,
                    OLD.subsidiasuransi_tindakan ,
                    OLD.subsidipemerintah_tindakan ,
                    OLD.subsisidirumahsakit_tindakan ,
                    OLD.uangditerima_tindakan ,
                    OLD.keterangantindakan ,
                    OLD.pembulatan ,
                    OLD.implementasi_id ,
                    OLD.is_dilakukan ,
                    OLD.pemakaianambulan_id ,
                    OLD.is_penatajasa ,
                    OLD.additional_riwayat ,
                    OLD.is_valid ,
                    OLD.kamarruangan_id ,
                    OLD.kamartempattidur_id ,
                    OLD.penyulit_tindakan ,
                    OLD.tarifpenyulit_tindakan ,
                    OLD.additional_data ,
                    OLD.created_date ,
                    OLD.created_by ,
                    OLD.modified_count,
                    OLD.last_modified_date,
                    OLD.last_modified_by,
                    OLD.is_deleted,
                    OLD.is_active,
                    OLD.deleted_date,
                    OLD.deleted_by,
                    'ACCRUAL REVERSAL',
                    OLD.no_tindakanpelayanan,
                                        -1 * OLD.tarif_dijamin,
                                        -1 * OLD.tarif_dibayarkan,
                                        -1 * OLD.tarif_diskon,
                                        OLD.pembayaran_id
                );
        
            INSERT INTO tindakanpelayanan_r (       
                        tindakanpelayanan_id ,
                        shift_id ,
                        kelaspelayanan_id ,
                        kelastanggungan_id ,
                        pasien_id ,
                        rencanaoperasi_id ,
                        instalasi_id ,
                        daftartindakan_id ,
                        alatmedis_id ,
                        tipepaket_id ,
                        tindakansudahbayar_id ,
                        carabayar_id ,
                        pendaftaran_id ,
                        hasilpemeriksaanrad_id ,
                        jeniskasuspenyakit_id ,
                        hasilpemeriksaanrm_id ,
                        ruangan_id ,
                        konsulpoli_id ,
                        pasienmasukpenunjang_id ,
                        hasilpemeriksaanlabdetail_id ,
                        penjamin_id ,
                        pasienadmisi_id ,
                        verifikasitagihan_id ,
                        jurnalrekening_id ,
                        instruksitindakan_id ,
                        tgl_tindakan ,
                        tarif_rsakomodasi ,
                        tarif_medis ,
                        tarif_paramedis ,
                        tarif_bhp ,
                        tarif_satuan ,
                        tarif_tindakan ,
                        tarifcyto_tindakan ,
                        satuan_tindakan ,
                        qty_tindakan ,
                        cyto_tindakan ,
                        dokterpenanggungjawab_id ,
                        dokterpelaksana_id ,
                        dokteranastesi_id ,
                        dokterdelegasi_id ,
                        bidan1_id ,
                        bidan2_id ,
                        perawat1_id ,
                        perawat2_id ,
                        discount_tindakan ,
                        pembebasan_tindakan ,
                        subsidiasuransi_tindakan ,
                        subsidipemerintah_tindakan ,
                        subsisidirumahsakit_tindakan ,
                        uangditerima_tindakan ,
                        keterangantindakan ,
                        pembulatan ,
                        implementasi_id ,
                        is_dilakukan ,
                        pemakaianambulan_id ,
                        is_penatajasa ,
                        additional_riwayat ,
                        is_valid ,
                        kamarruangan_id ,
                        kamartempattidur_id ,
                        penyulit_tindakan ,
                        tarifpenyulit_tindakan ,
                        additional_data ,
                        created_date ,
                        created_by ,
                        modified_count,
                        last_modified_date,
                        last_modified_by,
                        is_deleted,
                        is_active,
                        deleted_date,
                        deleted_by,
                        keterangan,
                        no_tindakanpelayanan,
                                                tarif_dijamin,
                                                tarif_dibayarkan,
                                                tarif_diskon,
                                                pembayaran_id
                    )VALUES(
                        OLD.tindakanpelayanan_id ,
                        OLD.shift_id ,
                        OLD.kelaspelayanan_id ,
                        OLD.kelastanggungan_id ,
                        OLD.pasien_id ,
                        OLD.rencanaoperasi_id ,
                        OLD.instalasi_id ,
                        OLD.daftartindakan_id ,
                        OLD.alatmedis_id ,
                        OLD.tipepaket_id ,
                        OLD.tindakansudahbayar_id ,
                        OLD.carabayar_id ,
                        OLD.pendaftaran_id ,
                        OLD.hasilpemeriksaanrad_id ,
                        OLD.jeniskasuspenyakit_id ,
                        OLD.hasilpemeriksaanrm_id ,
                        OLD.ruangan_id ,
                        OLD.konsulpoli_id ,
                        OLD.pasienmasukpenunjang_id ,
                        OLD.hasilpemeriksaanlabdetail_id ,
                        OLD.penjamin_id ,
                        OLD.pasienadmisi_id ,
                        OLD.verifikasitagihan_id ,
                        OLD.jurnalrekening_id ,
                        OLD.instruksitindakan_id ,
                        OLD.tgl_tindakan ,
                        OLD.tarif_rsakomodasi ,
                        OLD.tarif_medis ,
                        OLD.tarif_paramedis ,
                        OLD.tarif_bhp ,
                        OLD.tarif_satuan ,
                        OLD.tarif_tindakan ,
                        OLD.tarifcyto_tindakan ,
                        OLD.satuan_tindakan ,
                        OLD.qty_tindakan ,
                        OLD.cyto_tindakan ,
                        OLD.dokterpenanggungjawab_id ,
                        OLD.dokterpelaksana_id ,
                        OLD.dokteranastesi_id ,
                        OLD.dokterdelegasi_id ,
                        OLD.bidan1_id ,
                        OLD.bidan2_id ,
                        OLD.perawat1_id ,
                        OLD.perawat2_id ,
                        OLD.discount_tindakan ,
                        OLD.pembebasan_tindakan ,
                        OLD.subsidiasuransi_tindakan ,
                        OLD.subsidipemerintah_tindakan ,
                        OLD.subsisidirumahsakit_tindakan ,
                        OLD.uangditerima_tindakan ,
                        OLD.keterangantindakan ,
                        OLD.pembulatan ,
                        OLD.implementasi_id ,
                        OLD.is_dilakukan ,
                        OLD.pemakaianambulan_id ,
                        OLD.is_penatajasa ,
                        OLD.additional_riwayat ,
                        OLD.is_valid ,
                        OLD.kamarruangan_id ,
                        OLD.kamartempattidur_id ,
                        OLD.penyulit_tindakan ,
                        OLD.tarifpenyulit_tindakan ,
                        OLD.additional_data ,
                        OLD.created_date ,
                        OLD.created_by ,
                        OLD.modified_count,
                        OLD.last_modified_date,
                        OLD.last_modified_by,
                        OLD.is_deleted,
                        OLD.is_active,
                        OLD.deleted_date,
                        OLD.deleted_by,
                        'ACCRUAL',
                        OLD.no_tindakanpelayanan,
                                                NEW.tarif_dijamin,
                                                NEW.tarif_dibayarkan,
                                                NEW.tarif_diskon,
                                                NEW.pembayaran_id
                    );

            
    END IF;
RETURN NEW;

END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

    $this->execute('ALTER FUNCTION "public"."tindakanpelayanan_r_update"() OWNER TO "postgres";');

    $this->execute("
        CREATE OR REPLACE FUNCTION \"public\".\"tindakansudahbayar_t_cancel\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$ 
    
DECLARE
        v_keterangan VARCHAR;
    BEGIN
        IF(NEW.is_deleted IS TRUE)
        THEN
            -- INSERT table history tindakanpelayanan_r menjadi ACCRUAL(+), jika is_deleted=TRUE
            INSERT INTO tindakanpelayanan_r (       
                tindakanpelayanan_id ,
                shift_id ,
                kelaspelayanan_id ,
                kelastanggungan_id ,
                pasien_id ,
                rencanaoperasi_id ,
                instalasi_id ,
                daftartindakan_id ,
                alatmedis_id ,
                tipepaket_id ,
                tindakansudahbayar_id ,
                carabayar_id ,
                pendaftaran_id ,
                hasilpemeriksaanrad_id ,
                jeniskasuspenyakit_id ,
                hasilpemeriksaanrm_id ,
                ruangan_id ,
                konsulpoli_id ,
                pasienmasukpenunjang_id ,
                hasilpemeriksaanlabdetail_id ,
                penjamin_id ,
                pasienadmisi_id ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                instruksitindakan_id ,
                tgl_tindakan ,
                tarif_rsakomodasi ,
                tarif_medis ,
                tarif_paramedis ,
                tarif_bhp ,
                tarif_satuan ,
                tarif_tindakan ,
                tarifcyto_tindakan ,
                satuan_tindakan ,
                qty_tindakan ,
                cyto_tindakan ,
                dokterpenanggungjawab_id ,
                dokterpelaksana_id ,
                dokteranastesi_id ,
                dokterdelegasi_id ,
                bidan1_id ,
                bidan2_id ,
                perawat1_id ,
                perawat2_id ,
                discount_tindakan ,
                pembebasan_tindakan ,
                subsidiasuransi_tindakan ,
                subsidipemerintah_tindakan ,
                subsisidirumahsakit_tindakan ,
                uangditerima_tindakan ,
                keterangantindakan ,
                pembulatan ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_penatajasa ,
                additional_riwayat ,
                is_valid ,
                kamarruangan_id ,
                kamartempattidur_id ,
                penyulit_tindakan ,
                tarifpenyulit_tindakan ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date ,
                deleted_by ,
                keterangan,
                no_tindakanpelayanan,
                                tarif_dijamin,
                                tarif_dibayarkan,
                                tarif_diskon,
                                pembayaran_id
                )
                SELECT
                tindakanpelayanan_id ,
                shift_id ,
                kelaspelayanan_id ,
                kelastanggungan_id ,
                pasien_id ,
                rencanaoperasi_id ,
                instalasi_id ,
                daftartindakan_id ,
                alatmedis_id ,
                tipepaket_id ,
                NULL,
                carabayar_id ,
                pendaftaran_id ,
                hasilpemeriksaanrad_id ,
                jeniskasuspenyakit_id ,
                hasilpemeriksaanrm_id ,
                ruangan_id ,
                konsulpoli_id ,
                pasienmasukpenunjang_id ,
                hasilpemeriksaanlabdetail_id ,
                penjamin_id ,
                pasienadmisi_id ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                instruksitindakan_id ,
                tgl_tindakan ,
                tarif_rsakomodasi ,
                tarif_medis ,
                tarif_paramedis ,
                tarif_bhp ,
                tarif_satuan ,
                tarif_tindakan ,
                tarifcyto_tindakan ,
                satuan_tindakan ,
                qty_tindakan ,
                cyto_tindakan ,
                dokterpenanggungjawab_id ,
                dokterpelaksana_id ,
                dokteranastesi_id ,
                dokterdelegasi_id ,
                bidan1_id ,
                bidan2_id ,
                perawat1_id ,
                perawat2_id ,
                discount_tindakan ,
                pembebasan_tindakan ,
                subsidiasuransi_tindakan ,
                subsidipemerintah_tindakan ,
                subsisidirumahsakit_tindakan ,
                uangditerima_tindakan ,
                keterangantindakan ,
                pembulatan ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_penatajasa ,
                additional_riwayat ,
                is_valid ,
                kamarruangan_id ,
                kamartempattidur_id ,
                penyulit_tindakan ,
                tarifpenyulit_tindakan ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date ,
                deleted_by ,
                'ACCRUAL',
                no_tindakanpelayanan,
                                0,
                                0,
                                0,
                                NULL
                FROM tindakanpelayanan_t
            WHERE tindakanpelayanan_id = NEW.tindakanpelayanan_id;
        
        
            -- INSERT table history tindakanpelayanan_r menjadi BILLING CANCEL(-), jika is_deleted=TRUE
                INSERT INTO tindakanpelayanan_r (       
                    tindakanpelayanan_id ,
                    shift_id ,
                    kelaspelayanan_id ,
                    kelastanggungan_id ,
                    pasien_id ,
                    rencanaoperasi_id ,
                    instalasi_id ,
                    daftartindakan_id ,
                    alatmedis_id ,
                    tipepaket_id ,
                    tindakansudahbayar_id ,
                    carabayar_id ,
                    pendaftaran_id ,
                    hasilpemeriksaanrad_id ,
                    jeniskasuspenyakit_id ,
                    hasilpemeriksaanrm_id ,
                    ruangan_id ,
                    konsulpoli_id ,
                    pasienmasukpenunjang_id ,
                    hasilpemeriksaanlabdetail_id ,
                    penjamin_id ,
                    pasienadmisi_id ,
                    verifikasitagihan_id ,
                    jurnalrekening_id ,
                    instruksitindakan_id ,
                    tgl_tindakan ,
                    tarif_rsakomodasi ,
                    tarif_medis ,
                    tarif_paramedis ,
                    tarif_bhp ,
                    tarif_satuan ,
                    tarif_tindakan ,
                    tarifcyto_tindakan ,
                    satuan_tindakan ,
                    qty_tindakan ,
                    cyto_tindakan ,
                    dokterpenanggungjawab_id ,
                    dokterpelaksana_id ,
                    dokteranastesi_id ,
                    dokterdelegasi_id ,
                    bidan1_id ,
                    bidan2_id ,
                    perawat1_id ,
                    perawat2_id ,
                    discount_tindakan ,
                    pembebasan_tindakan ,
                    subsidiasuransi_tindakan ,
                    subsidipemerintah_tindakan ,
                    subsisidirumahsakit_tindakan ,
                    uangditerima_tindakan ,
                    keterangantindakan ,
                    pembulatan ,
                    implementasi_id ,
                    is_dilakukan ,
                    pemakaianambulan_id ,
                    is_penatajasa ,
                    additional_riwayat ,
                    is_valid ,
                    kamarruangan_id ,
                    kamartempattidur_id ,
                    penyulit_tindakan ,
                    tarifpenyulit_tindakan ,
                    additional_data ,
                    created_date ,
                    created_by ,
                    modified_count ,
                    last_modified_date ,
                    last_modified_by ,
                    is_deleted ,
                    is_active ,
                    deleted_date ,
                    deleted_by ,
                    keterangan,
                    no_tindakanpelayanan,
                                        tarif_dijamin,
                                        tarif_dibayarkan,
                                        tarif_diskon,
                                        pembayaran_id
                    )
                    SELECT
                    tindakanpelayanan_id ,
                    shift_id ,
                    kelaspelayanan_id ,
                    kelastanggungan_id ,
                    pasien_id ,
                    rencanaoperasi_id ,
                    instalasi_id ,
                    daftartindakan_id ,
                    alatmedis_id ,
                    tipepaket_id ,
                    NEW.tindakansudahbayar_id ,
                    carabayar_id ,
                    pendaftaran_id ,
                    hasilpemeriksaanrad_id ,
                    jeniskasuspenyakit_id ,
                    hasilpemeriksaanrm_id ,
                    ruangan_id ,
                    konsulpoli_id ,
                    pasienmasukpenunjang_id ,
                    hasilpemeriksaanlabdetail_id ,
                    penjamin_id ,
                    pasienadmisi_id ,
                    verifikasitagihan_id ,
                    jurnalrekening_id ,
                    instruksitindakan_id ,
                    tgl_tindakan ,
                    tarif_rsakomodasi ,
                    tarif_medis ,
                    tarif_paramedis ,
                    tarif_bhp ,
                    tarif_satuan ,
                    -1 * tarif_tindakan ,
                    tarifcyto_tindakan ,
                    satuan_tindakan ,
                    -1 * qty_tindakan ,
                    cyto_tindakan ,
                    dokterpenanggungjawab_id ,
                    dokterpelaksana_id ,
                    dokteranastesi_id ,
                    dokterdelegasi_id ,
                    bidan1_id ,
                    bidan2_id ,
                    perawat1_id ,
                    perawat2_id ,
                    discount_tindakan ,
                    pembebasan_tindakan ,
                    subsidiasuransi_tindakan ,
                    subsidipemerintah_tindakan ,
                    subsisidirumahsakit_tindakan ,
                    uangditerima_tindakan ,
                    keterangantindakan ,
                    pembulatan ,
                    implementasi_id ,
                    is_dilakukan ,
                    pemakaianambulan_id ,
                    is_penatajasa ,
                    additional_riwayat ,
                    is_valid ,
                    kamarruangan_id ,
                    kamartempattidur_id ,
                    penyulit_tindakan ,
                    tarifpenyulit_tindakan ,
                    additional_data ,
                    created_date ,
                    created_by ,
                    modified_count ,
                    last_modified_date ,
                    last_modified_by ,
                    is_deleted ,
                    is_active ,
                    deleted_date ,
                    deleted_by ,
                    'BILLING CANCEL',
                    no_tindakanpelayanan,
                                        -1 * ((OLD.additional_data::json->>'data_dijamin')::json->>'dijamin')::float,
                                        -1 * ((OLD.additional_data::json->>'data_dijamin')::json->>'harusbayar')::float,
                                        -1 * (OLD.additional_data::json->>'tarif_diskon')::float,
                                        OLD.pembayaran_id 
                    FROM tindakanpelayanan_t
                WHERE tindakanpelayanan_id = NEW.tindakanpelayanan_id;
                
    END IF;
    
    RETURN NEW;

END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

    $this->execute('ALTER FUNCTION "public"."tindakansudahbayar_t_cancel"() OWNER TO "postgres";');

    $this->execute("
        CREATE OR REPLACE FUNCTION \"public\".\"tindakansudahbayar_t_insert\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$

BEGIN
        -- INSERT table history tindakanpelayanan_r BILLING(+)
        INSERT INTO tindakanpelayanan_r (       
            tindakanpelayanan_id ,
            shift_id ,
            kelaspelayanan_id ,
            kelastanggungan_id ,
            pasien_id ,
            rencanaoperasi_id ,
            instalasi_id ,
            daftartindakan_id ,
            alatmedis_id ,
            tipepaket_id ,
            tindakansudahbayar_id ,
            carabayar_id ,
            pendaftaran_id ,
            hasilpemeriksaanrad_id ,
            jeniskasuspenyakit_id ,
            hasilpemeriksaanrm_id ,
            ruangan_id ,
            konsulpoli_id ,
            pasienmasukpenunjang_id ,
            hasilpemeriksaanlabdetail_id ,
            penjamin_id ,
            pasienadmisi_id ,
            verifikasitagihan_id ,
            jurnalrekening_id ,
            instruksitindakan_id ,
            tgl_tindakan ,
            tarif_rsakomodasi ,
            tarif_medis ,
            tarif_paramedis ,
            tarif_bhp ,
            tarif_satuan ,
            tarif_tindakan ,
            tarifcyto_tindakan ,
            satuan_tindakan ,
            qty_tindakan ,
            cyto_tindakan ,
            dokterpenanggungjawab_id ,
            dokterpelaksana_id ,
            dokteranastesi_id ,
            dokterdelegasi_id ,
            bidan1_id ,
            bidan2_id ,
            perawat1_id ,
            perawat2_id ,
            discount_tindakan ,
            pembebasan_tindakan ,
            subsidiasuransi_tindakan ,
            subsidipemerintah_tindakan ,
            subsisidirumahsakit_tindakan ,
            uangditerima_tindakan ,
            keterangantindakan ,
            pembulatan ,
            implementasi_id ,
            is_dilakukan ,
            pemakaianambulan_id ,
            is_penatajasa ,
            additional_riwayat ,
            is_valid ,
            kamarruangan_id ,
            kamartempattidur_id ,
            penyulit_tindakan ,
            tarifpenyulit_tindakan ,
            additional_data ,
            created_date ,
            created_by ,
            keterangan,
            no_tindakanpelayanan,
            tarif_dijamin,
            tarif_dibayarkan,
                        tarif_diskon,
                        pembayaran_id
        )
        SELECT  
            tindakanpelayanan_id ,
            shift_id ,
            kelaspelayanan_id ,
            kelastanggungan_id ,
            pasien_id ,
            rencanaoperasi_id ,
            instalasi_id ,
            daftartindakan_id ,
            alatmedis_id ,
            tipepaket_id ,
            NEW.tindakansudahbayar_id,
            carabayar_id ,
            pendaftaran_id ,
            hasilpemeriksaanrad_id ,
            jeniskasuspenyakit_id ,
            hasilpemeriksaanrm_id ,
            ruangan_id ,
            konsulpoli_id ,
            pasienmasukpenunjang_id ,
            hasilpemeriksaanlabdetail_id ,
            penjamin_id ,
            pasienadmisi_id ,
            verifikasitagihan_id ,
            jurnalrekening_id ,
            instruksitindakan_id ,
            tgl_tindakan ,
            tarif_rsakomodasi ,
            tarif_medis ,
            tarif_paramedis ,
            tarif_bhp ,
            tarif_satuan ,
            tarif_tindakan ,
            tarifcyto_tindakan ,
            satuan_tindakan ,
            qty_tindakan ,
            cyto_tindakan ,
            dokterpenanggungjawab_id ,
            dokterpelaksana_id ,
            dokteranastesi_id ,
            dokterdelegasi_id ,
            bidan1_id ,
            bidan2_id ,
            perawat1_id ,
            perawat2_id ,
            discount_tindakan ,
            pembebasan_tindakan ,
            subsidiasuransi_tindakan ,
            subsidipemerintah_tindakan ,
            subsisidirumahsakit_tindakan ,
            uangditerima_tindakan ,
            keterangantindakan ,
            pembulatan ,
            implementasi_id ,
            is_dilakukan ,
            pemakaianambulan_id ,
            is_penatajasa ,
            additional_riwayat ,
            is_valid ,
            kamarruangan_id ,
            kamartempattidur_id ,
            penyulit_tindakan ,
            tarifpenyulit_tindakan ,
            additional_data ,
            created_date ,
            created_by ,
            'BILLING',
            no_tindakanpelayanan,
                        ((NEW.additional_data::json->>'data_dijamin')::json->>'dijamin')::float,
                        ((NEW.additional_data::json->>'data_dijamin')::json->>'harusbayar')::float,
                        (NEW.additional_data::json->>'tarif_diskon')::float,
                        NEW.pembayaran_id
    FROM tindakanpelayanan_t
    WHERE tindakanpelayanan_id = NEW.tindakanpelayanan_id;
    
    RETURN NEW;

END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

    $this->execute('ALTER FUNCTION "public"."tindakansudahbayar_t_insert"() OWNER TO "postgres";');

    

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m210426_020515_oddo_20210426_penyesuaianfunction cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m210426_020515_oddo_20210426_penyesuaianfunction cannot be reverted.\n";

        return false;
    }
    */
}
