<?php

use yii\db\Migration;

/**
 * Class m210413_061637_oddo_20210413_penyesuaiantrigger
 */
class m210413_061637_oddo_20210413_penyesuaiantrigger extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
    
    $this->execute("
        CREATE OR REPLACE FUNCTION \"public\".\"obatsudahbayar_t_cancel\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$ 
    
DECLARE
        v_keterangan VARCHAR;
    BEGIN
        IF(NEW.is_deleted IS TRUE)
        THEN
            -- INSERT table history obatalkespasien_r menjadi ACCRUAL(+), jika is_deleted=TRUE
            INSERT INTO obatalkespasien_r (     
                obatalkespasien_id ,
                sumberdana_id ,
                racikan_id ,
                returresepdetail_id ,
                tipepaket_id ,
                ruangan_id ,
                carabayar_id ,
                pegawai_id ,
                daftartindakan_id ,
                tindakanpelayanan_id ,
                satuankecil_id ,
                shift_id ,
                pendaftaran_id ,
                obatalkes_id ,
                pasien_id ,
                penjamin_id ,
                kelaspelayanan_id ,
                pasienanastesi_id ,
                pasienmasukpenunjang_id ,
                pasienadmisi_id ,
                obatsudahbayar_id ,
                penjualanresep_id ,
                tglpelayanan ,
                r ,
                rke ,
                permintaan_oa ,
                jmlkemasan_oa ,
                kekuatan_oa ,
                satuankekuatan_oa ,
                qty_oa ,
                hargasatuan_oa ,
                signa_oa ,
                harganetto_oa ,
                hargajual_oa , 
                etiket ,
                jmlexposerad ,
                kontrasrad ,
                biayaservice ,
                biayakonseling ,
                jasadokterresep ,
                biayakemasan ,
                biayaadministrasi ,
                tarifcyto ,
                discount , 
                subsidiasuransi ,
                subsidipemerintah ,
                subsidirs ,
                iurbiaya ,
                oa ,
                pembulatan ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                permohonanoadetail_id ,
                persenppnjual ,
                resepturdetail_id ,
                nilaippnjual ,
                perawat1_id ,
                perawat2_id ,
                instruksitindakanbmhp_id ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_jurnal ,
                konfigmargindetail_id ,
                qty_konversi ,
                is_penatajasa ,
                det ,
                status_bmhp ,
                det_konversi ,
                signa ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date , 
                deleted_by ,
                keterangan,
                                no_obatalkespasien,
                                tarif_dijamin,
                                tarif_dibayarkan,
                                tarif_diskon
                )
                SELECT
                obatalkespasien_id ,
                sumberdana_id ,
                racikan_id ,
                returresepdetail_id ,
                tipepaket_id ,
                ruangan_id ,
                carabayar_id ,
                pegawai_id ,
                daftartindakan_id ,
                tindakanpelayanan_id ,
                satuankecil_id ,
                shift_id ,
                pendaftaran_id ,
                obatalkes_id ,
                pasien_id ,
                penjamin_id ,
                kelaspelayanan_id ,
                pasienanastesi_id ,
                pasienmasukpenunjang_id ,
                pasienadmisi_id ,
                NEW.obatsudahbayar_id ,
                penjualanresep_id ,
                tglpelayanan ,
                r ,
                rke ,
                permintaan_oa ,
                jmlkemasan_oa ,
                kekuatan_oa ,
                satuankekuatan_oa ,
                qty_oa ,
                hargasatuan_oa ,
                signa_oa ,
                harganetto_oa ,
                hargajual_oa , 
                etiket ,
                jmlexposerad ,
                kontrasrad ,
                biayaservice ,
                biayakonseling ,
                jasadokterresep ,
                biayakemasan ,
                biayaadministrasi ,
                tarifcyto ,
                discount , 
                subsidiasuransi ,
                subsidipemerintah ,
                subsidirs ,
                iurbiaya ,
                oa ,
                pembulatan ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                permohonanoadetail_id ,
                persenppnjual ,
                resepturdetail_id ,
                nilaippnjual ,
                perawat1_id ,
                perawat2_id ,
                instruksitindakanbmhp_id ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_jurnal ,
                konfigmargindetail_id ,
                qty_konversi ,
                is_penatajasa ,
                det ,
                status_bmhp ,
                det_konversi ,
                signa ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date , 
                deleted_by ,
                'ACCRUAL',
                                no_obatalkespasien,
                                0,
                                0,
                                0
                FROM obatalkespasien_t
            WHERE obatalkespasien_id = NEW.obatalkespasien_id;
        
            -- INSERT table history obatalkespasien_r menjadi BILLING CANCEL(-), jika is_deleted=TRUE
                INSERT INTO obatalkespasien_r (     
                    obatalkespasien_id ,
                    sumberdana_id ,
                    racikan_id ,
                    returresepdetail_id ,
                    tipepaket_id ,
                    ruangan_id ,
                    carabayar_id ,
                    pegawai_id ,
                    daftartindakan_id ,
                    tindakanpelayanan_id ,
                    satuankecil_id ,
                    shift_id ,
                    pendaftaran_id ,
                    obatalkes_id ,
                    pasien_id ,
                    penjamin_id ,
                    kelaspelayanan_id ,
                    pasienanastesi_id ,
                    pasienmasukpenunjang_id ,
                    pasienadmisi_id ,
                    obatsudahbayar_id ,
                    penjualanresep_id ,
                    tglpelayanan ,
                    r ,
                    rke ,
                    permintaan_oa ,
                    jmlkemasan_oa ,
                    kekuatan_oa ,
                    satuankekuatan_oa ,
                    qty_oa ,
                    hargasatuan_oa ,
                    signa_oa ,
                    harganetto_oa ,
                    hargajual_oa , 
                    etiket ,
                    jmlexposerad ,
                    kontrasrad ,
                    biayaservice ,
                    biayakonseling ,
                    jasadokterresep ,
                    biayakemasan ,
                    biayaadministrasi ,
                    tarifcyto ,
                    discount , 
                    subsidiasuransi ,
                    subsidipemerintah ,
                    subsidirs ,
                    iurbiaya ,
                    oa ,
                    pembulatan ,
                    verifikasitagihan_id ,
                    jurnalrekening_id ,
                    permohonanoadetail_id ,
                    persenppnjual ,
                    resepturdetail_id ,
                    nilaippnjual ,
                    perawat1_id ,
                    perawat2_id ,
                    instruksitindakanbmhp_id ,
                    implementasi_id ,
                    is_dilakukan ,
                    pemakaianambulan_id ,
                    is_jurnal ,
                    konfigmargindetail_id ,
                    qty_konversi ,
                    is_penatajasa ,
                    det ,
                    status_bmhp ,
                    det_konversi ,
                    signa ,
                    additional_data ,
                    created_date ,
                    created_by ,
                    modified_count ,
                    last_modified_date ,
                    last_modified_by ,
                    is_deleted ,
                    is_active ,
                    deleted_date , 
                    deleted_by ,
                    keterangan,
                                        no_obatalkespasien,
                                        tarif_dijamin,
                                        tarif_dibayarkan,
                                        tarif_diskon
                    )
                    SELECT
                    obatalkespasien_id ,
                    sumberdana_id ,
                    racikan_id ,
                    returresepdetail_id ,
                    tipepaket_id ,
                    ruangan_id ,
                    carabayar_id ,
                    pegawai_id ,
                    daftartindakan_id ,
                    tindakanpelayanan_id ,
                    satuankecil_id ,
                    shift_id ,
                    pendaftaran_id ,
                    obatalkes_id ,
                    pasien_id ,
                    penjamin_id ,
                    kelaspelayanan_id ,
                    pasienanastesi_id ,
                    pasienmasukpenunjang_id ,
                    pasienadmisi_id ,
                    NEW.obatsudahbayar_id ,
                    penjualanresep_id ,
                    tglpelayanan ,
                    r ,
                    rke ,
                    permintaan_oa ,
                    jmlkemasan_oa ,
                    kekuatan_oa ,
                    satuankekuatan_oa ,
                    -1 * qty_oa ,
                    hargasatuan_oa ,
                    signa_oa ,
                    harganetto_oa ,
                    -1 * hargajual_oa,  
                    etiket ,
                    jmlexposerad ,
                    kontrasrad ,
                    biayaservice ,
                    biayakonseling ,
                    jasadokterresep ,
                    biayakemasan ,
                    biayaadministrasi ,
                    tarifcyto ,
                    discount , 
                    subsidiasuransi ,
                    subsidipemerintah ,
                    subsidirs ,
                    iurbiaya ,
                    oa ,
                    pembulatan ,
                    verifikasitagihan_id ,
                    jurnalrekening_id ,
                    permohonanoadetail_id ,
                    persenppnjual ,
                    resepturdetail_id ,
                    nilaippnjual ,
                    perawat1_id ,
                    perawat2_id ,
                    instruksitindakanbmhp_id ,
                    implementasi_id ,
                    is_dilakukan ,
                    pemakaianambulan_id ,
                    is_jurnal ,
                    konfigmargindetail_id ,
                    -1 * qty_konversi ,
                    is_penatajasa ,
                    -1 * det ,
                    status_bmhp ,
                    det_konversi ,
                    signa ,
                    additional_data ,
                    created_date ,
                    created_by ,
                    modified_count ,
                    last_modified_date ,
                    last_modified_by ,
                    is_deleted ,
                    is_active ,
                    deleted_date , 
                    deleted_by ,
                    'BILLING CANCEL',
                                        no_obatalkespasien,
                                        -1 * ((OLD.additional_data::json->>'data_dijamin')::json->>'dijamin')::float,
                                        -1 * ((OLD.additional_data::json->>'data_dijamin')::json->>'harusbayar')::float, 
                                        -1 * (OLD.additional_data::json->>'tarif_diskon')::float 
                    FROM obatalkespasien_t
                WHERE obatalkespasien_id = NEW.obatalkespasien_id;
                
    END IF;
    
    RETURN NEW;

END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

        $this->execute('ALTER FUNCTION "public"."obatsudahbayar_t_cancel"() OWNER TO "postgres";');


    $this->execute("
        CREATE OR REPLACE FUNCTION \"public\".\"tindakansudahbayar_t_cancel\"()
  RETURNS \"pg_catalog\".\"trigger\" AS \$BODY\$ 
    
DECLARE
        v_keterangan VARCHAR;
    BEGIN
        IF(NEW.is_deleted IS TRUE)
        THEN
            -- INSERT table history tindakanpelayanan_r menjadi ACCRUAL(+), jika is_deleted=TRUE
            INSERT INTO tindakanpelayanan_r (       
                tindakanpelayanan_id ,
                shift_id ,
                kelaspelayanan_id ,
                kelastanggungan_id ,
                pasien_id ,
                rencanaoperasi_id ,
                instalasi_id ,
                daftartindakan_id ,
                alatmedis_id ,
                tipepaket_id ,
                tindakansudahbayar_id ,
                carabayar_id ,
                pendaftaran_id ,
                hasilpemeriksaanrad_id ,
                jeniskasuspenyakit_id ,
                hasilpemeriksaanrm_id ,
                ruangan_id ,
                konsulpoli_id ,
                pasienmasukpenunjang_id ,
                hasilpemeriksaanlabdetail_id ,
                penjamin_id ,
                pasienadmisi_id ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                instruksitindakan_id ,
                tgl_tindakan ,
                tarif_rsakomodasi ,
                tarif_medis ,
                tarif_paramedis ,
                tarif_bhp ,
                tarif_satuan ,
                tarif_tindakan ,
                tarifcyto_tindakan ,
                satuan_tindakan ,
                qty_tindakan ,
                cyto_tindakan ,
                dokterpenanggungjawab_id ,
                dokterpelaksana_id ,
                dokteranastesi_id ,
                dokterdelegasi_id ,
                bidan1_id ,
                bidan2_id ,
                perawat1_id ,
                perawat2_id ,
                discount_tindakan ,
                pembebasan_tindakan ,
                subsidiasuransi_tindakan ,
                subsidipemerintah_tindakan ,
                subsisidirumahsakit_tindakan ,
                uangditerima_tindakan ,
                keterangantindakan ,
                pembulatan ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_penatajasa ,
                additional_riwayat ,
                is_valid ,
                kamarruangan_id ,
                kamartempattidur_id ,
                penyulit_tindakan ,
                tarifpenyulit_tindakan ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date ,
                deleted_by ,
                keterangan,
                no_tindakanpelayanan,
                                tarif_dijamin,
                                tarif_dibayarkan,
                                tarif_diskon
                )
                SELECT
                tindakanpelayanan_id ,
                shift_id ,
                kelaspelayanan_id ,
                kelastanggungan_id ,
                pasien_id ,
                rencanaoperasi_id ,
                instalasi_id ,
                daftartindakan_id ,
                alatmedis_id ,
                tipepaket_id ,
                NEW.tindakansudahbayar_id ,
                carabayar_id ,
                pendaftaran_id ,
                hasilpemeriksaanrad_id ,
                jeniskasuspenyakit_id ,
                hasilpemeriksaanrm_id ,
                ruangan_id ,
                konsulpoli_id ,
                pasienmasukpenunjang_id ,
                hasilpemeriksaanlabdetail_id ,
                penjamin_id ,
                pasienadmisi_id ,
                verifikasitagihan_id ,
                jurnalrekening_id ,
                instruksitindakan_id ,
                tgl_tindakan ,
                tarif_rsakomodasi ,
                tarif_medis ,
                tarif_paramedis ,
                tarif_bhp ,
                tarif_satuan ,
                tarif_tindakan ,
                tarifcyto_tindakan ,
                satuan_tindakan ,
                qty_tindakan ,
                cyto_tindakan ,
                dokterpenanggungjawab_id ,
                dokterpelaksana_id ,
                dokteranastesi_id ,
                dokterdelegasi_id ,
                bidan1_id ,
                bidan2_id ,
                perawat1_id ,
                perawat2_id ,
                discount_tindakan ,
                pembebasan_tindakan ,
                subsidiasuransi_tindakan ,
                subsidipemerintah_tindakan ,
                subsisidirumahsakit_tindakan ,
                uangditerima_tindakan ,
                keterangantindakan ,
                pembulatan ,
                implementasi_id ,
                is_dilakukan ,
                pemakaianambulan_id ,
                is_penatajasa ,
                additional_riwayat ,
                is_valid ,
                kamarruangan_id ,
                kamartempattidur_id ,
                penyulit_tindakan ,
                tarifpenyulit_tindakan ,
                additional_data ,
                created_date ,
                created_by ,
                modified_count ,
                last_modified_date ,
                last_modified_by ,
                is_deleted ,
                is_active ,
                deleted_date ,
                deleted_by ,
                'ACCRUAL',
                no_tindakanpelayanan,
                                0,
                                0,
                                0
                FROM tindakanpelayanan_t
            WHERE tindakanpelayanan_id = NEW.tindakanpelayanan_id;
        
        
            -- INSERT table history tindakanpelayanan_r menjadi BILLING CANCEL(-), jika is_deleted=TRUE
                INSERT INTO tindakanpelayanan_r (       
                    tindakanpelayanan_id ,
                    shift_id ,
                    kelaspelayanan_id ,
                    kelastanggungan_id ,
                    pasien_id ,
                    rencanaoperasi_id ,
                    instalasi_id ,
                    daftartindakan_id ,
                    alatmedis_id ,
                    tipepaket_id ,
                    tindakansudahbayar_id ,
                    carabayar_id ,
                    pendaftaran_id ,
                    hasilpemeriksaanrad_id ,
                    jeniskasuspenyakit_id ,
                    hasilpemeriksaanrm_id ,
                    ruangan_id ,
                    konsulpoli_id ,
                    pasienmasukpenunjang_id ,
                    hasilpemeriksaanlabdetail_id ,
                    penjamin_id ,
                    pasienadmisi_id ,
                    verifikasitagihan_id ,
                    jurnalrekening_id ,
                    instruksitindakan_id ,
                    tgl_tindakan ,
                    tarif_rsakomodasi ,
                    tarif_medis ,
                    tarif_paramedis ,
                    tarif_bhp ,
                    tarif_satuan ,
                    tarif_tindakan ,
                    tarifcyto_tindakan ,
                    satuan_tindakan ,
                    qty_tindakan ,
                    cyto_tindakan ,
                    dokterpenanggungjawab_id ,
                    dokterpelaksana_id ,
                    dokteranastesi_id ,
                    dokterdelegasi_id ,
                    bidan1_id ,
                    bidan2_id ,
                    perawat1_id ,
                    perawat2_id ,
                    discount_tindakan ,
                    pembebasan_tindakan ,
                    subsidiasuransi_tindakan ,
                    subsidipemerintah_tindakan ,
                    subsisidirumahsakit_tindakan ,
                    uangditerima_tindakan ,
                    keterangantindakan ,
                    pembulatan ,
                    implementasi_id ,
                    is_dilakukan ,
                    pemakaianambulan_id ,
                    is_penatajasa ,
                    additional_riwayat ,
                    is_valid ,
                    kamarruangan_id ,
                    kamartempattidur_id ,
                    penyulit_tindakan ,
                    tarifpenyulit_tindakan ,
                    additional_data ,
                    created_date ,
                    created_by ,
                    modified_count ,
                    last_modified_date ,
                    last_modified_by ,
                    is_deleted ,
                    is_active ,
                    deleted_date ,
                    deleted_by ,
                    keterangan,
                    no_tindakanpelayanan,
                                        tarif_dijamin,
                                        tarif_dibayarkan,
                                        tarif_diskon
                    )
                    SELECT
                    tindakanpelayanan_id ,
                    shift_id ,
                    kelaspelayanan_id ,
                    kelastanggungan_id ,
                    pasien_id ,
                    rencanaoperasi_id ,
                    instalasi_id ,
                    daftartindakan_id ,
                    alatmedis_id ,
                    tipepaket_id ,
                    NEW.tindakansudahbayar_id ,
                    carabayar_id ,
                    pendaftaran_id ,
                    hasilpemeriksaanrad_id ,
                    jeniskasuspenyakit_id ,
                    hasilpemeriksaanrm_id ,
                    ruangan_id ,
                    konsulpoli_id ,
                    pasienmasukpenunjang_id ,
                    hasilpemeriksaanlabdetail_id ,
                    penjamin_id ,
                    pasienadmisi_id ,
                    verifikasitagihan_id ,
                    jurnalrekening_id ,
                    instruksitindakan_id ,
                    tgl_tindakan ,
                    tarif_rsakomodasi ,
                    tarif_medis ,
                    tarif_paramedis ,
                    tarif_bhp ,
                    tarif_satuan ,
                    -1 * tarif_tindakan ,
                    tarifcyto_tindakan ,
                    satuan_tindakan ,
                    -1 * qty_tindakan ,
                    cyto_tindakan ,
                    dokterpenanggungjawab_id ,
                    dokterpelaksana_id ,
                    dokteranastesi_id ,
                    dokterdelegasi_id ,
                    bidan1_id ,
                    bidan2_id ,
                    perawat1_id ,
                    perawat2_id ,
                    discount_tindakan ,
                    pembebasan_tindakan ,
                    subsidiasuransi_tindakan ,
                    subsidipemerintah_tindakan ,
                    subsisidirumahsakit_tindakan ,
                    uangditerima_tindakan ,
                    keterangantindakan ,
                    pembulatan ,
                    implementasi_id ,
                    is_dilakukan ,
                    pemakaianambulan_id ,
                    is_penatajasa ,
                    additional_riwayat ,
                    is_valid ,
                    kamarruangan_id ,
                    kamartempattidur_id ,
                    penyulit_tindakan ,
                    tarifpenyulit_tindakan ,
                    additional_data ,
                    created_date ,
                    created_by ,
                    modified_count ,
                    last_modified_date ,
                    last_modified_by ,
                    is_deleted ,
                    is_active ,
                    deleted_date ,
                    deleted_by ,
                    'BILLING CANCEL',
                    no_tindakanpelayanan,
                                        -1 * ((OLD.additional_data::json->>'data_dijamin')::json->>'dijamin')::float,
                                        -1 * ((OLD.additional_data::json->>'data_dijamin')::json->>'harusbayar')::float,
                                        -1 * (OLD.additional_data::json->>'tarif_diskon')::float 
                    FROM tindakanpelayanan_t
                WHERE tindakanpelayanan_id = NEW.tindakanpelayanan_id;
                
    END IF;
    
    RETURN NEW;

END
\$BODY\$
  LANGUAGE plpgsql VOLATILE
  COST 100;");

    $this->execute('ALTER FUNCTION "public"."tindakansudahbayar_t_cancel"() OWNER TO "postgres";');

    $this->execute('DROP TRIGGER "pasien_r_update" ON "public"."pasien_m";');

    $this->execute('CREATE TRIGGER "pasien_r_update" AFTER UPDATE OF "nama_pasien", "no_rekam_medik", "alamat_sekarang", "alamat_pasien", "jenisidentitas", "tempat_lahir", "jeniskelamin", "namadepan", "no_telepon_pasien", "no_mobile_pasien", "alamatemail", "no_identitas_pasien", "tanggal_lahir" ON "public"."pasien_m"
FOR EACH ROW
EXECUTE PROCEDURE "public"."pasien_r_update"();');

    $this->execute('DROP TRIGGER "pendaftaran_r_update" ON "public"."pendaftaran_t";');

    $this->execute('CREATE TRIGGER "pendaftaran_r_update" AFTER UPDATE OF "pegawai_id", "instalasi_id", "no_pendaftaran", "pasien_id", "kelaspelayanan_id", "carabayar_id", "ruangan_id", "asuransipasien_id", "penjamin_id", "tgl_pendaftaran" ON "public"."pendaftaran_t"
FOR EACH ROW
EXECUTE PROCEDURE "public"."pendaftaran_r_update"();');
  

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m210413_061637_oddo_20210413_penyesuaiantrigger cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m210413_061637_oddo_20210413_penyesuaiantrigger cannot be reverted.\n";

        return false;
    }
    */
}
