<?php

use yii\db\Migration;

/**
 * Class m220729_100601_migrate_odoo_function_tindakanpelayanan_r_update
 */
class m220729_100601_migrate_odoo_function_tindakanpelayanan_r_update extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->execute('
            CREATE OR REPLACE FUNCTION "public"."tindakanpelayanan_r_update"()
              RETURNS "pg_catalog"."trigger" AS $BODY$

            DECLARE
                v_keterangan VARCHAR;
            BEGIN
                IF((NEW.is_deleted IS TRUE OR (NEW.tindakansudahbayar_id IS NOT NULL AND NEW.dokterpenanggungjawab_id = OLD.dokterpenanggungjawab_id)) AND OLD.is_deleted IS FALSE)
                    THEN
                        v_keterangan := \'ACCRUAL REVERSAL\';
                    --> INSERT table history tindakanpelayanan_r menjadi ACCRUAL REVERSAL(-)
                        INSERT INTO tindakanpelayanan_r (       
                        tindakanpelayanan_id ,
                        shift_id ,
                        kelaspelayanan_id ,
                        kelastanggungan_id ,
                        pasien_id ,
                        rencanaoperasi_id ,
                        instalasi_id ,
                        daftartindakan_id ,
                        alatmedis_id ,
                        tipepaket_id ,
                        tindakansudahbayar_id ,
                        carabayar_id ,
                        pendaftaran_id ,
                        hasilpemeriksaanrad_id ,
                        jeniskasuspenyakit_id ,
                        hasilpemeriksaanrm_id ,
                        ruangan_id ,
                        konsulpoli_id ,
                        pasienmasukpenunjang_id ,
                        hasilpemeriksaanlabdetail_id ,
                        penjamin_id ,
                        pasienadmisi_id ,
                        verifikasitagihan_id ,
                        jurnalrekening_id ,
                        instruksitindakan_id ,
                        tgl_tindakan ,
                        tarif_rsakomodasi ,
                        tarif_medis ,
                        tarif_paramedis ,
                        tarif_bhp ,
                        tarif_satuan ,
                        tarif_tindakan ,
                        tarifcyto_tindakan ,
                        satuan_tindakan ,
                        qty_tindakan ,
                        cyto_tindakan ,
                        dokterpenanggungjawab_id ,
                        dokterpelaksana_id ,
                        dokteranastesi_id ,
                        dokterdelegasi_id ,
                        bidan1_id ,
                        bidan2_id ,
                        perawat1_id ,
                        perawat2_id ,
                        discount_tindakan ,
                        pembebasan_tindakan ,
                        subsidiasuransi_tindakan ,
                        subsidipemerintah_tindakan ,
                        subsisidirumahsakit_tindakan ,
                        uangditerima_tindakan ,
                        keterangantindakan ,
                        pembulatan ,
                        implementasi_id ,
                        is_dilakukan ,
                        pemakaianambulan_id ,
                        is_penatajasa ,
                        additional_riwayat ,
                        is_valid ,
                        kamarruangan_id ,
                        kamartempattidur_id ,
                        penyulit_tindakan ,
                        tarifpenyulit_tindakan ,
                        additional_data ,
                        created_date ,
                        created_by ,
                        modified_count,
                        last_modified_date,
                        last_modified_by,
                        is_deleted,
                        is_active,
                        deleted_date,
                        deleted_by,
                        keterangan,
                        no_tindakanpelayanan,
                                    tarif_dijamin,
                                    tarif_dibayarkan,
                                    tarif_diskon,
                                    pembayaran_id
                    )VALUES(
                        OLD.tindakanpelayanan_id ,
                        OLD.shift_id ,
                        OLD.kelaspelayanan_id ,
                        OLD.kelastanggungan_id ,
                        OLD.pasien_id ,
                        OLD.rencanaoperasi_id ,
                        OLD.instalasi_id ,
                        OLD.daftartindakan_id ,
                        OLD.alatmedis_id ,
                        OLD.tipepaket_id ,
                        OLD.tindakansudahbayar_id ,
                        OLD.carabayar_id ,
                        OLD.pendaftaran_id ,
                        OLD.hasilpemeriksaanrad_id ,
                        OLD.jeniskasuspenyakit_id ,
                        OLD.hasilpemeriksaanrm_id ,
                        OLD.ruangan_id ,
                        OLD.konsulpoli_id ,
                        OLD.pasienmasukpenunjang_id ,
                        OLD.hasilpemeriksaanlabdetail_id ,
                        OLD.penjamin_id ,
                        OLD.pasienadmisi_id ,
                        OLD.verifikasitagihan_id ,
                        OLD.jurnalrekening_id ,
                        OLD.instruksitindakan_id ,
                        OLD.tgl_tindakan ,
                        OLD.tarif_rsakomodasi ,
                        OLD.tarif_medis ,
                        OLD.tarif_paramedis ,
                        OLD.tarif_bhp ,
                        OLD.tarif_satuan ,
                        -1 * OLD.tarif_tindakan ,
                        OLD.tarifcyto_tindakan ,
                        OLD.satuan_tindakan ,
                        -1 * OLD.qty_tindakan ,
                        OLD.cyto_tindakan ,
                        OLD.dokterpenanggungjawab_id ,
                        OLD.dokterpelaksana_id ,
                        OLD.dokteranastesi_id ,
                        OLD.dokterdelegasi_id ,
                        OLD.bidan1_id ,
                        OLD.bidan2_id ,
                        OLD.perawat1_id ,
                        OLD.perawat2_id ,
                        OLD.discount_tindakan ,
                        OLD.pembebasan_tindakan ,
                        OLD.subsidiasuransi_tindakan ,
                        OLD.subsidipemerintah_tindakan ,
                        OLD.subsisidirumahsakit_tindakan ,
                        OLD.uangditerima_tindakan ,
                        OLD.keterangantindakan ,
                        OLD.pembulatan ,
                        OLD.implementasi_id ,
                        OLD.is_dilakukan ,
                        OLD.pemakaianambulan_id ,
                        OLD.is_penatajasa ,
                        OLD.additional_riwayat ,
                        OLD.is_valid ,
                        OLD.kamarruangan_id ,
                        OLD.kamartempattidur_id ,
                        OLD.penyulit_tindakan ,
                        OLD.tarifpenyulit_tindakan ,
                        OLD.additional_data ,
                        OLD.created_date ,
                        OLD.created_by ,
                        OLD.modified_count,
                        OLD.last_modified_date,
                        OLD.last_modified_by,
                        OLD.is_deleted,
                        OLD.is_active,
                        OLD.deleted_date,
                        OLD.deleted_by,
                        v_keterangan,
                        OLD.no_tindakanpelayanan,
                                    0,
                                    0,
                                    0,
                                    NULL
                    );
                        RETURN NEW;
                        END IF;
                        
                        IF (old.tindakansudahbayar_id is null AND OLD.is_deleted= FALSE)
                            THEN    
                        -- INSERT table history tindakanpelayanan_r menjadi ACCRUAL REVERSAL(-) setelah BILLING CANCEL
                            INSERT INTO tindakanpelayanan_r (       
                                tindakanpelayanan_id ,
                                shift_id ,
                                kelaspelayanan_id ,
                                kelastanggungan_id ,
                                pasien_id ,
                                rencanaoperasi_id ,
                                instalasi_id ,
                                daftartindakan_id ,
                                alatmedis_id ,
                                tipepaket_id ,
                                tindakansudahbayar_id ,
                                carabayar_id ,
                                pendaftaran_id ,
                                hasilpemeriksaanrad_id ,
                                jeniskasuspenyakit_id ,
                                hasilpemeriksaanrm_id ,
                                ruangan_id ,
                                konsulpoli_id ,
                                pasienmasukpenunjang_id ,
                                hasilpemeriksaanlabdetail_id ,
                                penjamin_id ,
                                pasienadmisi_id ,
                                verifikasitagihan_id ,
                                jurnalrekening_id ,
                                instruksitindakan_id ,
                                tgl_tindakan ,
                                tarif_rsakomodasi ,
                                tarif_medis ,
                                tarif_paramedis ,
                                tarif_bhp ,
                                tarif_satuan ,
                                tarif_tindakan ,
                                tarifcyto_tindakan ,
                                satuan_tindakan ,
                                qty_tindakan ,
                                cyto_tindakan ,
                                dokterpenanggungjawab_id ,
                                dokterpelaksana_id ,
                                dokteranastesi_id ,
                                dokterdelegasi_id ,
                                bidan1_id ,
                                bidan2_id ,
                                perawat1_id ,
                                perawat2_id ,
                                discount_tindakan ,
                                pembebasan_tindakan ,
                                subsidiasuransi_tindakan ,
                                subsidipemerintah_tindakan ,
                                subsisidirumahsakit_tindakan ,
                                uangditerima_tindakan ,
                                keterangantindakan ,
                                pembulatan ,
                                implementasi_id ,
                                is_dilakukan ,
                                pemakaianambulan_id ,
                                is_penatajasa ,
                                additional_riwayat ,
                                is_valid ,
                                kamarruangan_id ,
                                kamartempattidur_id ,
                                penyulit_tindakan ,
                                tarifpenyulit_tindakan ,
                                additional_data ,
                                created_date ,
                                created_by ,
                                modified_count,
                                last_modified_date,
                                last_modified_by,
                                is_deleted,
                                is_active,
                                deleted_date,
                                deleted_by,
                                keterangan,
                                no_tindakanpelayanan,
                                                    tarif_dijamin,
                                                    tarif_dibayarkan,
                                                    tarif_diskon,
                                                    pembayaran_id
                            )VALUES(
                                OLD.tindakanpelayanan_id ,
                                OLD.shift_id ,
                                OLD.kelaspelayanan_id ,
                                OLD.kelastanggungan_id ,
                                OLD.pasien_id ,
                                OLD.rencanaoperasi_id ,
                                OLD.instalasi_id ,
                                OLD.daftartindakan_id ,
                                OLD.alatmedis_id ,
                                OLD.tipepaket_id ,
                                OLD.tindakansudahbayar_id ,
                                OLD.carabayar_id ,
                                OLD.pendaftaran_id ,
                                OLD.hasilpemeriksaanrad_id ,
                                OLD.jeniskasuspenyakit_id ,
                                OLD.hasilpemeriksaanrm_id ,
                                OLD.ruangan_id ,
                                OLD.konsulpoli_id ,
                                OLD.pasienmasukpenunjang_id ,
                                OLD.hasilpemeriksaanlabdetail_id ,
                                OLD.penjamin_id ,
                                OLD.pasienadmisi_id ,
                                OLD.verifikasitagihan_id ,
                                OLD.jurnalrekening_id ,
                                OLD.instruksitindakan_id ,
                                OLD.tgl_tindakan ,
                                OLD.tarif_rsakomodasi ,
                                OLD.tarif_medis ,
                                OLD.tarif_paramedis ,
                                OLD.tarif_bhp ,
                                OLD.tarif_satuan ,
                                -1 * OLD.tarif_tindakan ,
                                OLD.tarifcyto_tindakan ,
                                OLD.satuan_tindakan ,
                                -1 * OLD.qty_tindakan ,
                                OLD.cyto_tindakan ,
                                OLD.dokterpenanggungjawab_id ,
                                OLD.dokterpelaksana_id ,
                                OLD.dokteranastesi_id ,
                                OLD.dokterdelegasi_id ,
                                OLD.bidan1_id ,
                                OLD.bidan2_id ,
                                OLD.perawat1_id ,
                                OLD.perawat2_id ,
                                OLD.discount_tindakan ,
                                OLD.pembebasan_tindakan ,
                                OLD.subsidiasuransi_tindakan ,
                                OLD.subsidipemerintah_tindakan ,
                                OLD.subsisidirumahsakit_tindakan ,
                                OLD.uangditerima_tindakan ,
                                OLD.keterangantindakan ,
                                OLD.pembulatan ,
                                OLD.implementasi_id ,
                                OLD.is_dilakukan ,
                                OLD.pemakaianambulan_id ,
                                OLD.is_penatajasa ,
                                OLD.additional_riwayat ,
                                OLD.is_valid ,
                                OLD.kamarruangan_id ,
                                OLD.kamartempattidur_id ,
                                OLD.penyulit_tindakan ,
                                OLD.tarifpenyulit_tindakan ,
                                OLD.additional_data ,
                                OLD.created_date ,
                                OLD.created_by ,
                                OLD.modified_count,
                                OLD.last_modified_date,
                                OLD.last_modified_by,
                                OLD.is_deleted,
                                OLD.is_active,
                                OLD.deleted_date,
                                OLD.deleted_by,
                                \'ACCRUAL REVERSAL\',
                                OLD.no_tindakanpelayanan,
                                 0,
                                                     0,
                                 0,
                                 NULL
                            );
                    
                         IF (NEW.tindakansudahbayar_id is null AND OLD.is_deleted= FALSE)
                            THEN  
                                    INSERT INTO tindakanpelayanan_r (       
                                    tindakanpelayanan_id ,
                                    shift_id ,
                                    kelaspelayanan_id ,
                                    kelastanggungan_id ,
                                    pasien_id ,
                                    rencanaoperasi_id ,
                                    instalasi_id ,
                                    daftartindakan_id ,
                                    alatmedis_id ,
                                    tipepaket_id ,
                                    tindakansudahbayar_id ,
                                    carabayar_id ,
                                    pendaftaran_id ,
                                    hasilpemeriksaanrad_id ,
                                    jeniskasuspenyakit_id ,
                                    hasilpemeriksaanrm_id ,
                                    ruangan_id ,
                                    konsulpoli_id ,
                                    pasienmasukpenunjang_id ,
                                    hasilpemeriksaanlabdetail_id ,
                                    penjamin_id ,
                                    pasienadmisi_id ,
                                    verifikasitagihan_id ,
                                    jurnalrekening_id ,
                                    instruksitindakan_id ,
                                    tgl_tindakan ,
                                    tarif_rsakomodasi ,
                                    tarif_medis ,
                                    tarif_paramedis ,
                                    tarif_bhp ,
                                    tarif_satuan ,
                                    tarif_tindakan ,
                                    tarifcyto_tindakan ,
                                    satuan_tindakan ,
                                    qty_tindakan ,
                                    cyto_tindakan ,
                                    dokterpenanggungjawab_id ,
                                    dokterpelaksana_id ,
                                    dokteranastesi_id ,
                                    dokterdelegasi_id ,
                                    bidan1_id ,
                                    bidan2_id ,
                                    perawat1_id ,
                                    perawat2_id ,
                                    discount_tindakan ,
                                    pembebasan_tindakan ,
                                    subsidiasuransi_tindakan ,
                                    subsidipemerintah_tindakan ,
                                    subsisidirumahsakit_tindakan ,
                                    uangditerima_tindakan ,
                                    keterangantindakan ,
                                    pembulatan ,
                                    implementasi_id ,
                                    is_dilakukan ,
                                    pemakaianambulan_id ,
                                    is_penatajasa ,
                                    additional_riwayat ,
                                    is_valid ,
                                    kamarruangan_id ,
                                    kamartempattidur_id ,
                                    penyulit_tindakan ,
                                    tarifpenyulit_tindakan ,
                                    additional_data ,
                                    created_date ,
                                    created_by ,
                                    modified_count,
                                    last_modified_date,
                                    last_modified_by,
                                    is_deleted,
                                    is_active,
                                    deleted_date,
                                    deleted_by,
                                    keterangan,
                                    no_tindakanpelayanan,
                                                            tarif_dijamin,
                                                            tarif_dibayarkan,
                                                            tarif_diskon,
                                                            pembayaran_id
                                )VALUES(
                                    NEW.tindakanpelayanan_id ,
                                    NEW.shift_id ,
                                    NEW.kelaspelayanan_id ,
                                    NEW.kelastanggungan_id ,
                                    NEW.pasien_id ,
                                    NEW.rencanaoperasi_id ,
                                    NEW.instalasi_id ,
                                    NEW.daftartindakan_id ,
                                    NEW.alatmedis_id ,
                                    NEW.tipepaket_id ,
                                    NEW.tindakansudahbayar_id ,
                                    NEW.carabayar_id ,
                                    NEW.pendaftaran_id ,
                                    NEW.hasilpemeriksaanrad_id ,
                                    NEW.jeniskasuspenyakit_id ,
                                    NEW.hasilpemeriksaanrm_id ,
                                    NEW.ruangan_id ,
                                    NEW.konsulpoli_id ,
                                    NEW.pasienmasukpenunjang_id ,
                                    NEW.hasilpemeriksaanlabdetail_id ,
                                    NEW.penjamin_id ,
                                    NEW.pasienadmisi_id ,
                                    NEW.verifikasitagihan_id ,
                                    NEW.jurnalrekening_id ,
                                    NEW.instruksitindakan_id ,
                                    NEW.tgl_tindakan ,
                                    NEW.tarif_rsakomodasi ,
                                    NEW.tarif_medis ,
                                    NEW.tarif_paramedis ,
                                    NEW.tarif_bhp ,
                                    NEW.tarif_satuan ,
                                    NEW.tarif_tindakan ,
                                    NEW.tarifcyto_tindakan ,
                                    NEW.satuan_tindakan ,
                                    NEW.qty_tindakan ,
                                    NEW.cyto_tindakan ,
                                    NEW.dokterpenanggungjawab_id ,
                                    NEW.dokterpelaksana_id ,
                                    NEW.dokteranastesi_id ,
                                    NEW.dokterdelegasi_id ,
                                    NEW.bidan1_id ,
                                    NEW.bidan2_id ,
                                    NEW.perawat1_id ,
                                    NEW.perawat2_id ,
                                    NEW.discount_tindakan ,
                                    NEW.pembebasan_tindakan ,
                                    NEW.subsidiasuransi_tindakan ,
                                    NEW.subsidipemerintah_tindakan ,
                                    NEW.subsisidirumahsakit_tindakan ,
                                    NEW.uangditerima_tindakan ,
                                    NEW.keterangantindakan ,
                                    NEW.pembulatan ,
                                    NEW.implementasi_id ,
                                    NEW.is_dilakukan ,
                                    NEW.pemakaianambulan_id ,
                                    NEW.is_penatajasa ,
                                    NEW.additional_riwayat ,
                                    NEW.is_valid ,
                                    NEW.kamarruangan_id ,
                                    NEW.kamartempattidur_id ,
                                    NEW.penyulit_tindakan ,
                                    NEW.tarifpenyulit_tindakan ,
                                    OLD.additional_data ,
                                    OLD.created_date ,
                                    OLD.created_by ,
                                    OLD.modified_count,
                                    OLD.last_modified_date,
                                    OLD.last_modified_by,
                                    OLD.is_deleted,
                                    OLD.is_active,
                                    OLD.deleted_date,
                                    OLD.deleted_by,
                                    \'ACCRUAL\',
                                    OLD.no_tindakanpelayanan,
                                                            NEW.tarif_dijamin,
                                                            NEW.tarif_dibayarkan,
                                                            NEW.tarif_diskon,
                                                            NULL
                                );
                                                END IF; 

                        
                END IF;
            RETURN NEW;

            END
            $BODY$
              LANGUAGE plpgsql VOLATILE
              COST 100;
        ');
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        echo "m220729_100601_migrate_odoo_function_tindakanpelayanan_r_update cannot be reverted.\n";

        return false;
    }

    /*
    // Use up()/down() to run migration code without a transaction.
    public function up()
    {

    }

    public function down()
    {
        echo "m220729_100601_migrate_odoo_function_tindakanpelayanan_r_update cannot be reverted.\n";

        return false;
    }
    */
}
