<?php
    use yii\widgets\ActiveForm;
    use yii\helpers\Html;
?>

<div class="modal-header bg-inverse">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h5 class="modal-title"><?=$title;?></h5>
</div>
<div class="modal-body">
    <table class="table table-bordered table-condensed table-striped table-hover">
        <tr>
            <td><?=$model->getAttributeLabel('tahunprofilrs');?></td>
            <td>
                <?=$model->tahunprofilrs;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('kodejenisrs_profilrs');?></td>
            <td>
                <?=$model->kodejenisrs_profilrs;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('jenisrs_profilrs');?></td>
            <td>
                <?=$model->jenisrs_profilrs;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('statusrsswasta');?></td>
            <td>
                <?=$model->statusrsswasta;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('namakepemilikanrs');?></td>
            <td>
                <?=$model->namakepemilikanrs;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('kodestatuskepemilikanrs');?></td>
            <td>
                <?=$model->kodestatuskepemilikanrs;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('statuskepemilikanrs');?></td>
            <td>
                <?=$model->statuskepemilikanrs;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('pentahapanakreditasrs');?></td>
            <td>
                <?=$model->pentahapanakreditasrs;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('statusakreditasrs');?></td>
            <td>
                <?=$model->statusakreditasrs;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('nokode_rumahsakit');?></td>
            <td>
                <?=$model->nokode_rumahsakit;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('nama_rumahsakit');?></td>
            <td>
                <?=$model->nama_rumahsakit;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('kelas_rumahsakit');?></td>
            <td>
                <?=$model->kelas_rumahsakit;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('namadirektur_rumahsakit');?></td>
            <td>
                <?=$model->namadirektur_rumahsakit;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('alamatlokasi_rumahsakit');?></td>
            <td>
                <?=$model->alamatlokasi_rumahsakit;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('nomor_suratizin');?></td>
            <td>
                <?=$model->nomor_suratizin;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('tgl_suratizin');?></td>
            <td>
                <?=$model->tgl_suratizin;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('oleh_suratizin');?></td>
            <td>
                <?=$model->oleh_suratizin;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('sifat_suratizin');?></td>
            <td>
                <?=$model->sifat_suratizin;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('masaberlakutahun_suratizin');?></td>
            <td>
                <?=$model->masaberlakutahun_suratizin;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('motto');?></td>
            <td>
                <?=$model->motto;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('visi');?></td>
            <td>
                <?=$model->visi;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('no_faksimili');?></td>
            <td>
                <?=$model->no_faksimili;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('logo_rumahsakit');?></td>
            <td>
                <?=$model->logo_rumahsakit;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('path_logorumahsakit');?></td>
            <td>
                <?=$model->path_logorumahsakit;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('npwp');?></td>
            <td>
                <?=$model->npwp;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('tahun_diresmikan');?></td>
            <td>
                <?=$model->tahun_diresmikan;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('khususuntukswasta');?></td>
            <td>
                <?=$model->khususuntukswasta;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('website');?></td>
            <td>
                <?=$model->website;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('email');?></td>
            <td>
                <?=$model->email;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('no_telp_profilrs');?></td>
            <td>
                <?=$model->no_telp_profilrs;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('negara');?></td>
            <td>
                <?=$model->negara;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('tglakreditasi');?></td>
            <td>
                <?=$model->tglakreditasi;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('akreditasirs');?></td>
            <td>
                <?=$model->akreditasirs;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('tglregistrasi');?></td>
            <td>
                <?=$model->tglregistrasi;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('notelphumas');?></td>
            <td>
                <?=$model->notelphumas;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('luastanah');?></td>
            <td>
                <?=$model->luastanah;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('luasbangunan');?></td>
            <td>
                <?=$model->luasbangunan;?>
            </td>
        </tr>
        <tr>
            <td><?=$model->getAttributeLabel('ppkpelayanan');?></td>
            <td>
                <?=$model->ppkpelayanan;?>
            </td>
        </tr>
    </table>
</div>
<div class="modal-footer">
    <?=Html::button('Kembali',[
        'class' => 'btn btn-default btn-md',
        'data-dismiss' => 'modal'
    ]); ?>
</div>
