<p><strong>Selamat datang di Layanan TILAKA!</strong></p>
<p>Dengan ini, PT Tilaka Nusa Teknologi (“PSrE TILAKA” atau “Kami”) ingin menyampaikan bahwa selaku pemilik dan pengelola dari Layanan Tanda Tangan Elektronik yang dapat digunakan baik dengan mengakses secara langsung melalui URL: <a href="https://corporate.tilaka.id/ca-corporate-portal/login.xhtml" target="_blank">https://corporate.tilaka.id/ca-corporate-portal/login</a> atau melalui aplikasi yang dibuat, dikelola, dikembangkan, atau dimiliki oleh Mitra Bisnis (“Layanan TILAKA”) memiliki syarat dan ketentuan (“S&amp;K”) yang harus Pemilik dan/atau Pemohon (“Anda”) setujui sebelum menggunakan Layanan TILAKA. Anda berkewajiban untuk membaca, memahami, dan menyetujui isi dari S&amp;K ini sebelum melakukan permohonan penerbitan, permohonan penerbitan ulang, permohonan penggantian kunci, menerima, dan/atau menggunakan Sertifikat Pemilik (“Mengakses Layanan TILAKA”). Dalam hal Anda tidak menyetujui sebagian atau seluruh ketentuan yang diatur dalam S&amp;K ini, maka Anda tidak diperkenankan untuk Mengakses Layanan TILAKA.</p>
<p>S&amp;K ini berlaku efektif setelah ditampilkan pada salah satu halaman pada Layanan TILAKA saat Anda mengajukan permohonan penerbitan, permohonan penerbitan ulang, dan/atau permohonan penggantian kunci Sertifikat Pemilik. Atas permohonan penerbitan, permohonan penerbitan ulang, dan/atau permohonan penggantian kunci Sertifikat Pemilik yang dilakukan setelah S&amp;K ini berlaku efektif, maka ketentuan pada S&amp;K ini berlaku untuk Pemilik.</p>
<p>Anda dengan ini mengetahui, mengerti, dan menyetujui bahwa S&amp;K ini merupakan Dokumen Elektronik dan tindakan Anda memberikan tanda “centang” saat permohonan penerbitan, permohonan penerbitan ulang, dan/atau permohonan penggantian kunci Sertifikat Pemilik merupakan persetujuan Anda secara aktif untuk mengikatkan diri dan tunduk pada ketentuan yang terdapat pada S&amp;K ini. Oleh karena itu, S&amp;K ini telah berlaku sah dan mengikat Anda secara hukum dan terus berlaku sepanjang anda Mengakses Layanan TILAKA.</p>
<p><strong>Definisi</strong></p>
<ol>
<li>Akun adalah suatu kode alfanumerik yang diterbitkan oleh PSrE TILAKA yang berfungsi untuk mengidentifikasi Anda dalam menggunakan Layanan TILAKA.  </li>
<li>Data Pribadi adalah data tentang orang perseorangan yang teridentifikasi atau dapat diidentifikasi secara tersendiri atau dikombinasi dengan informasi lainnya baik secara langsung maupun tidak langsung melalui sistem elektronik atau nonelektronik.  </li>
<li>Dokumen Elektronik adalah setiap Informasi Elektronik yang dibuat, diteruskan, dikirimkan, diterima, atau disimpan dalam bentuk analog, digital, elektromagnetik, optikal, atau sejenisnya, yang dapat dilihat, ditampilkan dan/atau didengar melalui komputer atau sistem elektronik, termasuk atau sistem elektronik, termasuk tetapi tidak terbatas pada tulisan, suara, gambar, peta, rancangan, foto atau sejenisnya, huruf, tanda, angka, kode akses, simbol atau perforasi yang memiliki makna atau arti atau dapat dipahami oleh orang yang mampu memahaminya.  </li>
<li>Hari Kalender adalah semua hari dalam satu tahun sesuai kalender gregorius tanpa kecuali termasuk hari Sabtu, Minggu, dan hari libur nasional yang ditetapkan sewaktu-waktu oleh Pemerintah.  </li>
<li>Kontrak Elektronik adalah Perjanjian yang dibuat melalui sistem elektronik.  </li>
<li>Pemilik adalah Warga Negara Indonesia yang berada dalam ruang lingkup Pelanggan dan merupakan subjek dari Sertifikat Pemilik.  </li>
<li>Pemohon adalah Warga Negara Indonesia yang berada dalam ruang lingkup Pelanggan yang mengajukan permohonan penerbitan, penerbitan ulang, atau penggantian kunci Sertifikat Pemilik dalam ruang lingkup Pelanggan. Setelah Sertifikat diterbitkan, Pemohon disebut sebagai Pemilik.  </li>
<li>Pelanggan adalah Korporasi atau Personal yang berlangganan Layanan TILAKA.  </li>
<li>PT Tilaka Nusa Teknologi (“PSrE TILAKA”) adalah PSrE dengan status pengakuan berinduk yang Sertifikatnya telah ditandatangani oleh PSrE Induk.  </li>
<li>Mitra Bisnis adalah perorangan, badan hukum, dan/atau badan usaha yang memiliki hubungan hukum baik secara langsung maupun tidak langsung dengan PSrE TILAKA dan dapat dibuktikan oleh suatu dokumen yang dapat menunjukkan hubungan hukum tersebut.  </li>
<li>Repositori Tilaka adalah suatu halaman pada <em>website</em> PSrE TILAKA yang berisi semua dokumen publik milik PSrE TILAKA, yang dapat diakses melalui <a href="https://repository.tilaka.id/" target="_blank">https://repository.tilaka.id/</a>.  </li>
<li>Sertifikat adalah Sertifikat yang bersifat elektronik yang memuat tanda tangan elektronik dan identitas yang menunjukkan status subjek hukum para pihak dalam transaksi elektronik.  </li>
<li>Sertifikat Pemilik adalah Sertifikat yang diterbitkan oleh PSrE TILAKA.</li>
</ol>
<p><strong>Ketentuan Bagi Anda</strong></p>
<ol>
<li>Anda setuju untuk Mengakses Layanan TILAKA hanya untuk tujuan sebagaimana ditentukan dalam S&amp;K ini dan daftar Dokumen Publik sebagaimana disebutkan dalam S&amp;K ini. Anda dengan ini menjamin untuk tidak akan menggunakan Layanan TILAKA untuk tujuan penipuan, menyebabkan ketidaknyamanan kepada orang lain, atau melakukan tindakan lainnya yang dapat atau dianggap dapat menimbulkan kerugian dalam bentuk apapun terhadap orang atau badan hukum lainnya.  </li>
<li>Dalam rangka menggunakan Layanan TILAKA, Anda akan memiliki Akun yang hanya boleh digunakan oleh Anda dan tidak dapat dialihkan kepada orang lain dengan alasan ataupun keadaan apapun. Maka dari itu, Anda berkewajiban untuk menjaga kerahasiaan nama Akun dan kata sandi yang akan digunakan sehubungan dengan penggunaan Layanan TILAKA.  </li>
<li>Anda setuju untuk memberikan semua informasi dan/atau Data Pribadi yang diminta oleh PSrE TILAKA dengan disertai dengan dokumen pendukung yang dibutuhkan sehubungan dengan kegiatan Mengakses Layanan TILAKA.  </li>
<li>Anda setuju bahwa PSrE TILAKA berhak untuk melakukan verifikasi secara independen terhadap semua informasi dan/atau Data Pribadi sesuai dengan prosedur yang berlaku pada PSrE TILAKA.  </li>
<li>Anda dengan ini menjamin bahwa segala informasi dan/atau Data Pribadi  yang disampaikan kepada TILAKA sehubungan dengan kegiatan Mengakses Layanan TILAKA adalah benar, jelas, akurat dan lengkap. Anda berkewajiban untuk menginformasikan kepada PSrE TILAKA dalam hal terdapat perubahan, penambahan, atau pembaruan atas informasi dan/atau Data Pribadi. PSrE TILAKA berhak untuk menolak permohonan penerbitan Sertifikat Pemilik, menolak permohonan penerbitan ulang Sertifikat Pemilik, menolak permohonan penggantian kunci Sertifikat Pemilik,  dan/atau menolak melakukan perubahan, penambahan, atau pembaruan atas informasi dan/atau Data Pribadi yang tersimpan pada Layanan TILAKA, jika ditemukan atau patut diduga bahwa informasi dan/atau Data Pribadi yang diberikan oleh Anda tidak sesuai dengan ketentuan S&amp;K ini dan Dokumen Publik sebagaimana disebutkan dalam S&amp;K ini.  </li>
<li>Anda setuju atas isi yang tercantum dalam Sertifikat Pemilik yang diterbitkan oleh PSrE TILAKA, baik dari proses permohonan penerbitan, permohonan penerbitan ulang, dan/atau permohonan penggantian kunci Sertifikat Pemilik dalam hal:  </li>
<li>Anda telah memeriksa dan menyetujui informasi yang terkandung dalam Sertifikat Pemilik; atau  </li>
<li>Anda tidak memberikan tanggapan dalam jangka waktu 9 (sembilan) Hari Kalender sejak PSrE TILAKA mengirimkan <em>email</em> terkait penerbitan Sertifikat Pemilik.  </li>
<li>Dalam hal permohonan penggantian kunci Sertifikat Pemilik, Anda dengan ini mengetahui dan setuju bahwa:  </li>
<li>Penggantian kunci Sertifikat Pemilik mengakibatkan PSrE TILAKA akan melakukan penerbitan Sertifikat Pemilik baru dengan kunci publik, <em>serial number</em>, dan <em>key identifier</em> yang baru, sementara informasi pribadi Pemilik yang tercantum pada Sertifikat Pemilik yang digunakan untuk menandatangani permohonan penggantian kunci Sertifikat Pemilik baru ini akan tetap digunakan pada Sertifikat Pemilik baru yang akan diterbitkan PSrE TILAKA tersebut;  </li>
<li>Penggantian kunci Sertifikat Pemilik mengakibatkan PSrE TILAKA akan membangkitkan pasangan kunci baru yang terasosiasi dengan Sertifikat Pemilik yang digunakan untuk menandatangani permohonan penggantian kunci Sertifikat Pemilik baru ini; dan/atau  </li>
<li>Masa berlaku Sertifikat Pemilik baru akan berbeda dengan Sertifikat Pemilik yang Anda gunakan untuk menandatangani permohonan penggantian kunci Sertifikat Pemilik baru ini.  </li>
<li>Anda setuju untuk tidak menggunakan Layanan TILAKA dengan cara sebagai berikut:  </li>
<li>Menggunakan Layanan TILAKA untuk tujuan yang melanggar hukum atau ketentuan peraturan perundang-undangan yang berlaku;  </li>
<li>Melakukan tindakan yang disebabkan oleh kelalaian atau kesengajaan olehnya, yang pada pokoknya merusak, menghilangkan, menyembunyikan, menyebabkan perubahan, penambahan, pengurangan, dan/atau membuat tidak dapat digunakannya Layanan TILAKA baik sebagian maupun seluruhnya;  </li>
<li>Melakukan tindakan yang baik dengan sengaja atau karena kelalaiannya menyebabkan pelanggaran atas hak PSrE TILAKA dalam hal yang termasuk namun tidak terbatas pada pelanggaran privasi, hak cipta, merek, paten, rahasia dagang, atau hak kekayaan intelektual lainnya, hak yang timbul dari hubungan kontraktual antara PSrE TILAKA dengan pihak ketiga lainnya, dan/atau hak lain yang dimiliki PSrE TILAKA baik untuk masa sekarang maupun di kemudian hari yang dilindungi oleh peraturan perundang-undafngan yang berlaku; dan  </li>
<li>Melakukan tindakan menyalin, memodifikasi, mengadaptasi, menerjemahkan, membuat karya turunan dari, melakukan perekayasaan balik, atau membongkar bagian manapun baik sebagian atau seluruhnya atas Layanan TILAKA.  </li>
<li>Anda setuju bahwa PSrE TILAKA berhak untuk menghentikan sementara atau permanen dengan atau tanpa disertai dengan pencabutan Akun dan/atau Sertifikat Pemilik milik Anda dalam hal terdapat kegiatan untuk meningkatkan pelayanan yang terdapat pada Layanan TILAKA atau pelanggaran dari Anda terhadap ketentuan dari S&amp;K ini.  </li>
<li>Dalam rangka kegiatan Anda Mengakses Layanan TILAKA, Anda mengetahui dan setuju bahwa  PSrE TILAKA akan akan memberitahukan sebagian atau seluruh informasi yang terdapat dalam Sertifikat Pemilik kepada pihak pengandal dan/atau pihak lainnya, hal mana demikian akan dilakukan oleh PSrE TILAKA dengan tunduk pada ketentuan yang tercantum pada Dokumen Publik sebagaimana disebutkan dalam S&amp;K ini.  </li>
<li>Dalam rangka Mengakses Layanan TILAKA, Anda setuju untuk tunduk pada ketentuan yang terdapat pada Dokumen Publik yang terdapat pada Repositori Tilaka serta di tautan yang terdapat pada bagian akhir S&amp;K ini yang terdiri dari:  </li>
<li><em>Certification Practice Statement</em> (“CPS”);  </li>
<li>Kebijakan Privasi;  </li>
<li>Perjanjian Pemilik Sertifikat; dan  </li>
<li>Kebijakan Jaminan.  </li>
<li>Dalam hal Anda menggunakan Layanan TILAKA melalui aplikasi yang dibuat, dikelola, dikembangkan, atau dimiliki oleh Mitra Bisnis (“aplikasi mitra bisnis”), maka Anda harus mengetahui dan menyetujui bahwa Kami tidak memiliki kendali apapun terhadap konten-konten yang terdapat pada aplikasi tersebut sebelum Anda memilih untuk menggunakan Layanan TILAKA. Akses atau penggunaan Anda terhadap aplikasi mitra bisnis sebelum menggunakan Layanan TILAKA tersebut tunduk pada syarat dan ketentuan serta kebijakan privasi yang ditentukan oleh Mitra Bisnis.  </li>
<li>Dalam hal Anda menggunakan Layanan TILAKA melalui aplikasi mitra bisnis, Anda dengan ini mengetahui dan setuju bahwa:  </li>
<li>Mitra Bisnis dapat menyimpan hasil unggahan Dokumen Elektronik berupa Kartu Tanda Penduduk (“KTP”) yang Anda gunakan dalam rangka melakukan Permohonan Penerbitan Sertifikat Pemilik; dan  </li>
<li>Untuk kebutuhan pencatatan <em>log internal</em> terhadap Permohonan Penerbitan Sertifikat Pemilik yang Anda lakukan, Mitra Bisnis dapat menyimpan informasi nomor induk kependudukan (“NIK”) yang Anda berikan.  </li>
<li>Dalam hal Anda menggunakan Layanan TILAKA melalui aplikasi mitra bisnis, Anda dengan ini melepaskan tanggung jawab Kami terhadap segala tindakan yang dilakukan oleh Mitra Bisnis terhadap isi atau bagian apapun dari aplikasi mitra bisnis tersebut termasuk bagaimana aplikasi mitra bisnis tersebut memperoleh, mengumpulkan, mengolah, menyimpan, menampilkan, mengumumkan, mengirimkan, dan memusnahkan Data Pribadi Anda sebelum, saat, dan setelah Anda menggunakan Layanan TILAKA.  </li>
<li>Dalam hal karena kelalaian atau kesengajaannya dalam melaksanakan ketentuan dari S&amp;K ini menyebabkan kerugian yang diterima oleh PSrE TILAKA, Anda, atau pihak ketiga lainnya, maka, Anda dengan ini sepakat untuk melepaskan, membebaskan, memberikan ganti rugi, dan membela PSrE TILAKA, termasuk direktur, komisaris, karyawan dan/atau rekanan atas hal-hal yang termasuk namun tidak terbatas pada permintaan, klaim, kerugian, tuntutan, tanggung jawab, kewajiban, kerusakan, ongkos dan biaya yang timbul.</li>
</ol>
<p><strong>Kerahasiaan dan Keamanan</strong></p>
<p>Anda setuju bahwa PSrE TILAKA dapat mengungkapkan atau memberikan akses terhadap informasi, Dokumen Elektronik, Kontrak Elektronik, dan/atau Data Pribadi Anda dalam rangka memenuhi ketentuan hukum, peraturan perundang-undangan dan/atau keputusan pengadilan, hal tersebut dilakukan dalam rangka proses penegakan atau pengambilan tindakan pencegahan lebih lanjut sehubungan dengan kegiatan tidak berwenang, dugaan tindak pidana, pelanggaran hukum dan/atau pelanggaran terhadap peraturan perundang-undangan yang berlaku.</p>
<p><strong>Hak Kekayaan Intelektual</strong></p>
<p>Nama, kode program, model bisnis, desain, merek dagang, warna, gambar, <em>video</em>, audio, teknologi, dan hal lainnya sehubungan dengan Layanan TILAKA yang belum, dalam proses maupun telah terdaftar atas nama PSrE TILAKA, dilindungi oleh hak kekayaan intelektual termasuk namun tidak terbatas pada hak cipta, merek, paten dan hak kekayaan intelektual yang diatur berdasarkan hukum Negara Republik Indonesia. Tindakan Anda dalam hal mengakses dan menggunakan Layanan TILAKA, tidak mengakibatkan perpindahan baik sebagian atau seluruh Hak Kekayaan Intelektual sehubungan dengan Layanan TILAKA tersebut Anda.</p>
<p><strong>Hubungi TILAKA</strong></p>
<p>Anda dapat menghubungi PSrE TILAKA melalui surat elektronik (<em>email</em>) ke alamat <a href="mailto:info@tilaka.id" target="_blank">info@tilaka.id</a> atau dengan mengirimkan dokumen fisik melalui kantor PSrE TILAKA melalui alamat Belleza Shopping Arcade Lantai 3 Unit SA 0380, Jl. Arteri Permata Hijau Nomor 34, RT.004/RW.002, Grogol Utara, Kebayoran Lama, Jakarta Selatan, 12210.</p>
<p><strong>Sengketa</strong></p>
<p>Segala sengketa terkait dengan penafsiran atau pelaksanaan dari S&amp;K ini, para pihak sepakat untuk menyelesaikan secara musyawarah untuk mufakat. Apabila penyelesaian secara musyawarah untuk mencapai sepakat tersebut tidak tercapai, maka para pihak sepakat untuk menyelesaikannya melalui Pengadilan Negeri Jakarta Selatan sesuai domisili PSrE TILAKA.</p>
<small><a href="https://repository.tilaka.id/CP_CPS.pdf" target="_blank">CP/CPS</a></small><br><small><a href="https://repository.tilaka.id/kebijakan-jaminan.pdf" target="_blank">Kebijakan Jaminan/ Warranty Policy</a></small><br><small><a href="https://repository.tilaka.id/kebijakan-privasi.pdf" target="_blank">Kebijakan Privasi/ Privacy Policy</a></small><br><small><a href="https://repository.tilaka.id/perjanjian-pemilik-sertifikat.pdf" target="_blank">Perjanjian Pemilik Sertifikat/ Certificate Subscriber’s Agreement</a></small>