<?php

namespace app\modules\v1\models;

use Yii;

class AsesmenKeperawatanRD extends \Doco\components\DocoActiveRecord
{
    public static function tableName()
    {
        return 'asesmenperawatrd_t';
    }

    public function rules()
    {
        return [
            [
                [
                    'pendaftaran_id',
                    'ruangan_id',
                    'tgl_asesmen',
                    'perawat_id',
                    'tgl_pendaftaran',
                    'tgl_datang',
                    'prioritas_triage',
                    'is_trauma',
                    'pasien_datang',
                    'jenis_asmenperawat',
                    'alasan_kunjungan',
                    'is_alergi',
                    'is_alergiobat',
                    'alergi_obat',
                    'is_alergilainnya',
                    'alergi_lainnya',
                    'keadaan_umum',
                    'is_nyeri',
                    'pilih_skala',
                    'lokasi_nyeri',
                    'skala_nyeri',
                    'metode_nyeri',
                    'is_resikojatuh',
                    'keluhan',
                    'lama_sakit',
                    'r_penyakitdahulu',
                    'r_penyakitkeluarga',
                    'catatan_asesmen',
                    'gcseye_id',
                    'gcsverbal_id',
                    'gcsmotorik_id',
                    'hasil_gcs',
                    'is_kapitis',
                    'td_systolic',
                    'td_diastolic',
                    'tekanan_darah',
                    'hasil_td',
                    'detak_nadi',
                    'pernapasan',
                    'suhu_tubuh',
                    'tinggi_badan',
                    'berat_badan',
                    'bb_ideal',
                    'imt',
                    'ket_imt',
                    'spo2',
                    'kelaianan_tubuh',
                    'detail_asesmen',
                    'additional_data',
                    'created_date',
                    'created_by',
                    'modified_count',
                    'last_modified_date',
                    'last_modified_by',
                    'deleted_date',
                    'deleted_by',
                    'formulir_triage',
                    'formulir_fisik',
                    'tgl_keluar',
                    'agama_id',
                    'pekerjaan_id',
                    'caramasuk_id',
                    'pendidikan_id',
                    'jalur_nafas',
                    'jalur_nafas_oksigen',
                    'pernafasan',
                    'pernafasan_spontan',
                    'pernafasan_takipnea',
                    'tensi',
                    'reguler',
                    'ireguler',
                    'capilary_refill',
                    'perfusi',
                    'akral',
                    'pendarahan',
                    'pendarahan_cc',
                    'is_bradikarida',
                    'is_takikardia',
                    'pupil',
                    'reaksi_pupil',
                    'reaksi_pupil_lainnya',
                    'kepala',
                    'abdomen',
                    'maksilofacial',
                    'parineum',
                    'tulan_leher',
                    'muskuloskeletal',
                    'paru_paru',
                    'extremitas',
                    'skala_wong_baker',
                    'asesmen_auto',
                    'asesmen_auto_anamnesa',
                    'asesmen_allo',
                    'r_penyakitsaatini',
                    'r_pengobatan',
                    'jalan_nafas_bersin',
                    'nilai_decubitus',
                    'nilai_luka_bakar',
                    'survey_kepala',
                    'survey_kepala_lacerasi',
                    'survey_kepala_battle_sign',
                    'survey_kepala_lainnya',
                    'survey_mata',
                    'survey_mulut',
                    'survey_mulut_luka_dalam',
                    'survey_mulut_lainnya',
                    'survey_telinga',
                    'survey_leher',
                    'survey_leher_lainnya',
                    'survey_extremitas',
                    'survey_extremitas_pulsasi',
                    'survey_dada',
                    'survey_dada_simetris_asimetris',
                    'survey_dada_pneumo_hamatotoraks',
                    'survey_dada_nyeri_lokasi',
                    'survey_dada_nyeri_kapan',
                    'survey_dada_nyeri_durasi',
                    'survey_dada_nyeri_kegiatan',
                    'survey_dada_bunyi_jantung',
                    'survey_abdomen',
                    'survey_abdomen_memas',
                    'survey_abdomen_nyeri',
                    'survey_abdomen_lainnya',
                    'survey_abdomen_bising_usus',
                    'survey_pelvis',
                    'survey_pelvis_lainnya',
                    'survey_medulla_spinalis',
                    'survey_kolumna_vertebralis',
                    'perasaan_klien',
                    'sosial_support',
                    'hubungan_pasien',
                    'keluarga_lain',
                    'keadaan_emosi',
                    'suku_id',
                    'bahasa_dipakai',
                    'bahasa_dipakai_lainnya',
                    'is_penerjemah',
                    'media',
                    'media_lainnya',
                    'identifikasi_hambatan',
                    'is_sistem_rujukan',
                    'materi',
                    'edukator',
                    'is_ketersediaan_pasien',
                    'is_kemampuan_membaca',
                    'bahasa',
                    'is_dibutuhkan_penerjemah',
                    'penerjemah_bahasa',
                    'is_hambatan_emotional',
                    'hambatan_emotional_lainnya',
                    'is_keterbatasan_fisik',
                    'keterbatasan_fisik',
                    'bersihan_jalan',
                    'pola_nafas',
                    'gangguan_gas',
                    'nyeri',
                    'penurunan_jantung',
                    'gangguan_perfusi_cerebral',
                    'gangguan_perfusi_perifer',
                    'valume_cairan_tubuh',
                    'gangguan_thermoregulasi_nilai',
                    'gangguan_thermoregulasi_tipe',
                    'tujuan_pulang',
                    'tujuan_pulang_lainnya',
                    'transportasi',
                    'orang_merawat',
                    'sarana_kesehatan',
                    'masuk_ke',
                    'persen_luka_bakar',
                    'kategori_triase_sehari',
                    'kategori_triase_disaster',
                    'survey_kepala_utuh',
                    'pernafasan_gargling',
                    'ireguler_tipe',
                    'hasil_resiko_jatuh',
                    'tipe_nadi',
                    'hasil_nadi',
                    'pupil_os',
                    'pupil_od',
                    'jenis_resiko_jatuh',
                    'nutrisi_1a',
                    'nutrisi_1b',
                    'nutrisi_2',
                    'diagnosa_khusus',
                    'jenis_diagnosa_khusus',
                    'strongkids_kurus',
                    'strongkids_turunbb',
                    'strongkids_kondisikhusus',
                    'strongkids_keadaan_beresiko',
                    'resusitasi',
                    'skrining_gizi',
                    'skrining_gizi_kidz',
                    'extremitas_utuh',
                    'extremitas_fraktur',
                    'extremitas_nyeri',
                    'extremitas_deformitas',
                    'extremitas_defisit_neurologis',
                    'extremitas_jejas',
                    'extremitas_pulsasi',
                    'diagnosa_keperawatan',
                    'asesmen_allo_text',
                    'is_verifikasigizi',
                    'pegawaiverifikasigizi_id',
                    'tgl_verifikasi'
                ],
                'safe'
            ],
            [['is_verifikasigizi'], 'default', 'value' => false],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'tgl_datang' => 'Tanggal Datang',
            'tgl_keluar' => 'Tanggal Keluar',
            'pendaftaran_id' => 'pendaftaran_id',
            'ruangan_id' => 'ruangan_id',
            'tgl_asesmen' => 'tgl_asesmen',
            'perawat_id' => 'perawat_id',
            'tgl_pendaftaran' => 'tgl_pendaftaran',
            'prioritas_triage' => 'prioritas_triage',
            'is_trauma' => 'is_trauma',
            'pasien_datang' => 'pasien_datang',
            'jenis_asmenperawat' => 'jenis_asmenperawat',
            'alasan_kunjungan' => 'alasan_kunjungan',
            'is_alergi' => 'is_alergi',
            'is_alergiobat' => 'is_alergiobat',
            'alergi_obat' => 'alergi_obat',
            'is_alergilainnya' => 'is_alergilainnya',
            'alergi_lainnya' => 'alergi_lainnya',
            'keadaan_umum' => 'keadaan_umum',
            'is_nyeri' => 'is_nyeri',
            'lokasi_nyeri' => 'lokasi_nyeri',
            'skala_nyeri' => 'skala_nyeri',
            'metode_nyeri' => 'metode_nyeri',
            'is_resikojatuh' => 'is_resikojatuh',
            'keluhan' => 'Keluhan Utama',
            'lama_sakit' => 'lama_sakit',
            'r_penyakitdahulu' => 'Riwayat Penyakit Dahulu',
            'r_penyakitkeluarga' => 'Riwayat Penyakit Keluargas',
            'catatan_asesmen' => 'catatan_asesmen',
            'gcseye_id' => 'GCS Eye',
            'gcsverbal_id' => 'GCS Verbal',
            'gcsmotorik_id' => 'GCS Motorik',
            'hasil_gcs' => 'Hasil Metode GCS',
            'is_kapitis' => 'Kapitis',
            'td_systolic' => 'td_systolic',
            'td_diastolic' => 'td_diastolic',
            'tekanan_darah' => 'tekanan_darah',
            'hasil_td' => 'hasil_td',
            'detak_nadi' => 'Nadi',
            'pernapasan' => 'pernapasan',
            'suhu_tubuh' => 'Suhu',
            'tinggi_badan' => 'Tinggi Badan',
            'berat_badan' => 'Berat Badan',
            'bb_ideal' => 'bb_ideal',
            'imt' => 'imt',
            'ket_imt' => 'ket_imt',
            'spo2' => 'spo2',
            'kelaianan_tubuh' => 'kelaianan_tubuh',
            'detail_asesmen' => 'detail_asesmen',
            'additional_data' => 'additional_data',
            'created_date' => 'created_date',
            'created_by' => 'created_by',
            'modified_count' => 'modified_count',
            'last_modified_date' => 'last_modified_date',
            'last_modified_by' => 'last_modified_by',
            'is_deleted' => 'is_deleted',
            'is_active' => 'is_active',
            'deleted_date' => 'deleted_date',
            'deleted_by' => 'deleted_by',
            'formulir_triage' => 'formulir_triage',
            'formulir_fisik' => 'formulir_fisik',
            'agama_id' => 'Agama',
            'pekerjaan_id' => 'Pekerjaan',
            'caramasuk_id' => 'Cara Datang',
            'pendidikan_id' => 'Pendidikan',
            'jalur_nafas' => 'jalur_nafas',
            'jalur_nafas_oksigen' => 'jalur_nafas_oksigen',
            'pernafasan' => 'pernafasan',
            'pernafasan_spontan' => 'pernafasan_spontan',
            'pernafasan_takipnea' => 'pernafasan_takipnea',
            'tensi' => 'Tensi',
            'reguler' => 'Reguler',
            'ireguler' => 'Ireguler',
            'ireguler_tipe' => 'Ireguler Tipe',
            'capilary_refill' => 'capilary_refill',
            'perfusi' => 'Perfusi',
            'akral' => 'akral',
            'pendarahan' => 'pendarahan',
            'pendarahan_cc' => 'pendarahan_cc',
            'is_bradikarida' => 'is_bradikarida',
            'is_takikardia' => 'is_takikardia',
            'pupil' => 'Pupil',
            'reaksi_pupil' => 'Reaksi Pupil',
            'reaksi_pupil_lainnya' => 'Reaksi Pupil Lainnya',
            'kepala' => 'Kepala',
            'abdomen' => 'Abdomen',
            'maksilofacial' => 'Maksilofacial',
            'parineum' => 'Parineum',
            'tulan_leher' => 'Tulang Leher',
            'muskuloskeletal' => 'Muskuloskeletal',
            'paru_paru' => 'Paru-Paru',
            'extremitas' => 'Extremitas',
            'skala_wong_baker' => 'skala_wong_baker',
            'r_penyakitdahulu' => 'Riwayat Penyakit',
            'r_penyakitsaatini' => 'Riwayat Penyakit Saat ini',
            'r_pengobatan' => 'Riwayat Pengobatan',
            'jalan_nafas_bersin' => 'jalan_nafas_bersin',
            'asesmen_auto' => 'asesmen_auto',
            'asesmen_auto_anamnesa' => 'asesmen_auto_anamnesa',
            'asesmen_allo' => 'asesmen_allo',
            'nilai_decubitus' => 'Score Decubitus',
            'nilai_luka_bakar' => 'Nilai Luka Bakar',
            'survey_kepala' => 'survey_kepala',
            'survey_kepala_lacerasi' => 'survey_kepala_lacerasi',
            'survey_kepala_battle_sign' => 'survey_kepala_battle_sign',
            'survey_kepala_lainnya' => 'survey_kepala_lainnya',
            'survey_mata' => 'survey_mata',
            'survey_mulut' => 'survey_mulut',
            'survey_mulut_luka_dalam' => 'survey_mulut_luka_dalam',
            'survey_mulut_lainnya' => 'survey_mulut_lainnya',
            'survey_telinga' => 'survey_telinga',
            'survey_leher' => 'survey_leher',
            'survey_leher_lainnya' => 'survey_leher_lainnya',
            'survey_extremitas' => 'survey_extremitas',
            'survey_extremitas_pulsasi' => 'survey_extremitas_pulsasi',
            'survey_dada' => 'survey_dada',
            'survey_dada_simetris_asimetris' => 'survey_dada_simetris_asimetris',
            'survey_dada_pneumo_hamatotoraks' => 'survey_dada_pneumo_hamatotoraks',
            'survey_dada_nyeri_lokasi' => 'Lokasi',
            'survey_dada_nyeri_kapan' => 'Kapan',
            'survey_dada_nyeri_durasi' => 'Durasi',
            'survey_dada_nyeri_kegiatan' => 'Sedang melakukan kegiatan',
            'survey_dada_bunyi_jantung' => 'survey_dada_bunyi_jantung',
            'survey_abdomen' => 'survey_abdomen',
            'survey_abdomen_memas' => 'survey_abdomen_memas',
            'survey_abdomen_nyeri' => 'survey_abdomen_nyeri',
            'survey_abdomen_lainnya' => 'survey_abdomen_lainnya',
            'survey_abdomen_bising_usus' => 'survey_abdomen_bising_usus',
            'survey_pelvis' => 'survey_pelvis',
            'survey_pelvis_lainnya' => 'survey_pelvis_lainnya',
            'survey_medulla_spinalis' => 'survey_medulla_spinalis',
            'survey_kolumna_vertebralis' => 'survey_kolumna_vertebralis',
            'perasaan_klien' => 'perasaan_klien',
            'sosial_support' => 'sosial_support',
            'hubungan_pasien' => 'hubungan_pasien',
            'keluarga_lain' => 'keluarga_lain',
            'keadaan_emosi' => 'keadaan_emosi',
            'suku_id' => 'Kultural',
            'bahasa_dipakai' => 'bahasa_dipakai',
            'bahasa_dipakai_lainnya' => 'bahasa_dipakai_lainnya',
            'is_penerjemah' => 'is_penerjemah',
            'media' => 'media',
            'media_lainnya' => 'media_lainnya',
            'identifikasi_hambatan' => 'identifikasi_hambatan',
            'is_sistem_rujukan' => 'is_sistem_rujukan',
            'materi' => 'Materi',
            'edukator' => 'Edukator',
            'is_ketersediaan_pasien' => 'is_ketersediaan_pasien',
            'is_kemampuan_membaca' => 'is_kemampuan_membaca',
            'bahasa' => 'Bahasa',
            'is_dibutuhkan_penerjemah' => 'is_dibutuhkan_penerjemah',
            'penerjemah_bahasa' => 'penerjemah_bahasa',
            'is_hambatan_emotional' => 'is_hambatan_emotional',
            'hambatan_emotional_lainnya' => 'hambatan_emotional_lainnya',
            'is_keterbatasan_fisik' => 'is_keterbatasan_fisik',
            'keterbatasan_fisik' => 'keterbatasan_fisik',
            'bersihan_jalan' => 'Bersihan Jalan tidak efektif',
            'pola_nafas' => 'Pola napas tidak efektif',
            'gangguan_gas' => 'Gangguan pertukaran gas',
            'nyeri' => 'Nyeri',
            'penurunan_jantung' => 'Penurunan curah Jantung',
            'gangguan_perfusi_cerebral' => 'Gangguan Perfusi Cerebral',
            'gangguan_perfusi_perifer' => 'Gangguan perfusi jaringan perifer',
            'valume_cairan_tubuh' => 'Volume cairan tubuh kurang dari kebutuhan tubuh',
            'gangguan_thermoregulasi_nilai' => 'gangguan_thermoregulasi_nilai',
            'gangguan_thermoregulasi_tipe' => 'gangguan_thermoregulasi_tipe',
            'tujuan_pulang' => 'tujuan_pulang',
            'tujuan_pulang_lainnya' => 'tujuan_pulang_lainnya',
            'transportasi' => 'transportasi',
            'orang_merawat' => 'orang_merawat',
            'sarana_kesehatan' => 'sarana_kesehatan',
            'masuk_ke' => 'masuk_ke',
            'survey_kepala_hasil' => 'survey_kepala_hasil',
            'persen_luka_bakar' => 'survey_kepala_hasil',
            'survey_kepala_utuh' => 'survey_kepala_utuh',
            'pernafasan_gargling' => 'survey_kepala_utuh',
            'ireguler_tipe' => 'survey_kepala_utuh',
            'hasil_resiko_jatuh' => 'Resiko Jatuh',
            'tipe_nadi' => 'tipe_nadi',
            'hasil_nadi' => 'hasil_nadi',
            'pupil_os' => 'pupil_os',
            'pupil_od' => 'pupil_od',
            'jenis_resiko_jatuh' => 'jenis_resiko_jatuh',
            'skrining_gizi' => 'skrining_gizi',
            'skrining_gizi_kidz' => 'skrining_gizi_kidz',
            'extremitas_utuh' => 'extremitas_utuh',
            'extremitas_nyeri' => 'extremitas_nyeri',
            'extremitas_deformatis' => 'extremitas_deformatis',
            'extremitas_neurologis' => 'extremitas_neurologis',
            'extremitas_jejas' => 'extremitas_jejas',
            'extremitas_pulsasi' => 'extremitas_pulsasi',
            'pilih_skala' => 'pilih_skala',
        ];
    }
}
