<?php

namespace app\modules\v1\models;

use Yii;

class AsesmenMedisIGD extends \Doco\components\DocoActiveRecord
{
    public static function tableName()
    {
        return 'asesmenmedisrd_t';
    }

    public function rules()
    {
        return [
            [
                [
                    'asesmenmedisrd_id',
                    'pendaftaran_id',
                    'dokter_id',
                    'tgl_asesmen',
                    'jenis_asmenperawat',
                    'riwayat',
                    'riwayat_dahulu',
                    'diagnosakerja_id',
                    'gcseye_id',
                    'gcsverbal_id',
                    'gcsmotorik_id',
                    'hasil_gcs',
                    'is_kapitis',
                    'additional_data',
                    'created_date',
                    'created_by',
                    'modified_count',
                    'last_modified_date',
                    'last_modified_by',
                    'is_deleted',
                    'is_active',
                    'deleted_date',
                    'deleted_by',
                    'jumlah_gcs',
                    'tgl_pasien_datang',
                    'triage',
                    'dikirim_oleh',
                    'kasus_polisi',
                    'cara_datang',
                    'cara_datang_diantar',
                    'asesmen_allo',
                    'asesmen_auto',
                    'keluhan_utama',
                    'riwayat_penyakit_sekarang',
                    'riwayat_penyakit_dahulu',
                    'riwayat_terapi_sebelumnya',
                    'alergi',
                    'laboratorium',
                    'radiologi',
                    'ekg',
                    'lain_lain',
                    'diagnosa_id',
                    'terapi',
                    'tindak_lanjut',
                    'ku_keluar',
                    'tekanandarah_keluar',
                    'nadi_keluar',
                    'pernapasan_keluar',
                    'saturasi_o2_keluar',
                    'suhu_keluar',
                    'berat_badan',
                    'tinggi_badan',
                    'imt',
                    'tekanandarah',
                    'nadi',
                    'pernapasan',
                    'suhu',
                    'saturasi_o2',
                    'skrining_nyeri',
                    'pilih_skala',
                    'skala_nyeri',
                    'skala_nyeri_anak',
                    'keadaan_umum',
                    'kesadaran',
                    'keterangan_gcs',
                    'asesmen_auto_anamnesa',
                    'asesmen_allo_anamnesa',
                    'ket_imt',
                    // 'resolusi_image',
                    'kasus_kecelakaan',
                    'survey_kepala',
                    'survey_kepala_lacerasi',
                    'survey_kepala_battle_sign',
                    'survey_kepala_lainnya',
                    'survey_mata',
                    'survey_mulut',
                    'survey_mulut_luka_dalam',
                    'survey_mulut_lainnya',
                    'survey_telinga',
                    'survey_leher',
                    'survey_leher_lainnya',
                    'survey_extremitas',
                    'survey_extremitas_pulsasi',
                    'survey_dada',
                    'survey_dada_simetris_asimetris',
                    'survey_dada_pneumo_hamatotoraks',
                    'survey_dada_nyeri_lokasi',
                    'survey_dada_nyeri_kapan',
                    'survey_dada_nyeri_durasi',
                    'survey_dada_nyeri_kegiatan',
                    'survey_dada_bunyi_jantung',
                    'survey_abdomen',
                    'survey_abdomen_memas',
                    'survey_abdomen_nyeri',
                    'survey_abdomen_lainnya',
                    'survey_abdomen_bising_usus',
                    'survey_pelvis',
                    'survey_pelvis_lainnya',
                    'survey_medulla_spinalis',
                    'survey_kolumna_vertebralis',
                    'survey_kepala_utuh',
                    'extremitas_utuh',
                    'extremitas_fraktur',
                    'extremitas_nyeri',
                    'extremitas_deformitas',
                    'extremitas_defisit_neurologis',
                    'extremitas_jejas',
                    'extremitas_pulsasi',
                    'kepala',
                    'mulut',
                    'mata',
                    'tht',
                    'leher',
                    'toraks',
                    'pergerakan',
                    'perkusi',
                    'nafas',
                    'rochi',
                    'wheezing',
                    'irama',
                    'bunyi_jantung',
                    'kelainan',
                    'benjolan',
                    'nyeri_tekan',
                    'hernia',
                    'bising_usus',
                    'distensi',
                    'tulang_belakang',
                    'sistem_saraf',
                    'genetalia',
                    'edema',
                    'crt',
                    'kepala_lainnya',
                    'mata_lainnya',
                    'tht_lainnya',
                    'leher_lainnya',
                    'mulut_lainnya',
                    'thoraks_lainnya',
                    'perkusi_lainnya',
                    'pernapasan_lainnya',
                    'bunyi_jantung_lainnya',
                    'kelaianan_lainnya',
                    'benjolan_lainnya',
                    'nyeri_tekan_lainnya',
                    'hernia_lainnya',
                    'bising_usus_lainnya',
                    'distensi_lainnya',
                    'tulang_belakang_lainnya',
                    'sistem_saraf_lainnya',
                    'genetalia_lainnya',
                    'edema_lainnya',
                    'crt_lainnya',
                    'pemeriksaan_fisik_lainnya',
                    'diagnosis'
                ],
                'safe'
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'asesmenmedisrd_id' => 'asesmenmedisrd_id',
            'pendaftaran_id' => 'pendaftaran_id',
            'dokter_id' => 'dokter_id',
            'tgl_asesmen' => 'tgl_asesmen',
            'jenis_asmenperawat' => 'jenis_asmenperawat',
            'riwayat' => 'riwayat',
            'riwayat_dahulu' => 'riwayat_dahulu',
            'diagnosakerja_id' => 'diagnosakerja_id',
            'gcseye_id' => 'gcseye_id',
            'gcsverbal_id' => 'gcsverbal_id',
            'gcsmotorik_id' => 'gcsmotorik_id',
            'hasil_gcs' => 'hasil_gcs',
            'is_kapitis' => 'is_kapitis',
            'additional_data' => 'additional_data',
            'created_date' => 'created_date',
            'created_by' => 'created_by',
            'modified_count' => 'modified_count',
            'last_modified_date' => 'last_modified_date',
            'last_modified_by' => 'last_modified_by',
            'is_deleted' => 'is_deleted',
            'is_active' => 'is_active',
            'deleted_date' => 'deleted_date',
            'deleted_by' => 'deleted_by',
            'jumlah_gcs' => 'jumlah_gcs',
            'tgl_pasien_datang' => 'tgl_pasien_datang',
            'triage' => 'triage',
            'dikirim_oleh' => 'dikirim_oleh',
            'kasus_polisi' => 'kasus_polisi',
            'cara_datang' => 'cara_datang',
            'cara_datang_diantar' => 'cara_datang_diantar',
            'asesmen_allo' => 'asesmen_allo',
            'asesmen_auto' => 'asesmen_auto',
            'keluhan_utama' => 'keluhan_utama',
            'riwayat_penyakit_sekarang' => 'riwayat_penyakit_sekarang',
            'riwayat_penyakit_dahulu' => 'riwayat_penyakit_dahulu',
            'riwayat_terapi_sebelumnya' => 'riwayat_terapi_sebelumnya',
            'alergi' => 'alergi',
            'laboratorium' => 'laboratorium',
            'radiologi' => 'radiologi',
            'ekg' => 'ekg',
            'lain_lain' => 'lain_lain',
            'diagnosa_id' => 'diagnosa_id',
            'terapi' => 'terapi',
            'tindak_lanjut' => 'tindak_lanjut',
            'ku_keluar' => 'ku_keluar',
            'tekanandarah_keluar' => 'tekanandarah_keluar',
            'nadi_keluar' => 'nadi_keluar',
            'pernapasan_keluar' => 'pernapasan_keluar',
            'saturasi_o2_keluar' => 'saturasi_o2_keluar',
            'suhu_keluar' => 'suhu_keluar',
            'berat_badan' => 'berat_badan',
            'tinggi_badan' => 'tinggi_badan',
            'imt' => 'imt',
            'tekanandarah' => 'tekanandarah',
            'nadi' => 'nadi',
            'pernapasan' => 'pernapasan',
            'suhu' => 'suhu',
            'saturasi_o2' => 'saturasi_o2',
            'skrining_nyeri' => 'skrining_nyeri',
            'pilih_skala' => 'pilih_skala',
            'skala_nyeri' => 'skala_nyeri',
            'skala_nyeri_anak' => 'skala_nyeri_anak',
            'keadaan_umum' => 'keadaan_umum',
            'kesadaran' => 'kesadaran',
            'keterangan_gcs' => 'keterangan_gcs',
            'asesmen_auto_anamnesa' => 'asesmen_auto_anamnesa',
            'asesmen_allo_anamnesa' => 'asesmen_allo_anamnesa',
            'kasus_kecelakaan' => 'kasus_kecelakaan',
            // 'resolusi_image'     => 'resolusi_image',
            'ket_imt' => 'ket_imt',
            'survey_kepala' => 'survey_kepala',
            'survey_kepala_lacerasi' => 'survey_kepala_lacerasi',
            'survey_kepala_battle_sign' => 'survey_kepala_battle_sign',
            'survey_kepala_lainnya' => 'survey_kepala_lainnya',
            'survey_mata' => 'survey_mata',
            'survey_mulut' => 'survey_mulut',
            'survey_mulut_luka_dalam' => 'survey_mulut_luka_dalam',
            'survey_mulut_lainnya' => 'survey_mulut_lainnya',
            'survey_telinga' => 'survey_telinga',
            'survey_leher' => 'survey_leher',
            'survey_leher_lainnya' => 'survey_leher_lainnya',
            'survey_extremitas' => 'survey_extremitas',
            'survey_extremitas_pulsasi' => 'survey_extremitas_pulsasi',
            'survey_dada' => 'survey_dada',
            'survey_dada_simetris_asimetris' => 'survey_dada_simetris_asimetris',
            'survey_dada_pneumo_hamatotoraks' => 'survey_dada_pneumo_hamatotoraks',
            'survey_dada_nyeri_lokasi' => 'Lokasi',
            'survey_dada_nyeri_kapan' => 'Kapan',
            'survey_dada_nyeri_durasi' => 'Durasi',
            'survey_dada_nyeri_kegiatan' => 'Sedang melakukan kegiatan',
            'survey_dada_bunyi_jantung' => 'survey_dada_bunyi_jantung',
            'survey_abdomen' => 'survey_abdomen',
            'survey_abdomen_memas' => 'survey_abdomen_memas',
            'survey_abdomen_nyeri' => 'survey_abdomen_nyeri',
            'survey_abdomen_lainnya' => 'survey_abdomen_lainnya',
            'survey_abdomen_bising_usus' => 'survey_abdomen_bising_usus',
            'survey_pelvis' => 'survey_pelvis',
            'survey_pelvis_lainnya' => 'survey_pelvis_lainnya',
            'survey_medulla_spinalis' => 'survey_medulla_spinalis',
            'survey_kolumna_vertebralis' => 'survey_kolumna_vertebralis',
            'survey_kepala_utuh' => 'survey_kepala_utuh',
            'diagnosis' => 'diagnosis'
        ];
    }
}
