<?php

namespace app\modules\v1\models;

use Yii;

class AsesmenKeperawatan extends \Doco\components\DocoActiveRecord
{
    public static function tableName()
    {
        return 'anamnesa_t';
    }

    // public function rules()
    // {
    //     return [
    //         [
    //             [
    //                 'pendaftaran_id',
    //                 'perawat_id',
    //                 'perawat_nama',
    //                 'dokter_id',
    //                 'dokter_nama',
    //                 'sumber_data',
    //                 'rujukan',
    //                 'tujuan_rujukan',
    //                 'rujukan_rs',
    //                 'diagnosa_rujukan',
    //                 'keluhan',
    //                 'berat_badan',
    //                 'tinggi_badan',
    //                 'nadi',
    //                 'rr',
    //                 'td',
    //                 'suhu',
    //                 'riwayat_penyakit',
    //                 'riwayat_penyakit_nama',
    //                 'dirawat',
    //                 'dirawat_diagnosa',
    //                 'dirawat_waktu',
    //                 'dirawat_tempat',
    //                 'dioperasi',
    //                 'dioperasi_diagnosa',
    //                 'dioperasi_waktu',
    //                 'obat_dikonsumsi',
    //                 'obat_dikonsumsi_nama',
    //                 'riwayat_penyakit_keluarga',
    //                 'riwayat_penyakit_keluarga_list',
    //                 'ketergantungan',
    //                 'ketergantungan_jenis',
    //                 'riwayat_pekerjaan',
    //                 'riwayat_pekerjaan_nama',
    //                 'alergi',
    //                 'alergi_obat',
    //                 'alergi_makanan',
    //                 'alergi_lainnya',
    //                 'reaksi_alergi',
    //                 'status_psikologi',
    //                 'status_sosial',
    //                 'nama_kerabat_terdekat',
    //                 'hubungan_kerabat_terdekat',
    //                 'kontak_kerabat_terdekat',
    //                 'status_ekonomi',
    //                 'nilai_kebudayaan',
    //                 'suku_id',
    //                 'hambatan',
    //                 'jenis_hambatan',
    //                 'butuh_penerjemah',
    //                 'butuh_penerjemah_nama',
    //                 'bahasa_isyarat',
    //                 'kesediaan_menerima_informasi',
    //                 'kemampuan_membaca',
    //                 'bahasa',
    //                 'kebutuhan_edukasi',
    //                 'kebutuhan_edukasi_lainnya',
    //                 'kebutuhan_edukasi_keperawatan',
    //                 'resiko_cedera_pertama',
    //                 'resiko_cedera_kedua',
    //                 'hasil_resiko',
    //                 'aktivitas',
    //                 'bantuan_aktivitas',
    //                 'alat_bantu_jalan',
    //                 'nyeri',
    //                 'skala_nyeri',
    //                 'nyeri_kronis_pertama',
    //                 'lokasi_nyeri_kronis_pertama',
    //                 'frekuensi_nyeri_kronis_pertama',
    //                 'durasi_nyeri_kronis_pertama',
    //                 'nyeri_kronis_kedua',
    //                 'lokasi_nyeri_kronis_kedua',
    //                 'frekuensi_nyeri_kronis_kedua',
    //                 'durasi_nyeri_kronis_kedua',
    //                 'skor_nyeri',
    //                 'nyeri_menjalar',
    //                 'kualitas_nyeri',
    //                 'faktor_pereda_nyeri',
    //                 'nutrisi_1a',
    //                 'nutrisi_1b',
    //                 'nutrisi_2',
    //                 'nilai_nutrisi',
    //                 'diagnosa_khusus',
    //                 'jenis_diagnosa_khusus',
    //                 'diagnosa_keperawatan'
    //             ],
    //             'safe'
    //         ],
    //     ];
    // }

        public function rules()
    {
        return [
            [
                [
                    'anamesa_id',
                    'pendaftaran_id',
                    'pasien_id',
                    'triase_id',
                    'pasienadmisi_id',
                    'pegawaidokter_id',
                    'pegawaiperawat_id',
                    'pegawaitriase_id',
                    'tgl_anamnesis',
                    'keluhan_utama',
                    'keluhan_tambahan',
                    'riwayat_penyakitterdahulu',
                    'riwayat_penyakitkeluarga',
                    'lama_sakit',
                    'pengobatan_ygsudahdilakukan',
                    'riwayat_alergiobat',
                    'riwayat_kelahiran',
                    'riwayat_makanan',
                    'riwayat_imunisasi',
                    'keterangan_anamesa',
                    'riwayat_perjalananpasien',
                    'status_merokok',
                    'jmlrokok_btgperhari',
                    'riwayat_imunisasiblm',
                    'riwayat_obatygsering',
                    'keb_olahraga',
                    'keb_jnsolahraga',
                    'keb_frekuensi_kaliminggu',
                    'keb_konsumsialkohol',
                    'keb_minumkopi',
                    'riwayat_kecelakaan',
                    'riwayat_operasi',
                    'keb_konsumsidrug',
                    'additional_data',
                    'created_date',
                    'created_by',
                    'modified_count',
                    'last_modified_date',
                    'last_modified_by',
                    'is_deleted',
                    'is_active',
                    'deleted_date',
                    'deleted_by',
                    'is_nyeri',
                    'lokasi_nyeri',
                    'skala_nyeri',
                    'is_resikojatuh',
                    'is_alergi',
                    'alergi_obat',
                    'alergi_lainnya',
                    'ket_anamnesa',
                    'tujuan_rujukan',
                    'sumber_data',
                    'rujukan',
                    'rujukan_rs',
                    'diagnosa_rujukan',
                    'berat_badan',
                    'tinggi_badan',
                    'nadi',
                    'rr',
                    'td',
                    'suhu',
                    'riwayat_penyakit',
                    'riwayat_penyakit_nama',
                    'dirawat',
                    'dirawat_diagnosa',
                    'dirawat_waktu',
                    'dirawat_tempat',
                    'dioperasi',
                    'dioperasi_diagnosa',
                    'dioperasi_waktu',
                    'obat_dikonsumsi',
                    'obat_dikonsumsi_nama',
                    'riwayat_penyakit_keluarga',
                    'riwayat_penyakit_keluarga_list',
                    'ketergantungan',
                    'ketergantungan_jenis',
                    'riwayat_pekerjaan',
                    'riwayat_pekerjaan_nama',
                    'alergi',
                    'alergi_makanan',
                    'reaksi_alergi',
                    'status_psikologi',
                    'status_sosial',
                    'nama_kerabat_terdekat',
                    'hubungan_kerabat_terdekat',
                    'kontak_kerabat_terdekat',
                    'status_ekonomi',
                    'nilai_kebudayaan',
                    'hambatan',
                    'jenis_hambatan',
                    'butuh_penerjemah',
                    'butuh_penerjemah_nama',
                    'bahasa_isyarat',
                    'kesediaan_menerima_informasi',
                    'kebutuhan_edukasi',
                    'kebutuhan_edukasi_lainnya',
                    'kebutuhan_edukasi_keperawatan',
                    'resiko_cedera_pertama',
                    'resiko_cedera_kedua',
                    'hasil_resiko',
                    'aktivitas',
                    'bantuan_aktivitas',
                    'alat_bantu_jalan',
                    'nyeri_kronis_pertama',
                    'lokasi_nyeri_kronis_pertama',
                    'frekuensi_nyeri_kronis_pertama',
                    'durasi_nyeri_kronis_pertama',
                    'nyeri_kronis_kedua',
                    'lokasi_nyeri_kronis_kedua',
                    'frekuensi_nyeri_kronis_kedua',
                    'durasi_nyeri_kronis_kedua',
                    'skor_nyeri',
                    'nyeri_menjalar',
                    'kualitas_nyeri',
                    'faktor_pereda_nyeri',
                    'nutrisi_1a',
                    'nutrisi_1b',
                    'nutrisi_1c1',
                    'nutrisi_1c2',
                    'nutrisi_1c3',
                    'nutrisi_1c4',
                    'nutrisi_2',
                    'nutrisi_2b',
                    'nilai_nutrisi',
                    'diagnosa_khusus',
                    'jenis_diagnosa_khusus',
                    'diagnosa_keperawatan',
                    'suku_id',
                    'kemampuan_membaca',
                    'bahasa'
                ],
                'safe'
            ],
        ];
    }
}