CREATE OR REPLACE FUNCTION public.obatalkespasien_r_update()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$ 
    
DECLARE
        v_keterangan VARCHAR;
BEGIN
		IF (NEW.det is null)
				THEN 
						NEW.hargajual_oa = ROUND(NEW.hargasatuan_oa) * NEW.qty_oa;
						NEW.hargasatuan_oa = ROUND(NEW.hargasatuan_oa);
				ELSE 
						NEW.hargajual_oa = ROUND(NEW.hargasatuan_oa) * NEW.det;
						NEW.hargasatuan_oa = ROUND(NEW.hargasatuan_oa);
		END IF; 
		
		IF((NEW.is_deleted IS TRUE OR NEW.obatsudahbayar_id IS NOT NULL) AND OLD.is_deleted IS FALSE)
		THEN
						v_keterangan := 'ACCRUAL REVERSAL';
						--> INSERT table history obatalkespasien_r menjadi ACCRUAL REVERSAL(-)
						INSERT INTO obatalkespasien_r (     
						obatalkespasien_id ,
						sumberdana_id ,
						racikan_id ,
						returresepdetail_id ,
						tipepaket_id ,
						ruangan_id ,
						carabayar_id ,
						pegawai_id ,
						daftartindakan_id ,
						tindakanpelayanan_id ,
						satuankecil_id ,
						shift_id ,
						pendaftaran_id ,
						obatalkes_id ,
						pasien_id ,
						penjamin_id ,
						kelaspelayanan_id ,
						pasienanastesi_id ,
						pasienmasukpenunjang_id ,
						pasienadmisi_id ,
						obatsudahbayar_id ,
						penjualanresep_id ,
						tglpelayanan ,
						r ,
						rke ,
						permintaan_oa ,
						jmlkemasan_oa ,
						kekuatan_oa ,
						satuankekuatan_oa ,
						qty_oa ,
						hargasatuan_oa ,
						signa_oa ,
						harganetto_oa ,
						hargajual_oa , 
						etiket ,
						jmlexposerad ,
						kontrasrad ,
						biayaservice ,
						biayakonseling ,
						jasadokterresep ,
						biayakemasan ,
						biayaadministrasi ,
						tarifcyto ,
						discount , 
						subsidiasuransi ,
						subsidipemerintah ,
						subsidirs ,
						iurbiaya ,
						oa ,
						pembulatan ,
						verifikasitagihan_id ,
						jurnalrekening_id ,
						permohonanoadetail_id ,
						persenppnjual ,
						resepturdetail_id ,
						nilaippnjual ,
						perawat1_id ,
						perawat2_id ,
						instruksitindakanbmhp_id ,
						implementasi_id ,
						is_dilakukan ,
						pemakaianambulan_id ,
						is_jurnal ,
						konfigmargindetail_id ,
						qty_konversi ,
						is_penatajasa ,
						det ,
						status_bmhp ,
						det_konversi ,
						signa ,
						additional_data ,
						created_date ,
						created_by ,
						modified_count ,
						last_modified_date ,
						last_modified_by ,
						is_deleted ,
						is_active ,
						deleted_date , 
						deleted_by ,
						keterangan,
						no_obatalkespasien,
						tarif_dijamin,
						tarif_dibayarkan,
						tarif_diskon,
						pembayaran_id
				)VALUES(
						OLD.obatalkespasien_id ,
						OLD.sumberdana_id ,
						OLD.racikan_id ,
						OLD.returresepdetail_id ,
						OLD.tipepaket_id ,
						OLD.ruangan_id ,
						OLD.carabayar_id ,
						OLD.pegawai_id ,
						OLD.daftartindakan_id ,
						OLD.tindakanpelayanan_id ,
						OLD.satuankecil_id ,
						OLD.shift_id ,
						OLD.pendaftaran_id ,
						OLD.obatalkes_id ,
						OLD.pasien_id ,
						OLD.penjamin_id ,
						OLD.kelaspelayanan_id ,
						OLD.pasienanastesi_id ,
						OLD.pasienmasukpenunjang_id ,
						OLD.pasienadmisi_id ,
						OLD.obatsudahbayar_id ,
						OLD.penjualanresep_id ,
						OLD.tglpelayanan ,
						OLD.r ,
						OLD.rke ,
						OLD.permintaan_oa ,
						OLD.jmlkemasan_oa ,
						OLD.kekuatan_oa ,
						OLD.satuankekuatan_oa ,
						-1 * OLD.qty_oa ,
						OLD.hargasatuan_oa ,
						OLD.signa_oa ,
						OLD.harganetto_oa ,
						CASE
								WHEN OLD.det <> 0  THEN -1 * OLD.hargasatuan_oa * OLD.det
								WHEN OLD.det = 0 OR OLD.det IS NULL THEN  -1 * OLD.hargasatuan_oa * OLD.qty_oa 
						END, 
						OLD.etiket ,
						OLD.jmlexposerad ,
						OLD.kontrasrad ,
						OLD.biayaservice ,
						OLD.biayakonseling ,
						OLD.jasadokterresep ,
						OLD.biayakemasan ,
						OLD.biayaadministrasi ,
						OLD.tarifcyto ,
						OLD.discount , 
						OLD.subsidiasuransi ,
						OLD.subsidipemerintah ,
						OLD.subsidirs ,
						OLD.iurbiaya ,
						OLD.oa ,
						OLD.pembulatan ,
						OLD.verifikasitagihan_id ,
						OLD.jurnalrekening_id ,
						OLD.permohonanoadetail_id ,
						OLD.persenppnjual ,
						OLD.resepturdetail_id ,
						OLD.nilaippnjual ,
						OLD.perawat1_id ,
						OLD.perawat2_id ,
						OLD.instruksitindakanbmhp_id ,
						OLD.implementasi_id ,
						OLD.is_dilakukan ,
						OLD.pemakaianambulan_id ,
						OLD.is_jurnal ,
						OLD.konfigmargindetail_id ,
						-1 * OLD.qty_konversi ,
						OLD.is_penatajasa ,
						-1 * OLD.det ,
						OLD.status_bmhp ,
						-1 * OLD.det_konversi ,
						OLD.signa ,
						OLD.additional_data ,
						OLD.created_date ,
						OLD.created_by ,
						OLD.modified_count ,
						OLD.last_modified_date ,
						OLD.last_modified_by ,
						OLD.is_deleted ,
						OLD.is_active ,
						OLD.deleted_date , 
						OLD.deleted_by ,
						v_keterangan,
						OLD.no_obatalkespasien,
						0,
						0,
						0,
						NULL
				);
		RETURN NEW;
		END IF;
				
				IF (OLD.obatsudahbayar_id is null and OLD.is_deleted is FALSE)
						THEN    
						-- INSERT table history obatalkespasien_r menjadi ACCRUAL REVERSAL(-) setelah BILLING CANCEL
						INSERT INTO obatalkespasien_r (     
						obatalkespasien_id ,
						sumberdana_id ,
						racikan_id ,
						returresepdetail_id ,
						tipepaket_id ,
						ruangan_id ,
						carabayar_id ,
						pegawai_id ,
						daftartindakan_id ,
						tindakanpelayanan_id ,
						satuankecil_id ,
						shift_id ,
						pendaftaran_id ,
						obatalkes_id ,
						pasien_id ,
						penjamin_id ,
						kelaspelayanan_id ,
						pasienanastesi_id ,
						pasienmasukpenunjang_id ,
						pasienadmisi_id ,
						obatsudahbayar_id ,
						penjualanresep_id ,
						tglpelayanan ,
						r ,
						rke ,
						permintaan_oa ,
						jmlkemasan_oa ,
						kekuatan_oa ,
						satuankekuatan_oa ,
						qty_oa ,
						hargasatuan_oa ,
						signa_oa ,
						harganetto_oa ,
						hargajual_oa , 
						etiket ,
						jmlexposerad ,
						kontrasrad ,
						biayaservice ,
						biayakonseling ,
						jasadokterresep ,
						biayakemasan ,
						biayaadministrasi ,
						tarifcyto ,
						discount , 
						subsidiasuransi ,
						subsidipemerintah ,
						subsidirs ,
						iurbiaya ,
						oa ,
						pembulatan ,
						verifikasitagihan_id ,
						jurnalrekening_id ,
						permohonanoadetail_id ,
						persenppnjual ,
						resepturdetail_id ,
						nilaippnjual ,
						perawat1_id ,
						perawat2_id ,
						instruksitindakanbmhp_id ,
						implementasi_id ,
						is_dilakukan ,
						pemakaianambulan_id ,
						is_jurnal ,
						konfigmargindetail_id ,
						qty_konversi ,
						is_penatajasa ,
						det ,
						status_bmhp ,
						det_konversi ,
						signa ,
						additional_data ,
						created_date ,
						created_by ,
						modified_count ,
						last_modified_date ,
						last_modified_by ,
						is_deleted ,
						is_active ,
						deleted_date , 
						deleted_by ,
						keterangan,
						no_obatalkespasien,
						tarif_dijamin,
						tarif_dibayarkan,
						tarif_diskon,
						pembayaran_id
				)VALUES(
						OLD.obatalkespasien_id ,
						OLD.sumberdana_id ,
						OLD.racikan_id ,
						OLD.returresepdetail_id ,
						OLD.tipepaket_id ,
						OLD.ruangan_id ,
						OLD.carabayar_id ,
						OLD.pegawai_id ,
						OLD.daftartindakan_id ,
						OLD.tindakanpelayanan_id ,
						OLD.satuankecil_id ,
						OLD.shift_id ,
						OLD.pendaftaran_id ,
						OLD.obatalkes_id ,
						OLD.pasien_id ,
						OLD.penjamin_id ,
						OLD.kelaspelayanan_id ,
						OLD.pasienanastesi_id ,
						OLD.pasienmasukpenunjang_id ,
						OLD.pasienadmisi_id ,
						OLD.obatsudahbayar_id ,
						OLD.penjualanresep_id ,
						OLD.tglpelayanan ,
						OLD.r ,
						OLD.rke ,
						OLD.permintaan_oa ,
						OLD.jmlkemasan_oa ,
						OLD.kekuatan_oa ,
						OLD.satuankekuatan_oa ,
						-1 * OLD.qty_oa ,
						OLD.hargasatuan_oa ,
						OLD.signa_oa ,
						OLD.harganetto_oa ,
						CASE
								WHEN OLD.det <> 0  THEN -1 * OLD.hargasatuan_oa * OLD.det
								WHEN OLD.det = 0 OR OLD.det IS NULL THEN  -1 * OLD.hargasatuan_oa * OLD.qty_oa 
						END,  
						OLD.etiket ,
						OLD.jmlexposerad ,
						OLD.kontrasrad ,
						OLD.biayaservice ,
						OLD.biayakonseling ,
						OLD.jasadokterresep ,
						OLD.biayakemasan ,
						OLD.biayaadministrasi ,
						OLD.tarifcyto ,
						OLD.discount , 
						OLD.subsidiasuransi ,
						OLD.subsidipemerintah ,
						OLD.subsidirs ,
						OLD.iurbiaya ,
						OLD.oa ,
						OLD.pembulatan ,
						OLD.verifikasitagihan_id ,
						OLD.jurnalrekening_id ,
						OLD.permohonanoadetail_id ,
						OLD.persenppnjual ,
						OLD.resepturdetail_id ,
						OLD.nilaippnjual ,
						OLD.perawat1_id ,
						OLD.perawat2_id ,
						OLD.instruksitindakanbmhp_id ,
						OLD.implementasi_id ,
						OLD.is_dilakukan ,
						OLD.pemakaianambulan_id ,
						OLD.is_jurnal ,
						OLD.konfigmargindetail_id ,
						-1 * OLD.qty_konversi ,
						OLD.is_penatajasa ,
						-1 * OLD.det ,
						OLD.status_bmhp ,
						-1 * OLD.det_konversi ,
						OLD.signa ,
						OLD.additional_data ,
						OLD.created_date ,
						OLD.created_by ,
						OLD.modified_count ,
						OLD.last_modified_date ,
						OLD.last_modified_by ,
						OLD.is_deleted ,
						OLD.is_active ,
						OLD.deleted_date , 
						OLD.deleted_by ,
						'ACCRUAL REVERSAL',
						OLD.no_obatalkespasien,
						0,
						0,
						0,
						NULL
				);
		
				INSERT INTO obatalkespasien_r (     
						obatalkespasien_id ,
						sumberdana_id ,
						racikan_id ,
						returresepdetail_id ,
						tipepaket_id ,
						ruangan_id ,
						carabayar_id ,
						pegawai_id ,
						daftartindakan_id ,
						tindakanpelayanan_id ,
						satuankecil_id ,
						shift_id ,
						pendaftaran_id ,
						obatalkes_id ,
						pasien_id ,
						penjamin_id ,
						kelaspelayanan_id ,
						pasienanastesi_id ,
						pasienmasukpenunjang_id ,
						pasienadmisi_id ,
						obatsudahbayar_id ,
						penjualanresep_id ,
						tglpelayanan ,
						r ,
						rke ,
						permintaan_oa ,
						jmlkemasan_oa ,
						kekuatan_oa ,
						satuankekuatan_oa ,
						qty_oa ,
						hargasatuan_oa ,
						signa_oa ,
						harganetto_oa ,
						hargajual_oa , 
						etiket ,
						jmlexposerad ,
						kontrasrad ,
						biayaservice ,
						biayakonseling ,
						jasadokterresep ,
						biayakemasan ,
						biayaadministrasi ,
						tarifcyto ,
						discount , 
						subsidiasuransi ,
						subsidipemerintah ,
						subsidirs ,
						iurbiaya ,
						oa ,
						pembulatan ,
						verifikasitagihan_id ,
						jurnalrekening_id ,
						permohonanoadetail_id ,
						persenppnjual ,
						resepturdetail_id ,
						nilaippnjual ,
						perawat1_id ,
						perawat2_id ,
						instruksitindakanbmhp_id ,
						implementasi_id ,
						is_dilakukan ,
						pemakaianambulan_id ,
						is_jurnal ,
						konfigmargindetail_id ,
						qty_konversi ,
						is_penatajasa ,
						det ,
						status_bmhp ,
						det_konversi ,
						signa ,
						additional_data ,
						created_date ,
						created_by ,
						modified_count ,
						last_modified_date ,
						last_modified_by ,
						is_deleted ,
						is_active ,
						deleted_date , 
						deleted_by ,
						keterangan,
						no_obatalkespasien,
						tarif_dijamin,
						tarif_dibayarkan,
						tarif_diskon,
						pembayaran_id
				)VALUES(
						OLD.obatalkespasien_id ,
						OLD.sumberdana_id ,
						OLD.racikan_id ,
						NEW.returresepdetail_id ,
						OLD.tipepaket_id ,
						OLD.ruangan_id ,
						NEW.carabayar_id ,
						NEW.pegawai_id ,
						NEW.daftartindakan_id ,
						NEW.tindakanpelayanan_id ,
						OLD.satuankecil_id ,
						OLD.shift_id ,
						OLD.pendaftaran_id ,
						OLD.obatalkes_id ,
						OLD.pasien_id ,
						NEW.penjamin_id ,
						NEW.kelaspelayanan_id ,
						OLD.pasienanastesi_id ,
						OLD.pasienmasukpenunjang_id ,
						OLD.pasienadmisi_id ,
						OLD.obatsudahbayar_id ,
						OLD.penjualanresep_id ,
						NEW.tglpelayanan ,
						OLD.r ,
						OLD.rke ,
						OLD.permintaan_oa ,
						OLD.jmlkemasan_oa ,
						OLD.kekuatan_oa ,
						OLD.satuankekuatan_oa ,
						NEW.qty_oa ,
						NEW.hargasatuan_oa ,
						NEW.signa_oa ,
						NEW.harganetto_oa ,
														CASE
																WHEN NEW.det <> 0  THEN NEW.hargasatuan_oa * NEW.det
																WHEN NEW.det = 0 OR NEW.det IS NULL THEN NEW.hargasatuan_oa * NEW.qty_oa 
														END,  
						OLD.etiket ,
						OLD.jmlexposerad ,
						OLD.kontrasrad ,
						OLD.biayaservice ,
						OLD.biayakonseling ,
						OLD.jasadokterresep ,
						OLD.biayakemasan ,
						OLD.biayaadministrasi ,
						OLD.tarifcyto ,
						OLD.discount , 
						OLD.subsidiasuransi ,
						OLD.subsidipemerintah ,
						OLD.subsidirs ,
						OLD.iurbiaya ,
						OLD.oa ,
						OLD.pembulatan ,
						OLD.verifikasitagihan_id ,
						OLD.jurnalrekening_id ,
						OLD.permohonanoadetail_id ,
						OLD.persenppnjual ,
						OLD.resepturdetail_id ,
						OLD.nilaippnjual ,
						OLD.perawat1_id ,
						OLD.perawat2_id ,
						OLD.instruksitindakanbmhp_id ,
						OLD.implementasi_id ,
						OLD.is_dilakukan ,
						OLD.pemakaianambulan_id ,
						OLD.is_jurnal ,
						OLD.konfigmargindetail_id ,
						NEW.qty_konversi ,
						OLD.is_penatajasa ,
						NEW.det ,
						OLD.status_bmhp ,
						NEW.det_konversi ,
						OLD.signa ,
						OLD.additional_data ,
						OLD.created_date ,
						OLD.created_by ,
						OLD.modified_count ,
						OLD.last_modified_date ,
						OLD.last_modified_by ,
						OLD.is_deleted ,
						OLD.is_active ,
						OLD.deleted_date , 
						OLD.deleted_by ,
						'ACCRUAL',
						OLD.no_obatalkespasien,
						NEW.tarif_dijamin,
						NEW.tarif_dibayarkan,
						NEW.tarif_diskon,
						NEW.pembayaran_id
				);  

		END IF;

    RETURN NEW;

END
$function$
;
