CREATE TABLE public.sbar_t (
    sbar_id serial4 NOT NULL,
    pendaftaran_id int4 NULL,
    pasienadmisi_id int4 NULL,
    dokter_tujuan_id int4 NULL,
    tgl_sbar timestamp NULL,
    situasi text NULL,
    vitalsign_id int4 NULL,
    sistol float4 NULL,
    diastol float4 NULL,
    nadi float4 NULL,
    respirasi float4 NULL,
    tinggi_badan float4 NULL,
    berat_badan float4 NULL,
    spo2 float4 NULL,
    suhu float4 NULL,
    lingkar_kepala float4 NULL,
    asesmen text NULL,
    rekomendasi text NULL,
    is_verifikasi bool NULL DEFAULT false,
    pegawai_verifikasi_id int4 NULL,
    tanggal_verifikasi timestamp NULL,
    additional_data text NULL,
    created_date timestamp NULL,
    created_by int4 NULL,
    modified_count int4 NULL,
    last_modified_date timestamp NULL,
    last_modified_by int4 NULL,
    is_deleted bool NULL DEFAULT false,
    is_active bool NULL DEFAULT true,
    deleted_date timestamp NULL,
    deleted_by int4 NULL,
    is_ttv bool NULL DEFAULT false,
    CONSTRAINT sbar_t_pk PRIMARY KEY (sbar_id)
);