CREATE TABLE IF NOT EXISTS public.vitalsign_t (
    vitalsign_id serial4 NOT NULL,
    pasien_id int4 NOT NULL,
    pendaftaran_id int4 NOT NULL,
    tanggal_ttv timestamp NOT NULL,
    sumberttv_id int4 NOT NULL,
    sumberttv varchar NOT NULL,
    jenisttv_id int4 NULL,
    jenisttv varchar NULL,
    tingkatkesadaran_id int4 NULL,
    tingkatkesadaran varchar NULL,
    sistol float4 NULL,
    diastol float4 NULL,
    nadi float4 NULL,
    respirasi float4 NULL,
    spo2 float4 NULL,
    suhu float4 NULL,
    tinggi_badan float4 NULL,
    berat_badan float4 NULL,
    gcs_e float4 NULL,
    gcs_v float4 NULL,
    gcs_m float4 NULL,
    is_active bool NULL,
    is_deleted bool NULL,
    created_date timestamp NULL,
    created_by int4 NULL,
    last_modified_date timestamp NULL,
    last_modified_by int4 NULL,
    modified_count int4 NULL,
    deleted_date timestamp NULL,
    deleted_by int4 NULL,
    CONSTRAINT vitalsign_t_pk PRIMARY KEY (vitalsign_id)
);